# תכונות הדמות

## ערכי תכונות

לכל דמות יהיה ערך הנע בין 3 ל-18 בכל אחת מן התכונות שלהלן. לכל ערך מוצמד תוסף או מחסר, כפי שמוצג בטבלה. לכל מקצוע יש ערך תכונה שהוא [דרישה עיקרית](class.qmd#מקצועות), והוא חייב להיות לפחות 9 כדי שהדמות תוכל להשתייך לאותו מקצוע; בנוסף, קיימים ערכי מינימום ומקסימום נדרשים לכל גזע דמות מלבד בני אדם, כפי שמתואר תחת [גזעי דמויות](races.qmd#גזעי-דמויות).

| ערך תכונה | תוסף/מחסר |
|:------:|:------:|
| 3 | -3 |
| 4-5 | -2 |
| 6-8 | -1 |
| 9-12 | 0 |
| 13-15 | +1 |
| 16-17 | +2 |
| 18 | +3 |

**כוח:** כפי שהשם מרמז, תכונה זו מודדת את העוצמה הגופנית הגולמית של הדמות. כוח הוא הדרישה העיקרית עבור [לוחמים](class.qmd#לוחם). יש להחיל את התוסף או המחסר של כוח על כל גלגולי ההתקפה והנזק בקרב פנים אל פנים (קפא"פ). שימו לב שמחסר כאן לא יפחית בשום מקרה את הנזק מהתקפה מוצלחת אל מתחת לנקודה אחת (ראו את סעיף [קרב](combat.qmd#נזק) לפרטים).

**תבונה:** זוהי היכולת ללמוד וליישם ידע. תבונה היא הדרישה העיקרית עבור [קוסמים](class.qmd#קוסם). התוסף לתבונה מתווסף למספר ה[שפות](abilities.qmd#שפות) שהדמות מסוגלת ללמוד לקרוא ולכתוב; אם לדמות יש מחסר לתבונה, היא אינה יכולה לקרוא יותר ממילה או שתיים, ותדע רק את שפת האם שלה.

**חוכמה:** שילוב של אינטואיציה, כוח רצון ושכל ישר. חוכמה היא הדרישה העיקרית עבור [כוהנים](class.qmd#כוהן). התוסף או המחסר לחוכמה עשוי לחול על חלק מגלגולי ההצלה נגד התקפות קסומות, במיוחד כאלה המשפיעות על כוח הרצון של המטרה.

**זריזות:** תכונה זו מודדת את מהירות התגובה ושיווי המשקל של הדמות, וכן את הכישרון בשימוש בכלים. זריזות היא הדרישה העיקרית עבור [גנבים](class.qmd#גנב). התוסף או המחסר לזריזות מוחל על כל [גלגולי ההתקפה](combat.qmd#תמרוני-התקפה) עם נשקי קליעים (לטווח), על ערך [דירוג השריון](equipment.qmd#שריון-ומגנים) של הדמות, ועל גלגול קוביית ה[יוזמה](combat.qmd#יוזמה) של הדמות.

**חוסן:** שילוב של בריאות כללית וחיוניות. יש להחיל את התוסף או המחסר לחוסן על כל קוביית פגיעה שמגלגלת הדמות. שימו לב שמחסר כאן לא יפחית שום גלגול של קוביית פגיעה אל מתחת לנקודה אחת.

**כריזמה:** זוהי היכולת להשפיע על אנשים ואף להנהיגם; בעלי כריזמה גבוהה הם אהודים, או לכל הפחות זוכים להערכה רבה. יש להחיל את התוסף או המחסר לכריזמה על גלגולי תגובה. בנוסף, מספר ה[מלווים](hirelings.qmd#מלווים) שדמות יכולה לשכור, ונאמנותם של אותם מלווים, מושפעים מכריזמה.

#### מחולל תכונות

```{ojs}
import { generalDice } from "../custom.js"

viewof statRolls = {
  const btn = Inputs.button("גלגל תכונות", {value: null, reduce: () => [generalDice(3,6,0),generalDice(3,6,0),generalDice(3,6,0),generalDice(3,6,0),generalDice(3,6,0),generalDice(3,6,0)]});
  const wrapper = html`<div style="direction: rtl; text-align: right;">${btn}</div>`;
  wrapper.value = btn.value;
  btn.addEventListener("input", () => { wrapper.value = btn.value; wrapper.dispatchEvent(new Event("input")); });
  return wrapper;
}
```


```{ojs}
import { calculateModifier } from "../custom.js"
{
    var x = ""
/*     if (statRolls != null){
        x = md`<br>${statRolls[0]} &emsp; (${calculateModifier(statRolls[0])}) 
        <br>${statRolls[1]} &emsp; (${calculateModifier(statRolls[1])})
        <br>${statRolls[2]} &emsp; (${calculateModifier(statRolls[2])})
        <br>${statRolls[3]} &emsp; (${calculateModifier(statRolls[3])}) 
        <br>${statRolls[4]} &emsp; (${calculateModifier(statRolls[4])}) 
        <br>${statRolls[5]} &emsp; (${calculateModifier(statRolls[5])})`
    } else {x = md`<br><b>לחץ על הכפתור לגלגול תכונות<b>`} */

    if (statRolls != null) {
        x = html`<br><table style="max-width:20%; direction: rtl; margin-right: 0; margin-left: auto;">
                    <tr>
                        <td>${statRolls[0]}</td>
                        <td>(${calculateModifier(statRolls[0])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[1]}</td>
                        <td>(${calculateModifier(statRolls[1])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[2]}</td>
                        <td>(${calculateModifier(statRolls[2])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[3]}</td>
                        <td>(${calculateModifier(statRolls[3])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[4]}</td>
                        <td>(${calculateModifier(statRolls[4])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[5]}</td>
                        <td>(${calculateModifier(statRolls[5])})</td>
                    </tr>
                `
    } else {x = html`<div style="direction: rtl; text-align: right;"><br><b>לחצו על הכפתור לגלגול תכונות</b></div>`}

    return x
    } 

```

## נקודות פגיעה וקוביות פגיעה

כאשר דמות נפצעת, היא מאבדת נקודות פגיעה מן הסכום הנוכחי שלה. שימו לב שאין בכך כדי לשנות את הערך שגולגל, אלא רק להפחית את הסכום הנוכחי; ריפוי ישיב נקודות פגיעה, עד לגבול הערך שגולגל אך לא מעבר לו.

כאשר סך נקודות הפגיעה שלה מגיע ל-0, ייתכן שהדמות שלך מתה. ייתכן שזה לא יהיה הסוף עבור הדמות; אל תקרע את דף הדמות.

דמויות בדרגה ראשונה מתחילות את המשחק עם קוביית פגיעה אחת מן הסוג המתאים, בתוספת התוסף או המחסר לחוסן, עם **מינימום** של נקודת פגיעה אחת. בכל פעם שדמות עולה בדרגה, על השחקן לגלגל קוביית פגיעה נוספת ולהוסיף את התוסף או המחסר לחוסן של הדמות, כאשר גם כאן התוצאה היא מינימום של נקודה אחת. הוסיפו כמות זו לערך נקודות הפגיעה המרבי של הדמות. שימו לב שלאחר הדרגה התשיעית, דמויות מקבלות מספר קבוע של נקודות פגיעה בכל דרגה, כפי שמוצג ב[טבלת ההתקדמות של המקצוע](class.qmd#מקצועות), ואינן מוסיפות עוד את התוסף או המחסר לחוסן.

## שפות

כל הדמויות מתחילות את המשחק כשהן יודעות את שפת האם שלהן. ברוב עולמות המערכה, כל בני האדם (או כמעט כולם) מדברים באותה שפה, שלעתים קרובות נקראת "מדוברת". לכל גזע דמוי-אדם יש שפה משלו, כלומר אלפית, גמדית או שפת בני-המחצית, וחברי הגזעים דמויי-האדם מתחילים את המשחק כשהם יודעים הן את שפתם שלהם והן את המדוברת (או את השפה המקומית של בני האדם אם אינה נקראת מדוברת).

דמויות בעלות תבונה 13 ומעלה רשאיות לבחור להתחיל את המשחק כשהן יודעות שפה אחת או יותר מעבר לאלו שניתנו לעיל; מספר השפות הנוספות שניתן ללמוד שווה לתוסף התבונה (+1, +2, או +3). דמויות יכולות לבחור ללמוד שפות נוספות של דמויי-אדם, וכן שפות של הומנואידים כגון אורקית, גובלינית וכדומה. המנחה תחליט אילו שפות של הומנואידים ניתן ללמוד. השחקן רשאי לבחור להשאיר "משבצת" אחת או יותר לשפה נוספת פתוחה, כדי למלא אותה במהלך המשחק. מנחות מסוימות עשויות אף לאפשר לדמויות שחקן ללמוד שפות אקזוטיות כגון דרקונית; כמו כן, ייתכן שיותרו שפות "מתות" או שפות ארכאיות אחרות לדמויות מלומדות יותר.