# התקדמות

## נקודות ניסיון (נק"נ)

נקודות ניסיון ניתנות עבור מפלצות שהובסו ועבור אתגרים אחרים כפי שהמנחה רואה לנכון. הטבלה הבאה מספקת ערכי נק"נ למפלצות. כאשר למפלצת יש גם דרגת דמות וגם קוביות פגיעה, יש להשתמש בערך הגבוה יותר כדרגת המפלצת. אתגרים שאינם קרביים יכולים לקבל דרגה או ערך נק"נ קבוע, לפי רצון המנחה.

אם מופיעות כוכביות לאחר רישום קוביות הפגיעה של מפלצת, כל כוכבית מוסיפה פעם אחת את הבונוס ליכולת מיוחדת המופיע בטבלה עבור אותה דרגת קוביות פגיעה; לדוגמה, יצור עם רישום קוביות פגיעה של 2** שווה 125 נק"נ.

למפלצות עם יותר מ־25 קוביות פגיעה יש להוסיף 750 נק"נ לערך הבסיסי, וכן 25 נק"נ לבונוס ליכולת מיוחדת עבור כל קוביית פגיעה נוספת.

לדמויות מנחה יש להתייחס כמפלצות עם מספר קוביות פגיעה השווה לדרגת הדמות. יש להוסיף בונוס ליכולת מיוחדת עבור כוהנים וקוסמים אם הם מסוגלים להטיל לחשים מועילים במהלך המפגש.

לאחר חישוב הנק"נ שנצברו בהרפתקה נתונה, יש לחלק את הכמות בין מספר ההרפתקנים. כפי שתואר לעיל, כל מלווה מקבל חצי חלק; לכן, קבוצה עם ארבע דמויות שחקן ומלווה נחשבת כבעלת 4½ חברים. אם קבוצה זו מרוויחה 2,000 נק"נ, חלק אחד הוא 444 נק"נ, והמלווה מקבל 222 נק"נ.

שום דמות אינה יכולה להתקדם יותר מדרגה אחת בעקבות נקודות ניסיון מהרפתקה אחת. לדוגמה, ברת’אל הגנב הוא בדרגה 1 ויש לו 1,000 נק"נ לפני שהוא יוצא להרפתקה; במהלך ההרפתקה הוא מרוויח 2,000 נק"נ נוספים (הישג מדהים). הדבר היה מביא את סך הנק"נ שלו ל־3,000, והוא היה הופך לגנב בדרגה 3. הדבר אינו מותר; במקום זאת, הוא מתקדם ל־2,499 נק"נ, נקודה אחת פחות מהכמות הנדרשת לדרגה 3, ומתחיל את ההרפתקה הבאה בדרגה 2.


<div class="tableFixHead">


| **קוביות פגיעה של מפלצת** | **ערך נק"נ** | **בונוס ליכולת מיוחדת** |
|---------------------------|-------------|--------------------------|
| פחות מ־1                  | 10          | 3                        |
| 1                         | 25          | 12                       |
| 2                         | 75          | 25                       |
| 3                         | 145         | 30                       |
| 4                         | 240         | 40                       |
| 5                         | 360         | 45                       |
| 6                         | 500         | 55                       |
| 7                         | 670         | 65                       |
| 8                         | 875         | 70                       |
| 9                         | 1,075       | 75                       |
| 10                        | 1,300       | 90                       |
| 11                        | 1,575       | 95                       |
| 12                        | 1,875       | 100                      |
| 13                        | 2,175       | 110                      |
| 14                        | 2,500       | 115                      |
| 15                        | 2,850       | 125                      |
| 16                        | 3,250       | 135                      |
| 17                        | 3,600       | 145                      |
| 18                        | 4,000       | 160                      |
| 19                        | 4,500       | 175                      |
| 20                        | 5,250       | 200                      |
| 21                        | 6,000       | 225                      |
| 22                        | 6,750       | 250                      |
| 23                        | 7,500       | 275                      |
| 24                        | 8,250       | 300                      |
| 25                        | 9,000       | 325                      |


: ערכי נק"נ למפלצות {#tbl-monster-xp}

</div>