# לחשים, לפי סדר אלפביתי

<input type="text" id="input" placeholder="Filter Spell">

<div class="spell" data-tag="Animate Dead" id="Animate Dead">

## החייאת מתים

טווח: 9 מטר

כוהן 4, קוסם 5

משך: מיוחד

הטלת לחש זה גורמת לשאריות גופות של יצורים שנפטרו לקום כשלדים או זומבים מונפשים. מפלצות אל-מתות אלו נשארות עד שהן נהרגות, ומצייתות לפקודות המילוליות של המטילה. הטלה אחת של לחש זה יכולה להנפיש מספר קוביות פגיעה של אל-מתים השווה לפי שניים לדרגת היכולת של המטילה, ולא יותר. לשלדים מונפשים יש קוביות פגיעה השוות למספר שהיצור היה לו בחיים; עבור שלדים של חברי גזעים של דמויות שחקן, זה אומר קוביית פגיעה אחת, ללא קשר לדרגת הדמות שנפטרה. לזומבים יש קוביית פגיעה אחת יותר ממה שהיה ליצורים בחיים.

סוג המפלצות שנוצרות תלוי במצב השאריות. גופה שלמה יחסית יכולה לקום רק כזומבי, בעוד ששאריות שלד שלמות יכולות להיות מונפשות רק כשלד. המטילה בוחרת אילו שאריות להנפיש בעת הטלת הלחש, בכל מקרה שבו יש יותר גופות ממה שהמטילה יכולה להנפיש.

שום דמות לא יכולה לשלוט בדרך כלל ביותר קוביות פגיעה של אל-מתים מאשר פי 4 מדרגתה, ללא קשר לכמה פעמים הלחש הזה מוטל.

</div>
<div class="spell" data-tag="Animate Objects" id="Animate Objects">

## הנפשת חפצים

טווח: 30 מטר+3 מטר/דרגה

כוהן 6

משך: 1 סיבוב/דרגה

לחש זה מאפשר למטילה להנפיש חפצים שהם בדרך כלל דוממים, כך שהם יכולים לנוע ואפילו להיראות כחיים. חפצים להנפשה לא יכולים להיות ברשות (נלבשים או נישאים) של שום יצור, וחייבים להיות לא-קסומים בטבעם. המטילה יכולה להנפיש חפץ אחד לכל דרגה, עד למקסימום של 11 ק"ג לכל דרגת מטילה (כלומר 135 ק"ג בדרגה 12, 146 ק"ג בדרגה 13, וכן הלאה).

חפצים כאלה משמשים בדרך כלל לתקיפת אויבי המטילה, והמנהלת חייבת להחליט על יעילותם בקרב. באופן כללי, חפצים מונפשים תוקפים באמצעות אותו בונוס תקיפה כמו של המטילה. חפצים קטנים או קלים לא גורמים יותר מ-1d4 נזק לכל פגיעה, בעוד שחפצים גדולים ו/או כבדים יותר גורמים 1d6 או 1d8 (לפי שיקול דעת המנהלת). במקרה מיוחד, כלי נשק שמונפשים גורמים נזק באמצעות גלגול הקובייה הרגיל לסוג, אך רק עד למקסימום של 1d8. לחפצים מונפשים יש קצב תנועה של 3 מטר, ובדרך כלל הם חייבים לנוע במגע עם הקרקע (הליכה, קפיצה, זחילה או קפיצה, כפי שנראה הכי מתאים למנהלת).

</div>
<div class="spell" data-tag="Anti-Magic Shell" id="Anti-Magic Shell">

## מעטפת נגד קסם

טווח: רדיוס 3 מטר

קוסם 6

משך: 1 תור/דרגה

בתוך רדיוס של 3 מטר סביב המטילה, כל הקסם מנוטרל למשך כל משך הלחש. התקפות קסומות לא ישפיעו על המטילה, חפצים קסומים ולחשים בתוך הרדיוס מדוכאים, והמטילה לא יכולה לבצע קסמים נוספים עד שהלחש יפוג.

</div>
<div class="spell" data-tag="Blade Barrier" id="Blade Barrier">

## מחסום להבים

טווח: 27 מטר

כוהן 6

משך: 1 סיבוב/דרגה

לחש זה יוצר מחסום של להבים מעופפים, מסתובבים ומבהיקים. המטילה יכולה לבחור מחסום בגובה של עד 6 מטר שנמשך עד 6 מטר אורך לכל דרגת מטילה, או מחסום בצורת טבעת בגובה של עד 6 מטר עם רדיוס של עד 1.5 מטר לכל שתי דרגות מטילה מלאות (כך 9 מטר בדרגה 12 או 13, 10.5 מטר בדרגה 14 או 15, וכן הלאה).

אם יצור כלשהו עובר דרך הקיר, הוא סובל 1d6 נקודות נזק לכל דרגת מטילה, עם נזק מקסימלי של 15d6. גלגול הצלה מוצלח נגד קרן מוות מפחית את הנזק בחצי.

המטילה יכולה לבחור לזמן את הקיר באזור שבו יצורים כבר נמצאים; אם זה נעשה, כל היצורים הללו נפגעים כאילו עברו דרך הקיר, אך גלגול הצלה מוצלח נגד קרן מוות במקרה זה מציין שהיצור נמנע מכל נזק על ידי קפיצה לצד אחד או אחר של הקיר כפי שנבחר על ידי היצור.

כל התקפות מרחוק שעוברות דרך מחסום להבים סובלות מעונש של -4 בגלגול התקיפה.

</div>
<div class="spell" data-tag="Bless*" id="Bless*">

## ברכה*

טווח: רדיוס 15 מטר

כוהן 2

משך: 1 דקה/דרגה

לחש זה נותן למטילה ולבעלות בריתה בתוך רדיוס של 15 מטר בונוס של +1 על כל גלגולי התקיפה, בדיקות מורל (למפלצות או דמויות שאינן שחקן שבעלות ברית עם המטילה), וגלגולי הצלה נגד כל סוג של **פחד** קסום. מטילות בדרגה 7 או גבוהה יותר מעניקות בונוס של +2 להתקפות ולהצלה נגד **פחד**, אך בונוס המורל נשאר +1.

ההפך של **ברכה** נקרא **קללה**. אויבי המטילה בתוך רדיוס של 15 מטר הופכים לפחדנים ולא בטוחים, מה שגורם להם לסבול מעונש של -1 על גלגולי התקיפה, בדיקות המורל, וגלגולי הצלה נגד כל סוג של **פחד** קסום. מטילות בדרגה 7 או גבוהה יותר מחילות עונש של -2 להתקפות ולהצלה נגד **פחד**, אך עונש המורל נשאר -1.

</div>
<div class="spell" data-tag="Charm Animal" id="Charm Animal">

## הקסמת חיה

טווח: 18 מטר

כוהן 2

משך: דרגה+1d4 סיבובים

```{ojs}
// function rolld4() {
//   var randomNumber = Math.floor(Math.random() * 4) + 1;
//   return randomNumber;
// }

import {rolld4} from "../custom.js"

viewof click = Inputs.button("גלגל 1d4", {value: 0, reduce: () => rolld4()})
```


1d4 = ${click}

לחש זה מאפשר למטילה להקסים חיה אחת או יותר, בדומה מאוד ל**הקסמת אדם**, בקצב של 1 קוביית פגיעה לכל דרגת מטילה. המטילה יכולה להחליט אילו חיות בודדות מתוך קבוצה מעורבת יושפעו ראשונות; קוביות פגיעה עודפות של ההשפעה מתעלמות. אין גלגול הצלה מותר, לא לחיות רגילות ולא לחיות בגודל ענק, אך יצורים בעלי טבע פנטסטי יותר (כפי שנקבע על ידי המנהלת) מורשים לגלגל הצלה נגד לחשים כדי להתנגד. כאשר משך הזמן פג, החיות יחזרו לפעילות רגילה מיד.

לחש זה לא מעניק למטילה שום אמצעי תקשורת מיוחד עם החיות המושפעות; אם משולב עם **דבר עם חיות**, לחש זה הופך לשימושי הרבה יותר.

</div>
<div class="spell" data-tag="Charm Monster" id="Charm Monster">

## הקסמת מפלצת

טווח: 9 מטר

קוסם 4

משך: מיוחד

לחש זה פועל כמו **הקסמת אדם**, אלא שההשפעה אינה מוגבלת לפי סוג או גודל היצור. מפלצות אל-מתות אינן מושפעות, כמו גם מבנים כגון גולמים וכל יצור שהוא חסר תודעה באופן פונקציונלי (כגון כל סוג של ג'לי). לחש זה יכול להשפיע על 3d6 קוביות פגיעה של יצורים בעלי 3 קוביות פגיעה או פחות, או על יצור אחד בעל יותר מ-3 קוביות פגיעה. גלגולי הצלה נעשים בדיוק כמו עבור **הקסמת אדם**.

</div>
<div class="spell" data-tag="Charm Person" id="Charm Person">

## הקסמת אדם

טווח: 9 מטר

קוסם 1

משך: מיוחד

לחש זה גורם ליצור דמוי אדם (כולל כל גזעי הדמויות כמו גם יצורים כגון אורקים, גובלינים, גנולים, וכן הלאה) בעל 4 קוביות פגיעה או פחות לתפוס את המטילה כחברה קרובה, עניין אהבה, או לפחות כבעלת ברית מהימנה. דמויות רגילות (דמויות שחקן או דמויות שאינן שחקן) עשויות להיות מושפעות ללא קשר לדרגת היכולת.

גלגול הצלה נגד לחשים יבטל את ההשפעה. אם עוינות כבר החלה או שהמטרה מרגישה מאוימת על ידי המטילה, היא מקבלת בונוס של +5 על גלגול ההצלה שלה.

המטילה לא שולטת ישירות במטרה; במקום זאת, יש לתת פקודות בעל פה, בכתב, או באמצעות מחוות. ברור שפקודות בעל פה יעבדו רק אם המטרה והמטילה חולקות שפה מדוברת, והגבלה זו חלה גם על פקודות כתובות. כמו כן, יש לציין כי התפיסה המדויקת של המטילה על ידי הפרט המושפע אינה בשליטת המטילה; המנהלת צריכה להחליט כיצד הנושא של לחש זה תופס את יחסו למטילה.

המטרה מקבלת גלגול הצלה חדש בכל יום אם יש לה תבונה של 13 או יותר, בכל שבוע אם תבונתה היא 9-12, או בכל חודש אם תבונתה היא 8 או פחות; המנהלת חייבת להחליט על התבונה המקבילה של מפלצות דמויות אדם.

</div>
<div class="spell" data-tag="Clairvoyance" id="Clairvoyance">

## ראיית הנסתר

טווח: 18 מטר

קוסם 3

משך: 12 תורות

לחש זה מאפשר למטילה לראות לאזור אחר דרך עיניו של יצור חי באותו אזור. המטילה חייבת לציין את הכיוון והמרחק המשוער, עד למקסימום של 18 מטר משם. אם אין יצור מתאים באזור זה, הלחש נכשל. אין גלגול הצלה מותר, והיצור המטרה אינו מודע לכך שהוא משמש כך. המטילה יכולה לבחור יצור נושא אחר לאחר שעבר לפחות תור אחד, מה שמאפשר לצפות במיקומים מרובים. אם היצור הנושא נע מחוץ לטווח, הקשר אובד, אם כי המטילה עשויה להיות מסוגלת לבחור מטרה אחרת במקרה זה.

</div>
<div class="spell" data-tag="Cloudkill" id="Cloudkill">

## ענן מוות

טווח: 30 מטר+3 מטר/דרגה

קוסם 5

משך: 6 סיבובים/דרגה

לחש זה יוצר ענן של 6 מטרx6 מטרx6 מטר של גז רעיל הנע בקצב של 3 מטר לסיבוב תחת שליטת המטילה (כל עוד היא מתרכזת בו). הגז הורג מיד כל יצור בעל 3 קוביות פגיעה או דרגות או פחות שהוא בא במגע איתו; יצורים בעלי 4 קוביות פגיעה או דרגות או יותר חייבים לגלגל הצלה נגד רעל או למות. הענן נשאר למשך כל הזמן גם אם המטילה מפסיקה להתרכז בו.

</div>
<div class="spell" data-tag="Commune" id="Commune">

## תקשורת

טווח: עצמי

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מכניס את המטילה למגע עם אלוהותה הפטרונית או משרת חוץ-ממדי שלה, שעונה על שאלה אחת של כן-או-לא לכל דרגת מטילה. הטקס להטלת לחש זה לוקח 1 תור להשלמה. הישות שנוצר קשר עמה עשויה או לא להיות כל-יודעת, ויתר על כן, למרות שהישות היא טכנית בעלת ברית של המטילה, היא עדיין עשויה לא לענות על שאלות בצורה ברורה או מלאה. פרטים אלו נתונים לשיקול דעת המנהלת.

</div>
<div class="spell" data-tag="Confusion" id="Confusion">

## בלבול

טווח: 108 מטר

קוסם 4

משך: 2 סיבובים+1/דרגה

לחש זה גורם לעד 3d6 יצורים חיים בתוך מעגל ברדיוס של 9 מטר סביב נקודת המטרה להיות מבולבלים, מה שגורם להם לא להיות מסוגלים לקבוע באופן עצמאי מה הם יעשו. גלגול הצלה נגד לחשים מותר כדי להתנגד להשפעה. גלגלו על הטבלה הבאה על מספר היוזמה של כל נושא בכל סיבוב כדי לראות מה הנושא עושה.

```{ojs}

import {confusionTable, highlightTableRow} from "../custom.js"

viewof gemJewel3 = Inputs.button("גלגלו על הטבלה", {value: 0, reduce: () => highlightTableRow("#confusion-table", confusionTable())})

```

<br>

::: {#confusion-table}

| d10 | התנהגות |
|-----|-----|
| 1 | פועל כרגיל |
| 2 | נע לעבר המטילה, ותוקף אם אפשר |
| 3--5 | לא פועל כלל, אולי ממלמל |
| 6--7 | נע במהירות הרחק מהמטילה |
| 8--10 | תוקף את היצור הקרוב ביותר, ללא קשר אם הוא חבר או אויב |

:::

אם המטרה לא יכולה לבצע את הפעולה המצוינת, המנהלת צריכה לרדת בטבלה (לחזור לראש אם הטבלה נגמרת) עד שנמצאת פעולה שהמטרה יכולה לבצע. אם יצור מבולבל מותקף, הוא מחזיר את ההתקפה במספר היוזמה הבא שלו (מאוחר יותר בסיבוב זה או בסיבוב הבא אם כבר פעל) ללא קשר למה שגלגלו בטבלה.

</div>
<div class="spell" data-tag="Conjure Elemental" id="Conjure Elemental">

## זימון יסודן

טווח: 72 מטר

קוסם 5

משך: מיוחד

פתח פורטל לאחד ממישורי היסוד של אוויר, אדמה, אש או מים, המאפשר לקוסם לזמן יסודן מאותו מישור. עייני בערך [יסודן](monstersAll.qmd#elemental) בסעיף המפלצות לפרטים נוספים על הסוגים הזמינים והסטטיסטיקות שלהם. לכל היותר ניתן לזמן יסודן אחד מכל סוג על ידי המכשפת ביום נתון. ברגע שהיסודן מופיע, הוא משרת את המזמנת ללא הגבלת זמן, בתנאי שהקוסמת מתרכזת אך ורק בשליטה ביצור; הטלת לחשים, קרב או תנועה ביותר מחצי מהקצב הרגיל יגרמו לאובדן הריכוז. המזמנת, בזמן שהיא שולטת ביסודן, יכולה להחזיר אותו למישור המקורי שלו כרצונה (לעשות זאת ביוזמה שלה אם בקרב). אם הקוסמת מאבדת ריכוז, השליטה ביסודן המזומן אובדת ולא ניתן להחזירה. היצור אז מחפש לתקוף את המזמנת ואת כל האחרים בדרכו. רק **ביטול קסם** או **ביטול רוע** יגרשו את היסודן לאחר שאבדת השליטה. יסודן עשוי, כמובן, לבחור לחזור למישור הבית שלו בעצמו; יצורים כאלה לא יבחרו להישאר במישור החומרי לאורך זמן.

</div>
<div class="spell" data-tag="Continual Light*" id="Continual Light*">

## אור מתמיד*

טווח: 108 מטר

כוהן 3, קוסם 2

משך: שנה אחת/דרגה

לחש זה יוצר אזור כדורי של אור, בהיר כמו אור יום מלא עד רדיוס של 9 מטר, עם אור בעוצמה פחותה עד רדיוס של 18 מטר. אור מתמיד יכול להיות מוטל על חפץ, באוויר או על יצור, בדיוק כמו הלחש **אור**, עד טווח מקסימלי של 108 מטר מהמכשפת. הלחש נשאר בתוקף למשך שנה אחת לכל דרגה של המכשפת.

כמו עם **אור**, ניתן להשתמש בלחש זה כדי לעוור יצור אם הוא מוטל על איברי הראייה שלו. יצורים הממוקדים על ידי לחש זה מורשים לגלגל הצלה נגד קרן מוות; אם ההצלה מצליחה, הלחש מוטל באוויר ממש מאחורי היצור הממוקד. קנס של -4 מוחל על גלגולי התקיפה של היצור העיוור אם גלגול ההצלה נכשל.

הלחש ההפוך, **חושך מתמיד**, גורם להיעדר מוחלט של אור באזור ההשפעה, ומתגבר על מקורות אור רגילים. חושך מתמיד עשוי לשמש לעיוור באותו אופן כמו אור מתמיד.

</div>
<div class="spell" data-tag="Create Food" id="Create Food">

## יצירת מזון

טווח: 3 מטר

כוהן 5

משך: קבוע

לחש זה יוצר מזון מספיק להאכיל עד 3 אנשים או סוס אחד לכל דרגת מכשפת ליום אחד. מזון זה נשאר אכיל רק ליום אחד, אך ניתן להאריך זאת ביום על ידי הטלת **טיהור מזון ומים** עליו (וזה ניתן לעשות שוב ושוב, לשמור על המזון טוב ללא הגבלת זמן). המזון שנוצר על ידי לחש זה מזין ומשביע, אך הוא די תפל.

</div>
<div class="spell" data-tag="Create Water" id="Create Water">

## יצירת מים

טווח: 3 מטר

כוהן 4

משך: קבוע

לחש זה יוצר גלון מים אחד לכל דרגת מכשפת. יש לציין כי כלי אחד או יותר להחזיק את המים חייבים להיות זמינים בזמן ההטלה. המים שנוצרים על ידי לחש זה הם כמו מים גשמים נקיים. הערה: מים שוקלים כ-4 ק"ג לגלון, וקוביית רגל אחת של מים היא בערך 8 גלונים.

</div>
<div class="spell" data-tag="Cure Blindness*" id="Cure Blindness*">

## ריפוי עיוורון*

טווח: מגע

כוהן 3

משך: מיידי

עם לחש זה המכשפת יכולה לרפא יצור הסובל מעיוורון (בין אם נגרם מפציעה או מכשף, כולל **אור** או **אור מתמיד**). עיוורון שנגרם מקללה לא ניתן לריפוי על ידי לחש זה.

בהפוך, לחש זה הופך ל**גרימת עיוורון**, שגורם לייצור חי שנגע בו המכשפת להיות עיוור. נדרש גלגול תקיפה מוצלח בקרב פנים אל פנים כדי לגעת בקורבן, ולא ניתנת גלגול הצלה. יצורים עיוורים סובלים מהעונשים המתוארים ב[חירשות ועיוורון](combat.qmd#deafness-and-blindness).

</div>
<div class="spell" data-tag="Cure Disease*" id="Cure Disease*">

## ריפוי מחלות*

טווח: מגע

כוהן 3

משך: מיידי

ריפוי מחלות מרפא את כל המחלות והורג את כל הטפילים הפוגעים ביצור המטרה. מחלה קסומה או מיוחדת אחרת (כפי שמוגדרת על ידי המנחה) עשויה להיות לא מושפעת על ידי לחש זה, או עשויה לדרוש מכשפת בדרגה מינימלית מסוימת כדי לרפא אותה. כמו כן, יש לציין כי רק בגלל שמחלה או טפיל הוסרו, אין זה אומר שהקורבן לא יכול להידבק מחדש אם יפגוש את המחלה שוב.

הצורה ההפוכה של לחש זה, **גרימת מחלה**, גורמת לייצור חי שנגע בו המכשפת לסבול ממחלה מתישה וקטלנית פוטנציאלית למשך 1d10 ימים הבאים. נדרש גלגול תקיפה מוצלח בקרב פנים אל פנים כדי לגעת בקורבן, ולא ניתנת גלגול הצלה. המטרה סובלת מעונש של -2 לגלגולי התקיפה, דירוג שריון וגלגולי הצלה. בזמן שהקורבן חולה, הוא לא יכול להנות מריפוי טבעי של נזק או אובדן נקודות חוסן, ולא להכין לחשים או לנוע במהירות ריצה. בסוף כל יום שבו דמות נגועה ביצעה כל סוג של מאמץ (לדוגמה, על ידי לחימה, נסיעה, עבודה או מחקר קסום), הדמות חייבת לגלגל גלגול הצלה נגד לחשים או לסבול 1d6 נקודות נזק. ברגע שמשך הלחש חלף, הדמות המושפעת, אם עדיין בחיים, משתחררת מהמחלה ויכולה להתחיל לרפא נזק ולהחזיר נקודות חוסן שאבדו, ויכולה שוב להכין לחשים.

</div>
<div class="spell" data-tag="Cure Light Wounds*" id="Cure Light Wounds*">

## ריפוי פצעים קלים*

כוהן 1

טווח: מגע

משך: מיידי

עם לחש זה המכשפת מרפאת 1d6+1 נקודות פגיעה על ידי הנחת ידה על היצור הפצוע.

הצורה ההפוכה של לחש זה, **גרימת פצעים קלים**, גורמת ל-1d6+1 נזק לייצור המושפע ממנו. נדרש גלגול תקיפה מוצלח במקרה זה, והלחש מתבזבז אם גלגול התקיפה נכשל.

אל-מתים מושפעים מלחש זה וההפוך שלו באופן הפוך; הם נפגעים על ידי **ריפוי פצעים קלים** ונרפאים על ידי **גרימת פצעים קלים**.

</div>
<div class="spell" data-tag="Cure Serious Wounds*" id="Cure Serious Wounds*">

## ריפוי פצעים חמורים*

כוהן 4

טווח: מגע

משך: מיידי

לחש זה פועל בדיוק כמו **ריפוי פצעים קלים**, אלא שהוא מרפא 2d6 נקודות נזק, ועוד נקודה לכל דרגת מכשפת. ההפוך, **גרימת פצעים חמורים**, פועל גם הוא בדיוק כמו **גרימת פצעים קלים**, אלא שהוא גורם ל-2d6 + 2 נקודות לכל דרגת מכשפת.

</div>
<div class="spell" data-tag="Darkvision" id="Darkvision">

## ראיית חושך

טווח: מגע

קוסם 3

משך: שעה אחת/דרגה

הנושא מקבל [ראיית חושך](dungeonAdventures.qmd#darkvision) בטווח של 18 מטר למשך הלחש.

</div>
<div class="spell" data-tag="Death Spell" id="Death Spell">

## לחש מוות

טווח: 72 מטר

קוסם 6

משך: מיידי

לחש זה יהרוג 3d12 קוביות פגיעה או דרגות של יצורים בכדור רדיוס 9 מטר במרכז בכל מקום שהמכשפת רוצה (בתוך מגבלת הטווח). רמות עודפות של יעילות אובדות. כל יצור מושפע מורשה לגלגל הצלה נגד קרן מוות; אלו שנכשלים בגלגול מתים מיד. יצורים של 8 או יותר קוביות פגיעה או דרגות חסינים ללחש, כמו גם מפלצות אל-מתות, גולמים וכל "יצור" אחר שאינו חי באמת.

</div>
<div class="spell" data-tag="Detect Evil*" id="Detect Evil*">

## גילוי רוע*

טווח: 18 מטר

כוהן 1, קוסם 2

משך: סיבוב אחד/דרגה

לחש זה מאפשר למכשפת לגלות רוע; באופן ספציפי, המכשפת יכולה לגלות יצורים עם כוונות רעות, חפצי קסם עם כישופים רעים, ואולי יצורים חוצניים בעלי טבע רע. דמויות רגילות, אפילו דמויות "רעות", לא ניתנות לגילוי על ידי לחש זה, שכן רק רוע מוחץ ניתן לגילוי. המכשפת רואה את היצורים או החפצים ה"רעים" עם זוהר ברור סביבם, אך הזוהר לא ניתן לראות על ידי אף אחד אחר.

ההגדרה המדויקת של רוע נותרת להחלטת המנחה. יש לציין כי פריטים כמו מלכודות רגילות או רעלים אינם "רעים", ולכן לא ניתנים לגילוי על ידי לחש זה.

בהפוך, לחש זה הופך ל**גילוי טוב**, שפועל בדיוק כפי שתואר לעיל ביחס לגילוי כישופים "טובים", יצורים מלאכיים, וכדומה.

</div>
<div class="spell" data-tag="Detect Invisible" id="Detect Invisible">

## גילוי בלתי נראה

טווח: 18 מטר

קוסם 2

משך: תור אחד/דרגה

באמצעות לחש זה המכשפת יכולה לראות דמויות, יצורים או חפצים בלתי נראים בתוך הטווח הנתון, ולראות אותם כצורות שקופות.

</div>
<div class="spell" data-tag="Detect Magic" id="Detect Magic">

## גילוי קסם

טווח: 18 מטר

כוהן 1, קוסם 1

משך: 2 תורות

המכשפת של לחש זה יכולה לגלות חפצים או יצורים מכושפים או מכושפים בתוך הטווח הנתון על ידי ראייה, ולראות אותם מוקפים באור זוהר חיוור. רק המכשפת רואה את הזוהר. יצורים או חפצים בלתי נראים לא ניתנים לגילוי על ידי לחש זה, אך הקרינות של קסם הבלתי נראות ייראו כערפל זוהר אמורפי, מה שעשוי לאפשר למכשפת (רק) לתקוף את היצור הבלתי נראה בעונש תקיפה של רק -2.

</div>
<div class="spell" data-tag="Dimension Door" id="Dimension Door">

## דלת ממדית

טווח: 3 מטר

קוסם 4

משך: מיידי

המכשפת של לחש זה מעבירה את עצמה או כל יצור מטרה יחיד בטווח, לכל נקודה בתוך 60 מטר ועוד 6 מטר לכל דרגת מכשפת. המכשפת או יצור המטרה תמיד מגיעים בדיוק לנקודה הרצויה, בין אם המכשפת מדמיינת את האזור או מציינת כיוון ומרחק. מטרה לא רצויה יכולה לגלגל הצלה נגד לחשים כדי להימנע מהעברה. כל מה שנלבש או נישא על ידי המכשפת או יצור המטרה יועבר גם הוא, כולל דמות או יצור אחר אם המועבר יכול להרים אותו. אם אזור המטרה נמצא בתוך אובייקט מוצק, הלחש נכשל אוטומטית.

</div>
<div class="spell" data-tag="Disintegrate" id="Disintegrate">

## התפוררות

טווח: 18 מטר

קוסם 6

משך: מיידי

לחש זה גורם לקרן אור ירוקה דמוית לייזר לצאת מאצבע המצביעה של המכשפת. כל יצור או אובייקט יחיד (עד קוביית 10x10x3 מטר של חומר) יתפורר לחלוטין. המטרה מורשית לגלגל הצלה נגד לחשים כדי להתנגד. לחש זה יכול למקד רק יצור אחד לכל הטלה, כך שאם המטרה מצליחה בגלגול ההצלה, הלחש מתבזבז.

ציוד שנלבש או נישא על ידי יצור שהתפורר אינו מושפע, וייפול באופן טבעי לרצפה כאילו נפל.

</div>
<div class="spell" data-tag="Dispel Evil" id="Dispel Evil">

## ביטול רוע

טווח: מגע

כוהן 5

משך: סיבוב אחד/דרגה

לחש עוצמתי זה מסייע למכשפת בהתמודדות עם יצורים ממישורים תחתונים, מכאן ואילך נקראים "יצורים רעים".

ראשית, דירוג השריון של המכשפת משתפר ב-4 נקודות כאשר מותקפת על ידי יצורים רעים; השפעה זו נמשכת עד שהלחש מסתיים, בין אם על ידי פקיעת משך הזמן או באמצעות השימוש באחת מההשפעות הבאות.

עם גלגול תקיפה מוצלח המכשפת יכולה להחזיר יצור רע למישורים התחתונים; המכשפת חייבת כמובן להיות מעורבת עם היצור (כלומר בטווח קרב פנים אל פנים). היצור יכול לגלגל הצלה נגד לחשים כדי להתנגד. כל גלגול תקיפה מוצלח של המכשפת למטרה זו מסיים את השפעות הלחש, בין אם היצור מציל ובין אם לא.

באמצעות נגיעה ביצור, חפץ או אזור המושפעים, המטילה יכולה מיד לבטל כל לחש או אפקט קסום דומה שהוטל על ידי היצור הרשע. אין צורך בגלגול עבור אפקט זה, אלא אם המטרה היא יצור שאינו מסכים, ואז יש צורך בגלגול תקיפה כדי לגעת בו בפועל. הלחשים היחידים שלא ניתן לסיים בדרך זו הם אלו שחסינים ל**ביטול קסם**. ביצוע המגע בהצלחה מסיים את הלחש, ללא קשר אם קסם רשע כלשהו אכן בוטל.

</div>
<div class="spell" data-tag="Dispel Magic" id="Dispel Magic">

## ביטול קסם

טווח: 36 מטר

כוהן 4, קוסם 3

משך: מיידי

המטילה יכולה להשתמש בביטול קסם כדי לסיים לחשים מתמשכים שהוטלו על יצור או חפץ, או לסיים לחשים מתמשכים (או לפחות את האפקטים שלהם) בתוך אזור קובייתי בגודל 6 מטר בכל צד. המטילה חייבת לבחור אם לבטל קסם על יצור או חפץ, או להשפיע על אזור.

אם ביטול קסם מכוון ליצורים, כל אפקטי הלחשים (כולל אפקטים מתמשכים של שיקויים) עשויים להתבטל. אם הוא מוטל על אזור, כל האפקטים הללו בתוך האזור עשויים להתבטל. כל לחש או אפקט עם דרגת מטילה שווה או פחותה מדרגת המטילה של **ביטול קסם** מסתיים אוטומטית. אלו שנוצרו על ידי מטילים בדרגה גבוהה יותר עשויים שלא להתבטל; יש סיכוי של 5% שהביטול ייכשל עבור כל דרגה שהאפקט עולה על דרגת המטילה. לדוגמה, מטילה בדרגה 10 שמבטלת קסם שנוצר על ידי מטילה בדרגה 14 יש לה סיכוי של 20% לכישלון.

ישנם לחשים שלא ניתן לסיים על ידי ביטול קסם; זה כולל במיוחד כל קללה, כולל אלו שנוצרו על ידי **הענקת קללה** (ההפך של **הסרת קללה**) וכן על ידי חפצים מקוללים.

</div>

<div class="spell" data-tag="Feeblemind*" id="Feeblemind*">

## טמטום*

טווח: 54 מטר

קוסם 5

משך: קבוע

לחש זה מאפשר למטילה להטיל קללה נוראה על יצור חי, ולהפחית את התבונה והכריזמה לנקודה אחת כל אחת. גלגול הצלה מול לחשים מותר להתנגד לאפקט זה, אך אם היצור המטרה הוא מטיל לחשים, מוחל עונש של -4 לגלגול ההצלה.

ברגע שהוטמטם, הקורבן של לחש זה לא יכול עוד להטיל לחשים, לדבר או להבין כל שפה, או למעשה לתקשר בכלל שכן מוחו לא יכול להבין אפילו דברים פשוטים כמו הצבעה או קריצה. הקורבן עדיין מכיר את חבריו ובעלי בריתו ויעקוב אחריהם וינסה לעזור או להגן עליהם.

אפקט זה ניתן להסרה עם לחש **ריפוי**, או עם הצורה ההפוכה של לחש זה **שחזור תבונה**.

</div>
<div class="spell" data-tag="Find Traps" id="Find Traps">

## מציאת מלכודות

טווח: 9 מטר

כוהן 2

משך: 3 תורות

לחש זה מאפשר למטילה לזהות מגוון של מלכודות, הן מכניות והן קסומות. כאשר המטילה מתקרבת למרחק של 9 מטר ממלכודת, היא תראה אותה זוהרת בהילה ירקרקה-כחולה חלשה. עם זאת, המטילה אינה מסוגלת לזהות סכנות טבעיות מסוימות כמו חול טובעני, בולען, או קירות לא בטוחים של סלע טבעי. הלחש גם לא מעניק למטילה את הידע הנדרש לנטרל את המלכודת, ולא פרטים כלשהם על סוגה או טבעה.

</div>
<div class="spell" data-tag="Find the Path" id="Find the Path">

## מציאת הדרך

טווח: מגע

כוהן 6

משך: 1 תור/דרגה

לחש זה מעניק למטילה, או לנושא אחר שהמטילה נוגעת בו, את היכולת למצוא את המסלול הטוב והקצר ביותר ליעד שנבחר על ידי המטילה. המטילה חייבת להיות בעלת ידע כלשהו על המיקום; כל מיקום שהמטילה אי פעם ביקרה בו יכול להיות מאותר כך, כמו גם מיקומים שתוארו למטילה. אפילו לדעת את שם המיקום (אם יש לו שם) מספיק כדי שלחש זה יפעל.

לחש זה פועל היטב בתוך מבנים או אפילו מתחת לאדמה כמו שהוא פועל בחוץ. עם זאת, **מציאת הדרך** פועל ביחס למיקומים, לא לחפצים או יצורים. הוא יכול להוביל מישהו רק ליעד שנמצא באותו מישור קיום כמו המטילה בעת הלחישה; זה יכול להיות מאוד מגביל אם המטילה (והנושא אם יש) נמצאים ביקום סגור או כיס כלשהו.
 
הנושא יכול לחוש את הכיוון המשוער של היעד, אך גם יודע את המסלול הטוב ביותר להגיע לשם, חש כל פנייה ויודע אילו שבילים או מסדרונות לעקוב כאשר מופיעות בחירות (אך לא מוקדם יותר, למרבה הצער). הלחש אפילו מתגבר על דברים כמו דלתות סודיות, שהנושא יחוש וידע כיצד לפתוח, ומעניק את הידע של סיסמאות או קודים ברגעים הנכונים.

שימו לב שהלחש תמיד יבחר את המסלול הטוב ביותר. לדוגמה, אם הדרך הקצרה ביותר דורשת שימוש במפתח שאין לנושא, הלחש יבחר דרך אחרת, כנראה ארוכה יותר אם אפשר. אם זה לא אפשרי, הנושא יובל לדלת הנעולה ויבין שעליו למצוא דרך לעבור בעצמו.

הלחש מסתיים כאשר הנושא מגיע ליעד או כאשר הזמן פג, מה שיקרה קודם. אם הזמן פג לפני ההגעה, הנושא עשוי עדיין לזכור את הכיוון המשוער ליעד אך לא יידע עוד את הדרך.

</div>
<div class="spell" data-tag="Fireball" id="Fireball">

## כדור אש

טווח: 30 מטר+3 מטר/דרגה

קוסם 3

משך: מיידי

הטלת לחש זה גורמת לגחלת זוהרת קטנה בגודל אפונה לעוף מאצבעה המצביעה של המטילה, על פי הכיוון המצבוין. הגחלת עפה במהירות חץ ומתפוצצת ללהבות הממלאות כדור ברדיוס של 6 מטר כאשר היא מגיעה למרחק שנבחר על ידי המטילה (עד לטווח המרבי שלה), או מוקדם יותר אם היא פוגעת בכל משטח מוצק או נוזלי. אלו שבאזור הלהבות סובלים 1d6 נקודות נזק לכל דרגת מטילה, עם גלגול הצלה מול לחשים המותר לחצי נזק.

אין צורך בגלגול בדרך כלל כאשר מטילים לחש זה, אך אם המטילה רוצה להשליך את הגחלת דרך חריץ או פתח קטן אחר, עליה לגלגל התקפת קליעים (ללא התאמות טווח) כדי לפגוע בו; כישלון מציין שכדור האש פוגע במשטח סמוך ומתפוצץ שם.

חפצים או חומרים דליקים בתוך אזור ההשפעה יתפסו אש בדרך כלל וייתכן שייהרסו (כפי שנקבע על ידי המנחה). מתכות עם נקודות התכה נמוכות כמו זהב, כסף, עופרת, נחושת או ברונזה עשויות להתרכך לזמן קצר ולכן להתעוות, אך הלהבות אינן נמשכות מספיק זמן כדי להמיס את פריטי המתכת אלא אם כן הם קטנים מאוד (כמו שרשרת זהב דקה למשל).

בעוד שכדור האש מפעיל מעט אם בכלל כוח או לחץ בעת הפיצוץ, הוא עשוי עדיין להרוס מחסומים חלשים או דליקים; אם דבר כזה קורה (בהחלטת המנחה, כמובן), כדור האש משלים את התפשטותו בחלל שמעבר למחסום שנהרס.

</div>
<div class="spell" data-tag="Flesh to Stone*" id="Flesh to Stone*">

## בשר לאבן*

טווח: 9 מטר/דרגה

קוסם 6

משך: קבוע

לחש זה גורם ליצור חי, יחד עם כל הציוד שהוא לובש או נושא, להתאבן. זהו אותו אפקט שנגרם על ידי מבט של מדוזה או מגע של קוקטריס. גלגול הצלה מול התאבנות מותר להתנגד ללחש.

הקורבן המאובן הופך רדום; מוחו לא יכול להיות מקושר בשום דרך, והוא אינו חי כראוי ואינו מת. נזק שנגרם לצורתו הפסלית יחול על צורתו הבשרית אם אי פעם ישוחזר; שבירת זרוע או רגל היא כנראה מספיק כדי לגרום למוות עקב אובדן דם. המנחה צריכה לקבוע את ההשפעות של כל פגיעה כזו.

הלחש ההפוך, **אבן לבשר**, פועל כלחש נגד ל**בשר לאבן**, ומשחזר את היצור בדיוק כפי שהיה כאשר התאבן. הוא לא עושה דבר אם מוחל על אבן שאינה תוצאה של **בשר לאבן** או אפקטי התאבנות דומים (כמו מבט של מדוזה).

</div>
<div class="spell" data-tag="Floating Disc" id="Floating Disc">

## דיסק מרחף

טווח: 0

קוסם 1

משך: 5 תורות +1/דרגה

הטלת לחש זה גורמת להופעת פלטפורמה בלתי נראית של כוח קסום. היא בגודל של מגן, כ-1 מטר בקוטר ועומק של אינץ' במרכז. היא יכולה לתמוך במשקל מרבי של 225 ק"ג. (שימו לב שמים שוקלים כ-4 ק"ג לגלון.) הדיסק מרחף בגובה הקרקע, בגובה מותני המטילה. הוא נשאר במקום כאשר הוא במרחק של 3 מטר מהמטילה, ועוקב בקצב התנועה של המטילה אם היא מתרחקת ממנו. הדיסק המרחף יכול להיות נדחף לפי הצורך למקם אותו אך יתבטל אם יוזז איכשהו יותר מ-3 מטר מהמטילה. כאשר משך הלחש פג, הדיסק נעלם מהקיום ומפיל את מה שתמך בו על המשטח שמתחת.

יש לטעון את הדיסק כך שהפריטים המונחים עליו יהיו נתמכים כראוי, אחרת הם ייפלו (כמובן). לדוגמה, הדיסק יכול לתמוך ביותר מ-62 גלונים של מים, אך המים חייבים להיות בחבית או מיכל סביר אחר שניתן להניח על הדיסק. באופן דומה, ערימה של מטבעות רופפים תחליק ותגלוש, וחלקם ייפלו עם כל צעד שהמטילה תעשה; אך שק גדול מלא במטבעות, קשור כראוי, יישאר יציב.

</div>
<div class="spell" data-tag="Fly" id="Fly">

## לעוף

טווח: מגע

קוסם 3

משך: 1 תור/דרגה

נושא לחש זה יכול לעוף במהירות השווה לקצב התנועה הרגיל שלו על הקרקע (כפי שמותאם על ידי עומס). הנושא יכול לעלות בחצי מהירות ולרדת במהירות כפולה, עם אותה יכולת תמרון שיש לנושא כאשר הוא נע על הקרקע. לעוף תחת השפעת לחש זה דורש רק ריכוז כמו הליכה, כך שהנושא יכול לתקוף או להטיל לחשים כרגיל. הנושא של לחש לעוף לא יכול להסתער או לרוץ, ולא לשאת באוויר יותר משקל מהעומס המרבי שלו.

אם משך הלחש פג בעוד הנושא עדיין באוויר, הקסם נכשל לאט כך שהנושא יורד בקצב של 36 מטר לסיבוב למשך 1d10 סיבובים. אם הנושא מגיע לקרקע בזמן זה, הוא נוחת בבטחה; אם לא, הנושא נופל את שאר המרחק וסובל מנזק נפילה רגיל. עם זאת, אם לחש זה מסתיים על ידי **ביטול קסם** או כוחות חיצוניים דומים, הנושא נופל מיד. עבור כל נפילה כזו, ראו [נזק נפילה](combat.qmd#falling-damage) לפרטים על ההשלכות.

</div>
<div class="spell" data-tag="Geas*" id="Geas*">

## גזירה*

טווח: 1.5 מטר לכל דרגה

קוסם 6

משך: מיוחד

באמצעות לחש זה המטילה מכריחה יצור חי לבצע פעולה או שירות מסוימים, או לחלופין להימנע מביצוע פעולה מסוימת. היצור המטרה חייב להיות מסוגל לשמוע ולהבין את המטילה, אחרת הוא לא יכול להיות מושפע. לחש זה ייכשל אוטומטית אם ישתמשו בו כדי להכריח יצור לעסוק בפעולה הרסנית עצמית באופן ברור.

גלגול הצלה נגד לחשים יאפשר למטרה לא מרצון להתנגד לגז כאשר הוא מוטל לראשונה. עם זאת, המטרה עשויה לבחור לקבל את הגז, בדרך כלל כחלק מעסקה עם המטילה עבור שירות כלשהו. לאחר שהכפיפה ללחש זה, הנושא חייב לציית להוראות שניתנו על ידי המטילה ללא הגבלת זמן, אם כי אם הגז הוא לבצע פעולה כלשהי, הלחש למעשה מסתיים כאשר הפעולה הושלמה.

לכל 24 שעות שהנושא בוחר לא לציית לגז (או נמנע מלציית לו), הוא סובל מעונש של -2 לכל אחד מציוני היכולת שלו, עד לעונש מקסימלי של -8. אף ציון יכולת לא יכול להיות מופחת לפחות מ-3 על ידי השפעה זו. אם הנושא חוזר לציית לגז, כל העונשים הללו מוסרים לאחר 24 שעות.

אם המשימה שהוקצתה לנושא הלחש הזה היא פתוחה או אחרת בלתי ניתנת להשלמה, הנושא עדיין מחויב לנסות לבצע את המשימה, אך הלחש יסתיים לא יותר מיום אחד לכל דרגת מטילה. יצורים חכמים מאוד עשויים להיות מסוגלים לעקוף את ההוראות שניתנו; המנחה חייבת להחליט על תוצאות כל ניסיונות כאלה.

לחש זה יכול להסתיים על ידי **הסרת קללה** המוטלת על ידי דמות בדרגה גבוהה יותר מהמטילה של הגז, אך לעולם לא מושפע על ידי **ביטול קסם**.

</div>
<div class="spell" data-tag="Growth of Animals" id="Growth of Animals">

## גדילת בעלי חיים

כוהן 3

טווח: 18 מטר+3 מטר/דרגה

משך: 1 תור/דרגה

לחש זה גורם לחיה לגדול לגודל כפול מגודלה הרגיל ולמשקל שמונה פעמים ממשקלה הרגיל. היצור המושפע יגרום לנזק כפול מהנזק הרגיל בכל התקפות הפיזיות, ודירוג השריון הטבעי הקיים שלו יגדל ב-2. יכולת הנשיאה של החיה גם מוכפלת. חיות לא ידידותיות עשויות להציל נגד לחשים כדי להתנגד ללחש זה; בדרך כלל, חיות מבויתות לא ינסו להתנגד לו, אם כי הן עשויות להתבלבל או להיכנס לפאניקה לאחר מכן (לפי שיקול דעתה של המנחה).

כל ציוד שנלבש או נישא על ידי חיה מוגדל באופן דומה על ידי הלחש, אם כי שינוי זה אינו משפיע על התכונות הקסומות של כל ציוד כזה. כל פריט מוגדל שעוזב את החזקת היצור המוגדל חוזר מיד לגודלו הרגיל.

הלחש אינו נותן אמצעי פיקוד או השפעה על החיות המוגדלות.

</div>
<div class="spell" data-tag="Growth of Plants*" id="Growth of Plants*">

## גדילת צמחים*

טווח: 36 מטר

קוסם 4

משך: קבוע

לחש זה גורם לצמחייה רגילה מכל סוג בטווח להפוך לעבה ומגודלת. שטח ההשפעה נקבע על ידי המטילה, אך לא יכול לעלות על 1,0 מטר מרובע (שטח של 3 מטרx30 מטר או שווה ערך) לכל 5 דרגות מטילה. הצמחים הופכים לסבוכים בצפיפות, ודמויות או יצורים הרוצים לעבור דרכם חייבים לחתוך או לכפות את דרכם דרכו. כל תנועה בתוך השטח המושפע מופחתת ללא יותר מ-1.5 מטר לסיבוב עבור יצורים קטנים מגודל ענק; יצורים בגודל ענק מופחתים לחצי מקצב התנועה הרגיל.

לחש זה לא יכול להיכנס לתוקף באזור שאין בו כבר כמה צמחים. כל סוג של יצור צמח מונפש המושפע על ידי לחש זה רשאי לגלגל הצלה נגד לחשים כדי להתנגד, אך אם גלגול זה נכשל הוא מושפע כמו ב**גדילת בעלי חיים** לעיל.

הצורה ההפוכה, **כיווץ צמחים**, עשויה לשמש כדי להפוך אזורים מגודלים לנגישים. שטח ההשפעה זהה לגרסה הרגילה. יצורי צמח מונפשים בדרך כלל אינם מושפעים על ידי לחש זה, אך אם יצורים כאלה כבר הוגדלו על ידי **גדילת צמחים** לחש זה יהפוך את ההשפעה. במקרה האחרון, גלגול הצלה נגד לחשים מותר כדי להתנגד.

שתי הצורות של לחש זה הן קבועות עד שיבוטלו, או על ידי ההפך של הלחש או על ידי **ביטול קסם**.

</div>
<div class="spell" data-tag="Hallucinatory Terrain" id="Hallucinatory Terrain">

## שטח מדומה

קוסם 4

טווח: 120 מטר+12 מטר/דרגה

משך: 12 תורות/דרגה

לחש זה גורם לקוביה של 10 יארד לכל דרגת מטילה של שטח חיצוני להיראות כמו סוג אחר (למשל, שדה ליער, אדמת עשב למדבר, או דומה). לחש זה דורש תור מלא להטלה.

השטח המושפע נראה, נשמע ומריח כמו סוג אחר של שטח טבעי. מבנים, ציוד ויצורים בתוך האזור אינם מוסתרים או משתנים במראה. הצלה נגד לחשים מותרת לראות דרך האשליה, אך רק אם היצורים או הדמויות המושפעות מנסות לעשות זאת באופן פעיל.

</div>
<div class="spell" data-tag="Haste*" id="Haste*">

## האצה*

טווח: 9 מטר+3 מטר/דרגה

קוסם 3

משך: 1 סיבוב/דרגה

לחש זה מאיץ את הפעולות של יצור אחד לכל דרגת מטילה. היצורים המושפעים נעים ופועלים פי שניים מהר יותר מהרגיל, עם קצב תנועה כפול מהרגיל ומבצעים פי שניים מהתקפות הרגילות לסיבוב, למשך הלחש. הטלת לחשים אינה מואצת, וגם לא השימוש בפריטים קסומים כמו שרביטים, שעדיין ניתן להשתמש בהם רק פעם אחת לסיבוב. השפעות האצה או מהירות מרובות אינן מצטברות; יש ליישם רק את ההשפעה החזקה או הארוכה ביותר.

בקרב, הנושא של לחש זה מבצע סיבוב מלא של פעולות (תנועה ולאחר מכן התקפה) ביוזמה הרגילה שלו; לאחר שכל הלוחמים פעלו, הנושא עשוי לבצע סיבוב נוסף של פעולות כפי שהיה קודם. אם שניים או יותר לוחמים נמצאים תחת השפעת לחש זה, יש להשתמש באותם מספרי יוזמה כדי לקבוע את סדר פעולותיהם בכל אחד מהסיבובים ה"נוספים" שלהם.

בהפוכה, האצה הופכת ל**האטה**; היצורים המושפעים נעים בחצי מהירות, תוקפים בחצי מהתדירות (בדרך כלל, כל סיבוב שני) ומבצעים חצי תנועה רגילה כל סיבוב. כמובן, יצורים המטרה עשויים להציל נגד לחשים כדי להימנע מההשפעה. האצה והאטה מבטלים ומפזרים זה את זה.

</div>
<div class="spell" data-tag="Heal*" id="Heal*">

## ריפוי*

טווח: מגע

כוהן 6

משך: קבוע

לחש זה מאפשר למטילה כמעט לרפא לחלוטין פצעים, מחלות ומחלות אחרות של יצור חי יחיד. במגע המטילה מרפאת עיוורון, חירשות, **בלבול**, מחלה, **חוסר תבונה**, חנק, בחילה ורעל. כל נקודות הפגיעה מלבד 1d4 מוחזרות לנושא, אם יש לו פציעות כלשהן. הפסדי נקודות יכולת מוחזרים במלואם, אם ורק אם הפסדים אלה היו ניתנים להחזרה ללא לחש זה; הפסדים קבועים לציוני יכולת אינם מוחזרים. ניקוז אנרגיה גם אינו מושפע על ידי לחש זה.

הלחש ההפוך, **פגיעה**, פוגע ביצור הנוגע בצורה כה חמורה שהוא נותר עם רק 1d4 נקודות פגיעה. המטילה חייבת להצליח בגלגול התקפה רגיל במקרה זה; כישלון פירושו שהלחש מבוזבז. שימו לב, שאם לקורבן נותרו פחות נקודות פגיעה מהמספר שגולגל, הוא או היא ייקחו לפחות נקודת נזק אחת (וזו המקרה היחיד שבו **פגיעה** עשויה להרוג יצור).

באופן כללי, גם **ריפוי** וגם **פגיעה** משפיעים רק על יצורים חיים. אם משתמשים בהם נגד יצור מת, ריפוי פועל במקום פגיעה; באופן דומה, פגיעה משפיעה על מתים כמו ריפוי. מבנים כמו גולמים אינם מושפעים על ידי אף אחד מהלחשים.

</div>
<div class="spell" data-tag="Hold Monster" id="Hold Monster">

## עצירת מפלצת

טווח: 54 מטר

קוסם 5

משך: 2d8 תורות

לחש זה פועל כמו **עצירת אדם**, אלא שהוא משפיע על כל יצור חי שנכשל בהצלה נגד לחשים.

</div>
<div class="spell" data-tag="Hold Person" id="Hold Person">

## עצירת אדם

טווח: 54 מטר

כוהן 2, קוסם 3

משך: 2d8 תורות

לחש זה ישתק כל יצור אנושי חי (לא מת) (כפי שמוגדר ב**קסם אדם**) בפרליז. יצורים גדולים מאוגרים לא יושפעו מלחש זה. מטרות הלחש מודעות ויכולות לנשום, אך אינן יכולות לזוז, לפעול או לדבר בשום אופן. הצלה מוצלחת נגד לחשים מותרת כדי להתנגד להשפעה. הלחש עשוי להיות מוטל על אדם יחיד, שמבצע את ההצלה שלו ב-2, או על קבוצה, ובמקרה זה 1d4 מהיצורים בקבוצה עשויים להיות מושפעים.

שחיין משותק לא יכול לשחות ועלול לטבוע. דמות שזכתה איכשהו בכנפיים ואז משותקת בזמן שהיא באוויר לא תוכל להזיז את כנפיה כדי לעוף ולכן תיפול.

</div>
<div class="spell" data-tag="Hold Portal" id="Hold Portal">

## עצירת פורטל

טווח: 30 מטר+3 מטר/דרגה

קוסם 1

משך: 1 סיבוב/דרגה

לחש זה מאבטח פורטל כמו דלת, שער, חלון או תריס העשויים מחומרים בנייה רגילים ולא קסומים; הפורטל מתנהג כאילו הוא נעול היטב למשך הלחש. הדלת עשויה להיפתח מוקדם רק באמצעות **נקישה** או הטלה מוצלחת של **ביטול קסם**, או על ידי השמדת הדלת בפועל (מה שעשוי לדרוש יותר זמן ממה שמשך הלחש הזה מאפשר).

</div>
<div class="spell" data-tag="Ice Storm" id="Ice Storm">

## סערת קרח

טווח: 90 מטר+9 מטר/דרגה

קוסם 4

משך: 1 סיבוב

לחש זה גורם לסערה עוצמתית של שלג וברד ליפול ברדיוס של 6 מטר סביב הנקודה המטרה למשך סיבוב מלא. השפעה זו גורמת ל-5d6 נקודות נזק לכל יצור בתוך האזור, עם הצלה נגד לחשים המותרת להפחתת הנזק בחצי. סערת הקרח ממלאת נפח אנכי של 12 מטר, כך שיצורים גבוהים מהמרחק הזה מעל הנקודה המטרה אינם מושפעים. כל יצור העמיד באופן טבעי לקור לוקח חצי נזק (או רבע נזק אם הוא מבצע את ההצלה שלו).

הראות בתוך הסערה גרועה מאוד, כך שרוב היצורים יתקפו עם עונש של -2 על גלגול ההתקפה. תנועת הליכה מופחתת לחצי מהירות, וריצה אינה אפשרית בתוך הסערה; כל מי שמנסה ייפול וייאלץ להישאר על הקרקע עד שהלחש יסתיים. גם תעופה אינה אפשרית, וכל יצור מעופף בתוך האזור יונחת לקרקע. עונש של -20% מוחל על כל גלגולי האזנה שנעשו על ידי אלה שבאזור הסערה.

כאשר הלחש מסתיים, הברד והקרח שהופקדו על ידי הסערה נעלמים כאילו מעולם לא היו קיימים.

</div>
<div class="spell" data-tag="Insect Plague" id="Insect Plague">

## מגפת חרקים

טווח: 90 מטר+9 מטר/דרגה

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מזמן נחיל אחד של ארבה לכל שלוש דרגות מטילה, עד למקסימום של שישה נחילים בדרגה 18. ראו [נחיל חרקים](monstersAll.qmd#insect-swarm) בסעיף **מפלצות** עבור ההשפעות של נחיל. כפי שמוסבר שם, נחיל חרקים רגיל תופס שטח רציף השווה לשלוש קוביות של 3 מטר; כל הנחילים שמזומנים על ידי לחש זה חייבים להיות רציפים זה עם זה כך שהם למעשה יוצרים נחיל ענק אחד, אם כי המטילה עשויה למתוח אותם בקו, ליצור אותם לבלוק, או אכן לסדר אותם בצורה מפותלת אם רצוי.

הנחילים המזומנים נמשכים למשך הזמן הנ"ל, או עד שהם נהרגים, מה שיבוא קודם. המטילה עשויה לזמן אותם באזורים שבהם יצורים כבר נמצאים. לאחר שזומנו, הנחילים הם נייחים עד שהם נעלמים או נהרגים, והם תוקפים כל יצור שנמצא בתוך האזור שלהם.

</div>
<div class="spell" data-tag="Invisibility" id="Invisibility">

## היעלמות

טווח: מגע

קוסם 2

משך: מיוחד

לחש זה גורם ליצור שנגעו בו (שיכול להיות המטיל עצמו) להפוך לבלתי נראה, בלתי ניתן לגילוי על ידי ראייה רגילה או ראיית חושך. יצורים בלתי נראים עשויים להתגלות על ידי אלו שיש להם יכולות חישה לא-ויזואליות.

כל הפריטים הנלבשים או נישאים על ידי המטרה בעת הטלת הלחש הופכים לבלתי נראים גם הם. אם המטרה מניחה פריט בלתי נראה, הוא הופך מיד לגלוי שוב; מצד שני, פריטים שנאספים לא הופכים אוטומטית לבלתי נראים. אם המטרה מניחה פריט גלוי לחלוטין בתוך בגדיה הבלתי נראים, תרמיל, כיס או מיכל אחר כך שאם המטרה הייתה גלויה הפריט לא היה נראה, הוא יהפוך לבלתי נראה כאילו הוחזק בעת הטלת הלחש.

שימו לב שהטלת לחש זה על אחר הופכת את המטרה לבלתי נראית גם למטילה וגם לכל האחרים. קבוצה של דמויות בלתי נראות עשויה לחוות בעיות בהתנגשות או מעידה אחת על השנייה. הלחש נמשך לכל היותר 24 שעות אם לא הסתיים מוקדם יותר. הוא מסתיים מיד אם המטרה תוקפת יריב או מטילה כל לחש. פעולות אחרות בדרך כלל לא מסיימות את הלחש. המטרה יכולה לסיים את הלחש כרצונה.

חפצים שמפיצים אור עשויים להפוך לבלתי נראים אך האור עצמו יישאר גלוי, ומקור האור הזה (והדמות הנושאת אותו) יכול להיחשף. גשם, אבק, צבע וכל חומר גלוי אחר שנזרק או מוחל על יצור בלתי נראה יהפוך אותו גם כן לניתן לגילוי.

</div>
<div class="spell" data-tag="Invisibility 3 מטר Radius" id="Invisibility 3 מטר Radius">

## בלתי נראות רדיוס 3 מטר

קוסם 3

טווח: מגע

משך: 1 תור/דרגה

המטרה של לחש זה הופכת לבלתי נראית בדיוק כמו עם **בלתי נראות**, אך בנוסף כל היצורים האחרים בתוך 3 מטר מהמטרה בזמן ההטלה (המכונים חברי הקבוצה) הופכים גם הם לבלתי נראים. בניגוד לבלתי נראות רגילה, כל החברים יכולים לראות זה את זה ואת עצמם כרגיל.

אם כל חבר מבטל את ההשפעה על ידי תקיפה או הטלת לחש, הוא הופך לגלוי אך כל שאר החברים נשארים בלתי נראים. עם זאת, אם הנושא המקורי נוקט בפעולה שמבטלת את הבלתי נראות, היא מסתיימת עבור כל הקבוצה. אם חבר מבטל את הבלתי נראות שלו, אותו חבר לא יוכל עוד לראות את חברי הקבוצה שעדיין בלתי נראים. התרחקות יותר מ-3 מטר מהמטרה גם גורמת לחבר קבוצה להפוך לגלוי; חזרה לאזור לא מחזירה את הבלתי נראות.

</div>
<div class="spell" data-tag="Invisible Stalker" id="Invisible Stalker">

## עוקב בלתי נראה

טווח: 0

קוסם 6

משך: מיוחד

המטילה מזמנת **עוקב בלתי נראה** לבצע את פקודותיה (ראו את סעיף ה[מפלצות](monstersAll.qmd#invisible-stalker) למטה לפרטים). הלחש נמשך עד ש**הסרת רוע** מוטל על היצור, הוא נהרג, או שהמשימה הושלמה. מומלץ למנחה לעיין בכניסת המפלצת עבור העוקב הבלתי נראה כאשר לחש זה משומש, שכן הם עשויים לא תמיד להיות משרתים אמינים.

</div>
<div class="spell" data-tag="Knock" id="Knock">

## נוק

טווח: 9 מטר

קוסם 2

משך: מיוחד

לחש הנוק פותח דלתות תקועות, נעולות, **מוחזקות** או **נעולות בקסם**. הוא פותח דלתות סודיות, כמו גם קופסאות או תיבות נעולות או עם פתיחה טריקית. הוא גם משחרר ריתוכים, אזיקים או שרשראות (בתנאי שהם משמשים להחזיק משהו שניתן לפתוח). אם משתמשים בו לפתוח דלת **נעולה בקסם**, הלחש לא מסיר את ה**נעילה בקסם** אלא פשוט משעה את פעולתה למשך תור אחד. בכל המקרים האחרים, הדלת לא ננעלת מחדש או הופכת שוב לתקועה מעצמה. נוק לא ירים שער או יפעיל כל מנגנון דומה אחר, ולא ישפיע על חבלים, גפנים וכדומה.

כל הטלה מבטלת שיטה אחת של אבטחת הדלת או הפריט, כך שלמשל דלת שהיא גם נעולה וגם תקועה יכולה להיפתח אך עדיין תהיה תקועה; הטלה שנייה של נוק תפתח דלת כזו.

</div>
<div class="spell" data-tag="Levitate" id="Levitate">

## ריחוף

טווח: מגע

קוסם 2

משך: 1 תור/דרגה

כאשר לחש זה מוטל, המטילה או כל יצור או חפץ אחד שהיא נוגעת בו מתחיל לרחף. ריחוף מאפשר למטילה לגרום לנושא לעלות או לרדת בקצב של עד 6 מטר לסיבוב.

אם יצור מטרה אינו מסכים, המטילה חייבת לגלגל גלגול תקיפה מוצלח כדי לגעת במטרה, וגם אם גלגול זה מצליח, המטרה רשאית לגלגל הצלה נגד לחשים כדי להתנגד לקסם. כמו כן, אם המטרה היא חפץ המוחזק על ידי יצור שאינו מסכים, יידרש גלגול תקיפה וגלגול הצלה דומים. חפצים לא מאוישים מושפעים אוטומטית כאשר נוגעים בהם.

המטילה שולטת בנושא המרחף מנטלית. אם המטילה מפסיקה לשלוט בנושא, הוא נשאר בגובהו הנוכחי עד שהלחש מסתיים, ובאותו רגע הוא נופל.

ריחוף אינו מספק אמצעי תנועה אופקית, אך גם הנושא המרחף אינו מקובע במקום. ניתן להזיזו על ידי דחיפה או גרירה עם חבל, למשל. יצור המרחף יכול למשוך את עצמו לאורך צוק או על פני תקרה, או למשוך את עצמו עם חבל המחובר לחפץ מוצק. תנועה מסוג זה היא בדרך כלל במחצית מהירות ההליכה הרגילה. עם זאת, הנושא אינו יכול לשנות את גובהו בעצמו.

אם יצור מרחף מנסה לתקוף עם רוב הנשקים, הוא ימצא שהוא אינו יציב. התקיפה הראשונה כזו נעשית בעונש של -1 לגלגול התקיפה, ועונש זה מחמיר בעוד -1 נוסף כל סיבוב עד לעונש מקסימלי של -5. אם היצור נמנע מלעשות תקיפה למשך סיבוב מלא, הוא מופחת לרמת עונש של -1 בסיבוב הבא. זה בדרך כלל לא משפיע על הטלת לחשים בזמן ריחוף, עם זאת.

</div>
<div class="spell" data-tag="Light*" id="Light*">

## אור*

טווח: 36 מטר

כוהן 1, קוסם 1

משך: 6 תורות + 1/דרגה

לחש זה יוצר אור השווה לאור לפיד שמאיר שטח ברדיוס של 9 מטר) סביב מיקום או חפץ המטרה. האפקט אינו נייד אם הוא מוטל על שטח, אך ניתן להטילו על חפץ נייד. אור שנלקח לאזור של חושך קסום אינו פועל.

בהיפוך, **אור** הופך ל**חושך**, יוצר אזור של חושך בדיוק כפי שתואר לעיל. חושך זה חוסם ראיית חושך ומבטל מקורות אור רגילים.

לחש אור עשוי להיות מוטל כדי לנטרל ולבטל לחש חושך של מטיל באותה דרגה או נמוכה יותר (ולהיפך). פעולה זו גורמת לשני הלחשים להפסיק מיד, ומשיבה את רמת האור הסביבתית הקיימת.

כל גרסה של לחש זה עשויה לשמש לעיוור יריב על ידי הטלתו על איברי הראייה של המטרה. המטרה רשאית לגלגל הצלה נגד קרן מוות כדי להימנע מההשפעה, ואם ההצלה מצליחה, הלחש אינו נכנס לתוקף כלל. לחש **אור** או **חושך** המוטל לעיוור אינו משפיע על האזור הנתון (כלומר, לא נפלט אור או חושך סביב הקורבן).

</div>
<div class="spell" data-tag="Lightning Bolt" id="Lightning Bolt">

## ברק

טווח: 30 מטר + 3 מטר/דרגה

קוסם 3

משך: מיידי

הטלת לחש זה גורמת לניצוץ בהיר ודק בעובי חוט לעוף מאצבע המצביעה של המטילה, שמצביעה על הכיוון. הניצוץ נמתח במהירות כמו חץ עד שהוא מגיע למרחק שנבחר על ידי המטילה (אך לא יותר מהטווח הנתון לעיל) או פוגע במשטח מוצק או נוזלי, ובאותו רגע הוא מתפוצץ לברק מלא המשתרע עוד 18 מטר נוספים. הברק עובר דרך שטח ברוחב 1.5 מטר, מקפץ ומדלג, כך שבעוד שהוא לא באמת ברוחב 1.5 מטר, למטרות משחק הוא נחשב כאילו הוא כזה.

אלו שבתחום הברק סובלים 1d6 נקודות נזק לכל דרגת מטילה, עם גלגול הצלה נגד לחשים המותר לחצי נזק.

אם ברק מכוון לגוף מים, הוא מתפוצץ בנקודת הפגיעה, כפי שתואר לעיל, אך בתוך נפח המים שנפגע הוא מתפשט כמו כדור אש לרדיוס מקסימלי של 6 מטר במקום לפעול כפי שהוא עושה באוויר. אם ברק מוטל מתחת למים, הוא מתפוצץ באותו אופן, אך בקצה אצבעה המושטת של המטילה.

הברק מצית חומרים דליקים וגורם נזק לחפצים בדרכו. הוא יכול לגרום נזק למתכות עם נקודת התכה נמוכה; מתכות כמו זהב, כסף, עופרת, נחושת או ברונזה עשויות להתרכך לזמן קצר ולכן להתעוות, אך הברק אינו נמשך מספיק זמן כדי להמיס את החפצים המתכתיים אלא אם הם קטנים מאוד (כגון שרשרת זהב דקה למשל).

אם הנזק שנגרם למחסום מתערב שובר או חודר דרכו, הברק עשוי להמשיך מעבר למחסום אם טווח הלחש מאפשר; אחרת, הוא עשוי להשתקף מהמחסום חזרה לעבר המטילה, או בכיוון אקראי לפי שיקול דעתה של המנחה. יצורים שכבר הושפעו מהברק אינם סובלים נזק נוסף אם נפגעים מההשתקפות של אותו ברק.

</div>
<div class="spell" data-tag="Locate Object" id="Locate Object">

## איתור חפץ

טווח: 108 מטר

כוהן 3, קוסם 2

משך: 1 סיבוב/דרגה

לחש זה מעניק למטילה ידע על מיקום חפץ. המטילה חייבת להכיר את החפץ היטב או להיות מסוגלת לדמיין אותו בבירור. (צפייה בציור או תמונה מדויקת תספיק לאפשרות האחרונה.) ניתן לאתר פריט כללי; אם יותר מפריט אחד כזה נמצא בטווח, הלחש יוביל את המטילה אל הקרוב ביותר.

פריטים ייחודיים או יוצאי דופן יכולים להימצא רק אם למטילה יש ידע ממקור ראשון (לא רק באמצעות חיזוי כמו **ראיית הנסתר** או **כדור בדולח**). הלחש לא יכול לשמש לאיתור יצורים מכל סוג שהוא. שכבת עופרת או זהב דקה כמו נייר המקיפה את החפץ תמנע את איתורו.

</div>
<div class="spell" data-tag="Lower Water" id="Lower Water">

## הורדת מים

טווח: 6 מטר/דרגה

קוסם 6

משך: 1 תור/דרגה

באמצעות לחש זה המטילה מורידה את מפלס המים בנהר, אגם או אפילו בים בעד 0.5 מטר לכל דרגת מטילה למשך הזמן הנתון, אך לא לפחות מ-1 אינץ' עומק. הלחש משפיע על שטח ברדיוס של לכל היותר 3 מטר לכל דרגה, במרכז המיקום שנבחר על ידי המטילה (בתוך הטווח הנתון).

יהיה שיפוע תלול עד לפני השטח של כל אזור מים שלא הורד שנמצא מחוץ לרדיוס הלחש. ספינות שכבר היו באזור ההשפעה כמו גם כל אלו שמעיזות להיכנס אליו לא יוכלו לטפס על השיפוע ולכן לא יוכלו לעזוב את האזור (אם לא ייחסמו על ידי הלחש מלכתחילה).

ללחש זה יש את ההשפעה של **האטה** (ההיפוך של **האצה**) כאשר הוא מוטל על אלמנטלים של מים ויצורים אחרים שנוצרו ממים; גלגול הצלה נגד לחשים מותר, עם הצלחה מבטלת את ההשפעה. לא ניתן להטילו על כל סוג אחר של יצורים.

</div>
<div class="spell" data-tag="Magic Jar" id="Magic Jar">

## צנצנת קסם

טווח: 18 מטר

קוסם 5

משך: מיוחד

לחש זה מאפשר למטיל הלחש לנסות להשתלט על גופו של יצור חי אחר. המטיל מתחיל בהעברת רוחו לאבן חן, תכשיט או קריסטל גדול כלשהו בטווח הלחש, הנקרא צנצנת הקסם. המטיל צריך לדעת היכן נמצאת צנצנת הקסם, אך אין צורך שתהיה לו יכולת לראות אותה. בזמן שרוחו של המטיל מחוץ לגופו, הגוף נראה לכל דבר ועניין כמת, אך אינו עובר ריקבון כפי שגוף מת רגיל היה עובר.

בכל סיבוב לאחר הכניסה לצנצנת הקסם, רוחו של המטיל יכולה לנסות להשתלט על גופו של יצור חי בטווח הלחש; המטרה מקבלת גלגול הצלה נגד לחשים כדי להתנגד. אם גלגול ההצלה נכשל, רוחו של היעד (כעת נקרא המארח) נלכדת בצנצנת הקסם ורוחו של המטיל משתלטת על גופו של המארח. השתלטות על יצור באמצעות לחש זה נחסמת על ידי **הגנה מרוע** או מחסום דומה.

אם הניסיון להשתלט על הקורבן נכשל, רוחו של המטיל נשארת בצנצנת הקסם, והיצור המטרה חסין לניסיונות נוספים למשך הלחש. המטיל יכול לנסות להשתלט על מטרה אחרת בסיבוב הבא, אם ירצה.

אם לעומת זאת הניסיון להשתלטות מצליח, המטיל יכול להישאר בשליטה על גופו של המארח כל עוד ירצה. רוחו של המטיל יכולה לחזור לצנצנת הקסם בכל עת כשהיא בטווח הלחש, ולהחזיר את רוחו של המארח לגופו. המטיל לא יכול לחזור לגופו של אותו מארח שוב למשך שארית משך הלחש, אך יכול לנסות להשתלט עליו שוב בלחש הבא.

בכל פעם שרוחו של המטיל נמצאת בצנצנת הקסם, היא יכולה לבחור לחזור לגופה אם הוא בטווח הלחש. אם הגוף אינו בטווח, רוחו של המטיל עלולה להילכד אם אין יצורים פגיעים בטווח.

בכל פעם שרוחו של המטיל חוזרת לגופו, הלחש מסתיים. יש סיכוי של 50% שצנצנת הקסם תתנפץ כשהלחש מסתיים (אם הלחש לא הסתיים כי נשבר), ותהפוך לחסרת ערך ולא ניתנת לשימוש.

כאשר רוחו של המטיל משתלטת על מארח, למטיל יש גישה ליכולות הפיזיות של גופו של המארח, כולל כוח, זריזות וחוסן, תוך שמירה על תבונתו, חוכמתו וכריזמתו שלו. למטיל יש גישה רק לידע שלו, למקצוע ולדרגה שלו, לבונוס התקיפה, לגלגולי ההצלה, ליכולת הטלת הלחשים ולכל יכולת מנטלית טהורה אחרת.

המטיל לא מקבל גישה לכוחות על-טבעיים או יוצאי דופן של המארח, ואולי לא יוכל לבצע פעולות פיזיות שמעולם לא ביצע קודם לכן (כגון תעופה, אם השתלט על גוף מכונף). למטיל יש גישה ליכולות החושיות של המארח, כגון ראיית חושך, חוש הריח המוגבר של כלב, וכדומה.

אם רוחו של המטיל נמצאת בצנצנת הקסם, והצנצנת נשברת (בין אם על ידי **ביטול קסם** או נזק פיזי), רוחו של המטיל תחזור לגופה אם הוא בטווח הלחש; אם לא, רוחו של המטיל עוזבת (כלומר, המטיל מת). בכל מקרה, הלחש מסתיים.

אם רוחו של המטיל מגורשת מגוף המארח על ידי ביטול רוע, וצנצנת הקסם בטווח מגוף המארח, רוחו של המטיל חוזרת לצנצנת ורוחו של המארח חוזרת לגופו. המטיל לא יוכל להשתלט שוב על אותו מארח למשך שארית משך הלחש. אם צנצנת הקסם אינה בטווח מגוף המארח, רוחו של המטיל עוזבת, רוחו של המארח משתחררת מהצנצנת ועוזבת גם היא, וגופו של המארח מת.

אם רוחו של המארח נמצאת בצנצנת הקסם, והצנצנת נשברת בזמן שהיא בטווח מגוף המארח, רוחו של המטיל עוזבת, רוחו של המארח חוזרת לגופו, והלחש מסתיים. אם הצנצנת נשברת בזמן שהיא מחוץ לטווח מגוף המארח, רוחו של המארח עוזבת, רוחו של המטיל נתקעת בגוף המארח. שימו לב כאן שהלחש לא הסתיים. **ביטול רוע** עדיין יכול לשמש כדי לגרש את רוחו של המטיל מהגוף, שתעזוב כפי שצוין, והלחש יסתיים. מטיל שנתקע יכול להשתמש בלחש נוסף זה (עם צנצנת קסם אחרת, כמובן) כדי לחזור לגופו, מה שכמובן הורג את גופו של המארח.

</div>
<div class="spell" data-tag="Magic Missile" id="Magic Missile">

## טיל קסם

טווח: 30 מטר+3 מטר/דרגה

קוסם 1

משך: מיידי

לחש זה גורם לטיל של אנרגיה קסומה לירות מאצבעו של המטיל ולפגוע במטרתו, שחייבת להיות לפחות חלקית נראית למטיל, ולגרום ל-1d6+1 נקודות נזק. הטיל פוגע ללא כשלון. לא ניתן לבחור חלקים ספציפיים של יצור. חפצים דוממים אינם ניזוקים מהלחש.

לכל שלוש דרגות מטיל מעבר לדרגה 1, נורה טיל נוסף — שניים בדרגה 4, שלושה בדרגה 7, ארבעה בדרגה 10, והמקסימום של חמישה טילים בדרגה 13 או יותר. אם המטיל יורה מספר טילים, הוא או היא יכולים לכוון לייצור יחיד או למספר יצורים. טיל יחיד יכול לפגוע רק ביצור אחד. יש לקבוע את המטרות לפני גלגול הנזק.

</div>
<div class="spell" data-tag="Magic Mouth" id="Magic Mouth">

## פה קסום

טווח: 9 מטר

קוסם 1

משך: מיוחד

לחש זה מטיל צורה פשוטה של אשליה מתוכנתת על חפץ דומם בטווח. כאשר מופעל, הלחש גורם להופעת אשליה של פה על החפץ ולהשמעת הודעה בקול רם. הכישוף יכול להישאר במקום ללא הגבלת זמן, אך מתכלה כאשר מופעל (כלומר, ההודעה נמסרת בדרך כלל רק פעם אחת).

ההודעה יכולה להיות באורך של עד שלוש מילים לכל דרגת מטיל. המטיל יכול להכניס הפסקות בהודעה, אך כל ההודעה חייבת להימסר בפרק זמן של לא יותר מתור. קול הלחש יכול להישמע בכל עוצמה שניתן להשיג על ידי אדם רגיל. הוא יישמע מספיק כמו קולו של המטיל כדי להיות מזוהה על ידי מכר קרוב של המטיל, אך לא זהה.

הפה האשלייתי נע כאילו הוא מדבר את ההודעה הנמסרת, ונשאר גלוי במהלך ההפסקות. אם הונח על תיאור אמנותי של יצור עם פה (כגון ציור או פסל), הלחש יכול להיראות כאילו הוא מפעיל את פיו של החפץ.

לחש זה לא יכול לשמש להפעלת חפצים קסומים שיש להם מילות פקודה, ולא להפעלת כל השפעה קסומה אחרת.

המטיל חייב לבחור את התנאים שבהם הלחש הזה מופעל. התנאים יכולים להיות מסובכים או פשוטים ככל שירצה, אך חייבים להסתמך רק על ראייה ושמיעה; ללחש אין יכולות חישה אחרות. ללחש גם אין אינטליגנציה מסוימת, וניתן להטעות אותו על ידי תחפושות או אשליות. ללחש יש את היכולת לראות ביעילות בחושך רגיל, אך לא בכל סוג של חושך קסום, והוא אינו יכול לזהות יצורים בלתי נראים או לראות דרך דלתות, קירות או אפילו וילונות אטומים. כמו כן, התגנבות או שתיקה קסומה יעילים במניעת הפעלות קוליות. לבסוף, הלחש אינו יכול לזהות את מקצועו, דרגתו, ציוני היכולת או כל תכונה אחרת שאינה ברורה ל-NPC רגיל.

להפעלות יש טווח חישה אפקטיבי של 3 מטר לכל דרגת מטיל; קולות, מראות או פעולות מחוץ לטווח זה לעולם לא יפעילו את הלחש.

</div>
<div class="spell" data-tag="Massmorph" id="Massmorph">

## מסמורף

טווח: 30 מטר+3 מטר/דרגה

קוסם 4

משך: 1 שעה/דרגה

עם לחש זה המטיל גורם ל-1d4+1 יצורים בגודל אדם (או קטנים יותר) לכל ארבע דרגות מטיל להיראות כאילו הם תופעות טבעיות של השטח (למשל, עצים ביער, נטיפים במערה, אלמוגים מתחת למים, סלעים במערה, וכו'). כל היצורים שיש להסתירם חייבים להיות בטווח של 36 מטר מהמטיל בזמן הטלת הלחש. רק היצורים שהמטיל רוצה להסתיר מושפעים, ורק אם הם מוכנים להיות מוסתרים. המטיל יכול לכלול את עצמו או את עצמה בין היצורים המושפעים.

המושפעים מוסתרים כך מיצורים אחרים העוברים באזור כל עוד הם נשארים ללא תנועה. אם יצור מושפע בוחר לזוז או לתקוף, האשליה מתבטלת עבור אותו יצור, אך אלו שנשארים ללא תנועה ממשיכים להיות מוסתרים. המטיל יכול לסיים את הלחש מוקדם אם ירצה על ידי אמירת מילה אחת. האשליה יכולה גם להסתיים על ידי **ביטול קסם**.

</div>

<div class="spell" data-tag="Mind Control" id="Mind Control">

## קריאת מחשבות

טווח: 18 מטר

קוסם 2

משך: 1 תור/דרגה

לחש זה, המכונה לפעמים בטעות **ESP**, מאפשר למטיל לשמוע (ואולי לראות, אם המטרה מדמיינת משהו) את המחשבות השטחיות של יצור אחד או יותר בטווח. המטיל חייב לבחור כיוון או לבחור מטרה נראית, ואז להתרכז למשך תור כדי "לשמוע" את המחשבות. בכל תור המטיל יכול לבחור "להאזין" בכיוון אחר. המטיל יכול להפסיק להאזין, ואז להמשיך שוב מאוחר יותר, כל עוד המשך לא פג. היצור המטרה בדרך כלל אינו מודע לכך שמרגלים עליו בדרך זו, אם כי כל יצור שכבר נמצא תחת השפעת לחש זה או כל צורה דומה של טלפתיה יידע מיד ויוכל לחוש את כיוון המטיל.

סלע בעובי של יותר מ-2 אינץ' או אפילו כיסוי דק מאוד של עופרת או זהב יחסום את הלחש. כל היצורים המתים חסינים להשפעה זו, כמו גם יצורים חסרי תודעה ומבנים כמו גולמים.

</div>

<div class="spell" data-tag="Mirror Image" id="Mirror Image">

## דמות מראה

טווח: עצמי

קוסם 2

משך: 1 תור/דרגה

לחש זה מאפשר למטיל ליצור כפילים אשלייתיים מרובים (הנקראים דמויות) שנראים מסתובבים ונעים סביב ובתוך זה את זה כמו גם סביב המטיל כמעט כל הזמן, מה שהופך את זה לבלתי אפשרי עבור רוב היצורים לקבוע מי הוא האמיתי. סך של 1d4 דמויות פלוס דמות אחת לכל שלוש דרגות מטיל (מקסימום שמונה דמויות בסך הכל) נוצרות.

הדמויות מחקות את פעולות המטיל, עוברות את תנועות הטלת הלחשים, שתיית השיקויים, ריחוף, וכדומה, בדיוק כפי שהמטיל עושה. הדמויות תמיד נראות בדיוק כמו המטיל.

כל יריב שתוקף או מטיל לחשים ישירות על המטיל תמיד יפגע בדמות במקום זאת. תקיפת דמות משמידה אותה, בין אם גלגול ההתקפה מצליח ובין אם לא, כמו גם כל לחש התקפה המכוון לאחת. לחשים בעלי השפעה אזורית אינם מוטלים ישירות על המטיל, ולכן נראים משפיעים על כל הדמויות בדיוק כפי שהם משפיעים על המטיל; לדוגמה, אם המטיל נתון ל**כדור אש**, כל הדמויות ייראו פגועות בדיוק כפי שהמטיל נפגע.

</div>
<div class="spell" data-tag="Neutralize Poison*" id="Neutralize Poison*">

## נטרול רעל*

טווח: מגע

כוהן 4

משך: מיידי

לחש זה מנטרל כל סוג של רעל ביצור או חפץ שנגעו בו. יצור מורעל לא יסבול מהשפעות נוספות מהרעל; אם הלחש מוטל על יצור שנהרג מרעל ב-10 הסיבובים האחרונים, היצור יוחזר לחיים עם 1 נקודת פגיעה. אם הלחש מוטל על חפץ רעיל (נשק, מלכודת וכו'), הרעל יהפוך לבלתי יעיל לצמיתות.

בהיפוך, לחש זה הופך ל**רעל**. המטילה חייבת לבצע גלגול תקיפה מוצלח; אם ההתקפה מצליחה, המטרה חייבת לגלגל הצלה נגד רעל או למות. המגע של המטילה נשאר רעיל למשך סיבוב אחד לכל דרגת יכולת, או עד לפריקה (כלומר רק יצור אחד יכול להיות מושפע מהלחש ההפוך).

</div>
<div class="spell" data-tag="Passwall" id="Passwall">

## מעבר קיר

טווח: 9 מטר

קוסם 5

משך: 3 תורות

מעבר קיר יוצר מעבר דרך קירות עץ, טיח או אבן, אך לא דרך מתכת או חומרים קשים יותר. המעבר יכול להיות עד 3 מטר עומק ועוד 3 מטר עומק לכל שלוש דרגות מטילה מעל דרגה 9 (6 מטר בדרגה 12, 9 מטר עומק בדרגה 15, 12 מטר עומק בדרגה 18). אם עובי הקיר גדול מעומק המעבר שנוצר, מעבר קיר אחד פשוט יוצר נישה או מנהרה קצרה. מספר לחשי מעבר קיר יכולים ליצור מעבר מתמשך כדי לפרוץ קירות עבים מאוד. כאשר מעבר קיר מסתיים (בגלל משך הזמן, **ביטול קסם**, או בחירת המטילה), יצורים בתוך המעבר נפלטים החוצה ליציאה הקרובה ביותר.

</div>
<div class="spell" data-tag="Phantasmal Force" id="Phantasmal Force">

## כוח פנטסמלי

טווח: 54 מטר

קוסם 2

משך: ריכוז

לחש זה יוצר אשליה חזותית של חפץ, יצור (או קבוצה קטנה של יצורים), או אפקט אחר, כפי שמדמיינת המטילה עד לגודל מקסימלי של 6 מטרx6 מטרx6 מטר. האשליה לא יוצרת קול, ריח, מרקם או טמפרטורה. המטילה יכולה להנפיש את התמונה בתוך גבולות שטח ההשפעה. התמונה נמשכת כל עוד המטילה מתרכזת בה.

אם משתמשים בלחש כדי ליצור אשליה של יצור אחד או יותר, יהיה להם דירוג שריון של 11 והם ייעלמו אם ייפגעו בקרב. נזק שנגרם על ידי מפלצות, לחשים וכו' המדומים על ידי לחש זה אינו אמיתי; אלו ש"נהרגו" או נראים מושבתים יתעוררו ללא פגע (לפחות מלחש זה) לאחר 2d8 סיבובים. הנזק האשלייתי שנגרם יהיה שווה לנזק הרגיל לכל צורת התקפה המדומה.

ניסיון להנפיש יותר יצורים מדרגת המטילה מעניק ליצורים הצופים עם לפחות תבונה ממוצעת גלגול הצלה מיידי נגד לחשים כדי לזהות את היצורים כאשליות; אלו שמצליחים בגלגול לא יושפעו מכל פעולה שנעשית על ידי האשליות מאותו רגע ואילך. גלגול הצלה דומה עשוי להינתן על ידי המנחה בכל פעם שהיא מרגישה שהאשליה עשויה להיחשף, במיוחד אם השחקן מתאר אשליה שנראית בלתי סבירה או מתוכננת בצורה גרועה.

</div>
<div class="spell" data-tag="Polymorph Other" id="Polymorph Other">

## שינוי צורה לאחר

טווח: 9 מטר

קוסם 4

משך: קבוע

לחש זה מאפשר למטילה לשנות מטרה אחת לצורה אחרת של יצור חי. הצורה המתקבלת לא יכולה להיות בעלת יותר קוביות פגיעה מדרגת המטילה, או להיות חסרת גוף או גזית. בניגוד ל**שינוי צורה עצמי**, המטרה המוסבת גם מקבלת את התכונות ההתנהגותיות והמנטליות, כל התקפות פיזיות, יכולות מיוחדות, על-טבעיות או דמויות לחש של הצורה החדשה, בנוסף ליכולות הפיזיות והסטטיסטיקות של זו. אם הצורה החדשה היא בעלת תבונה פחותה משמעותית, המטרה עשויה לא לזכור את חייה הקודמים.

ליצור המטרה יהיו אותו מספר נקודות פגיעה שהיו לו קודם, ללא קשר לקוביות הפגיעה של הצורה המתקבלת. יצורים חסרי גוף או גזיים חסינים ללחש זה, כפי שנאמר לעיל. יצור עם יכולות שינוי צורה כמו דופלגנגר יכול לחזור לצורתו הטבעית לאחר סיבוב אחד.

ציוד שנלבש או נישא ייפול אם הצורה החדשה לא יכולה ללבוש או לשאת את הפריטים. אם פריטים כאלה יהיו מגבילים או מזיקים פיזית לצורה החדשה, השינוי מאט ומשתנה כך שהם ייפלו ללא נזק לפריטים וללא פגיעה ליצורת המטרה. אם המנחה קובעת כי פריטים כלשהם לא יכולים להיות מוסרים בדרך זו, עליה להחליט על התוצאות המדויקות.

מטרות לא רצויות שמצליחות בגלגול הצלה נגד שינוי צורה אינן מושפעות. הלחש הוא קבוע עד לביטולו או עד שהיצור נהרג, ובאותו זמן המטרה חוזרת לצורתה המקורית.

</div>
<div class="spell" data-tag="Polymorph Self" id="Polymorph Self">

## שינוי צורה עצמי

טווח: עצמי

קוסם 4

משך: 1 שעה/דרגה

לחש זה מאפשר למטילה לשנות לצורה אחרת של יצור חי. הצורה המתקבלת לא יכולה להיות בעלת יותר קוביות פגיעה מדרגות המטילה, או להיות חסרת גוף או גזית.

המטילה מקבלת את הטבע הפיזי של הצורה המתקבלת תוך שמירה על התכונות המנטליות והרוחניות שלה. היא מקבלת את דירוג השריון וכל ההתקפות הפיזיות של הצורה אך לא מקבלת יכולות מיוחדות, על-טבעיות או דמויות לחש. נשימת דרקון היא יכולת מיוחדת, למשל, כך שאם המטילה תבחר בצורת דרקון היא תוכל להשתמש בהתקפות הטפרים, הנשיכה והזנב של הדרקון, אך לא בנשימת הדרקון.

אם הצורה המתקבלת מסוגלת לדבר ולבצע מחוות מתאימות (כפי שנקבע על ידי המנחה) המטילה יכולה להשתמש בלחשים שלה בצורתה המתקבלת.

ציוד שנלבש או נישא ייפול אם הצורה החדשה לא יכולה ללבוש או לשאת את הפריטים. אם פריט כזה יהיה מגביל או מזיק פיזית לצורה החדשה, השינוי מאט ומשתנה כך שהפריט ייפול ללא נזק לפריטים וללא פגיעה ליצורת המטרה. אם המנחה מחליטה שפריט כזה לא יכול להיות מוסר בדרך זו, הלחש נכשל.

המטילה יכולה להישאר בצורתה המוסבת עד שעה אחת לכל דרגת יכולת, או יכולה לבחור לסיים את הלחש לפני כן אם היא רוצה.

</div>
<div class="spell" data-tag="Projected Image" id="Projected Image">

## דמות מוקרנת

טווח: 72 מטר

קוסם 6

משך: 6 תורות

לחש זה יוצר גרסה כמעין-אמיתית, אשלייתית של המטילה. דמות מוקרנת זו נראית, נשמעת ומריחה כמו המטילה, בנוסף לחיקוי מחוות ופעולות (כולל דיבור, שמוקרן מהמטילה לדמות האשלייתית כאילו באמצעות סוג של **בִּטוּן קוֹל**). כל לחשים נוספים שנשלחים נראים כאילו הם נובעים מהאשליה, ולא מהמטילה האמיתית.

קו ראייה בין המטילה לדמותה האשלייתית חייב להישמר או שהלחש מסתיים. כל אפקט או פעולה שמפרים את קו הראייה מבטלים את הדמות, כמו גם אם הדמות האשלייתית נפגעת בקרב. שימו לב שלחש זה לא מעניק כוחות חישה מיוחדים למטילה; לדוגמה, אם הדמות האשלייתית ממוקמת כך שתוכל לראות משהו שהמטילה לא יכולה לראות ישירות, המטילה לא תראה אותו. כמו כן, כל טווחי הלחשים עדיין מחושבים ממיקום המטילה האמיתית, ולא ממיקום הדמות האשלייתית.

</div>
<div class="spell" data-tag="Protection from Evil*" id="Protection from Evil*">

## הגנה מרוע*

כוהן 1, קוסם 1

טווח: מגע

משך: 1 תור/דרגה

לחש זה מגן על המטילה או על יצור שנגע בו המטילה (ה"נושא") מרוע; באופן ספציפי, הלחש מגן מפני יצורים מזומנים, יצורים עם כוונות רעות משמעותיות, ויצורים חוצניים בעלי טבע רע. מחסום קסום עם רדיוס של 0.5 מטר בלבד נוצר סביב הנושא. המחסום נע עם הנושא, ומספק שלוש צורות ספציפיות של הגנה קסומה מפני התקפות או השפעות אחרות שניסו היצורים המושפעים על הנושא.

ראשית, הנושא מקבל בונוס של +2 לדירוג השריון שלו, ובונוס דומה של +2 על כל גלגולי ההצלה. שנית, המחסום חוסם כל ניסיון ל**קסם** או לשלוט אחרת בנושא, או להשתלט על הנושא (כמו עם **צנצנת קסם**). ניסיונות כאלה פשוט נכשלים במהלך משך הלחש. שימו לב עם זאת שיצור שמקבל הגנה זו לאחר שהשתלטו עליו לא נרפא מההשתלטות.

שלישית, כל היצורים המזומנים והיצורים החוצניים בעלי טבע רע אינם יכולים לגעת פיזית בנושא. התקפות על ידי יצורים כאלה באמצעות נשקיהם הטבעיים פשוט נכשלות. אפקט זה מבוטל אם הנושא מבצע כל סוג של התקפה פיזית (אפילו עם נשק טווח) על כל יצור מושפע, אך שאר תכונות הלחש ממשיכות לפעול.

בהיפוך, לחש זה הופך ל**הגנה מטוב**. הוא פועל בכל הדרכים כפי שתואר לעיל, למעט שיצורים "טובים" נשמרים במרחק, ולא "רעים".

</div>
<div class="spell" data-tag="Protection from Evil 3 מטר Radius*" id="Protection from Evil 3 מטר Radius*">

## הגנה מרוע ברדיוס 3 מטר*

כוהן 4, קוסם 3

טווח: מגע

משך: 1 תור/דרגה

לחש זה פועל בדיוק כמו **הגנה מרוע**, אך עם רדיוס של 3 מטר במקום רדיוס של 0.5 מטר. כל מי שנמצא בתוך הרדיוס מקבל את ההגנה; אלו שעוזבים ואז חוזרים, או שנכנסים לאחר שהלחש הוטל, מקבלים את ההגנה גם כן.

בהיפוך, לחש זה הופך ל**הגנה מטוב ברדיוס 3 מטר**, ופועל בדיוק כמו הצורה ההפוכה של **הגנה מרוע**, למעט שהוא מכסה רדיוס של 3 מטר סביב המטרה ולא הרדיוס הרגיל של 0.5 מטר.

</div>
<div class="spell" data-tag="Protection from Normal Missiles" id="Protection from Normal Missiles">

## הגנה מקליעים רגילים

קוסם 3

טווח: עצמי

משך: 1 תור/דרגה

המטילה מוגנת לחלוטין מהתקפות קליעים קטנים, לא קסומים. לכן, חיצים קסומים, סלעים מושלכים או דומים אינם נחסמים, אך כל מספר של חיצים רגילים, כדורי קלע, בריחי קשת, פגיונות מושלכים וכו' יידחו. שימו לב שקליעים רגילים המושלכים על ידי קשתות קסומות נחשבים לקליעים קסומים לצורך לחש זה.

</div>
<div class="spell" data-tag="Purify Food and Water" id="Purify Food and Water">

## טיהור מזון ומים

כוהן 1

טווח: 3 מטר

משך: מיידי

עם לחש זה המטילה הופכת מזון או מים מזוהמים לטהורים ובטוחים לאכילה או שתייה. רעל מנוטרל וקלקול מתהפך על ידי לחש זה. הלחש אינו מגן מפני ריקבון עתידי, עם זאת, ואינו משפיע על שיקויים קסומים (כולל, למרבה הצער, **שיקויי רעל**). מים לא קדושים, אם הם קיימים בקמפיין שלך, נהרסים על ידי הטלת לחש זה. הלחש משפיע על כ-1 ק"ג של מזון ו/או שתייה לכל דרגת מטילה; שימו לב שכרבע מים או שתייה דומה שוקלים מעט יותר מ-1 ק"ג.

</div>
<div class="spell" data-tag="Quest*" id="Quest*">

## משימה*

טווח: 1.5 מטר/דרגה

כוהן 5

משך: מיוחד

באמצעות לחש זה המטילה מכריחה יצור חי לבצע פעולה או שירות מסוים, או לחלופין להימנע מביצוע פעולה מסוימת. יצור המטרה חייב להיות מסוגל לשמוע ולהבין את המטילה, אחרת הוא לא יכול להיות מושפע. לחש זה ייכשל אוטומטית אם משתמשים בו כדי להכריח יצור לעסוק בפעולה הרסנית עצמית באופן ברור.

גלגול הצלה נגד לחשים יאפשר למטרה לא מרצון להתנגד למשימה כאשר היא מוטלת לראשונה. עם זאת, המטרה עשויה לבחור לקבל את המשימה, בדרך כלל כחלק מעסקה עם המטילה לבצע שירות כלשהו. לאחר שהוטל עליה לחש זה, על הנושא לציית להוראות שניתנו על ידי המטילה ללא הגבלת זמן, אם כי אם המשימה היא לבצע פעולה כלשהי, הלחש למעשה מסתיים כאשר פעולה זו הושלמה.

על כל 24 שעות שיצור מושפע בוחר לא לציית למשימה (או נמנע מלעשות זאת), הוא סובל 3d6 נקודות נזק. נזק זה מוגבל, בכך שהוא לא יהרוג את המטרה; אם הנזק מספיק כדי לעשות זאת, יש לגלגל 1d4 עבור מספר נקודות הפגיעה שהיצור המושפע שומר (בדומה ללחש **פגיעה**, ההפוך של **ריפוי**).

אם המשימה שהוטלה על נושא לחש זה היא פתוחה או שאינה ניתנת להשלמה, הנושא עדיין מחויב לנסות לבצע את המשימה, אך הלחש יסתיים לא יותר מיום אחד לכל דרגת מטילה.

יצורים חכמים מאוד עשויים להיות מסוגלים לעקוף את ההוראות שניתנו; על המנחה להחליט על תוצאות של כל ניסיונות כאלה.

משימה (וכל ההשפעות שלה) יכולה להסתיים על ידי לחש **הסרת קללה** ממטילה בדרגה גבוהה יותר בשתי דרגות או יותר ממטילת המשימה, או על ידי משאלה, או על ידי ההפוך של לחש זה. **הסרת קסם** אינה משפיעה על לחש משימה.

</div>
<div class="spell" data-tag="Raise Dead*" id="Raise Dead*">

## החייאת מתים*

טווח: מגע

כוהן 5

משך: מיידי

לחש זה מחזיר חיים לדמות אדם שנפטרה (כפי שמוגדר ב**קסם אדם**). המטילה יכולה להחיות רק ישות שלא מתה יותר ימים ממספר הדרגות של המטילה. רוח המטרה של לחש זה חייבת להיות מוכנה לחזור. אם רוח המטרה כלואה או מוגבלת בכל דרך שהיא, הלחש ייכשל. הוא גם ייכשל אם המטרה מתה מזקנה, שכן הגוף פשוט אין בו חיים יותר. באופן דומה, יצורים מתים-חיים אינם מושפעים מלחש זה שכן הם כבר לא יכולים לחזור לחיים במובן רגיל.

גוף המטרה חייב להיות שלם מספיק כדי לתמוך בחיים, אך כל הפצעים, לא משנה כמה חמורים, נרפאים. חלקי גוף שחסרים כאשר המטרה מוחזרת עדיין חסרים לאחר מכן. רעל רגיל ומחלות רגילות נרפאים בתהליך החייאת הנושא, אך מחלות קסומות וקללות אינן מבוטלות.

יצורים שהוחזרו מהמתים תמיד סובלים מאובדן או עונש כלשהו מהחוויה. דמויות מאבדות דרגה אחת של יכולת לצמיתות (כלומר, זה לא מצטבר כדרגה שלילית, אלא מאבדת דרגה ממשית, ומופחתת למספר המינימלי של נקודות ניסיון הנדרשות לדרגה הקודמת). דמויות בדרגה ראשונה מופחתות למעמד אדם רגיל; אם הדמות הייתה כבר אדם רגיל היא מאבדת נקודת חוסן. אובדנים אלה הם קבועים, אם כי כמובן הדמות עשויה לעלות בדרגות בצורה רגילה. (דמויות שהופחתו למעמד אדם רגיל חייבות לצבור 1,000 נקודות ניסיון כדי לחזור לדרגה ראשונה).

דמויות אדם מפלצתיות (אורקים, גובלינים וכדומה) מאבדות קוביית פגיעה אחת, או מופחתות ל-½ קוביות פגיעה אם למפלצת יש רק אחת להתחיל איתה. דמויות אדם כאלה שכבר יש להן ½ קוביות פגיעה מופחתות לנקודת פגיעה אחת. אובדנים אלה הם בדרך כלל קבועים, אם כי המנחה עשויה לאפשר ליצורים כאלה בשירות דמות שחקן להתאושש על ידי צבירת 1,000 נקודות ניסיון לכל קוביית פגיעה שהיצור יחזור אליה (כך שאיש לטאה שהופחת לקוביית פגיעה אחת חייב לצבור 2,000 נקודות ניסיון כדי לחזור לשתי קוביות הפגיעה המקוריות שלו); יש להתייחס ליצורים כאלה כעוזרים למטרה זו.

עם החייאתו, למטרה יש נקודת פגיעה אחת לכל דרגה או קוביית פגיעה (באמצעות המספר המופחת הנוכחי שלה, כמובן), עם מינימום של נקודת פגיעה אחת. דמות שמתה עם לחשים מוכנים אין לה לחשים מוכנים עם החייאתה.

ההפוך של לחש זה, **הרג חי**, יהרוג מיד את היצור שנגעו בו (שיכול להיות מכל סוג, לא רק דמות אדם) אלא אם כן נעשה גלגול הצלה נגד לחשים. אם גלגול ההצלה מצליח, 2d6 נקודות נזק נגרמות לקורבן במקום זאת. יש צורך בגלגול תקיפה כדי להפעיל לחש זה בקרב.

</div>
<div class="spell" data-tag="Read Languages" id="Read Languages">

## קריאת שפות

טווח: 0

קוסם 1

משך: מיוחד

לחש זה מעניק למטילה את היכולת לקרוא כמעט כל שפה כתובה. ניתן להטיל אותו באחד משלושה מצבים:

במצב הראשון, הלחש מאפשר למטילה לקרוא כל מספר של יצירות כתובות במגוון שפות. מצב זה נמשך למשך תור אחד לכל דרגת מטילה.

במצב השני, הלחש מאפשר למטילה לקרוא ספר או כרך אחד; מצב זה נמשך 3 שעות לכל דרגת מטילה.

במצב השלישי, הלחש מאפשר למטילה לקרוא מגילה לא קסומה אחת או מסמך חד-דפי אחר; מצב זה הוא קבוע.

לחש זה אינו פועל על כל סוג של טקסט קסום, כגון מגילות לחשים או ספרי לחשים; ראה **קריאת קסם**, למטה, עבור הלחש הנכון לשימוש במקרים כאלה.

הלחש מעניק את היכולת לקרוא את הטקסטים, אך אינו מזרז את הקריאה בשום אופן ואינו מעניק הבנה של מושגים שהמטילה אינה יכולה להבין אחרת. בנוסף, כדי שלחש זה יפעל, חייב להיות לפחות יצור חי אחד שיכול לקרוא את השפה הנתונה באותו מישור. הידע אינו מועתק ממוחו של היצור; אלא, קיומו של הידע הוא שמאפשר ללחש לפעול.

</div>
<div class="spell" data-tag="Read Magic" id="Read Magic">

## קריאת קסם

טווח: 0

קוסם 1

משך: קבוע

כאשר מוטל על כל טקסט קסום, כגון ספר לחשים או מגילת לחשים של קוסם, לחש זה מאפשר למטילה לקרוא את הטקסט. הטלת לחש זה על טקסט מקולל תפעיל בדרך כלל את הקללה. כל הקוסמים מתחילים את המשחק כשהם יודעים לחש זה, וניתן להכינו גם אם הקוסם מאבד גישה לספר הלחשים שלו או שלה.

</div>
<div class="spell" data-tag="Regenerate" id="Regenerate">

## התחדשות

טווח: מגע

כוהן 6

משך: קבוע

לחש זה גורם לאיברי גוף כרותים של הנושא (אצבעות, בהונות, ידיים, רגליים, זרועות, רגליים, זנבות, או אפילו ראשים של יצורים רב-ראשיים), עצמות שבורות ואיברים הרוסים לצמוח מחדש. לאחר שהלחש מוטל, ההתחדשות הפיזית מושלמת תוך סיבוב אחד אם האיברים הכרותים נוכחים ונוגעים ביצור. אחרת, נדרש תור מלא להשלמת ההתחדשות.

לחש זה גם מרפא 3d8 נקודות נזק. התחדשות אינה משפיעה על יצורים לא חיים או מבנים (כולל מתים-חיים).

</div>
<div class="spell" data-tag="Reincarnate" id="Reincarnate">

## גלגול מחדש

טווח: מגע

קוסם 6

משך: מיידי

על ידי נגיעה בגופו של דמות אדם שנפטרה (כפי שמוגדר ב**קסם אדם**), המטילה מחזירה אותם בגוף חדש לחלוטין. הגוף כולו אינו נחוץ; למעשה, אפילו השבר הקטן ביותר של הגוף מספיק, כל עוד שבר זה היה חלק מהגוף בזמן מותו של המטרה.

המטילה יכולה לגלגל מחדש ישות שלא מתה יותר משבוע. רוח המטרה של לחש זה חייבת להיות מוכנה לחזור. אם רוח המטרה כלואה או מוגבלת בכל דרך שהיא, הלחש ייכשל.

גלגל בטבלה הבאה כדי לקבוע לאיזה סוג של יצור הדמות הופכת:

```{ojs}

import {generalTableSelect} from "../custom.js"

viewof reincarnate = Inputs.button("גלגל בטבלה", {value: 0, reduce: () => highlightTableRow("#reincarnate-spell", generalTableSelect([1,100,0],[[1,1],[2,15],[16,29],[30,30],[31,39],[40,46],[47,60],[61,88],[89,91],[92,93],[94,98],[99,100]]))})

```
<br>

:::{#reincarnate-spell}

| d% | גלגול מחדש |
|----|----|
| 01 | בוגביר |
| 02--15 | גמד |
| 16--29 | אלף |
| 30 | גנול |
| 31--39 | גנום |
| 40--46 | גובלין |
| 47--60 | בן-מחצית |
| 61--88 | אדם |
| 89--91 | קובולד |
| 92--93 | איש לטאה |
| 94--98 | אורק |
| 99--100 | בחירה* |

:::

אם "בחירה" מתגלגל עבור דמות שחקן שמגלגלת מחדש, השחקן רשאי לבחור את הצורה החדשה מבין אלו שבטבלה למעלה. אם דמות NPC מגלגלת מחדש, המנחה עשויה לבחור או לגלגל שוב.

כאשר הלחש מוטל, גוף חדש נוצר במיקום סמוך שנבחר על ידי המטילה. הגוף נוצר במשך 6 תורות (כלומר שעה), תחילה כצללית ערפילית, ואז הופך למוצק יותר מרגע לרגע עד שהוא נושם את נשימתו הראשונה ומתעורר. הצורה החדשה היא מבוגר צעיר, אלא אם המטרה הייתה צעירה מכך כאשר מתה, ובמקרה זה הגוף החדש הוא באותו גיל כמו הגוף שנפטר.

גופו החדש של היצור המטרה לא סבל כמובן מאף אחד מהנזקים שייתכן שנגרמו לגוף הישן, והוא בריא לחלוטין (לפחות, בהתחלה).

המטרה זוכרת את חייה הקודמים, ושומרת על אותה מקצוע (אם אפשרי לצורה החדשה) כמו גם על תבונה, חוכמה וכריזמה שלה. כוח, זריזות וחוסן צריכים להתגלגל מחדש. (אם ציוני היכולת של הדמות הם מחוץ לטווח המותר לצורה החדשה, יש להתאים אותם למעלה או למטה על ידי המנחה לפי הצורך.) המטרה מאבדת דרגה אחת (או קוביית פגיעה); זהו הפחתה אמיתית, לא דרגה שלילית, ואינה כפופה ל**שחזור** קסום. נקודות הפגיעה של המטרה צריכות להתגלגל מחדש לחלוטין, שכן זהו גוף חדש לחלוטין. אם המטרה הייתה בדרגה ראשונה, במקום הפחתת נקודות פגיעה, הציון החדש של חוסן מופחת ב-2.

דמויות שהופכות לדמויות אדם לא-דמויות (כגון אלף שחוזר כקובולד) ידרשו שיפוט על ידי המנחה; אם המטרה שהוחזרה היא דמות שחקן, המנחה מומלץ לתת לשחקן כמה שיותר חופש עם הצורה החדשה של הדמות. לעומת זאת, דמויות אדם לא-דמויות שחוזרות כדמויות יצטרכו את כל ציוני היכולת להתגלגל; דמויות כאלה יהיו בדרך כלל לוחמים בדרגה השווה לקוביות הפגיעה הקודמות של המטרה פחות 1, או כאנשים רגילים אם קוביות הפגיעה הקודמות של המטרה היו 1 או פחות.

יצורים מתים-חיים אינם מושפעים מלחש זה; יצורים כאלה כבר לא יכולים לחזור לחיים במובן רגיל.

</div>
<div class="spell" data-tag="Remove Curse*" id="Remove Curse*">

## הסרת קללה*

טווח: 9 מטר

כוהן 3, קוסם 4

משך: מיידי

לחש זה מסיר כל קללה רגילה שמטרידה יצור. הוא אינו מסיר בדרך כלל את הקללה מפריט קסום כגון חרב או שריון, אך דמות המוטרדת מפריט מקולל מסוג זה תשוחרר ממנו מספיק זמן כדי להשליך את הפריט (לפחות תור).

חלק מהקללות המיוחדות קשות יותר להסרה, ועשויות לדרוש מטילה בדרגה מינימלית מסוימת. מעט מאוד קללות שנוצרו על ידי ישויות אלוהיות לא ניתן להסיר על ידי לחש זה כלל.

ההפוך של לחש זה, הענקת קללה, מאפשר למטילה להטיל קללה על הנושא. גלגול הצלה נגד לחשים מותר להתנגד. המטילה חייבת לבחור באחת משלוש ההשפעות הבאות:

* הפחתה של 4- לציון יכולת (מינימום 1).

* עונש של 4- על גלגולי תקיפה והצלה.

* בכל סיבוב קרב, יש למטרה סיכוי של 50% לפעול כרגיל; אחרת, היא לא נוקטת בפעולה.

המטיל יכול גם להמציא קללה משלו או שלה, אך היא לא צריכה להיות חזקה יותר מאלו שתוארו לעיל. הקללה המוטלת לא ניתנת להסרה, אך ניתן להסירה באמצעות לחש **הסרת קללה**.

</div>
<div class="spell" data-tag="Remove Fear*" id="Remove Fear*">

## הסרת פחד*

טווח: מגע (36 מטר)

כוהן 1

משך: מיידי (2 תורות)

לחש זה ירגיע את היצור שנגעו בו. אם היצור המטרה נמצא כרגע תחת כל סוג של פחד קסום, הוא מקבל גלגול הצלה חדש נגד לחשים כדי להתנגד לפחד זה, עם בונוס של +1 לכל דרגת המטיל.

ההיפוך של לחש זה, **גרימת פחד**, גורם ליציר מטרה אחד בטווח של 36 מטר להפוך למפוחד; אם המטרה נכשלת בגלגול הצלה נגד לחשים, היא בורחת למשך 2 תורות. יצורים עם 6 קוביות פגיעה או יותר חסינים להשפעה זו.

</div>
<div class="spell" data-tag="Resist Cold" id="Resist Cold">

## עמידות לקור

טווח: מגע

כוהן 1

משך: 1 סיבוב/דרגה

לחש זה הופך את המטיל, או כל יצור חי שהמטיל נוגע בו, לחסין לחלוטין לקור רגיל. הלחש גם מעניק הגנה מפני קור קסום או עליון כמו נשימת דרקון קרח או לחש **סערת קרח**. באופן ספציפי, הלחש מעניק לייצור המוגן בונוס של +3 על כל גלגולי הצלה נגד השפעות כאלה, ומפחית כל נזק שנגרם בחצי (כך שלמשל הצלה מוצלחת נגד נשימת דרקון הקרח תקטין את הנזק לרבע מהרגיל, ואפילו אם גלגול ההצלה נכשל, היצור המוגן סופג רק חצי מהנזק).

</div>
<div class="spell" data-tag="Resist Fire" id="Resist Fire">

## עמידות לאש

טווח: מגע

כוהן 2

משך: 1 סיבוב/דרגה

לחש זה הופך את המטיל, או כל יצור חי שהמטיל נוגע בו, לחסין לחלוטין לחום או אש רגילים. הלחש גם מעניק הגנה מפני חום או אש קסומים או עליונים כמו נשימת דרקון הרים או לחש **כדור אש**. באופן ספציפי, הלחש מעניק לייצור המוגן בונוס של +3 על כל גלגולי הצלה נגד השפעות כאלה, ומפחית כל נזק שנגרם בחצי (כך שלמשל הצלה מוצלחת נגד לחש **כדור אש** תקטין את הנזק לרבע מהרגיל, ואפילו אם גלגול ההצלה נכשל, היצור המוגן סופג רק חצי מהנזק).

</div>
<div class="spell" data-tag="Restoration" id="Restoration">

## השבה

טווח: מגע

כוהן 6

משך: קבוע

כל הטלת לחש מסירה דרגה שלילית אחת מיצור שסבל מניקוז אנרגיה. בדרגה 16, ניתן להסיר שתי דרגות שליליות. ראו את הכללים לניקוז אנרגיה (בקטע [מפגש](combat.qmd#energy-drain)) לפרטים נוספים.

לחילופין, לחש זה יכול לשמש לשחזור נקודות תכונה שנוקזו. אם מוחל על דמות שסבלה מאובדן זמני של נקודות תכונה, הוא ישחזר עד 1d4 נקודות שאבדו לכל תכונה שנוקזה מיד. אם מוחל על דמות שסבלה מאובדן קבוע של נקודות תכונה, ניתן לשחזר נקודה אחת.

השבה אינה משחזרת דרגות שאבדו עקב מוות (כמתואר בלחש **החייאת מתים**).

</div>
<div class="spell" data-tag="Shield" id="Shield">

## מגן

טווח: עצמי

קוסם 1

משך: 5 סיבובים+1/דרגה

מגן יוצר דיסק בלתי נראה דמוי מגן של כוח שמרחף מול המטיל. הוא מבטל התקפות **טיל קסם** המכוונות למטיל, ומשפר את דירוג השריון של המטיל ב-+3 נגד התקפות קרב פנים אל פנים וב-+6 נגד נשקי קליעים. יתרונות דירוג השריון אינם חלים על התקפות שמקורן מאחורי המטיל, אך **טילי קסם** נדחים מכל הכיוונים.

</div>
<div class="spell" data-tag="Silence 4.5 מטר Radius" id="Silence 4.5 מטר Radius">

## שתיקה ברדיוס 4.5 מטר

כוהן 2

טווח: 108 מטר

משך: 2 סיבובים/דרגה

לחש זה יוצר אזור כדורי ברדיוס של 4.5 מטר שבו לא יעבור קול. אף אחד בתוך האזור המושפע לא יכול להפיק או לשמוע קול. גם קול לא יוצא מהאזור המושפע; אלו שבחוץ לא יכולים לשמוע את אלו שבפנים. אפקט זה חוסם תקשורת מילולית, כמובן, כמו גם הטלת לחשים.

אפקט זה יכול להיות מוטל באזור קבוע, על חפץ (מה שהופך אותו לנייד), או על יצור. מטרה לא רצויה מקבלת גלגול הצלה נגד לחשים כדי לבטל את הלחש. אם חפץ ברשות יצור אחר הוא המטרה, אותו יצור גם מקבל גלגול הצלה נגד לחשים כדי לבטל.

לחש זה יכול לשמש להגנה מפני כל סוג של התקפה או קסם שבו הקורבנות חייבים להיות מסוגלים לשמוע את התוקף, שכן התקפות כאלה אינן יכולות לעבור לתוך או מחוץ לאזור המושפע.

</div>
<div class="spell" data-tag="Sleep" id="Sleep">

## שינה

טווח: 27 מטר

קוסם 1

משך: 5 סיבובים/דרגה

לחש זה מכניס מספר יצורים עם 3 קוביות פגיעה או פחות, או יצור אחד עם 4 קוביות פגיעה, לשינה קסומה. יצורים עם 5 קוביות פגיעה או יותר אינם מושפעים. המטיל בוחר נקודת מוצא ללחש (בטווח הנתון, כמובן), והיצורים שנמצאים בטווח של 9 מטר מנקודת המוצא עשויים להיות מושפעים. כל יצור באזור ההשפעה מקבל גלגול הצלה נגד לחשים כדי להתנגד.

קורבנות לחש זה יכולים תמיד להיפגע אם תוקפים אותם. פגיעה ביצור כזה תעיר אותו, והוא עשוי להתחיל להילחם או להגן על עצמו בסיבוב הבא. טפיחה או ניעור של יצור כזה יעירו אותו ב-1d4 סיבובים, אך רעשים רגילים לא יעירו אותו.

שינה אינה משפיעה על יצורים מחוסרי הכרה, מבנים או יצורים אל-מתים.

כאשר משך הזמן פג, היצורים הישנים מתעוררים בדרך כלל מיד; עם זאת, אם הם נעשים מאוד נוחים והסביבה שקטה, היצורים המושפעים עשויים להמשיך לישון כרגיל לפי שיקול דעתה של מנחת המשחק.

</div>
<div class="spell" data-tag="Speak with Animals" id="Speak with Animals">

## דיבור עם חיות

כוהן 2

טווח: מיוחד

משך: 1 תור/4 דרגות

לחש זה מאפשר למטיל לדבר ולהבין כל חיה יחידה (בגודל רגיל או ענק, אך לא קסומה או מפלצתית) שנמצאת בטווח ראיית המטיל ויכולה לשמוע אותו. המטיל יכול לשנות את החיה איתה הוא מדבר כרצונו, פעם אחת בכל סיבוב. הלחש אינו משנה את תגובת החיה או את גישתה כלפי המטיל; יש לבצע גלגול תגובה סטנדרטי כדי לקבוע זאת. מנחת המשחק צריכה לוודא שסגנון הדיבור של החיה משקף את האינטליגנציה והטבע שלה.

</div>
<div class="spell" data-tag="Speak with Monsters" id="Speak with Monsters">

## דיבור עם מפלצות

כוהן 6

טווח: מיוחד

משך: 1 תור/5 דרגות

לחש זה מאפשר למטיל לדבר ולהבין כל מפלצת חיה יחידה שנמצאת בטווח ראיית המטיל ויכולה לשמוע אותו. המטיל יכול לשנות את המפלצת איתה הוא מדבר כרצונו, פעם אחת בכל סיבוב. אחרים שמסוגלים להבין את השפה המדוברת על ידי המפלצת המטרה (אם יש כזו) יוכלו להבין את המטיל. הלחש אינו משנה את תגובת המפלצת או את גישתה כלפי המטיל. מפלצות חסרות תודעה, יצורי צמחים ואל-מתים אינם מושפעים מלחש זה.

</div>
<div class="spell" data-tag="Speak with Plants" id="Speak with Plants">

## דיבור עם צמחים

טווח: 6 מטר

כוהן 4

משך: 1 תור

לחש זה מאפשר למטיל לדבר ולהבין כל צמח יחיד (בין אם צמח רגיל או יצור צמחי מונפש). מנחת המשחק צריכה לזכור שלצמחים רגילים יש תחושה מוגבלת של סביבתם, ורובם לעולם לא זזים מהמקום שבו נבטו. הלחש אינו משנה את תגובת הצמח או את גישתו כלפי המטיל; עם זאת, צמחים רגילים בדרך כלל יתקשרו בחופשיות עם המטיל, שכן אין להם דבר חשוב אחר לעשות. יצורי צמחים נוטים להיות אינטליגנטים מעט יותר, ויש להשתמש בגלגול תגובה כדי לקבוע כיצד יצורים כאלה מגיבים לדברי המטיל.

</div>
<div class="spell" data-tag="Speak with Dead" id="Speak with Dead">

## דיבור עם מתים

טווח: 3 מטר

כוהן 3

משך: 3 סיבובים/דרגה

עם לחש זה המטיל גורם לגופה של יצור אינטליגנטי להתעורר ולענות על שאלות המטיל. לא משנה כמה זמן הגופה מתה, אך היא חייבת להיות שלמה בעיקר עם לפחות פה שלם כדי לענות על שאלות. הגופה תענה על מקסימום שאלה אחת לכל שתי דרגות של המטיל, אך אם משך הזמן פג, כל השאלות הנותרות אובדות. הגופה יודעת רק מה שידעה כשהייתה בחיים; זה כולל את השפות שידעה בחיים. לכן, המטיל חייב לחלוק שפה עם הנפטר כדי לקבל תשובות כלשהן.

התשובות הניתנות נמשכות מידע "מוטבע" על הגופה במהלך החיים; המטיל אינו מתקשר בפועל עם רוח היצור הנפטר. הגופה אינה יכולה לשמור על כל מידע שניתן לה, ואינה זוכרת אפילו מקרים קודמים של תקשורת באמצעות לחש זה.

התשובות הניתנות עשויות שלא להיות מועילות מסיבות שונות. אם הגופה הכירה את המטיל כשהייתה בחיים, או אם המטיל הוא חבר בקבוצה שהנפטר לא אהב, היא עשויה לבחור לשקר או להטעות את המטיל. אם המטיל שואל את הגופה שאלות אישיות, או שאלות שמצביעות על כך שהמטיל עשוי לפעול נגד האינטרסים שהיו לגופה בחיים, היא כמעט בוודאות תנסה להטעות את המטיל.

אם הגופה עוררה על ידי לחש זה במהלך שבעת הימים האחרונים, הלחש ייכשל. יצורים אל-מתים (כולל שרידי יצורים אל-מתים מובסים) אינם יכולים להיות מושפעים מלחש זה.

</div>
<div class="spell" data-tag="Spiritual Hammer" id="Spiritual Hammer">

## פטיש רוחני

טווח: 9 מטר

כוהן 2

משך: 1 סיבוב/דרגה

לחש זה גורם לפטיש מלחמה עשוי כוח טהור להופיע, תוקף כל אויב שנבחר על ידי הכוהן בטווח פעם אחת בכל סיבוב. הוא גורם לנזק של 1d6 נקודות פגיעה לכל מכה, +1 נקודה לכל שלוש דרגות של המטיל (מקסימום של +5). הוא משתמש בבונוס התקיפה הרגיל של המטיל, תוקף כנשק קסום, ולכן יכול לגרום נזק ליצורים שנפגעים רק על ידי נשקים קסומים. אם הפטיש יוצא מעבר לטווח הלחש, הכוהן מאבד קשר עין איתו, או שהמטיל מפסיק לכוון אותו, הפטיש נעלם. הפטיש לא יכול להיות מותקף או נפגע על ידי התקפות פיזיות, אך **ביטול קסם**, **התפוררות**, או **מטה ביטול** יבטלו אותו.

</div>
<div class="spell" data-tag="Sticks to Snakes" id="Sticks to Snakes">

## מקלות לנחשים

טווח: 36 מטר

כוהן 4

משך: 6 תורות

לחש זה הופך מקלות עץ רגילים ל-1d4 קוביות פגיעה של נחשים רגילים (לא ענקיים) לכל ארבע דרגות של המטיל. (ראו את קטע **מפלצות** לפרטים על סוגי [נחשים](monstersAll.qmd#snake-giant-rattlesnake).) הנחשים עוקבים אחרי פקודות המטיל. כאשר הם נהרגים, מבוטלים, או שהלחש פג, הנחשים חוזרים לצורת המקל המקורית שלהם. "מקלות" קסומים כמו מטות מכושפים אינם יכולים להיות מושפעים.

</div>
<div class="spell" data-tag="Striking" id="Striking">

## הכאה

טווח: מגע

כוהן 3

משך: 1 סיבוב/דרגה

לחש זה מעניק לנשק אחד את היכולת לגרום לנזק נוסף של 1d6 נקודות. נזק נוסף זה מוחל על כל התקפה מוצלחת למשך הלחש. הוא אינו מספק בונוס התקפה, אך אם מוטל על נשק רגיל, הלחש מאפשר לפגוע במפלצות שנפגעות רק על ידי נשקים קסומים; עם זאת, רק 1d6 נקודות הנזק הקסום מוחלות על מפלצת כזו.

</div>
<div class="spell" data-tag="Telekinesis" id="Telekinesis">

## טלקינזיס

טווח: עצמי

קוסם 5

משך: 3 תורות

לחש זה מאפשר למטיל להזיז חפצים או יצורים באמצעות ריכוז בלבד; המטיל יכול להזיז דברים כאלה שמשקלם עד 23 ק"ג לכל דרגת מטיל בקצב של עד 6 מטר לסיבוב. יצורים הממוקדים בלחש זה רשאים לגלגל גלגול הצלה נגד קרן מוות כדי להתנגד, בין אם מדובר ביצור עצמו המושפע או בחפץ שבחזקתו.

כדי להשתמש בכוח זה, על המטיל לשמור על ריכוז, לנוע לא יותר מתנועה רגילה (ללא ריצה), לא לבצע תקיפות ולא להטיל לחשים נוספים. אם הריכוז אובד (בין אם בכוונה או לא), ניתן להשתמש בכוח שוב בסיבוב הבא, אך המטרה של ההשפעה רשאית לגלגל גלגול הצלה חדש.

</div>
<div class="spell" data-tag="Teleport" id="Teleport">

## טלפורט

טווח: עצמי

קוסם 5

משך: מיידי

המטיל של לחש זה מועבר מיידית למיקום אחר עד 150 ק"מ לכל דרגת יכולת. הלחש מעביר את המטיל רק בתוך המישור הקיים שלו. יצורים אחרים (נוסעים) וחפצים דוממים (מטען) יכולים להיות מועברים יחד עם המטיל, עד למקסימום של 135 ק"ג ועוד 45 ק"ג לכל דרגה מעל ה-10. המטיל חייב להיות במגע עם כל החפצים ו/או היצורים שיועברו (למרות שיצורים שיועברו יכולים להיות במגע אחד עם השני, כאשר לפחות אחד מהיצורים במגע עם המטיל). יצורים שאינם מעוניינים רשאים לגלגל גלגול הצלה נגד לחשים כדי להתנגד ללחש, והמטיל עשוי להזדקק לגלגול תקיפה כדי ליצור מגע עם יצור כזה. כמו כן, גלגול הצלה מוצלח נגד לחשים ימנע מחפצים שבחזקת יצור מלהיות מועברים בטלפורט.

הלחש מונחה על ידי מחשבת המטיל, שחייב לדמיין את אזור היעד; כישלון לדמיין אותו כראוי יכול לגרום ללחש להיכשל במגוון דרכים, ויעדים רוויים באנרגיה קסומה (כפי שמוגדר על ידי מנחה המשחק) יגרמו ללחש להיכשל אוטומטית.

כדי לקבוע את תוצאות הלחש הזה, גלגלי d% והתייעצו בטבלה למטה. מתחת לטבלה יש הסבר על המונחים המשמשים.

| מכיר היטב | מכיר במידה מסוימת | ראה פעם אחת | תוצאת הלחש | 
|------------|--------------------|-------------|-------------|
| 01         | 01--02             | 01-03       | אסון        |
| 02         | 03--07             | 04--13      | מקום שגוי   |
| 03         | 08--13             | 14--25      | קצר הדרך    |
| 04--100    | 14--00             | 26--100     | הצלחה!      |


**מכיר היטב** חל כאשר המטיל ביקר ביעד לעיתים קרובות ו/או בילה שם זמן משמעותי; בדרך כלל, המטיל צריך היה לבלות לפחות 7 ימים (לא בהכרח ברצף) ביעד בשנה האחרונה כדי להיכלל בקטגוריה זו. כל מקום שבו המטיל התגורר יותר מחודש בעשר השנים האחרונות, או יותר משנה בחייו, גם כן נכלל.

**מכיר במידה מסוימת** חל כאשר המטיל בילה זמן משמעותי באזור היעד, אך לא מספיק כדי להיכלל ב"מכיר היטב". לחלופין, המטיל עשוי היה לבצע מחקר מעמיק של האזור, להסתכל על ציורים מדויקים, מפות ותוכניות או לבלות שעות בהאזנה לתיאורים מאדם אחד או יותר שמכירים היטב את היעד.

**ראה פעם אחת** חל כאשר המטיל ביקר במקום למשך יום אחד, אך לא יותר, או כאשר המטיל ניסה את המחקר הנדרש להגדרה השנייה של "מכיר במידה מסוימת" אך לא הצליח לרכוש מספיק מידע (לדעת מנחה המשחק).

**אם המטיל מנסה לנסוע למיקום שאינו קיים**, או אולי היה קיים פעם אך נהרס או השתנה כל כך שהמטיל לא יזהה אותו, גלגלי 2d20 במקום d% לתוצאת ההטלה. במקרה זה, אם מתגלגלת הצלחה! הלחש פשוט נכשל ואיש לא מועבר לשום מקום.

**הצלחה!** פירושו בדיוק מה שזה אומר. המטיל, הנוסעים והמטען מגיעים בבטחה בדיוק למקום שהמטיל התכוון אליו.

**קצר הדרך** מציין שהמטיל, הנוסעים והמטען מגיעים בבטחה ל-1d8x10% מהדרך ליעד המיועד. שימו לב שהגעה "בבטחה" אינה אומרת שהיעד בטוח, אלא רק שהמסע היה בטוח.

**מקום שגוי** פירושו שהמטיל, הנוסעים והמטען מגיעים למקום כלשהו שדומה ליעד המיועד. פירוש הדבר שהמטיל מופיע במקום הדומה הקרוב ביותר בטווח, כפי שנקבע על ידי מנחה המשחק. אם אין אזור כזה בטווח הלחש, הלחש פשוט נכשל במקום.

**אסון** מציין שהמטיל, הנוסעים והמטען נתקלו בטורבולנציה מימדית והתרסקו, והופרדו (אם נוסעים ו/או מטען ליוו את המטיל) ונפגעו בתהליך. כל יצור כולל המטיל סובל 1d12 נקודות נזק, ואז מגלגל שוב באותה עמודה באמצעות 2d20 במקום d%. אם מתגלגל אסון נוסף עבור כל יצור, יש להחיל עוד 1d12 נקודות נזק ולגלגל פעם נוספת. חפצי מטען בדרך כלל אינם נפגעים אך יש לגלגל את התוצאה עבור כל חפץ כזה כדי לקבוע היכן הוא הופיע; במקרה זה, אם מתגלגל אסון, חפץ המטען נעלם לנצח.

</div>
<div class="spell" data-tag="True Seeing" id="True Seeing">

## ראייה אמיתית

טווח: מגע

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מעניק למטרה את היכולת לראות את כל הדברים כפי שהם באמת. הנושא רואה דרך חושך רגיל וקסום, מבחין בדלתות סודיות, רואה את המיקומים המדויקים של יצורים או חפצים שהוזזו, רואה דרך תחפושות רגילות או קסומות, רואה יצורים או חפצים בלתי נראים באופן רגיל, רואה דרך אשליות, ורואה את הצורה האמיתית של דברים שהשתנו, הוסבו או הומרו. טווח הראייה האמיתית המוענק הוא 36 מטר.

ראייה אמיתית, עם זאת, אינה חודרת חפצים מוצקים. היא בשום אופן אינה מעניקה ראיית רנטגן או שוות ערך לה. היא אינה מבטלת הסתרה, כולל זו הנגרמת על ידי ערפל וכדומה. בנוסף, השפעות הלחש אינן יכולות להיות משופרות עוד יותר עם קסם ידוע, כך שלא ניתן להשתמש בראייה אמיתית דרך **כדור בדולח** או בשילוב עם **ראיית הנסתר**.

</div>
<div class="spell" data-tag="Ventriloquism" id="Ventriloquism">

## דיבור מהבטן

טווח: 18 מטר

קוסם 1

משך: 1 תור/דרגה

לחש זה גורם לקולו של המטיל להישמע כאילו הוא מגיע ממיקום אחר בטווח, למשל, מנישה חשוכה או פסל. המטיל יכול לבחור מיקום חדש בכל סיבוב אם רצוי, ויכול לגרום ללחש להפסיק זמנית מבלי לסיים אותו ואז להפעילו שוב בכל עת בתוך משך הזמן הנתון.

</div>
<div class="spell" data-tag="Wall of Fire" id="Wall of Fire">

## חומת אש

טווח: 54 מטר

כוהן 5, קוסם 4

משך: 1 סיבוב/דרגה (או מיוחד)

לחש זה יוצר יריעת להבות אנכית באזור שצוין על ידי המטיל, שהיא או חומת להבות באורך של עד 6 מטר לכל דרגת מטיל, או טבעת ברדיוס של עד 1.5 מטר לכל דרגת מטיל. המטיל יכול לבחור לעשות את החומה קטנה יותר אם רצוי. החומה יכולה להיות בגובה של עד 6 מטר (כפי שרוצה המטיל ו/או מוגבל על ידי התקרה). כל החומה חייבת להיות בתוך הטווח הנתון לעיל. צד אחד או שני הצדדים של החומה יכולים להיות חמים, כפי שנקבע על ידי המטיל בזמן ההטלה. לאחר שנוצרה, החומה לא יכולה להיות מועברת או משתנה.

כל יצור בתוך 6 מטר מצד חם של החומה יסבול 1d4 נקודות נזק כל סיבוב, או 2d4 נקודות אם בתוך 3 מטר. הנזק מוחל בסיבוב שבו הלחש מוטל וכל סיבוב לאחר מכן. מעבר דרך החומה גורם ל-2d6 נקודות נזק, ועוד 1 לכל דרגת מטיל, אפילו אם הצד שממנו נכנס הדמות או היצור לא היה צד חם.

יצורים לא-מתים רגישים במיוחד ללחש זה, וסובלים פי שניים מהנזק המתואר לעיל.

אם המטיל מזמן את החומה כך שהיא מופיעה במקום שבו נמצאים יצורים, כל יצור לוקח נזק כאילו עבר דרך החומה; גלגול הצלה נגד לחשים מותר, עם הצלחה מציינת שהנזק מגולגל כאילו היצור נמצא בתוך 3 מטר מהחומה.

המטיל יכול לבחור לשמור על הלחש ללא הגבלת זמן (בתוך גבולות סבירים של סיבולת) על ידי ריכוז, או להטיל אותו עם משך הזמן הסטנדרטי של 1 סיבוב לכל דרגה, לפי בחירתו.

</div>
<div class="spell" data-tag="Wall of Iron" id="Wall of Iron">

## חומת ברזל

טווח: 27 מטר

קוסם 6

משך: קבוע

באמצעות לחש זה המטיל יוצר חומת ברזל. החומה עומדת זקופה, ומורכבת מעד קטע מרובע של 3 מטרx3 מטר, בעובי של אינץ' אחד (2.5 ס"מ), לכל דרגת מטיל. המטיל יכול להגדיל את עובי החומה עם הפחתה פרופורציונלית בשטח; לדוגמה, הכפלת העובי חוצה את השטח. המטיל יכול לבחור לעשות את החומה קטנה מהגודל המקסימלי אם רצוי. החומה לא יכולה להיות פחות מעובי של אינץ' אחד (2.5 ס"מ), ותמיד חייבת להיווצר במגע עם הקרקע או הרצפה שמתחתיה. היא תמיד לוח שטוח ללא עיקולים, אך הקצוות לא חייבים להיות ישרים; למעשה, המטיל יכול לגרום לקצה החומה להתעצב סביב כל חפץ מפריע בצורה קרובה מאוד. החומה לא יכולה להיווצר כך שהיא תתפוס את המרחב של כל חפץ או יצור.

אם המטיל רוצה, קצוות החומה יתחברו לכל חומר דומם שהם נוגעים בו (קירות אבן, אדמה, רהיטים וכדומה). אם זה לא נעשה, החומה עשויה להיות לא נתמכת (כפי שנקבע על ידי מנחה המשחק בהתבסס על המצב) ולכן סביר להניח שתיפול. אם נשארת ללא השגחה, יש סיכוי שווה שהיא תיפול לכל כיוון ב-1d6 סיבובים, אך ניתן לדחוף אותה בכיוון מסוים על ידי כל דמות שיש לה מינימום של דירוג כוח של 13, או כל מפלצת עם 4 או יותר קוביות פגיעה. מספר יצורים יכולים לעבוד יחד כדי לעשות זאת אם רצוי. (אם משתמשים בכלל גלגול היכולת האופציונלי, גלגול כוח ב-3- מספיק כדי להפיל את החומה.)

כאשר החומה נופלת, כל יצור שהיא נופלת עליו סביר להניח שייפגע או ייהרג. אם אפשרי לדמות או לייצור להימלט מהאזור (כלומר יש לו קצב תנועה מספיק ואינו נמנע מכך מסיבה כלשהי), הוא רשאי לגלגל גלגול הצלה נגד קרן מוות (עם תוספת זריזות). אם גלגול זה מצליח, היצור או הדמות נעים בדרך הישירה ביותר למקום הבטוח הקרוב ביותר; אם הגלגול נכשל או שזה בלתי אפשרי לברוח מסיבה כלשהי, 10d6 נקודות נזק נגרמות לקורבן זה. יצורים גדולים יותר מגודל של אורק חסינים מפני ריסוק ופשוט יופלו אם הגלגול נכשל.

החומה היא קבועה, כפי שצוין, אך בהיותה עשויה מברזל היא רגישה לחלודה וקורוזיה.

</div>
<div class="spell" data-tag="Wall of Stone" id="Wall of Stone">

## חומת אבן

טווח: 4.5 מטר לכל דרגה

קוסם 5

משך: קבוע

באמצעות לחש זה, המטיל יוצר קיר אבן. הקיר מורכב מעד חלק מרובע אחד בגודל 3 מטרx3 מטר, בעובי רגל אחת, לכל דרגת מטיל. המטיל יכול לעצב את הקיר כמעט בכל צורה, עם כמה מגבלות. המטיל יכול להגדיל את עובי הקיר עם הפחתה פרופורציונלית בשטח; לדוגמה, הכפלת העובי חוצה את השטח. הקיר לא יכול להיווצר כך שהוא תופס את המרחב של כל חפץ או יצור. עליו להיות נתמך כראוי על ידי אבן קיימת, אליה הוא יתחבר אוטומטית, אך אין צורך לתמוך בו על פני כל שטחו. לדוגמה, קיר אבן יכול להיווצר כגשר מעל נחל או תהום, כל עוד שני קצות הגשר נשענים בחוזקה על (ומתחברים עם) אבן קיימת.

גשרים ארוכים מ-6 מטר חייבים להיות מקושתים, נתמכים, או שניהם כדי לעמוד; בנייה נוספת זו מפחיתה את נפח הקיר השימושי בחצי, כמו גם יצירת קיר עם חומות, חרכי ירי ואלמנטים מבניים בסיסיים דומים. לא ניתן ליצור אלמנטים מבניים מורכבים באמצעות לחש זה.

למרות שנוצר על ידי קסם, הקיר עשוי מאבן וניתן לשבור או לפגוע בו כאילו היה אבן רגילה.

הקיר יכול להיווצר כמיכל ללכידת יצורים, ואם זה נעשה, המטרות של הלחש יכולות לגלגל גלגול הצלה נגד קרן מוות כדי להימנע מלכידה. אם הגלגול מצליח, המטרות יכולות לבצע תנועה מלאה אחת למרחב מחוץ למיכל.

</div>
<div class="spell" data-tag="Water Breathing" id="Water Breathing">

## נשימת מים

טווח: מגע

קוסם 3

משך: 2 שעות/דרגה

לחש זה מעניק ליצורים חיים שנגעו על ידי המטיל (כולל המטיל, אם רצוי) את היכולת לנשום במים כמו דג. ניתן לחלק את משך הזמן באופן שווה אם המטיל נוגע במספר מטרות אחת אחרי השנייה. המטרות המושפעות לא מאבדות את היכולת לנשום אוויר.

</div>
<div class="spell" data-tag="Web" id="Web">

## קורים

טווח: 3 מטר לכל דרגה

קוסם 2

משך: 2 תורות/דרגה

לחש זה יוצר נפח של חוטים דביקים הדומים לקורי עכביש אך גדולים ועבים בהרבה. הלחש ממלא נפח של עד 8,0 מטר מעוקב (שווה ערך לשמונה קוביות של 3 מטרx3 מטרx3 מטר). הקורים חייבים להיות מחוברים לעצמים מוצקים סמוכים כמו קירות, עמודים וכדומה; כל חלק של קורים שאינו נתמך קורס לקרקע ונעלם. בתוך מגבלה זו, המטיל יכול לבחור כל סידור של קורים שירצה, עד לגבול הטווח והנפח הנתון של 8,0 מטר מעוקב. המטיל יכול לבחור ליצור נפח קטן יותר אם ירצה.

יצורים בתוך הקורים בזמן שהלחש מוטל, כמו גם כל מי שנכנס לאזור לאחר מכן, יסתבכו. כל אחד מהם צריך לגלגל גלגול הצלה נגד קרן מוות, וכל יצור שמצליח בגלגול זה יכול לנוע דרך הקורים אך מהירותו מופחתת לחצי מהמהירות הרגילה. יצורים כאלה לא יכולים להטיל לחשים או לבצע התקפות רגילות; האם פעולות אחרות אפשריות נתון להחלטת המנחה. ברגע שיצור מסובך יוצא מאזור ההשפעה של הקורים, הוא יוכל לפעול שוב כרגיל.

אלה שנכשלים בגלגול ההצלה מסובכים ומלכדים לחלוטין. הם לא יכולים לנוע, להטיל לחשים, או לבצע התקפות רגילות או כל פעולה פיזית אחרת. דיבור נשאר אפשרי, עם זאת. יצורים עם כוח של 13 או יותר (או 4 קוביות פגיעה או יותר) עשויים להיות מסוגלים להשתחרר; כל סיבוב, יצורים כאלה מורשים לגלגל גלגול הצלה נוסף נגד קרן מוות עם תוצאות כפי שניתן לעיל. יצורים שנכשלים בגלגול ההצלה הראשוני ויש להם כוח של 12 או פחות (או פחות מ-4 קוביות פגיעה) לכודים עד שהמשך פג או שהקורים מוסרים בדרך אחרת.

התקפות נגד יצור מסובך על ידי אחד מחוץ לקורים לא ילכדו בדרך כלל את התוקף, כל עוד הם לא צריכים להיכנס לקורים כדי להגיע למטרה המסובכת.

ניתן להדליק את הקורים; כל יישום של אש לקורים יגרום לקוביה של 3 מטר להישרף תוך סיבוב אחד, וכל קוביות של 3 מטר סמוכות לזו שנהרסה יישרפו בסיבוב הבא, וכן הלאה. אם כל חלק מהקורים הופך ללא נתמך, הוא יקרוס וייעלם כפי שנאמר לעיל.

יצורים לכודים בתוך הקורים הבוערים סובלים 2d4 נקודות נזק כאשר הקוביה שבה הם לכודים נשרפת, אך לאחר מכן הם חופשיים לחלוטין מהקורים.

</div>
<div class="spell" data-tag="Wizard Eye" id="Wizard Eye">

## עין הקוסם

טווח: 72 מטר

קוסם 4

משך: 6 תורות

עם לחש זה, המטיל יוצר "עין" קסומה בלתי נראית שדרכה הוא או היא יכולים לראות. לעין יש ראיית חושך, אך אחרת היא רואה בדיוק כפי שהמטיל היה רואה. ניתן ליצור אותה בכל מקום שהמטיל יכול לראות, עד לטווח של 72 מטר משם, ולאחר מכן היא יכולה לנוע בקצב של 12 מטר לסיבוב כפי שהמטיל מכוון. העין לא תנוע יותר מ-72 מטר רגל מהמטיל בשום נסיבות. העין לא יכולה לעבור דרך עצמים מוצקים, אך מכיוון שהיא בגודל של עין אנושית רגילה, היא יכולה לעבור דרך חורים קטנים בקוטר של 1 אינץ'. המטיל חייב להתרכז כדי להשתמש בעין.

</div>
<div class="spell" data-tag="Wizard Lock" id="Wizard Lock">

## נעילת הקוסם

טווח: 6 מטר

קוסם 2

משך: קבוע

לחש זה מחזיק באופן קסום דלת, שער, חלון או תריס מעץ, מתכת או אבן סגורים. הקסם משפיע על הפתח כאילו הוא סגור היטב ונעול כרגיל. ההשפעה נמשכת ללא הגבלת זמן. **נקישה** יכולה לשמש לפתיחת הפתח מבלי לסיים את הלחש, ו**הסרת קסם** יכולה לשמש לסיים אותו לצמיתות. המטיל של לחש זה יכול לפתוח בקלות את הדלת או הפתח האחר מבלי לסיים את הלחש, כמו גם קוסם בדרגה שלוש או יותר מעל המטיל.

</div>

<div class="spell" data-tag="Word of Recall" id="Word of Recall">

## מילת החזרה

טווח: עצמי (מיוחד)

כוהן 6

משך: מיידי

עם אמירת מילה אחת, לחש זה מעביר את המטיל למקום מקלט שהיא מייעדת בעת הכנת הלחש. המקום חייב להיות מוכר היטב (כפי שמוסבר עבור **טלפורט**) למטיל כדי להיות מיועד כך. לחש זה לא יכול להעביר את המטיל מעבר למישור הקיום הנוכחי שלה.

המטיל יכול להביא עמו חפצים או יצורים, לא יעלה על 135 ק"ג פלוס 45 ק"ג לכל דרגה מעל ה-10. המטיל חייב להיות במגע עם כל החפצים ו/או היצורים שיועברו (למרות שיצורים שיועברו יכולים להיות במגע זה עם זה, עם לפחות אחד מהיצורים האלה במגע עם המטיל).

יצורים שאינם מסכימים לא יכולים להיות מועברים על ידי לחש זה, וגם לא חפצים ברשותם. אם המטיל או אחד מהנוסעים שלה מחזיקים חפץ שגם מוחזק על ידי יצור שאינו מסכים, האחרון יכול לשמור על החפץ עם גלגול הצלה מוצלח נגד לחשים.

</div>

```{=html}

<script>
let input = document.getElementById('input');
let animalDivs = document.querySelectorAll('.spell');

input.addEventListener('input', function(e) {
  const term = this.value.toLowerCase();
  animalDivs.forEach(function(div) {
    const animal = div.dataset.tag.toLocaleLowerCase();
    div.hidden = !animal.includes(term)
  });
});
</script>
```
