# הרפתקאות במבוך

### זמן וקנה מידה

הזמן במבוך נמדד ב**תורות משחק**, שאורכם (בערך) 10 דקות. כאשר מתחיל קרב, קנה המידה של הזמן משתנה ל**סיבובי קרב**, שאורכם (בערך) 10 שניות. כך שישנם 60 סיבובי קרב בכל תור משחק.

מרחקים במבוך נמדדים ברגל. בחוץ, יש לשנות את כל מדידות המרחקים (תנועה, טווח וכו') ליארדים (כך ש-30 מטר הופך ל-100 יארדים) אך מדידות שטח ההשפעה (למשל עבור לחשים) נשארות בדרך כלל ברגל.


### כושר נשיאה

דמויות שחקן רגילות של בני אדם, אלפים וגמדים יכולות לשאת עד 27 ק"ג ועדיין להיחשב כטעונות קלות, או עד 68 ק"ג ולהיחשב כטעונות כבדות. בני-מחצית יכולים לשאת עד 23 ק"ג ולהיחשב כטעונים קלות, או עד 45 ק"ג ולהיחשב כטעונים כבדות. שימו לב ששריון לדמויות בני-מחצית שוקל בערך רבע מהמשקל של שריון לגזעים אחרים.

ערכים אלו מושפעים מכוח; כל +1 בבונוס הכוח מוסיף 10% לכושר הנשיאה של הדמות, בעוד שכל -1 מפחית 20%. כך שכושר הנשיאה לדמויות רגילות הוא כפי שמוצג להלן (מעוגל ל-2 ק"ג הקרובים לנוחות):

+:----------------------------------:+:------------------------:+
|   גמד, אלף, אדם                   | בן-מחצית                 |
+----------+------------+------------+------------+-------------+
| כוח      | טעינה קלה  | טעינה כבדה | טעינה קלה  | טעינה כבדה  |
+:=========+:==========:+:==========:+:==========:+:===========:+
| 3        | 25         |  60        |20          |  40         |
+----------+------------+------------+------------+-------------+
| 4-5      | 35         | 90         | 30         | 60          |
+----------+------------+------------+------------+-------------+
| 6-8      | 50         | 120        | 40         | 80          |
+----------+------------+------------+------------+-------------+
| 9-12     | 60         | 150        | 50         | 100         |
+----------+------------+------------+------------+-------------+
| 13-15    | 65         | 165        | 55         | 110         |
+----------+------------+------------+------------+-------------+
| 16-17    | 70         | 180        | 60         | 120         |
+----------+------------+------------+------------+-------------+
| 18       | 80         | 195        | 65         | 130         |
+----------+------------+------------+------------+-------------+

כושר הנשיאה של חיות מבויתות שונות ניתן ב[סעיף המפלצות](monsters.qmd#beasts-of-burden).

### תנועה ועומס

קצב התנועה של דמות או יצור מבוטא כמספר הרגליים שהוא יכול לנוע בכל סיבוב קרב. כל גזעי דמויות השחקן הרגילים יכולים לנוע 12 מטר לסיבוב. כאשר חוקרים מבוך, הזמן מבוטא בתורות, כפי שהוסבר לעיל; תנועה רגילה לתור היא פי 3 מקצב התנועה לסיבוב.

זה עשוי להיראות איטי, אך קצב תנועה זה כולל דברים כמו שרטוט מפות, שמירה על מלכודות ומפלצות (למרות שהן עדיין עשויות להפתיע את הקבוצה) וכו'. במצב קרב, לעומת זאת, כולם נעים במהירות, ודברים כמו שרטוט מפות אינם חשובים.

קצב התנועה של דמות מותאם לפי העומס שלה (המשקל שהיא נושאת) כדלקמן:

| סוג שריון | טעינה קלה | טעינה כבדה |
|---|----|-----|----|
| ללא שריון או עור קסום | 12 מטר | 9 מטר |
| שריון עור או מתכת קסום | 9 מטר | 6 מטר |
| שריון מתכת | 6 מטר | 3 מטר |

יש לכלול את משקל השריון הנלבש בעת חישוב העומס, משום ששריון נחשב גם לנפח וגם למגבלה וגם למשקל. שריון קסום נחשב למשקלו המלא אך אינו נפחי ומגביל כמו שריון רגיל, ולכן מעניק קצב תנועה משופר.

### מיפוי

בכל משלחת למבוך, חשוב להכין מפות. בדרך כלל שחקן אחד יעשה זאת, יכין מפה על נייר גרף כאשר מנחת המשחק מתארת כל חדר או מסדרון. דיוק מוחלט בדרך כלל אינו אפשרי; הדבר החשוב הוא להבטיח שהקבוצה תוכל למצוא את דרכה חזרה החוצה מהמבוך.

### אור

לפיד או פנס יספקו אור המכסה **רדיוס של 9 מטר**; אור עמום יתפשט כ-**6 מטר נוספים**. לפידים רגילים בוערים למשך 1d4+4 תורות, בעוד שמיכל שמן בפנס יבער למשך 18+1d6 תורות. נר יפיץ אור ברדיוס של 1.5 מטר, עם אור עמום המתפשט 1.5 מטר נוספים. באופן כללי, נרות מחודדים המשמשים להארה יבערו כ-3 תורות לכל אינץ' גובה.


```{ojs}
/* import {view} from '@tomlarkworthy/view' */
import {rolld4,rolld6} from "../custom.js"

viewof torch = Inputs.input(0)

htl.html`<div style="display:grid; grid-template-columns: 50% auto; vertical-align:midle"> 
<div>
${Inputs.bind(Inputs.button("תורות לפיד (1d4+4)", {value: 0, reduce: () => (4 + rolld4() )}), viewof torch)}
</div><div>
Torch burn turns = ${torch.value}</div>
</div>
`


```

<br>

```{ojs}

viewof oil = Inputs.input(0)

htl.html`<div style="display:grid; grid-template-columns: 50% auto; vertical-align:midle">
${Inputs.bind(Inputs.button("פנס שמן (1d6 + 18)", {value: 0, reduce: () => (18 + rolld6() )}), viewof oil)}
Lantern Turns = ${oil.value}
</div>
`


```



${form.select}


### זיוונות

חלק מגזעי הדמויות, וכמעט כל המפלצות, יש להם זיוונות. זה נותן להם את היכולת לראות אפילו בחושך מוחלט. זיוונות הוא בשחור-לבן בלבד אך אחרת כמו ראייה רגילה. זיוונות אינו מעניק את היכולת לראות בחושך קסום. טווח הזיוונות הוא בדרך כלל או 9 מטר או 18 מטר; אם לא ניתן עבור יצור מסוים, יש להניח את הטווח של 18 מטר.

זיוונות אינו יעיל כלל באור חזק יותר מאור ירח.

### דלתות

דלת תקועה יכולה להיפתח בגלגול של 1 על 1d6; יש להוסיף את בונוס הכוח של הדמות לטווח, כך שדמות עם בונוס של +2 יכולה לפתוח דלת תקועה בגלגול של 1-3 על 1d6.

דלתות נעולות יכולות להיפרץ על ידי גלגול אותו הטווח, אך על 1d10. מוטות מתכת יכולים לפעמים להתכופף בגלגול של טווח זה על 1d20.

דמות זהירה עשויה לבחור להאזין ליד דלת לפני פתיחתה. לגנבים יש יכולת מיוחדת, האזנה, שיש ליישם אם המאזין הוא גנב. עבור דמויות אחרות, המנחה מגלגלת 1d6, כאשר 1 מציין הצלחה. קולות שנשמעים עשויים לכלול קולות, צעדים או כל קול אחר שהמנחה רואה לנכון. כמובן, החדר מעבר לדלת עשוי להיות שקט באמת; לכן, מנחת המשחק חייבת לבצע את הגלגול, כך שגלגול של 1 במקרה כזה לא יגלה דבר לשחקנים.


```{ojs}

import {generalDice} from "../custom.js"

viewof i = Inputs.input(0)
viewof j = Inputs.input(0)
viewof k = Inputs.input(0)


viewof form = Inputs.form(
  {
    doors: Inputs.bind(Inputs.button("1d6", {value: 1, reduce: () => (rolld6() )}), viewof i),
    forceBars: Inputs.bind(Inputs.button("כיפוף מוט", {value: 0, reduce: () => (generalDice(1,20,0) )}), viewof j),
    forceDoor: Inputs.bind(Inputs.button("פריצת דלת", {value: 0, reduce: () => (generalDice(1,10,0) )}), viewof k),
  },
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 50% auto; 
         vertical-align:midle;
         row-gap: 10px;
       ">
         ${Object.values(formParts)[0]} 1d6 result: ${i.value}
         ${Object.values(formParts)[1]} Force Bar: ${j.value}
         ${Object.values(formParts)[2]} Force Door: ${k.value}

       </div>
     </div>`
  }
)
```



### מלכודות

מבוכים וחרבות לעיתים קרובות מכילים מלכודות, כולל זורקי חניתות, בורות מכוסים וכו'. המנחה תחליט מה נדרש כדי להפעיל מלכודת, ומה קורה כאשר המלכודת מופעלת. (הנחיות מסוימות על כך ניתנות בסעיף מנחת המשחק בהמשך הספר.) באופן כללי, תהיה דרך להימנע או להפחית את השפעת הפעלת המלכודת. לדוגמה, גלגול הצלה נגד קרן מוות משמש לעיתים קרובות כדי להימנע מנפילה לבור מכוסה (עם בונוס זריזות נוסף), בעוד שזורקי חניתות, רובי קשת אוטומטיים וכדומה מטופלים לעיתים כאילו היו מפלצות (תוקפים נגד דירוג השריון של הקורבן עם בונוס תקיפה מסוים).

לדמויות רגילות יש סיכוי שווה לגלגול של 1 על 1d6 לגלות מלכודת אם מתבצע חיפוש אחר אחת. שימו לב שזהו סיכוי של כ-16.7%; לגנבים יש יכולת מיוחדת למצוא ולהסיר מלכודות, שמחליפה גלגול זה, כמו גם יכולת גילוי מלכודות באבן של גמדים. גנב גמדי הוא מקרה מיוחד; יש ליישם את יכולת גילוי המלכודות הגבוהה יותר. בכל המקרים, חיפוש אחר מלכודות לוקח לפחות תור לכל שטח של 3 מטר מרובע. דמות אחת יכולה לחפש ביעילות שטח נתון למלכודות רק פעם אחת, גם אם לדמות יש יותר מסוג אחד של גלגול גילוי מלכודות מותר (כגון הגנב הגמדי לעיל).

גילוי מלכודות עשוי לא להיות מותר אם המלכודת היא טהורה בטבעה; מצד שני, במקרים כאלה קוסמים ו/או כוהנים עשויים להיות מסוגלים לגלות מלכודות קסומות בסיכוי של 1 ב-1d6, לפי שיקול דעתה של מנחת המשחק.

### דלתות סודיות

בתנאים רגילים, חיפוש אחר דלתות סודיות לוקח תור אחד לכל דמות לכל 3 מטר של קיר שנחפש. דלת סודית נמצאת בגלגול של 1 על 1d6; דמויות עם תבונה של 15 או יותר מצליחות בגלגול של 1-2. כמו כן, כפי שנאמר קודם, אלפים מוסיפים 1 לטווח באופן אוטומטי, כך שאלף מגלה דלתות סודיות בגלגול של 1-2 על 1d6, או 1-3 אם לאלף יש תבונה של 15 או יותר. המנחה עשויה ליצור דלתות סודיות שקשה יותר (או קל יותר) לגלות לפי שיקול דעתה.

חיפוש של מספר דמויות אחר דלתות סודיות מבטיח שכל דלת כזו תתגלה בסופו של דבר; עם זאת, אם המחפש הראשון והשני נכשלים, המחפש הבא חייב לקחת שני תורות לחפש, וכל חיפושים נוספים של האזור דורשים שעה.

שימו לב שגילוי דלת סודית אינו מעניק הבנה כיצד היא פועלת. המנחה עשויה לדרוש גלגולים נוספים או פעולות אחרות לפני שניתן יהיה לפתוח את הדלת.

### הישרדות במבוך

כמתואר בסעיף [ציוד](equipment.qmd), דמויות רגילות חייבות לצרוך מנת מזון יומית אחת (או מזון שווה ערך) ולפחות רבע מים ביום.

כישלון בצריכת מספיק מזון אינו משפיע משמעותית על דמות במשך היומיים הראשונים, לאחר מכן היא מאבדת נקודת פגיעה אחת ביום. יתר על כן, בשלב זה הדמות מאבדת את היכולת לרפא פצעים באופן רגיל, אם כי קסם עדיין יעבוד. אכילת מספיק מזון ליום (במהלך יום בערך, לא בבת אחת) משחזרת את היכולת לרפא, והדמות תחלים נקודות פגיעה שאבדו בקצב הרגיל.

חוסר במים משפיע על דמויות במהירות רבה יותר; לאחר יום אחד בלבד ללא מספיק מים, הדמות מאבדת 1d4 נקודות פגיעה, ותאבד 1d4 נקודות פגיעה נוספות בכל יום לאחר מכן; יכולת הריפוי אובדת כאשר נזרק הקובייה הראשונה של הנזק.

