# חוקים נוספים וחלופיים

## לחשים בעוצמה אפס

### מבוא

לחשים בעוצמה 0 נקראים **קנטריפים** כאשר משתמשים בהם קוסמים ומקצועות קרובים, ו**תפילות** כאשר משתמשים בהם כוהנים ומקצועות קרובים. מטיל לחשים יכול להטיל מספר לחשים בעוצמה 0 ליום השווה לדרגתו בתוספת תוסף התכונה המתאים (תוסף תבונה עבור קוסמים ומקצועות קרובים; תוסף חוכמה עבור כוהנים ומקצועות קרובים). מאחר שלחשים אלה דורשים זמן קצר מאוד להטלה (בשל רכיביהם המילוליים והתנועתיים המקוצרים), דמות יכולה להטיל אחד מהם ובאותו סיבוב גם לבצע פעולה נוספת. אין צורך להכין לחשים בעוצמה 0 מראש, בניגוד לקסמים חזקים יותר.

לפי בחירתה של המנחה, ייתכן שדמות שאינה מטילת לחשים תורשה להשתמש בקנטריפים, בדרך כלל 1 ליום בתוספת מתאם התבונה שלה. לחלופין, המספר עשוי להיות 0 בתוספת מתאם התבונה, וכך דמויות כאלה יהיו נדירות יותר. בדומה לכך, ניתן להתיר תפילות גם למי שאינם כוהנים אך אדוקים מאוד, עם מגבלות דומות (תוך שימוש בתוסף חוכמה במקום תוסף תבונה). דמויות כאלה חייבות להקדיש סיבוב שלם כדי להטיל אחד מן הלחשים הללו.

:::{.column-margin}
**מהדורה 4**

Copyright © 2009, 2020 Sidney Parham, Nazim Karaca, R. Kevin Smoot, ckutalik, steveman, Svankensen, Mike West, and Chris Gonnerman

כל הזכויות שמורות

מופץ בהתאם לתנאי Open Game License גרסה 1.0a
:::

תוספת זו כוללת מידע הרלוונטי למקצועות תוספת (נוספים) המופיעים באתר בייסיק פנטזי; ובפרט: דרואידים, אשליינים, נקרומנסרים ויוצרי-לחשים. שים לב שתוספות אלה זמינות רק בהסכמתה של המנחה, גם אם היא בחרה לכלול תוספת זו.

### לימוד לחשים בעוצמה אפס

מטיל לחשים לומד במהלך אימון מספר לחשים בעוצמה 0 השווה ל־1d4 בתוספת תוסף התכונה המתאים לו, ויכול ללמוד קנטריפים נוספים בכל עת שבה זמין מדריך. מי שאינם מטילי לחשים יכולים ללמוד לחשים בעוצמה 0 רק ממדריך.

### שימוש בלחשים בעוצמה אפס

לקנטריפים בדרך כלל טווח של 3 מטרים ומשך מיידי. כמו בלחשים רגילים, חלק מן הלחשים בעוצמה 0 עשויים להיות הפיכים, דבר המסומן בכוכבית לאחר השם.

### לחשים חדשים

#### תפילות של כוהנים ודרואידים

**קריאה לתפילה:** תפילה זו מודיעה מנטלית לחברי קהילת הכנסייה של הכוהן (בתוך 1.5 קילומטרים לכל דרגה) שטקסי הפולחן עומדים להתחיל. התפילה אינה כופה עליהם להגיע.

**ריפוי פצעים מזעריים:** מרפא 1 נקודת פגיעה.

**הכוונה\*:** הכוהן מעניק +1 לגלגול ההתקפה הבא של מטרה כלשהי. בהיפוך, הלחש הופך ל״הטעיה״, המעניק למטרה -1 לגלגול ההתקפה הבא שלה.

**ברכת סעודה:** הכוהן אומר תפילה קצרה זו לפני ארוחה כדי להעניק לסועדים ברכה. כל מי שאוכל מן הארוחה בתוך 20 דקות משיב לעצמו 1 נקודת פגיעה. הארוחה חייבת להיות מוכנה בדרך הרגילה ולהיות מושגת בדרך שהאלוהות מתירה.

**תיקון:** מתקן שברים, שקעים וחורים בחפצים קטנים.

**חיזוי מזג אוויר:** הכוהן יכול לחזות את מזג האוויר עד 24 שעות מראש.

**מעלה טובה:** מטרה מקבלת 1 נקודת פגיעה זמנית.

**מיגון\*:** מעניק +1 לגלגול ההצלה הבא של המטרה. בהיפוך, הלחש הופך ל״קללה״, המעניקה את האפקט ההפוך.

**מים ליין:** הכוהן יכול להפוך 1 בקבוקון או ספל של מים ליין.

#### קנטריפים של קוסמים ואשליינים

**הנפשת כלי:** כלי קטן יחיד (כגון קולמוס, כף, מחט תפירה או פטיש קטן) מונפש באמצעות קנטריפ זה. הוא יבצע משימה יחידה וחוזרת (כגון כתיבת מילים מוכתבות, ערבוב סיר מרק, תפירת שולי שמלה או מסמור לוחות בבניית בית) למשך תור. הקוסם חייב להיות מסוגל לבצע את הפעולה החוזרת בידיו בעצמו. לא ניתן להנפיש כלי נשק באמצעות קנטריפ זה, וחפצים שהונפשו אינם יכולים לשמש ככלי נשק.

**ניקוי\*:** קוסם המשתמש בקנטריפ זה יכול לנקות, להבריק, להסיר אבק או לצחצח חפץ קטן או משטח ששטחו עד 900 סמ"ר. בהיפוך, הלחש הופך ל״לכלוך״, היכול להפוך את אותו השטח למלוכלך, מוכתם, משופשף או מאובק.

**הבזק:** באמצעות קנטריפ זה ניתן ליצור הבזק אור, כדור אש קטן מאוד או עננת עשן צבעונית. בדרך כלל הם לא יימשכו יותר משנייה.

**טעם\*:** קנטריפ זה יכול לגרום למנה יחידה לטעום כפי שמטיל הלחש רוצה (וזוהי אשליה), או להוסיף מלח, תבלין, ממתיק או חומר טעם אחר (וזה אמיתי). בהיפוך, הוא הופך ל״הרקבה״, הגורמת למזון או למשקה להתקלקל (וזה אמיתי) או לטעום כאילו הוכן באופן שגוי (וזוהי אשליה).

**חריטה:** קנטריפ זה חורט עד 900 סמ"ר של כתיבה או ציור על כמעט כל משטח דומם.

**גירוי:** קנטריפ זה מאלץ אדם אחר למצמץ, להנהן, להתגרד, לצחקק או לבצע תנועה גופנית קטנה אחרת באופן בלתי רצוני.

**קשר\*:** לחש זה יכול לקשור בחוזקה או לסבך חבל, חוט או חפץ דומה בכל קשר שמטיל הלחש היה מסוגל לקשור בעצמו. בהיפוך, לחש ״התרת קשר״ יכול להתיר כל קשר שמטיל הלחש היה מסוגל להתיר בעצמו.

**יד הקוסם:** נוצרת יד ספקטרלית, היכולה להזיז 0.5 ק"ג של חומרים במהירות של 3 מטרים לסיבוב במשך 10 סיבובים (בטווח מרבי של 12 מטרים), או לתת לחפץ דחיפה חזקה בערך השווה לכוחו של מטיל הלחש בטווח של 3 מטרים.

**פתיחה/סגירה:** קנטריפ זה יכול לפתוח דלת, חלון או פתח אחר רגיל שאינו נעול.

**זימון שרצים\*:** קנטריפ זה מזמן חרק קטן ורגיל לחלוטין (כגון חיפושית, זבוב או עכביש), מכרסם קטן (כגון עכבר שדה), או עננת יבחושים אל אזור מסוים. אם מכוונים אותו בתבונה, הלחש עשוי לשבש הטלת לחשים, אך לעולם לא יגרום נזק ממשי כלשהו (כולל רעל) למטרה. בהיפוך, קנטריפ זה הופך ל״השמדה״, היכול להרוג יצור יחיד בגודל דומה לאלה המתוארים בלחש.

**שינוי צורה:** קנטריפ זה יכול לשנות את צורתו, גודלו, צבעו או מרקמו של חפץ קטן (עד 440 סמ"ק). שינויים קיצוניים (כגון יצירת יצורים חיים קטנים) אינם צפויים להימשך יותר מתור אחד, אך שינויים קלים (כגון צביעת שיער בוורוד זוהר) עשויים להישאר עד חודש. שינויים ״קשורים״, כגון יצירת גור קיפוד מכרית סיכות, עשויים להימשך זמן רב יותר משינויים שאינם קשורים (כגון שינוי ספר ללטאה).

#### קנטריפים של נקרומנסרים

נקרומנסרים משתמשים באותה רשימת קנטריפים שבה משתמשים קוסמים. בנוסף, הם מקבלים 3 קנטריפים נוספים לשימושם.

**חיזוק\*:** אל-מתים בטווח של 3 מטרים ממטיל הלחש קשים יותר לגירוש או לפיקוד; הם נחשבים קשים יותר להשפעה בנקודה אחת (בטבלת הגירוש). האפקט נמשך שעה אחת או עד שמתבצע ניסיון גירוש (או פיקוד). בהיפוך, הקנטריפ הופך אל-מתים לקלים יותר להשפעה בנקודה אחת למשך אותו פרק זמן.

**חניטה:** מכין באופן מיוחד גופה אחת לקבורה (או לשימוש נוסף). כאשר הקנטריפ מוטל על מת טרי כהכנה ללחשים מסוג **הנפשה מחדש**, הזומבי שיוקם יקבל +1 לגלגול נקודות הפגיעה עבור כל קוביית פגיעה (עד למקסימום נקודות הפגיעה לכל קוביית פגיעה).

**ביטול צחנה\*:** מסיר צחנה מיצור אחד (או מגופה), כולל גועלים או גסטים (גלגול הצלה נגד לחשים כדי להתנגד לאפקט). האפקט נמשך 1 סיבוב לכל דרגה. בהיפוך, הצחנה מתחזקת ומעניקה לכל מי שנפגע ממנה מחסר של -2 לכל גלגול הצלה רלוונטי.

## נטייה

### מבוא

נטייה היא דרך לתאר את הקוד המוסרי של יצור. חוקים אלה מיועדים לשימוש עם חוקי משחק התפקידים של בייסיק פנטזי. אם עדיין אין ברשותך עותק של חוקי בייסיק פנטזי, בקר באתר והורד עותק.

:::{.column-margin}
**גרסה 2006.0**

Copyright © 2006 Todd Roe

כל הזכויות שמורות

מופץ בהתאם לתנאי Open Game License גרסה 1.0a
:::

### יסודות הנטייה

העמדות המוסריות והאישיות הכלליות של יצור מיוצגות באמצעות הנטייה שלו: סדר-טוב, ניטרלי-טוב, תוהו-טוב, סדר-ניטרלי, ניטרלי, תוהו-ניטרלי, סדר-רע, ניטרלי-רע או תוהו-רע.

בהתאם למערכה, המנחה עשויה לדרוש מן השחקנים לבחור נטייה לדמויותיהם.

נטייה היא כלי לפיתוח זהות הדמות שלך. היא אינה סד שמטרתו להגביל את הדמות שלך. כל נטייה מייצגת טווח רחב של טיפוסי אישיות או פילוסופיות אישיות, ולכן גם 2 דמויות בעלות אותה נטייה יכולות להיות שונות מאוד זו מזו. בנוסף, מעטים האנשים שהם עקביים לחלוטין.

### טוב מול רע

דמויות ויצורים טובים מגינים על חיי חפים מפשע. דמויות ויצורים רעים מבזים או משמידים את חייהם של חפים מפשע, בין אם לשם הנאה ובין אם לשם רווח.

״טוב״ מרמז על אלטרואיזם, כבוד לחיים ודאגה לכבודם של יצורים תבוניים. דמויות טובות מקריבות קורבנות אישיים כדי לעזור לאחרים.

״רע״ מרמז על פגיעה, דיכוי והרג של אחרים. יש יצורים רעים שפשוט אין בהם חמלה כלפי אחרים והם הורגים ללא נקיפות מצפון אם הדבר נוח להם. אחרים רודפים אחר הרוע באופן פעיל, הורגים לשם ספורט או מתוך חובה לאלוהות רעה או לאדון רע כלשהו.

אנשים שהם ניטרליים ביחס לטוב ולרע חשים נקיפות מצפון לגבי הרג חפים מפשע, אך חסרה להם המחויבות להקריב קורבנות כדי להגן על אחרים או לסייע להם. אנשים ניטרליים מחויבים לאחרים באמצעות קשרים אישיים.

להיות טוב או רע יכול להיות בחירה מודעת. אולם עבור רוב האנשים, להיות טוב או רע הוא גישה שהם מזהים בעצמם אך אינם בוחרים בה. להיות ניטרלי על ציר הטוב–רע מייצג בדרך כלל היעדר מחויבות לכאן או לכאן, אך עבור חלק הוא מייצג מחויבות חיובית להשקפה מאוזנת. תוך הכרה בכך שטוב ורע הם מצבים אובייקטיביים ולא רק דעות, אנשים אלה טוענים שאיזון בין השניים הוא המקום הראוי לבני אדם, או לפחות עבורם.

בעלי חיים ויצורים אחרים שאינם מסוגלים לפעולה מוסרית הם ניטרליים ולא טובים או רעים. אפילו צפעים וטיגריסים קטלניים שאוכלים בני אדם הם ניטרליים, משום שאין להם יכולת להתנהגות נכונה או שגויה מבחינה מוסרית.

### סדר מול תוהו

דמויות סדר דוברות אמת, עומדות במילתן, מכבדות סמכות ומסורת, ושופטות את מי שאינם עומדים בחובותיהם. דמויות תוהו פועלות לפי מצפונן, מתמרמרות כשאומרים להן מה לעשות, מעדיפות רעיונות חדשים על פני מסורת ומקיימות את מה שהבטיחו רק אם מתחשק להן.

״סדר״ מרמז על כבוד, אמינות, ציות לסמכות ומהימנות. מן הצד השלילי, דבקות בסדר עשויה לכלול צרות אופקים, דבקות תגובתית במסורת, שיפוטיות וחוסר יכולת להסתגל. מי שמקדמים סדר במודע אומרים שרק התנהגות של סדר יוצרת חברה שבה אנשים יכולים לסמוך זה על זה ולקבל את ההחלטות הנכונות בביטחון מלא שאחרים יפעלו כפי שעליהם לפעול.

״תוהו״ מרמז על חירות, יכולת הסתגלות וגמישות. מן הצד השלילי, תוהו עשוי לכלול פזיזות, טינה כלפי סמכות לגיטימית, פעולות שרירותיות וחוסר אחריות. מי שמקדמים התנהגות של תוהו אומרים שרק חירות אישית בלתי מרוסנת מאפשרת לאנשים לבטא את עצמם במלואם ומאפשרת לחברה להפיק תועלת מן הפוטנציאל הטמון ביחידיה.

אדם הניטרלי ביחס לסדר ולתוהו רוחש כבוד רגיל לסמכות ואינו חש לא דחף לציית ולא דחף למרוד. הוא ישר, אך עשוי להתפתות לשקר או להונות אחרים.

דבקות בסדר או בתוהו עשויה להיות בחירה מודעת, אך לעיתים קרובות יותר היא תכונת אופי שמזהים בעצמם ולא דבר שבוחרים בו. ניטרליות על הציר סדר–תוהו היא בדרך כלל פשוט מצב אמצע, שבו אין דחף לצד זה או אחר. עם זאת, מעטים מבין הניטרליים הללו דוגלים בניטרליות כעדיפה על סדר או תוהו, ורואים בכל אחד מהם קיצוניות בעלת נקודות עיוורון וחסרונות משלה.

בעלי חיים ויצורים אחרים שאינם מסוגלים לפעולה מוסרית הם ניטרליים. כלבים עשויים להיות צייתנים וחתולים חופשיים ברוחם, אך אין להם היכולת המוסרית להיות באמת סדריים או תוהניים.

### תשע הנטיות

9 נטיות מובחנות מגדירות את כל הצירופים האפשריים של הציר סדר–תוהו עם הציר טוב–רע. כל תיאור נטייה להלן מציג דמות טיפוסית של אותה נטייה. זכור שיחידים עשויים לסטות מן הנורמה הזו, ושדמות נתונה עשויה לפעול בהתאם לנטייתה במידה רבה או מועטה יותר מיום ליום. השתמש בתיאורים הללו כהנחיות, לא כתסריטים.

6 הנטיות הראשונות, מסדר-טוב ועד תוהו-ניטרלי, הן הנטיות הסטנדרטיות לדמויות שחקן. 3 הנטיות הרעות מיועדות למפלצות ולנבלים.

**סדר-טוב, "צלבן"**: דמות סדר-טוב פועלת כפי שמצופה או נדרש מאדם טוב לפעול. היא משלבת מחויבות להתנגד לרוע עם המשמעת להילחם ללא לאות. היא אומרת אמת, עומדת במילתה, מסייעת לנזקקים ומוחה נגד עוול. דמות סדר-טוב שונאת לראות אשמים שאינם נענשים.

סדר-טוב היא הנטייה הטובה ביותר שאפשר להיות, משום שהיא משלבת כבוד וחמלה.

**ניטרלי-טוב, "מיטיב"**: דמות ניטרלי-טוב עושה את המיטב שאדם טוב יכול לעשות. היא מסורה לעזרה לאחרים. היא עובדת עם מלכים ושופטים, אך אינה חשה מחויבות כלפיהם.

ניטרלי-טוב היא הנטייה הטובה ביותר שאפשר להיות, משום שמשמעותה לעשות את הטוב בלי משוא פנים בעד סדר או נגדו.

**תוהו-טוב, "מורד"**: דמות תוהו-טוב פועלת כפי שמצפונה מנחה אותה, תוך התחשבות מועטה במה שאחרים מצפים ממנה. היא סוללת את דרכה בעצמה, אך היא טובת לב ומיטיבה. היא מאמינה בטוב ובצדק, אך אינה מייחסת חשיבות רבה לחוקים ולתקנות. היא שונאת כשאנשים מנסים להטיל אימה על אחרים ולהגיד להם מה לעשות. היא הולכת לפי המצפן המוסרי שלה, שאף שהוא טוב, עשוי שלא להתאים לזה של החברה.

תוהו-טוב היא הנטייה הטובה ביותר שאפשר להיות, משום שהיא משלבת לב טוב עם רוח חופשית.

**סדר-ניטרלי, "שופט"**: דמות סדר-ניטרלי פועלת כפי שמכתיבים לה החוק, המסורת או קוד אישי. סדר וארגון הם מעל לכל בעיניה. היא עשויה להאמין בסדר אישי ולחיות לפי קוד או אמת מידה, או להאמין בסדר החל על כולם ולהעדיף ממשל חזק ומאורגן.

סדר-ניטרלי היא הנטייה הטובה ביותר שאפשר להיות, משום שמשמעותה שאתה אמין ובעל כבוד בלי להיות קנאי.

**ניטרלי, "מתלבט"**: דמות ניטרלית עושה את מה שנראה כרעיון טוב. היא אינה חשה בעוצמה לכאן או לכאן כשמדובר בטוב מול רע או בסדר מול תוהו. רוב הדמויות הניטרליות מפגינות חוסר עמדה נחרצת או הטיה לצד מסוים, ולא מחויבות לניטרליות. דמות כזו חושבת שטוב עדיף על רע — אחרי הכול, היא מעדיפה שכנים ושליטים טובים על פני רעים. ובכל זאת, היא אינה מחויבת אישית לשמירה על הטוב באופן מופשט או אוניברסלי כלשהו.

יש דמויות ניטרליות, לעומת זאת, שמתחייבות מבחינה פילוסופית לניטרליות. הן רואות בטוב, ברע, בסדר ובתוהו דעות קדומות וקיצוניות מסוכנות. הן מצדדות בדרך האמצע של הניטרליות כדרך הטובה והמאוזנת ביותר בטווח הארוך.

ניטרלי היא הנטייה הטובה ביותר שאפשר להיות, משום שמשמעותה שאתה פועל באופן טבעי, ללא משוא פנים או דחף כפייתי.

**תוהו-ניטרלי, "רוח חופשית"**: דמות תוהו-ניטרלי הולכת אחר גחמותיה. היא אינדיבידואליסטית מתחילה ועד סוף. היא מעריכה את חירותה שלה, אך אינה שואפת להגן על חירותם של אחרים. היא נמנעת מסמכות, מתמרמרת על מגבלות ומאתגרת מסורות. דמות תוהו-ניטרלי אינה משבשת במכוון ארגונים כחלק ממערכה של אנרכיה. כדי לעשות זאת, עליה להיות מונעת או מטוב (ורצון לשחרר אחרים) או מרע (ורצון לגרום סבל למי ששונים ממנה). דמות תוהו-ניטרלי עשויה להיות בלתי צפויה, אך התנהגותה אינה אקראית לחלוטין. אין סבירות גבוהה יותר שתקפוץ מגשר מאשר שתחצה אותו.

תוהו-ניטרלי היא הנטייה הטובה ביותר שאפשר להיות, משום שהיא מייצגת חירות אמיתית הן ממגבלות החברה והן מקנאותם של מתקני עולם.

**סדר-רע, "שתלטן"**: נבל סדר-רע נוטל באופן שיטתי את מה שהוא רוצה במסגרת גבולות קוד ההתנהגות שלו, מבלי להתחשב במי שייפגע מכך. אכפת לו ממסורת, נאמנות וסדר, אך לא מחירות, מכבוד או מחיים. הוא משחק לפי הכללים, אך בלי רחמים או חמלה. הוא חש בנוח בהיררכיה והיה רוצה לשלוט, אך מוכן לשרת. הוא מגנה אחרים לא לפי מעשיהם אלא לפי גזע, דת, מולדת או מעמד חברתי. הוא נרתע מהפרת חוקים או הבטחות.

רתיעה זו נובעת בחלקה מטבעו ובחלקה משום שהוא תלוי בסדר כדי להגן על עצמו מפני מי שמתנגדים לו מטעמים מוסריים. לחלק מנבלי סדר-רע יש טאבוים מסוימים, כגון לא להרוג בדם קר (אך לתת לכפופים להם לעשות זאת) או לא לאפשר פגיעה בילדים (אם אפשר להימנע מכך). הם מדמיינים שעכבות אלו מציבות אותם מעל נבלים חסרי עקרונות.

יש אנשים ויצורים מסדר-רע המקדישים את עצמם לרוע בקנאות הדומה לזו של צלבן המחויב לטוב. מעבר לנכונות לפגוע באחרים למען מטרותיהם, הם מפיקים הנאה מהפצת רוע כמטרה בפני עצמה. הם עשויים גם לראות בעשיית רוע חלק מחובה כלפי אלוהות רעה או אדון רע.

סדר-רע נקראת לעיתים "שטנית", משום ששטנים הם התגלמות הסדר-רע.

סדר-רע היא הנטייה המסוכנת ביותר, משום שהיא מייצגת רוע שיטתי, מכוון ולעיתים קרובות גם מצליח.

**ניטרלי-רע, "עושה עוול"**: דמות נבל ניטרלי-רע עושה כל מה שהיא יכולה לעשות מבלי להיענש על כך. היא דואגת אך ורק לעצמה. היא אינה מזילה דמעה על מי שהיא הורגת, בין אם לשם רווח, ספורט או נוחות. אין לה אהבה לסדר והיא אינה אוחזת באשליה שציות לחוקים, למסורות או לקודים יהפוך אותה לטובה יותר או לאצילית יותר. מצד שני, אין לה את הטבע חסר המנוחה או אהבת העימות שיש לנבל תוהו-רע.

יש נבלים ניטרלי-רע שמעמידים את הרוע כאידיאל ומבצעים רוע לשמו. לרוב, נבלים כאלה מסורים לאלים רעים או לאגודות סודיות.

ניטרלי-רע היא הנטייה המסוכנת ביותר, משום שהיא מייצגת רוע טהור, ללא כבוד וללא כל גוון אחר.

**תוהו-רע, "משמיד"**: דמות תוהו-רע עושה כל מה שתאוות הבצע, השנאה ותשוקת ההרס דוחפות אותה לעשות. היא קצרת רוח, אכזרית, אלימה באופן שרירותי ובלתי צפויה. אם היא פשוט רודפת אחר כל מה שתוכל להשיג, היא חסרת רחמים וברוטלית. אם היא מחויבת להפצת רוע ותוהו, היא גרועה אף יותר. למרבה המזל, תוכניותיה מרושלות, וכל קבוצה שהיא מצטרפת אליה או מקימה מאורגנת בצורה גרועה. בדרך כלל, ניתן לגרום לאנשי תוהו-רע לעבוד יחד רק בכוח, ומנהיגם מחזיק מעמד רק כל עוד הוא מסוגל לסכל ניסיונות להפילו או להתנקש בו.

תוהו-רע נקראת לעיתים "דמונית", משום ששדים הם התגלמות התוהו-רע.

תוהו-רע היא הנטייה המסוכנת ביותר, משום שהיא מייצגת את ההרס לא רק של יופי וחיים, אלא גם של הסדר שעליו יופי וחיים תלויים.

#### הערה בנוגע לקיצורים

בטבלה שלהלן, הנטיות של היצורים השונים מקוצרות. האות הראשונה של הקיצור מייצגת את מיקומו של היצור ביחס לסדר ולתוהו, ולכן יכולה להיות L, N או C. האות השנייה מייצגת את מיקומו של היצור ביחס לטוב ולרע, ולכן יכולה להיות G, N או E. יצורים שניטרליים הן ביחס לסדר מול תוהו והן ביחס לטוב מול רע יהיו אז “NN”, אך לשם פשטות הדבר נכתב כ־N יחיד.

### נטיות מפלצות בבייסיק פנטזי

הערה: רשימה זו אינה מעודכנת למהדורה הרביעית.

<div style="max-height:400px; overflow-y:auto;column-count:3">

<span dir="ltr">(LE)</span> אורגובלין

<span dir="ltr">(LE)</span> אורק

<span dir="ltr">(N)</span> איש לטאה

<span dir="ltr">(N)</span> איש מערות

<span dir="ltr">(N)</span> אנטילופה

<span dir="ltr">(N)</span> אריה

<span dir="ltr">(N)</span> אריה הרים

<span dir="ltr">(N)</span> בבון סלע

<span dir="ltr">(N)</span> בזיליסק

<span dir="ltr">(N)</span> בת ים

<span dir="ltr">(LE)</span> גובלין

<span dir="ltr">(N)</span> גולם (כולם)

<span dir="ltr">(CE)</span> גועל

<span dir="ltr">(N)</span> גורגון

<span dir="ltr">(CG)</span> ג'יני

<span dir="ltr">(N)</span> ג'לי, אוכרי

<span dir="ltr">(CE)</span> גנול

<span dir="ltr">(CE)</span> גרגויל

<span dir="ltr">(N)</span> גריפון

<span dir="ltr">(N)</span> דבורה ענקית

<span dir="ltr">(N)</span> דג ענק (כולם)

<span dir="ltr">(N)</span> דוב (כולם)

<span dir="ltr">(CE)</span> דובלין

<span dir="ltr">(N)</span> דופלגנגר

<span dir="ltr">(N)</span> דיונון, ענק

<span dir="ltr">(LE)</span> דיספלייסר

<span dir="ltr">(N)</span> דריאדה

<span dir="ltr">(CE)</span> דרקון אדום

<span dir="ltr">(LG)</span> דרקון זהב

<span dir="ltr">(N)</span> דרקון, ים

<span dir="ltr">(LE)</span> דרקון ירוק

<span dir="ltr">(LE)</span> דרקון כחול

<span dir="ltr">(CE)</span> דרקון לבן

<span dir="ltr">(CE)</span> דרקון שחור

<span dir="ltr">(LE)</span> הובגובלין

<span dir="ltr">(N)</span> הידרה

<span dir="ltr">(N)</span> היפוגריף

<span dir="ltr">(CE)</span> הרפיה

<span dir="ltr">(NE)</span> ויוורן

<span dir="ltr">(N)</span> ורד דמים

<span dir="ltr">(N)</span> זאב

<span dir="ltr">(N)</span> זבוב ענק

<span dir="ltr">(N)</span> זומבי

<span dir="ltr">(N)</span> חגב מערה ענק

<span dir="ltr">(N)</span> חדף, ענק

<span dir="ltr">(CG)</span> חד-קרן (ואליקורן)

<span dir="ltr">(N)</span> חולדה (כולן)

<span dir="ltr">(N)</span> חזיר בר

<span dir="ltr">(N)</span> חיות משא

<span dir="ltr">(N)</span> חיפושית ענקית (כולן)

<span dir="ltr">(N)</span> חתול שן חרב

<span dir="ltr">(N)</span> טיגריס

<span dir="ltr">(N)</span> טיטנוטרה

<span dir="ltr">(N)</span> טירנוזאורוס רקס

<span dir="ltr">(CE)</span> טרוגלודיט

<span dir="ltr">(CE)</span> טרול

<span dir="ltr">(CG)</span> טריאנט

<span dir="ltr">(N)</span> טריצרטופס

<span dir="ltr">(N)</span> טרמיט מים, ענק

<span dir="ltr">(N)</span> יגואר

<span dir="ltr">(N)</span> ינשודוב

<span dir="ltr">(N)</span> יסודן (כולם)

<span dir="ltr">(CE)</span> כימרה

<span dir="ltr">(N)</span> כלב (כולם)

<span dir="ltr">(LG)</span> כלב הבהוב

<span dir="ltr">(LE)</span> כלב שאול

<span dir="ltr">(N)</span> כריש (כולם)

<span dir="ltr">(N)</span> לווייתן (כולם)

<span dir="ltr">(N)</span> לטאה ענקית (כולן)

<span dir="ltr">(CG)</span> ליקנתרופ, איש־דוב

<span dir="ltr">(CE)</span> ליקנתרופ, איש־זאב

<span dir="ltr">(LE)</span> ליקנתרופ, איש־חולדה

<span dir="ltr">(N)</span> ליקנתרופ, איש־חזיר

<span dir="ltr">(N)</span> ליקנתרופ, איש־טיגריס

<span dir="ltr">(LE)</span> מדוזה

<span dir="ltr">(LE)</span> מומיה

<span dir="ltr">(CE)</span> מינוטאור

<span dir="ltr">(LE)</span> מנטיקור

<span dir="ltr">(N)</span> מפלצת חלודה

<span dir="ltr">(N)</span> נדל ענק

<span dir="ltr">(N)</span> נחיל חרקים

<span dir="ltr">(N)</span> נחש (כולם)

<span dir="ltr">(N)</span> ניקסית

<span dir="ltr">(N)</span> נמלה ענקית

<span dir="ltr">(NG)</span> ננס

<span dir="ltr">(N)</span> נץ

<span dir="ltr">(N)</span> סטגוזאורוס

<span dir="ltr">(N)</span> סטריג'

<span dir="ltr">(N)</span> סלמנדרה

<span dir="ltr">(N)</span> סמור ענק (או חמוס ענק)

<span dir="ltr">(LE)</span> ספקטר

<span dir="ltr">(NG)</span> ספרייט

<span dir="ltr">(N)</span> סרטן ענק

<span dir="ltr">(N)</span> עובש צהוב

<span dir="ltr">(CE)</span> עוג

<span dir="ltr">(N)</span> עוקב בלתי נראה

<span dir="ltr">(N)</span> עטלף

<span dir="ltr">(N)</span> עטלף ענק

<span dir="ltr">(N)</span> עכביש ענק (כולם)

<span dir="ltr">(N)</span> עלוקה ענקית

<span dir="ltr">(N)</span> ענק, אבן

<span dir="ltr">(LE)</span> ענק, אש

<span dir="ltr">(CE)</span> ענק, גבעה

<span dir="ltr">(CE)</span> ענק, כפור

<span dir="ltr">(CG)</span> ענק, סערה

<span dir="ltr">(N)</span> ענק, ענן

<span dir="ltr">(CE)</span> ענק, קיקלופ

<span dir="ltr">(LE)</span> עפרית

<span dir="ltr">(NE)</span> עץ תליין

<span dir="ltr">(N)</span> עקרב, ענק

<span dir="ltr">(CE)</span> ערפד

<span dir="ltr">(CG)</span> פגסוס

<span dir="ltr">(N)</span> פודינג שחור

<span dir="ltr">(N)</span> פטרודקטיל/פטרנודון

<span dir="ltr">(N)</span> פיל

<span dir="ltr">(N)</span> פיקסי

<span dir="ltr">(N)</span> פסל חי (כולם)

<span dir="ltr">(N)</span> פתן ים

<span dir="ltr">(N)</span> צב דרקון

<span dir="ltr">(N)</span> צווחן

<span dir="ltr">(NE)</span> צל

<span dir="ltr">(N)</span> צפרדע/קרפדה ענקית

<span dir="ltr">(LE)</span> קובולד

<span dir="ltr">(N)</span> קוביית ג'לטין

<span dir="ltr">(N)</span> קוף טורף

<span dir="ltr">(N)</span> קוקטריס

<span dir="ltr">(CG)</span> קנטאור

<span dir="ltr">(N)</span> קרנף

<span dir="ltr">(N)</span> ראגודסה, ענקית

<span dir="ltr">(LE)</span> רוח צל

<span dir="ltr">(N)</span> רוק

<span dir="ltr">(LE)</span> רפא

<span dir="ltr">(N)</span> רפש אפור

<span dir="ltr">(N)</span> רפש ירוק

<span dir="ltr">(N)</span> שלד

<span dir="ltr">(N)</span> תולען, ענק

<span dir="ltr">(N)</span> תולעת זרועות

<span dir="ltr">(N)</span> תולעת סגולה

<span dir="ltr">(N)</span> תמנון ענק

<span dir="ltr">(N)</span> תנין

</div>

## שריונות ומגינים

### מבוא

תוספת זו מספקת שריונות ומגינים נוספים למשחק לפי חוקי משחק התפקידים בייסיק פנטזי. אם עדיין אין ברשותך עותק של חוקי בייסיק פנטזי RPG, בקר באתר והורד עותק.

הטבלאות שלהלן מספקות מגוון מורחב של שריונות ומגינים לשימוש במשחק. זמינותם של פריטים נוספים אלה נתונה, כמובן, לשיקול דעתה של המנחה.

אלא אם צוין אחרת, לבישת חליפת שריון או הסרתה אורכת 10 סיבובים פחות תוסף הזריזות של הדמות.

:::{.column-margin}
מהדורה 3

זכויות יוצרים © 2010 Jeff Johnson

כל הזכויות שמורות

מופץ בהתאם לתנאי רישיון המשחק הפתוח (Open Game License) גרסה 1.0a
:::

שריונות עשויים לעיתים מחומרים שונים, ובמיוחד מגינים. שריונות לוחות מסוימים עשויים מברונזה או אולי מסגסוגת אחרת, אף שעל פי רוב הם עשויים מפלדה. חומרים שונים והשפעתם על משקל, עלות ודירוג שריון חורגים מהיקף מסמך זה. המנחה מוזמנת לבצע התאמות אלה כפי שתמצא לנכון, תוך שמירה על אופיו הפשוט והבסיסי של בייסיק פנטזי RPG.

ניתן להניח בבטחה ששריון שמשקלו 11.5 ק"ג או פחות נחשב "קל", ושריון שמשקלו 22.5 ק"ג או יותר נחשב "כבד". כל שריון שנמצא בין גבולות אלה יכול להיחשב "בינוני".

### שריון

| סוג השריון       | עלות     | משקל (ק״ג) | דירוג שריון |
| ---------------- | -------- | ---------- | ----------- |
| ללא שריון        | 0 מ״ז    | 0          | 11          |
| שריון מרופד      | 15 מ״ז   | 4.5        | 12          |
| שריון עור גס     | 10 מ״ז   | 13.5       | 13          |
| שריון עור        | 20 מ״ז   | 7          | 13          |
| שריון עור ממוסמר | 30 מ״ז   | 11.5       | 14          |
| שריון טבעות      | 25 מ״ז   | 13.5       | 14          |
| שריון שרשראות    | 60 מ״ז   | 18         | 15          |
| שריון קשקשים     | 80 מ״ז   | 25         | 16          |
| שריון רצועות     | 100 מ״ז  | 20.5       | 16          |
| שריון לוחות      | 300 מ״ז  | 22.5       | 17          |
| שריון לוחות שדה  | 500 מ״ז  | 32         | 18          |
| שריון לוחות מלא  | 1500 מ״ז | 36.5       | 19          |

### מגן

| סוג מגן    | עלות  | משקל (ק״ג) | תוסף דירוג שריון: קרב פנים אל פנים/קליעים |
| ---------- | ----- | ---------- | ------------------------------------------ |
| מגן אגרוף  | 5 מ״ז | 1          | +1/0                                       |
| מגן בינוני | 7 מ״ז | 3          | +1/+1                                      |
| מגן מגדל   | 5 מ״ז | 5.5        | +1/+3                                      |

### תיאורי שריון

**שריון מרופד** נוצר משכבות בד המונחות זו על גבי זו. לעיתים הוא טקסי ואינו שימושי במיוחד, אך הוא מספק מידה מזערית של הגנה. שכבות הבד מצוינות לחודשי החורף משום שהן מספקות בידוד טוב, אך לעיתים קרובות הן נעשות מיוזעות ומלוכלכות אלא אם מכבסים אותן כראוי ובתדירות גבוהה.

**שריון עור גס** דומה מאוד לשריון עור באופן הכנתו וברמת ההגנה שהוא מספק. לעיתים קרובות ניתן למצוא שריון עור גס באזורים מרוחקים או בארצות ברבריות; זהו הסוג הנפוץ ביותר שבו משתמשים אורקים והומנואידים רבים אחרים. תהליך יצירת שריון עור גס כולל עיבוד עור החיה ותפירתו לבגד. לעיתים הוא חם ומגרד, אך מספק הגנה דומה לשריון עור רגיל.

**שריון עור** מורכב מחלקים של עור מוקשה ו/או רב-שכבתי. יש מגוון שיטות ליצירת שריון זה, שרובן כוללות הרתחה, עיצוב ולאחר מכן הקשחת השריון. חלקי העור נתפרים לבגד תחתון מבד לשם גמישות מרבית.

**שריון עור ממוסמר** דומה לשריון עור רגיל, אך במקום להקשיח את העור, מחברים אליו מסמרי מתכת ו/או לוחות קטנים באמצעות מסמרות. מסמרי המתכת, יחד עם העור, מספקים הגנה נוספת מפני התקפות, במחיר של פגיעה קלה בניידות.

**שריון טבעות** מורכב מטבעות פלדה שנתפרות ישירות לבגד תחתון. הטבעות עצמן מספקות גמישות רבה והגנה סבירה. הבגד שמתחת הוא בדרך כלל מעור רך וגמיש, העמיד בפני שחיקה קלה.

**שריון שרשראות** מורכב מטבעות מתכת השזורות זו בזו, ולא נתפרות לבגד עור. שריון שרשראות נלבש מעל בגד תחתון מרופד (ראה שריון מרופד, לעיל); אם נלבש ללא הבגד התחתון המרופד, שריון שרשראות מספק דירוג שריון 13 במשקל 13.5 ק"ג. שריון שרשראות גמיש מאוד ועמיד. זהו אחד מסוגי השריון הפופולריים והנגישים ביותר לדמויות שחקן. שריון שרשראות יכול להיעשות בצורת חליפה (כלומר טוניקה ומכנסיים) או בצורת הוברק, המורכב מטוניקה עם חצאית או קילט להגנת הרגליים.

**שריון קשקשים** עשוי מקשקשי מתכת השזורים ישירות בבגד תחתון, המספק גמישות והגנה מתונה.

**שריון רצועות** הוא צורה של שריון שרשראות שבה רצועות קטנות של מתכת עבה שזורות בין טבעות השריון. לוחות קטנים ומשובצים אלה מספקים כיסוי מצוין והגנה עבה יותר מאשר שריון שרשראות רגיל, במחיר של משקל נוסף ופחות גמישות.

**שריון לוחות** הוא צורה נפוצה נוספת של שריון מתכת. לוחות גדולים של מתכת קשה מעוצבים כך שיכסו את הגו, הזרועות והרגליים, ומחוברים במפרקים לחליפת שריון שרשראות שמתחת; מתחתיהם נלבש בגד תחתון מרופד (ראה שריון מרופד, לעיל). אם שריון לוחות נלבש ללא הבגד התחתון המרופד, דירוג השריון שהוא מספק הוא 15 במשקל 18 ק"ג. לחלקים השונים של שריון הלוחות יש שמות ייעודיים, כדלקמן:

- **לוח חזה** -- מכסה את החזה והגב של הלובש. לעיתים נקרא גם קיראס. לוח החזה הוא החלק הגדול ביותר של השריון ומשקלו כ־7.5 ק"ג.

- **פולדס** -- נלבשים מתחת ללוח החזה כדי לכסות את המותניים והירכיים. הפולדס שוקלים כ־4.5 ק"ג.

- **טאסטס** -- נלבשים על הירכיים. הטאסטס מהווים כ־3.5 ק"ג ממשקל השריון הכולל.

- **מגיני שוק** -- נלבשים על השוקיים. זוג מגיני שוק שוקל בדרך כלל כ־2 ק"ג.

- **מגיני כתף** -- נלבשים על הכתפיים. מגיני כתף שוקלים, בממוצע, כ־2.5 ק"ג.

- **מגיני אמה** -- נלבשים על האמות. מגיני אמה שוקלים בדרך כלל כ־2 ק"ג.

- **כפפות שריון** -- נלבשות על הידיים. כפפות שריון שוקלות רק כ־1 ק"ג.

**שריון לוחות שדה** מורכב מחלקים מוצקים של שריון לוחות, המחוברים זה לזה באמצעות מגוון חלקי החלקה מורכבים, צירים ורצועות. חלקים קטנים של שריון שרשראות משמשים לכיסוי מפרקים שקשה להגן עליהם, כגון מאחורי הברכיים ומתחת לזרועות. שריון לוחות שדה מספק הגנה טובה יותר מאשר שריון לוחות רגיל, עם עלייה קטנה יחסית במשקל, אך חייב להיות מותאם אישית ללובש; בדרך כלל משמעות הדבר היא שדמות הרוכשת שריון מסוג זה חייבת להמתין לפחות שבוע מלא בין ביצוע ההזמנה לבין קבלת החליפה המוגמרת. שריון לוחות שדה נלבש מעל בגד תחתון מרופד (ראה שריון מרופד, לעיל), ואם נלבש ללא הבגד התחתון המרופד, דירוג השריון שהוא מספק הוא 17 במשקל 27 ק"ג.

**שריון לוחות מלא** זהה בדרך כלל לשריון לוחות שדה, אך הוא בעל תכנון וייצור מעולים; רק שריונר מומחה יכול ליצור אותו. הלוחות מכסים את הלובש באופן מלא יותר, ובדרך כלל אין שימוש כלל בשריון שרשראות. בנוסף, הלוחות עצמם מתוכננים להסיט פגיעות נשק הרחק ממפרקים שאחרת היו פגיעים. מי שלובש שריון לוחות מלא סובל ממחסר של -1 לגלגולי התקפה בשל ניידות מוגבלת בעת לבישת השריון. לא ניתן ללבוש שריון לוחות מלא ללא עזרה, וגם בסיוע נדרש לפחות 1 תור כדי ללבוש אותו.

### תיאורי מגינים

**מגן אגרוף** הוא מגן קטן הנלבש על האמה כדי לחסום התקפות נכנסות. קוטרו בדרך כלל כ־30 ס"מ. הלובש מגן אגרוף מקבל +1 לדירוג השריון שלו בקרב פנים אל פנים, אך אינו מקבל כל הגנה מפני ירי קליעים. ניתן להשתמש במגן אגרוף בידי מי שמניף 2 כלי נשק, כפי שמתואר בתוספת אפשרויות הקרב; אם עושים זאת, הדמות יכולה לתקוף עם הנשק שביד המשנית או לקבל את תועלת המגן.

**מגן בינוני** הוא בדרך כלל בקוטר של כ־1 מטר ולעיתים קרובות הוא עגול, אף שמגינים יכולים להגיע במגוון צורות. מגן בינוני נלבש באמצעות השחלת הזרוע דרך רצועה ואז אחיזה בידית כלשהי בצדו האחורי של המגן. מגן בינוני מעניק ללובש +1 לדירוג השריון הן בקרב פנים אל פנים והן נגד קליעים; במילים אחרות, זהו המגן ה"סטנדרטי" כפי שמתואר בחוקי הבסיס.

**מגן מגדל** הוא מגן גדול מאוד שכמעט מגיע לגובה הלובש; מגן כזה הוא בדרך כלל מלבני, אך צורות אליפטיות, אובליות ומעוגלות אינן נדירות. בשל אופיו המגושם והמסורבל של מגן כה גדול, הוא מציע הגנה דומה לזו של מגן בינוני בקרב פנים אל פנים (+1), אך מעניק הגנה מעולה מפני ירי קליעים (+3) בזכות גודלו.

### חוקים אופציונליים

**שריון מורכב**

במקרים מסוימים, המנחה עשויה לרצות לאפשר לדמויות להרכיב יחד את החלקים השונים של שריון לוחות כדי ליצור מראה מותאם אישית או למטרה אחרת. הדבר ידוע בשם **שריון מורכב מחלקים**. על כל 2 חלקים של שריון לוחות, מלבד לוח החזה, דמות יכולה להוסיף +1 לדירוג השריון שלה, עד לתוסף כולל של +3. הדמות אינה יכולה לקבל תוסף גבוה מ־+3 לדירוג השריון. הערה: "חלק" של שריון לוחות כולל הן את הצד הימני והן את הצד השמאלי של אותו סוג חלק. מגן אמה יחיד אינו נחשב "חלק" עד שמצטרף אליו מגן אמה שני. לוח חזה ניתן ללבישה רק מעל שריון מרופד ומעניק תוסף +2 לדירוג השריון.

**לדוגמה:** תורוס הלוחם הגמדי לובש כעת שריון שרשראות. הוא מוצא חליפת שריון לוחות גמדית בעת שהוא חוקר מכרה נטוש, אך אחת מכפפות השריון ולוח החזה חסרים. הוא חוגר את מגיני השוק, הטאסטס, מגיני הכתף, מגיני האמה והפולדס. 5 חלקים מלאים נחגרו, וכך דירוג השריון הכולל של הגמד עולה ל־17. הדבר גם מגדיל את המשקל הכולל של שריונו ב־14.5 ק"ג, לסך של 32.5 ק"ג, שהוא כבד יותר משריון לוחות בשל החפיפה בין חלקי שריון הלוחות לחלקי שריון השרשראות.

## מיומנויות רקע

### מבוא

מסמך זה מציג שיטה חלופית להקצאת מיומנויות רקע לדמויות במשחק התפקידים בייסיק פנטזי. אם אין ברשותך עותק של **חוקי הבסיס של בייסיק פנטזי RPG**, בקר ב־www.basicfantasy.org והורד עותק... זה בחינם!

**חוקי הבסיס של בייסיק פנטזי RPG** מאפשרים לך ליצור לוחמים אמיצים, כוהנים אדוקים, גנבים ערמומיים וקוסמים מבריקים להרפתקאות בעולמות פנטזיה מגוונים. אך לעיתים הרפתקנים, הן במהלך הרפתקאות והן ביניהן, יודעים לעשות דברים נוספים מעבר להילחם, להתפלל, להתגנב או להטיל לחשים. חוקים חלופיים ואופציונליים אלה מנסים לכסות חלק מן המיומנויות המשניות הללו.

### הבסיס לחוקים אלה

המושג המרכזי כאן הוא "סבירות" -- אם הדבר סביר, המנחה צריכה לאפשר אותו (ייתכן תוך דרישה לגלגול תכונה).

### הרפתקנים יודעים כיצד לצאת להרפתקאות

דמויות שחקן, בניגוד לרוב האנשים הרגילים, הן הרפתקנים. אף שהן עשויות להיות רק הרפתקנים מתחילים בדרגה 1, עדיין מניחים שהן מכירות את יסודות ההרפתקה והחקירה. הנח שכל דמויות השחקן יודעות לקשור קשרים, לטפס, לשחות, לחתור בסירה קטנה, להדליק מדורה סבירה (בדרך כלל בעזרת ערכת הצתה), לבצע תיקונים קלים ותחזוקה לכלי נשק ולשריון ולרכוב על סוס. למעט ברברים (תת-מקצוע של לוחם), הנח שכל דמויות השחקן יודעות קרוא וכתוב בכל השפות שהן דוברות, יודעות לקרוא ויודעות מתמטיקה לפחות ברמת בית ספר יסודי; ברברים חייבים לבחור באוריינות כשפה.

עם זאת, העובדה שההרפתקן יודע לבצע כל אחת מן המשימות הבסיסיות הללו אינה אומרת שהוא יצליח בהן אוטומטית. המנחה צריכה לשפוט כל ניסיון ולהכריע בתוצאותיו. משימות פשוטות (כגון טיפוס בסולם או בחבל, או הדלקת מדורה מעץ יבש באמצעות ערכת הצתה) צריכות להצליח אוטומטית; משימות קשות (כגון טיפוס על מצוק או קיר קשים, או ניסיון להדליק אש ללא ערכת הצתה) צריכות לדרוש גלגול תכונה (בדוגמאות שלנו, על בסיס זריזות ותבונה, בהתאמה). משימות בלתי אפשריות בעליל (כגון ניסיון להצית אבנים באמצעות ערכת הצתה וללא שמן) צריכות תמיד להיכשל -- אין צורך בגלגול.

שים לב כי החשיבה צריכה בדרך כלל להיעשות בידי השחקנים, לא הדמויות. גלגול תבונה אינו אמור לפתור חידות או פאזלים -- השחקנים צריכים לנסות ולפענח אותם בעצמם (כך בדרך כלל גם מהנה הרבה יותר). למעשה, מניחים שהדמויות יודעות קרוא וכתוב ויודעות מעט מתמטיקה בדיוק מסיבה זו -- כדי לאפשר למנחה להציג לשחקנים אתגרים מעניינים ומהנים בלי יותר מדי בעיות.

### מיומנויות רקע

מעבר להרפתקאות, דמויות מוכשרות עשויות להיות מיומנות גם במקצוע אחד או יותר שאינם קשורים ישירות להרפתקאות. כל דמות מתחילה בדרגה 1 עם מספר מיומנויות רקע השווה לתוסף הדרישה העיקרית שלה, אך לא פחות מ־0. דמויות עם דרישות עיקריות נמוכות חייבות לעבוד קשה יותר כדי ללמוד את היכולות הבסיסיות של המקצוע שלהן, ולכן יש להן פחות זמן (או אין להן זמן כלל) ללמוד מלאכות אחרות; לעומת זאת, דמויות עם דרישות עיקריות גבוהות לומדות ביתר קלות את יכולות המקצוע שלהן ולכן יש להן יותר זמן פנוי ללמוד מקצועות נוספים.

כל מיומנות רקע היא מקצוע רחב, כגון בנאי, נגר, מלטש אבני חן, צורף, איכר, איש יער, נפח וכדומה. היא כוללת את כל המיומנויות הבסיסיות הכרוכות במקצוע זה. הנח שדמות יכולה לבצע בקלות את משימות היום-יום של כל אחת ממיומנויות הרקע שלה, כל עוד יש לה גישה לכלים, לציוד ולחומרים הנדרשים; אין צורך לגלגל קוביות במקרה כזה. רק משימות קשות דורשות גלגול תכונה. לדוגמה, דמות עם מיומנות הרקע נפח יכולה לייצר בקלות פרסות, סירים ואפילו ראשי חץ באיכות ממוצעת, כל עוד יש לה גישה לנפחייה פעילה, פחם, ברזל וכדומה; רק יצירת פריט מיוחד (כגון חרב איכותית המתאימה להקסמה בהמשך) תדרוש גלגול תכונה.

דמויות מנחה, כמובן, מיומנות במקצועותיהן ככל שהמנחה צריכה שיהיו.

### כמה דוגמאות למיומנויות רקע

ניתן להשתמש בקוביות אחוזים כדי לקבוע מיומנויות רקע, אם רוצים, או שהשחקן יכול פשוט לבחור מן הרשימה (או להמציא מקצוע אחר, בהסכמת המנחה).

|        |                    |
| ------ | ------------------ |
| 01-04  | עורך דין           |
| 05-08  | אלכימאי            |
| 09-12  | שריונר             |
| 13-16  | נפח                |
| 17-20  | עושה קשתות/חצים    |
| 21-24  | מבשל בירה          |
| 25-28  | סנדלר              |
| 29-32  | נגר                |
| 33-36  | טבח                |
| 37-40  | מהנדס              |
| 41-44  | איכר               |
| 45-48  | מלטש אבני חן       |
| 49-52  | עשבונאי            |
| 53-56  | צורף               |
| 57-60  | בנאי               |
| 61-64  | סוחר               |
| 65-68  | נווט               |
| 69-72  | רופא               |
| 73-76  | קדר                |
| 77-80  | מלח                |
| 81-84  | חייט               |
| 85-88  | בורסקאי            |
| 89-92  | נפח נשק            |
| 93-96  | אורג               |
| 97-100 | איש יער            |

### לימוד מיומנויות רקע חדשות

לימוד מקצוע חדש לוקח זמן. הרבה זמן. ולעיתים גם סכום כסף ניכר. יש 2 דרכים ללמוד מיומנות רקע חדשה: לשכור מורה או להפוך לשוליה.

מורה שכיר יכול לספק הכשרה אינטנסיבית הנמשכת עונה אחת (לדוגמה, חורף שלם) כדי ללמד מיומנות רקע. אפשרות זו, עם זאת, יקרה, שכן המורה אינו יכול לעשות דבר אחר במהלך הזמן הזה; עלות ההכשרה האינטנסיבית היא לכן 2,000 מ"ז. גם התלמיד אינו יכול לעשות דבר אחר (כולל לצאת להרפתקאות) במהלך אותה עונה. לחלופין, ניתן ללמוד את המיומנות מדי פעם בין הרפתקאות, כך שלוקח שנה שלמה ללמוד אותה במלואה; במקרה זה העלות היא 1,000 מ"ז. שים לב שמציאת מורים למקצועות מסוימים (כגון אלכימאי או מהנדס) עשויה להיות קשה יותר (ויקרה יותר!) ממציאת מורים למקצועות אחרים.

ההתלמדות כשוליה אינה כרוכה בתשלום, שכן השוליה עובד אצל בעל המלאכה שמלמד אותו. מצד שני, גם בעל המלאכה צריך לעבוד, ורבות מן המשימות שעל השוליה לבצע הן עבודות שחורות שונות ולא לימוד ממוקד. התלמדות במשרה מלאה (שאינה מאפשרת לצאת להרפתקאות בינתיים) דורשת שנה שלמה כדי ללמוד מיומנות רקע אחת. התלמדות במשרה חלקית (המאפשרת לצאת להרפתקאות) אורכת 3 שנים.

## אפשרויות קרב

### מבוא

תוספת זו מוסיפה אפשרויות קרב נוספות לדמויות שחקן ולדמויות מנחה לשימוש עם חוקי משחק התפקידים בייסיק פנטזי. אם עדיין אין ברשותך עותק של חוקי בייסיק פנטזי RPG, בקר באתר והורד עותק.

:::{.column-margin}
**מהדורה 4**

זכויות יוצרים © 2007-2018 Chris Gonnerman, Luigi Castellani, and R. Kevin Smoot

כל הזכויות שמורות

מופץ בהתאם לתנאי רישיון המשחק הפתוח (Open Game License) גרסה 1.0a
:::

### שימוש בחוקים אלה

להלן מוגדרים חוקים שונים לקרב שהם *אופציונליים*. על המנחה לבחור אילו מן החוקים הללו, אם בכלל, חלים במשחק שלה.

כדי להקל על השימוש באפשרויות אלה, לכל חוק אופציונלי יש תיבת סימון לצידו. המנחה עשויה לרצות להדפיס עותק של תוספת זו ולסמן את תיבות הסימון עבור החוקים שבחרה.

### התמחות בנשק ☐

לפי חוק זה, השחקן של לוחם יכול לבחור נשק שבו הדמות מיומנת במיוחד. התמחות חלה רק על לוחמים "אמיתיים", ולא על תתי-מקצוע שלהם שעשויים להופיע בתוספות אחרות, אלא אם צוין אחרת.

בדרגה 1, השחקן מקצה **רמת התמחות** אחת לנשק הנבחר. בחירה זו חייבת להיות ספציפית למדי; למשל, התמחות בחרב ארוכה לא תעניק שום תוסף בעת שימוש בחרב קצרה.

בכל דרגה שלישית לאחר דרגה 1 (כלומר, 4, 7, 10 וכו') השחקן מקצה רמת התמחות נוספת. כל רמה חדשה יכולה להיות מוקצית להתמחות קיימת או להתמחות חדשה.

לדוגמה, בדרגה 1 השחקן של דאריון מקצה רמת התמחות לחרב ארוכה. דאריון מקבל תוסף +1 לגלגולי התקפה בעת שימוש בחרב ארוכה. בדרגה 4, השחקן יכול להקצות את הרמה החדשה לחרב ארוכה, וכך לקבל תוסף +1 לגלגולי התקפה ותוסף +1 לנזק; לחלופין, ניתן להקצות את הרמה לנשק חדש, כגון קשת ארוכה, ובמקרה זה לשני כלי הנשק יש תוסף +1 לגלגולי התקפה אך אין להם תוסף לנזק.

כפי שמצוין בעמודת התקפות לסיבוב, ברמות התמחות גבוהות יותר הלוחם רשאי לתקוף יותר מפעם אחת בסיבוב. 3/2 פירושו שהדמות יכולה לתקוף 3 פעמים בכל 2 סיבובים: פעם אחת בסיבוב שמספרו אי-זוגי ופעמיים בסיבוב שמספרו זוגי. ב־2/1 הלוחם רשאי לתקוף עם הנשק שבו התמחה 2 פעמים בכל סיבוב. התקפות נוספות תמיד מתבצעות לאחר שכל שאר ההתקפות הוכרעו; כלומר, הלוחם תוקף פעם אחת במספר היוזמה שלו, ואז שוב לאחר שכל ההתקפות ה"ראשונות" הסתיימו. אם יותר ממומחה נשק אחד מעורב בקרב, יש לספור את היוזמה לאחור פעמיים: פעם אחת עבור ההתקפות ה"ראשונות" ושוב עבור ההתקפות ה"שניות".

| רמת התמחות | תוספי קרב (התקפה / נזק) | התקפות לסיבוב |
|------|-----------------------------|----------------|
| 1    | +1 / +0                     | 1 / 1          |
| 2    | +1 / +1                     | 1 / 1          |
| 3    | +2 / +1                     | 3 / 2          |
| 4    | +2 / +2                     | 3 / 2          |
| 5    | +3 / +2                     | 2 / 1          |
| 6    | +3 / +3                     | 2 / 1          |

יש מנחות שאינן אוהבות את קצב 3/2, משום שהוא מחייב לעקוב אחר סיבובים זוגיים ואי-זוגיים. במקרה כזה, המנחה יכולה לבחור להשתמש ב־1/1 עבור שתי הרמות, או ב־1/1 עבור רמה 3 וב־2/1 עבור רמה 4.

### מומחה מגן ☐

לוחם יכול להשקיע רמת התמחות כדי להתמחות בשימוש במגנים.

אם המנחה משתמשת בסוגי מגנים לא-סטנדרטיים נוספים (ראה את תוספת השריון והמגן), על הדמות לרכוש התמחות בכל סוג כזה בנפרד.

מומחה מגן מקבל תוסף נוסף של +1 לדירוג השריון בעת שימוש במגן.

### מומחה שריון ☐

לוחם יכול להשקיע רמת התמחות כדי להחשיב סוג שריון לבחירתו כקל יותר בקטגוריית משקל אחת לצורך קצב התנועה.

לוחם יכול להחיל רק רמת התמחות אחת על כל סוג שריון.

### פגיעות קריטיות ☐

20 טבעי בגלגול התקפה יוצר **איום**. גלגל שוב -- אם הגלגול השני פוגע (פגיעה רגילה, לא רק 20 טבעי נוסף), מתרחשת **פגיעה קריטית** ונגרם נזק כפול. עם זאת, אם הדרך היחידה שבה הדמות יכולה לפגוע היא לגלגל 20 טבעי, לא מתרחשות פגיעות קריטיות.

### תקלות ☐

1 טבעי בגלגול התקפה עשוי לגרום ל**תקלה**; במקרה כזה, השחקן חייב לבצע גלגול הצלה נגד קרן מוות עם החלת מתאם הזריזות. אם גלגול ההצלה נכשל, מתרחשת תקלה.

תוצאות התקלה משתנות בהתאם לסוג הנשק. עבור כלי נשק המוחזקים ביד, הנשק נשמט; השתמש בטבלת כלי הנשק דמויי-הרימון כדי לקבוע היכן הוא נופל, תוך התייחסות למחזיק כאילו הוא ה"מטרה" בטבלה. אם הדמות קושרת את נשקה לידה (כך שאינה יכולה להפיל אותו), התקלה גורמת לדמות לספוג נזק השווה לקוביית ההתקפה הרגילה של הנשק (ללא תוסף כוח, תוסף קסום או תוספים אחרים). עבור קשתות, התוצאה הרגילה היא מיתר קשת שנקרע; עבור רובה קשת, תקלה גורמת למנגנון להיתקע ודורשת 2d10 סיבובים כדי לשחרר אותו.

מומלץ למנחה להמציא תוצאות תקלה חלופיות כאשר הדבר מתאים לנסיבות, ולהשתמש בהצעות אלה כהנחיה.

### קרב בשני כלי נשק ☐

כלל זה מאפשר לדמות להשתמש בנשק בכל יד. הנשק ביד הראשית סובל ממחסר של -2 לגלגולי התקפה, ואילו הנשק ביד המשנית סובל בדרך כלל ממחסר של -5. תוסף הזריזות של הדמות מקטין את המחסרים הללו, אך אינו יכול להפוך אותם לתוסף (כך שדמות עם זריזות 18 אינה מקבלת בדרך זו תוסף +1 לגלגולי התקפה). הנשק הראשי חייב, כמובן, להיות חד-ידני, והנשק המשני חייב להיות פגיון, גרזן יד או נשק קטן מאוד דומה.

הנשק ביד המשנית בדרך כלל אינו מקבל התקפות מרובות, גם אם הדבר מותר באמצעות התמחות. כמו מפלצת המשתמשת ברצף התקפות (טופר-טופר-נשיכה), הנשק ביד המשנית תוקף באותו הזמן כמו הנשק הראשי.

הערה: התקפות עם הנשק ביד המשנית, ללא התקפה ביד הראשית, סובלות ממחסר בסיסי של -3, ותוסף הזריזות מקטין מחסר זה כפי שמתואר לעיל.

כאופציה, דמות המשתמשת בקרב בשני כלי נשק יכולה לבחור להשתמש בנשק שביד המשנית כחפץ הגנתי בדומה למגן. יש להצהיר על כך בתחילת הסיבוב.

במקרה זה, לא חל מחסר מיוחד על הנשק הראשי, והנשק ביד המשנית מעניק +1 לדירוג השריון של המחזיק נגד תוקף אחד בקרב פנים אל פנים בכל סיבוב.

אם הנשק קסום ויש לו תוסף, ניתן להחיל אותו; בנשק בעל כמה ערכי תוסף, ניתן להחיל רק את התוסף הבסיסי.

אם לדמות יש תוסף התמחות בנשק שביד המשנית שבו היא משתמשת להגנה, יש להוסיף לדירוג השריון גם את תוסף ההתקפה שמעניקה ההתמחות.

### התגוננות ☐

כללי דירוג השריון מניחים שהדמות מנסה להימנע מכל התקפה המכוונת אליה, תוך שהיא עדיין מבצעת התקפות משלה. עם זאת, יהיו מצבים שבהם הדמות פשוט רוצה להימנע מלהיפגע. על השחקן להצהיר שהדמות **מתגוננת**. ניתן לעשות זאת ללא קשר ליוזמה, ולכן זו בחירה טובה כאשר הדמות נלחמת ללא שריון ומפסידה ביוזמה.

דמות מתגוננת מקבלת תוסף +4 לדירוג השריון. אם הדמות מחזיקה או משתמשת בנשק שבו התמחתה, היא יכולה להוסיף לדירוג השריון את תוסף ההתקפה של ההתמחות, כדי לשקף מיומנות נוספת בהדיפה. כמו כן, נשקים קסומים בדרך כלל מעניקים את התוסף שלהם גם לדירוג השריון של הדמות המתגוננת (כמתואר תחת קרב בשני כלי נשק, לעיל).

### קרב מטה חלופי ☐

בדרך כלל יש לאחוז במטות בשתי ידיים, אף שבמטה הליכה ניתן להשתמש ביד אחת, ואז הוא גורם נזק כמו אלה. דמות המשתמשת במטה מכל סוג בשתי ידיים יכולה לבצע התקפה רגילה ועדיין להשתמש בנשק כדי להדוף התקפה אחת בקרב פנים אל פנים; הדבר מעניק למחזיק +1 לדירוג השריון נגד אותה התקפה, בדומה מאוד למגן. לחלופין, ניתן להשתמש במטה כמגן נגד כל מספר של תוקפים בקרב פנים אל פנים, ולקבל תוסף +1 לדירוג השריון, אך במקרה זה המחזיק אינו יכול לבצע התקפות משלו; לעיתים קרובות משלבים זאת עם כלל ההתגוננות, לעיל. כאשר משתמשים במטה כחפץ הגנתי, יש להחיל תוספים קסומים כפי שמוסבר בקרב בשני כלי נשק, לעיל.

לחלופין, המחזיק יכול לבחור לבצע 2 התקפות בסיבוב נתון, כאילו השתמש ב־2 אלות. המחסרים שניתנו תחת קרב בשני כלי נשק, לעיל, חלים כאשר משתמשים במטה בדרך זו, ולא ניתן להשתמש בנשק כדי להדוף התקפות במצב זה. שתי ההתקפות מתבצעות בהפרש של מספר יוזמה אחד; כלומר, מחזיק שגלגל 4 ליוזמה תוקף פעם אחת ב־4 ושוב ב־3.

### קרב ללא שריון ☐

דמויות אשר, מכל סיבה שהיא, נכנסות לקרב ללא כל שריון, מקבלות דירוג שריון בסיסי של 11, שאליו מוסיפים את תוסף הזריזות *ואת תוסף ההתקפה הרגיל של הדמות*. מותר להשתמש במגן (לדמויות שיכולות להשתמש במגנים כרגיל), וכן בחפצי הגנה קסומים שאינם שריון של ממש (כגון **טבעות** או **גלימות הגנה**). דירוג שריון בסיסי משופר זה חל רק נגד יריבים שהדמות מודעת לקיומם ושמיקומם ידוע לה לפחות בקירוב, שכן אי אפשר להתגונן ביעילות נגד תוקפים שהדמות אינה יודעת על קיומם. לעיתים קוראים לכך "אפשרות הסייף".

### קרב רכוב ☐

כאשר דמות רכובה, גלגול היוזמה של הרוכב משמש הן לרוכב והן לבהמת הרכיבה, שכן הרוכב הוא שמנחה את תנועותיה. לפיכך, כל ההתקפות של הרוכב ובהמת הרכיבה הן למעשה בו-זמניות ובדרך כלל כולן חייבות להיות נגד אותה מטרה. לפי בחירת המנחה, בהמות רכיבה אקזוטיות מסוימות עשויות לחרוג מכלל זה, במיוחד אם בהמת הרכיבה מהירה או איטית באופן חריג. לדוגמה, סוס זומבי עדיין נע ותוקף אחרון בסיבוב ללא קשר לגלגול היוזמה של הרוכב.

בעת הסתערות, רק אחד מן השניים, הרוכב או בהמת הרכיבה, מקבל את תוסף ההסתערות, והשני אינו תוקף באותו תור. שים לב שסוסים רגילים אינם מבצעים בדרך כלל התקפות הנהנות מתנועת הסתערות. כדי לקבל את יתרונות ההסתערות, על הרוכב להחזיק ציוד רכיבה מתאים, כלומר אוכף עם ארכובות.

על בהמת הרכיבה להיות מאומנת לקרב רכוב כדי לתאם התקפות עם הרוכב. אחרת, רק הרוכב רשאי לתקוף, והוא סובל ממחסר של -2 לתוסף ההתקפה. בהמות רכיבה בעלות תבונה הקרובה לזו של אדם (או גבוהה יותר) נחשבות אוטומטית כמאומנות לקרב.

בהמת הרכיבה בדרך כלל גדולה מספיק ביחס לרוכב כדי לאפשר לרוכב "להיערך נגד הסתערות" בעת שימוש בנשק מתאים. הרוכב ובהמת הרכיבה חייבים להישאר נייחים, ועל הרוכב להחזיק אוכף מתאים עם ארכובות כדי לעשות זאת.

כמעט כל צירוף של רוכב ובהמת רכיבה נחשב גדול לצורך לחימה נגד יצורים קטנים דמויי אדם, כגון בני-מחצית, שעשויים לקבל תוספים מיוחדים נגד יריבים כאלה.

אלא אם התוקף מציין אחרת, כל ההתקפות נחשבות כמכוונות נגד הרוכב ולא נגד בהמת הרכיבה. התקפה שמחטיאה את הרוכב ב־1 עד 2 נקודות, אך הייתה פוגעת בדירוג השריון של בהמת הרכיבה, פוגעת במקום זאת בבהמת הרכיבה.

בהמת רכיבה לא מאומנת שסופגת נזק חייבת לבצע בדיקת מורל, ובדרך כלל תנסה לברוח מיד אם הבדיקה נכשלת (ללא קשר ליוזמה). הרוכב חייב לבצע גלגול הצלה נגד קרן מוות עם תוסף הזריזות שלו, או שיושלך מגב בהמת הרכיבה. רוכב שהושלך סופג 1d6 נקודות נזק מנפילה, הוא שרוע ואינו יכול לבצע פעולה נוספת עד הסיבוב הבא. רוכב שנותר באוכף ישיב את בהמת הרכיבה לשליטתו 1d4 סיבובים לאחר שבהמת הרכיבה יצאה מטווח ראייתו של התוקף. המנחה תכריע במקרה שנעשה שימוש בקסם או באמצעים אחרים כדי להשיב את השליטה. שים לב שגם בהמות רכיבה מאומנות הנתונות ל**פחד** קסום יגיבו בדרך זו.

**דו-קרב רמחים:** דו-קרב רמחים הוא פשוט מצב שבו 2 רוכבים מסתערים זה לעבר זה עם רמחים. כל הכללים הסטנדרטיים חלים על התקפות כאלה, למעט שהמחסר לדירוג השריון עקב הסתערות אינו חל על התקפותיהם זה נגד זה (אך המחסר כן חל על התקפות שמבצעים צופים מן הצד).

כאשר אחד הרוכבים נפגע בידי יריבו, עליו לבצע גלגול הצלה נגד קרן מוות עם תוסף הכוח שלו, אחרת הוא יופל מן הסוס וינחת שרוע על הקרקע, ויספוג 1d6 נקודות נזק בדיוק כפי שניתן לעיל. כל 5 נקודות נזק מלאות שנגרמו מוסיפות מחסר של -1 לגלגול ההצלה. אם גלגול ההצלה נכשל ב־5 נקודות או יותר, הרוכב שהופל גם המום למשך 1d3 סיבובים, וסובל ממחסר של -2 לדירוג השריון וממחסר של -2 לתוסף ההתקפה למשך הזמן. אם גלגול ההצלה נכשל ב־10 נקודות או יותר, הרוכב מאבד את הכרתו לחלוטין למשך 2d4 סיבובים.

דו-קרב רמחים עם רמחים שהוקהו בכוונה (כפי שנעשה לעיתים קרובות בטורנירים) גורם לנזק הכנעה, אך כל שאר האפקטים לעיל עדיין חלים. נזק מהפלה מן הסוס עדיין יהיה נזק רגיל, למשל.

### חבטת מגן ☐

דמות יכולה להשתמש במגן כנשק במקום כפריט הגנתי. התקפה כזו היא התקפת קרב פנים אל פנים רגילה וגורמת 1d4 נקודות נזק הכנעה, בתוספת מתאם כוח, אם יש. מומחי מגן מקבלים תוסף נזק +1. אם המגן קסום, ניתן להחיל את התוספים הרגילים שלו הן על גלגול ההתקפה והן על גלגול הנזק.

כמובן, הדמות מאבדת את כל יתרונות דירוג השריון של המגן (כולל אלה של קסם והתמחות) עד תחילת הסיבוב הבא לאחר ניסיון חבטת מגן. מחסרים החלים בדרך כלל על נשק ביד המשנית אינם חלים, שכן מגנים נועדו להינשא ולהיות מופעלים בדרך זו.

### נשקים קלים ☐

לוחם או גנב המשתמש בנשק קל יכול לבחור להשתמש במתאם הזריזות שלו במקום במתאם הכוח בגלגולי התקפה. בלי קשר למתאם המשמש בגלגולי ההתקפה, מתאם הכוח משמש תמיד לשינוי גלגולי הנזק. בעת שימוש בכלל זה, ניתן להשתמש בחרב קצרה כדי לייצג רפיר, סאבר או כל חרב סיף אחרת.

נשקים קלים מתוך חוקי הבסיס כוללים: גרזן יד, פגיונות, חרב קצרה (והגרסאות שלה) ופטיש מלחמה (או פטיש הטלה).

### התקפות מכוונות ☐

התקפות מכוונות הן התקפות שאינן מבוצעות מתוך כוונה פשוט לגרום נזק, אלא כדי להשיג "אפקטים מיוחדים" כגון הכשלה, פריקה מנשק או הכנעה אחרת של המטרה.

הדמות המבצעת התקפה מכוונת מבצעת גלגול התקפה רגיל עם מחסר של -4.

ניתן להתנגד להתקפה מכוונת באמצעות גלגול הצלה מסוג כלשהו; במקרה של ספק, על המנחה לשקול גלגול הצלה נגד שיתוק או נגד קרן מוות. אם התוקף מומחה בנשק, יש להחיל את תוסף הנזק של ההתמחות כמחסר לגלגול ההצלה.

להלן כמה דוגמאות להתקפות מכוונות:

- **פריקה מנשק:** הדמות בוחרת לא לגרום נזק ופשוט לפרוק את האויב מנשקו; המטרה רשאית לבצע גלגול הצלה נגד שיתוק כדי להמשיך לאחוז בנשקה.

- **הכשלה:** הדמות מנסה לתפוס ולמשוך את היריב ארצה במקום לגרום נזק. אם ההתקפה מצליחה, הקורבן חייב לבצע גלגול הצלה נגד שיתוק או ליפול ארצה. קימה מחדש שקולה לתנועה מלאה.

## מיומנויות משניות

### מבוא

תוספת זו מגדירה שיטה חדשה של *מיומנויות משניות* עבור דמויות שחקן ודמויות מנחה, לשימוש עם חוקי משחק התפקידים בייסיק פנטזי. אם עדיין אין ברשותך עותק של חוקי בייסיק פנטזי, בקר באתר והורד עותק.

:::{.column-margin}
**מהדורה 2**

Copyright © 2007, 2019 Ray Allen

כל הזכויות שמורות

מופץ בהתאם לתנאי Open Game License גרסה 1.0a

:::

### מיומנויות משניות

כל מיומנות נוספת הנובעת מרקע הדמות נחשבת למיומנות משנית. אלו מיומנויות שהדמות רכשה לפני שהחלה בחיי ההרפתקנות שלה, או מיומנויות שניתן לראות בהן חלק ממקצוע הדמות. זוהי דרך להעשיר דמות ולהפוך אותה לייחודית יותר.

### מנגנון בדיקת המיומנות

כל מיומנויות הדמות מתחילות ברמה 1 ומשתמשות במספר המטרה שבטבלת גלגולי התכונה. כאשר השחקן מבצע פעולת מיומנות, הוא מגלגל 1d20, עם התאמה לפי ערך התכונה המשויך למיומנות. התוצאה חייבת להיות גדולה או שווה למספר המטרה שבטבלת גלגולי התכונה שבפרק החוקים האופציונליים של **חוקי הליבה של בייסיק פנטזי**. בכל דרגה לאחר דרגה 1, הדמות מקבלת 3 נקודות רמת מיומנות שהשחקן יכול להקצות לכל מיומנות או מיומנויות לפי ראות עיניו, כל עוד רמת המיומנות אינה עולה על דרגת הדמות.

אם לדמות יש רקע או ידע נוסף בתחום הקשור למיומנות (כגון בן או בת של נפח), הדמות מקבלת תוסף +1 למיומנויות העוסקות בידע הנוסף. על השחקן והמנחה לשקול אפשרות זו יחד.

כל מיומנות המופיעה ברשימת מיומנויות של מקצוע אחר נחשבת מיומנות מחוץ למקצוע ומספר המטרה שלה הוא 20. לא ניתן להעלות את רמתן של מיומנויות אלה באמצעות נקודות רמת מיומנות. שימוש ללא הכשרה במיומנות מן הרשימה הכללית או מרשימת המקצוע של הדמות הוא בעל מספר מטרה 17.

### רשימת מיומנויות ותיאורים

שחקנים יכולים לבחור מיומנויות מתוך המיומנויות הכלליות ומתוך סעיף מיומנויות המקצוע שלהם.

#### מיומנויות כלליות

**הערכת שווי** -- תבונה

אתה יכול להעריך חפצים נפוצים או מוכרים באמצעות בדיקת הערכת שווי. כישלון משמעו שאתה מעריך את שווי החפץ ב־50% עד 150% (2d6+3 כפול 10%) מערכו האמיתי.

הערכת חפץ נדיר או אקזוטי דורשת בדיקה מוצלחת נגד מספר מטרה 17 ומעלה. אם הבדיקה מצליחה, אתה מעריך את השווי נכון; כישלון משמעו שאינך יכול להעריך את שווי החפץ.

**מלאכה** (סוג מלאכה יחיד, למשל: שריונר, עושה קשתות, מנפח זכוכית, עובד עור, קדר, בונה ספינות, צורף כסף, בונה גלגלים, אורג) -- תבונה

מיומנות מלאכה מתמקדת באופן ספציפי ביצירה ו/או תיקון של דבר-מה. אם לא נוצר דבר כתוצאה מן המאמץ, סביר שהוא נופל תחת הכותרת של מיומנות מקצוע ולא מלאכה. דמות בעלת מיומנות זו נחשבת ל"אומן מומחה". נדרשים זמן וחומרים מתאימים כדי להצליח.

**דיפלומטיה** -- כריזמה

אתה יכול לשנות את גישתם של אחרים באמצעות בדיקת דיפלומטיה מוצלחת. במשא ומתן, המנחה מוסיפה את מספר נקודות המיומנות של הדמות בדיפלומטיה לגלגול התגובה בטבלת גלגול התגובה. ייתכן שיידרש יותר מגלגול אחד כדי לפתור מצבים שבהם 2 סנגורים או דיפלומטים מציגים טיעונים מנוגדים בשימוע בפני צד שלישי.

**טיפול בחיות** -- כריזמה

משימה זו כוללת מתן פקודה לחיה לבצע משימה או תרגיל שהיא מכירה. אם החיה פצועה או מפוחדת, מספר המטרה עולה ב־2. אם הבדיקה שלך מצליחה, החיה מבצעת את המשימה או התרגיל.

*"לדחוף" חיה*

לדחוף חיה משמעו לגרום לה לבצע משימה או תרגיל שהיא אינה מכירה, אך מסוגלת לבצע מבחינה פיזית. קטגוריה זו כוללת גם לגרום לחיה לבצע מסע מאולץ או לאלץ אותה לנוע בקצב מואץ במשך יותר משעה אחת בין מחזורי שינה. אם החיה פצועה, מספר המטרה עולה ב־2 רמות. אם הבדיקה שלך מצליחה, החיה מבצעת את המשימה או התרגיל בפעולה הבאה שלה.

*ללמד חיה תרגיל*

אתה יכול ללמד חיה תרגיל מסוים באמצעות שבוע עבודה אחד ובדיקת טיפול בחיות מוצלחת. חיה יכולה ללמוד לכל היותר 6 תרגילים. תרגילים אפשריים כוללים, אך אינם מוגבלים בהכרח, את הבאים.

- **התקפה:** החיה תוקפת יצורים שנראים כאויבים.
- **בוא:** החיה באה אליך, גם אם בדרך כלל לא הייתה עושה זאת.
- **הגנה:** החיה מגינה עליך (או מוכנה להגן עליך אם אין איום), גם בלי שניתנה כל פקודה. לחלופין, אתה יכול לפקוד על החיה להגן על דמות אחרת מסוימת.
- **חדל:** החיה מפסיקה את הקרב או נסוגה. חיה שאינה מכירה תרגיל זה ממשיכה להילחם עד שהיא חייבת לברוח או עד שיריבה מובס.
- **הבא:** החיה הולכת ומביאה משהו. אם אינך מצביע על פריט מסוים, החיה מביאה חפץ אקראי כלשהו.
- **שמירה:** החיה נשארת במקום ומונעת מאחרים להתקרב.
- **לצד:** החיה עוקבת אחריך מקרוב, אפילו למקומות שבדרך כלל לא הייתה הולכת אליהם.
- **הופעה:** החיה מבצעת מגוון תרגילים פשוטים, כגון לשבת זקוף, להתגלגל, לנבוח וכדומה.
- **חיפוש:** החיה נכנסת לאזור ומביטה סביב כדי למצוא כל דבר שהוא בבירור חי או מונפש.
- **הישאר:** החיה נשארת במקום וממתינה שתחזור. היא אינה מאתגרת יצורים אחרים שעוברים בסביבה, אף שהיא עדיין מגינה על עצמה אם יש צורך בכך.
- **עקיבה:** החיה עוקבת אחר הריח שמוצג לה.
- **עבודה:** החיה מושכת או דוחפת משא בינוני או כבד.

**קפיצה** -- כוח

- **קפיצה לרוחק:** קפיצה לרוחק היא קפיצה אופקית המתבצעת מעל פער, כגון תהום או נחל. בנקודת האמצע של הקפיצה, אתה מגיע לגובה אנכי השווה לרבע מן המרחק האופקי. מספר המטרה לקפיצה שווה לפי 3 מן המרחק הנקפץ במטרים.
- **קפיצה לגובה:** קפיצה לגובה היא זינוק אנכי שנועד להגיע למדף גבוה מעליך או לאחוז במשהו שמעל הראש. מספר המטרה שווה לפי 12 מן הגובה שיש לעבור, במטרים.

**עבודת כפיים** (סוג עבודה ידנית, למשל: בנאי לבנים, נגר, איכר, כורה, מלח) -- חוסן

הדמות מיומנת מאוד בסוג מסוים של עבודת כפיים. אלו סוגי עבודות שאינן דורשות רמות גבוהות של מיומנות, אך כן דורשות הכשרה מסוימת.

**ידע** -- תבונה

לדמות יש הבנה באחד מתחומי הלימוד הבאים:

- **אלכימיה** (כימיה ויסודות הטבע)
- **תורת הנסתר** (מסתורין עתיק, מסורות קסם, סמלים מאגיים, ביטויים מוצפנים, יצורים מלאכותיים, דרקונים, חיות קסומות)
- **הנדסה** (מבנים, אמות מים, גשרים, ביצורים וכדומה)
- **היסטוריה** (מלוכה, מלחמות, מושבות, נדידות, ייסוד ערים)
- **דת** (אלים ואלות, היסטוריה מיתית, סמלים קדושים, אל-מתים)
- **טקטיקה** (תנועות כוחות, מצורים, תמרונים ימיים)

**הופעה** -- כריזמה

הדמות מיומנת באחד מן הבאים: משחק (קומדיה, דרמה, פנטומימה), קומדיה (ליצנות, לימריקים, סיפור בדיחות), ריקוד (בלט, ואלס, ג'יג), כלי נגינה (אחד מן: פעמונים, פעמוניות, תופים, כינור, חליל, גונג, נבל, צ'מבלו, לאוטה, מנדולינה, חליל פאן, פסנתר, עוגב, חלילית, חצוצרה), נאום (אפוס, אודה, סיפור סיפורים), שירה (בלדה, מזמור, מנגינה).

**מקצוע** (סוג מקצוע שאינו עבודת כפיים, למשל: ניהול אחוזה, קרטוגרפיה, בישול, עריכת דין, איש דת מן השורה) -- חוכמה

אתה יכול לעסוק במקצועך ולהתפרנס בכבוד. אתה יודע כיצד להשתמש בכלי העבודה של מקצועך, כיצד לבצע את משימות היום-יום של המקצוע, כיצד לפקח על עוזרים וכיצד להתמודד עם בעיות נפוצות.

**רכיבה** -- זריזות

הדמות בקיאה ברכיבה על סוג אחד של בהמת רכיבה. היא יכולה לאכף, לעלות, לרכוב ולרדת ללא בעיה אם אינה ממהרת, אך פעולות מיוחדות בעת רכיבה דורשות בדיקת מיומנות (למשל: להנחות את בהמת הרכיבה באמצעות הברכיים, להישאר באוכף כדי להימנע מנפילה כאשר בהמת הרכיבה מזדקפת או פורצת בדהרה, לגרום לבהמת הרכיבה לזנק מעל מכשולים, או לנסות לשלוט בבהמת רכיבה שאינה מאומנת לקרב בעת רכיבה בקרב).

**הערכת מניעים** -- חוכמה

שימוש זה במיומנות כולל הערכה של המצב. אתה יכול לחוש מתוך התנהגותו של אחר שמשהו אינו כשורה, כגון כאשר אתה מדבר עם מתחזה. לחלופין, אתה יכול לחוש שמישהו ראוי לאמון.

**הבחנה** -- חוכמה

מיומנות **הבחנה** משמשת בעיקר כדי לזהות דמויות או יצורים המסתתרים, לזהות מישהו בתחפושת, וכן לקרוא שפתיים כאשר אינך יכול לשמוע או להבין מה מישהו אומר.

**הישרדות** -- חוכמה

אתה יכול לשמור על עצמך ועל אחרים בטוחים ולהשיג מזון בשטח הפתוח, או לעקוב אחר עקבות בשטח פתוח.

**שחייה** -- כוח

בצע בדיקת שחייה פעם אחת בכל סיבוב בעודך במים. הצלחה משמעה שאתה רשאי לשחות במהירות של עד מחצית ממהירותך. שחייה בשריון היא בדרך כלל בלתי אפשרית.

#### מיומנויות מקצוע של כוהן

**טקס** (אלוהות מסוימת) -- חוכמה

הדמות מיומנת בטקסים של אלוהות אחת (בדרך כלל האלוהות שלה). לדמות הבנה עמוקה של משמעותה של כל פעולה הנעשית במסגרת הטקסים.

**ריפוי** -- חוכמה

הדמות מבינה כיצד להעניק עזרה ראשונה כדי להציל גוססים. כאשר דמות יורדת מתחת ל־0 נקודות פגיעה, אך לא מתחת ל־−10, דמות אחרת בעלת מיומנות ריפוי יכולה לנסות להעניק עזרה ראשונה כדי להציל את חיי הדמות הגוססת. בדיקת מיומנות ריפוי מוצלחת מייצבת את הדמות הגוססת. על הדמות לבלות שבוע אחד במנוחה במיטה כדי להשיב את נקודת הפגיעה הראשונה; לאחר מכן, הריפוי מתקדם בקצב הרגיל.

**תורת הלחשים** -- תבונה

אתה יכול לזהות לחשים ואפקטים קסומים.

#### מיומנויות מקצוע של לוחם

**סיבולת** -- חוסן

לדמות יש יכולת לבצע משימות מתישות במשך פרקי זמן ארוכים. כל בדיקה מוצלחת מאפשרת לדמות לבצע את המשימה במשך שעה אחת. יש לבצע בדיקה נוספת בכל שעה, עם מחסר מצטבר של -1 לגלגול. כאשר הדמות מסיימת את המשימה או נכשלת בבדיקה, היא קורסת ועליה לנוח במשך זמן השווה לפי 3 ממשך הזמן שהושקע בביצוע המשימה.

**הפחדה** -- כריזמה

אתה יכול לשנות את התנהגותו של אחר. אם בדיקת המיומנות מצליחה, תוכל להתייחס אל המטרה כאל "חיובית מאוד", אך רק לצורך פעולות הנעשות כל עוד היא נותרת מאוימת. כלומר, המטרה שומרת על גישתה הרגילה, אך תפטפט, תייעץ, תציע עזרה מוגבלת או תפעל לטובתך כל עוד היא מאוימת. האפקט נמשך כל עוד המטרה נמצאת בנוכחותך, ולמשך 1d6×10 סיבובים לאחר מכן. לאחר זמן זה, גישת ברירת המחדל של המטרה כלפיך משתנה ל"שלילית" (או, אם היא שלילית בדרך כלל, ל"התקפה מיידית").

**מנהיגות** -- כריזמה

בדיקת מיומנות מנהיגות מוצלחת מוסיפה +1 לערך הנאמנות של מלווה. ניתן להשתמש בה גם כדי לשכנע דמויות מנחה שאינן משמשות כמלווים לציית לפקודה, אך במקרה זה הן לא יצייתו לפקודה אם יש סיבה טובה שלא לעשות זאת. שימוש במיומנות מנהיגות על דמות מנחה אינו משנה לאחר מכן את גישתה ל"שלילית".

#### מיומנויות מקצוע של קוסם

**פענוח כתב** -- תבונה

אתה יכול לפענח כתיבה בשפה בלתי מוכרת או מסר שנכתב בצורה חלקית או ארכאית. הדבר כולל כתיבה מורכבת, אקזוטית או עתיקה מאוד.

אם הבדיקה מצליחה, אתה מבין את התוכן הכללי של קטע כתוב באורך של כעמוד אחד (או שווה ערך). אם הבדיקה נכשלת, יש לבצע בדיקה נוספת כדי לראות אם אתה נמנע מהסקת מסקנה שגויה לגבי הטקסט. (הצלחה משמעה שאינך מסיק מסקנה שגויה; כישלון משמעו שכן.)

**תורת הלחשים** -- תבונה

אתה יכול לזהות לחשים ואפקטים קסומים.

#### מיומנויות מקצוע של גנב

**שיווי משקל** -- זריזות

אתה יכול ללכת על משטח רעוע. בדיקה מוצלחת מאפשרת לך לנוע במחצית ממהירותך לאורך המשטח במשך 1 סיבוב. כישלון ב־4 או פחות משמעו שאינך יכול לנוע במשך 1 סיבוב. כישלון ב־5 או יותר משמעו שאתה נופל.

**הטעיה** -- כריזמה

בדיקת הטעיה מוצלחת מעידה שהמטרה מגיבה כפי שאתה רוצה, לפחות לזמן קצר (בדרך כלל סיבוב אחד או פחות), או מאמינה במשהו שאתה רוצה שתאמין בו. הטעיה דורשת אינטראקציה בינך לבין המטרה. יצורים שאינם מודעים לנוכחותך אינם יכולים להיות מוטעים.

**פענוח כתב** -- תבונה

אתה יכול לפענח כתיבה בשפה בלתי מוכרת או מסר שנכתב בצורה חלקית או ארכאית. הדבר כולל כתיבה מורכבת, אקזוטית או עתיקה מאוד.

אם הבדיקה מצליחה, אתה מבין את התוכן הכללי של קטע כתוב באורך של כעמוד אחד (או שווה ערך). אם הבדיקה נכשלת, יש לבצע בדיקה נוספת כדי לראות אם אתה נמנע מהסקת מסקנה שגויה לגבי הטקסט (הצלחה משמעה שאינך מסיק מסקנה שגויה; כישלון משמעו שכן).

**תחפושת** -- כריזמה

זוהי היכולת לשנות את מראה הדמות שלך או להתחזות לדמות אחרת. תוצאת בדיקת התחפושת שלך קובעת עד כמה התחפושת טובה. מספר המטרה של הבדיקה נקבע לפי המצב שבו הדמות עומדת להשתמש בתחפושת. אם אינך מושך תשומת לב לעצמך, המנחה עשויה להעניק עד תוסף +5 לבדיקה. אם אתה מושך את תשומת לבם של אנשים חשדניים (כגון שומר העוקב אחר פשוטי-עם העוברים דרך שער העיר), ייתכן שמתאים להחיל מחסר של -5 על הבדיקה.

**היחלצות** -- זריזות

לדמות בעלת מיומנות היחלצות יש יכולת כמעט על-טבעית להשתחרר מחבלים כאשר היא קשורה.

**זיוף** -- תבונה

זיוף דורש חומרי כתיבה המתאימים למסמך המזויף, די אור או חדות ראייה מספקת כדי לראות את פרטי מה שאתה כותב, שעווה לחותמות (אם מתאים), וקצת זמן. כדי לזייף מסמך שבו כתב היד אינו ייחודי לאדם מסוים (פקודות צבאיות, צו ממשלתי, פנקס עסקי וכדומה), די בכך שראית בעבר מסמך דומה, ואתה מקבל תוסף +4 לבדיקה. כדי לזייף חתימה, אתה זקוק לדוגמת חתימה של אותו אדם כדי להעתיק, ואתה מקבל תוסף +2 לבדיקה. כדי לזייף מסמך ארוך יותר שנכתב בכתב ידו של אדם מסוים, נדרשת דוגמה גדולה של כתב ידו של אותו אדם.

בדיקת הזיוף מתבצעת בסתר על ידי המנחה, כך שאינך בטוח עד כמה הזיוף שלך טוב.

מסמך הסותר נוהל, פקודות או ידע קודם, או מסמך הדורש הקרבה מצד האדם הבודק אותו, יכול להגביר את חשדו של אותו אדם (ובכך ליצור נסיבות נוחות לבדיקת זיוף נגדית מצד הבודק).

**ידע (שמועות בעיר)** -- תבונה

הדמות בקיאה באירועים בעיירת או בעיר מגוריה. ערב אחד, כמה מטבעות זהב לקניית משקאות וליצירת חברים חדשים, ובדיקת ידע (שמועות בעיר) מעניקים לך מושג כללי על החדשות המרכזיות בעיר, בהנחה שאין סיבות ברורות לכך שהמידע יוסתר. ככל שתוצאת הבדיקה שלך גבוהה יותר, כך המידע טוב יותר.

**גלגול** -- זריזות

אתה יכול לנחות ברכות כאשר אתה נופל. אתה יכול גם להתגלגל כדי לבדר קהל (כאילו השתמשת במיומנות הופעה). אם בדיקת המיומנות מצליחה, בעת קביעת הנזק התייחס לנפילה כאילו הייתה קצרה ב־3 מטרים מכפי שהיא באמת.

### חוקי מיומנויות אופציונליים

דמות רשאית לבחור מיומנות שאינה מותרת בדרך כלל למקצוע שלה; עם זאת, עלות המיומנות היא 3 נקודות רמת מיומנות. לדוגמה, לוחם בדרגה 1 בוחר במיומנות היחלצות. הדבר עולה 3 נקודות רמת מיומנות, והדמות אינה רשאית לבחור מיומנות נוספת עד שתגיע לדרגה 2. מספר המטרה עדיין 17 עבור מיומנויות אלו.

מספר נקודות המיומנות לכל דרגה שווה לתוסף הכריזמה של הדמות, עם מינימום של נקודה 1 לכל דרגה.


<!-- -------------------------------------------------- -->






## OPEN GAME LICENSE

#### INTRODUCTION

The Basic Fantasy Role-Playing Game ("BFRPG") is based on the System Reference Document v3.5 ("SRD"), which is Open Game Content. Also, some monster descriptive text was taken from the Castles and Crusades: Monsters Support Product ("MSP"), which is also Open Game Content. The text of the Open Game License itself is not Open Game Content. Instructions on using the License are provided within the License itself.

Note regarding C&C Open Game Content used: The COPYRIGHT NOTICE section below lists both the Castles & Crusades: Players Handbook and the Castles & Crusades: Monster Support Document; both are listed because we are required to do so, but be advised that all Castles & Crusades materials used were taken only from the latter document.

Designation of Open Game Content: The entire text as well as all maps and floorplans incorporated in BFRPG (except the Open Game License, as noted above, and the Product Identity License, below) is Open Game Content, released under the Open Game License, Version 1.0a (reproduced below) as described in Section 1(d) of the License. Artwork (other than maps and floorplans) incorporated in this document is not Open Game Content, and remains the property of the copyright holder.

Designation of Product Identity: Product identity is not Open Game Content. The following is designated as product identity pursuant to OGL v1.0a(1)(e) and (7): (A) product and product line names, including Basic Fantasy Role-Playing Game, Basic Fantasy RPG, and BFRPG, as well as the phrase "make mine Basic"; (B) all artwork, logos, symbols, graphic designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual representations, including the "eye" logo, which is the personal mark of Chris Gonnerman for his various products, and which is Copyright © 2002 Chris Gonnerman, and the "Scribbled Dragon," which is Copyright © 2005 Erik Wilson; (C) logos and trademarks, including any trademark or registered trademark clearly identified as product identity by the owner of the product identity, and which specifically excludes the open game content.

More information on the Open Game License can be found at: <http://www.wizards.com/d20>.


#### OPEN GAME LICENSE VERSION 1.0A

The following text is the property of Wizards of the Coast, Inc. and is Copyright 2000 Wizards of the Coast, Inc ("Wizards"). All Rights Reserved.

1.  **Definitions:** (a)"Contributors" means the copyright and/or trademark owners who have contributed Open Game Content; (b)"Derivative Material" means copyrighted material including derivative works and translations (including into other computer languages), potation, modification, correction, addition, extension, upgrade, improvement, compilation, abridgment or other form in which an existing work may be recast, transformed or adapted; (c) "Distribute" means to reproduce, license, rent, lease, sell, broadcast, publicly display, transmit or otherwise distribute; (d)"Open Game Content" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identified as Open Game Content by the Contributor, and means any work covered by this License, including translations and derivative works under copyright law, but specifically excludes Product Identity. (e) "Product Identity" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; and any other trademark or registered trademark clearly identified as Product identity by the owner of the Product Identity, and which specifically excludes the Open Game Content; (f) "Trademark" means the logos, names, mark, sign, motto, designs that are used by a Contributor to identify itself or its products or the associated products contributed to the Open Game License by the Contributor (g) "Use", "Used" or "Using" means to use, Distribute, copy, edit, format, modify, translate and otherwise create Derivative Material of Open Game Content. (h) "You" or "Your" means the licensee in terms of this agreement.
2.  **The License:** This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must affix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself. No other terms or conditions may be applied to any Open Game Content distributed using this License.
3.  **Offer and Acceptance:** By Using the Open Game Content You indicate Your acceptance of the terms of this License.
4.  **Grant and Consideration:** In consideration for agreeing to use this License, the Contributors grant You a perpetual, worldwide, royalty-free, non-exclusive license with the exact terms of this License to Use, the Open Game Content.
5.  **Representation of Authority to Contribute:** If You are contributing original material as Open Game Content, You represent that Your Contributions are Your original creation and/or You have sufficient rights to grant the rights conveyed by this License.
6.  **Notice of License Copyright:** You must update the COPYRIGHT NOTICE portion of this License to include the exact text of the COPYRIGHT NOTICE of any Open Game Content You are copying, modifying or distributing, and You must add the title, the copyright date, and the copyright holder's name to the COPYRIGHT NOTICE of any original Open Game Content you Distribute.
7.  **Use of Product Identity:** You agree not to Use any Product Identity, including as an indication as to compatibility, except as expressly licensed in another, independent Agreement with the owner of each element of that Product Identity. You agree not to indicate compatibility or co-adaptability with any Trademark or Registered Trademark in conjunction with a work containing Open Game Content except as expressly licensed in another, independent Agreement with the owner of such Trademark or Registered Trademark. The use of any Product Identity in Open Game Content does not constitute a challenge to the ownership of that Product Identity. The owner of any Product Identity used in Open Game Content shall retain all rights, title and interest in and to that Product Identity.
8.  **Identification:** If you distribute Open Game Content You must clearly indicate which portions of the work that you are distributing are Open Game Content.
9.  **Updating the License:** Wizards or its designated Agents may publish updated versions of this License. You may use any authorized version of this License to copy, modify and distribute any Open Game Content originally distributed under any version of this License.
10. **Copy of this License:** You MUST include a copy of this License with every copy of the Open Game Content You Distribute.
11. **Use of Contributor Credits:** You may not market or advertise the Open Game Content using the name of any Contributor unless You have written permission from the Contributor to do so.
12. **Inability to Comply:** If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Open Game Content due to statute, judicial order, or governmental regulation then You may not Use any Open Game Material so affected.
13. **Termination:** This License will terminate automatically if You fail to comply with all terms herein and fail to cure such breach within 30 days of becoming aware of the breach. All sublicenses shall survive the termination of this License.
14. **Reformation:** If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable.

#### COPYRIGHT NOTICE

-   Open Game License v 1.0 Copyright 2000, Wizards of the Coast, Inc.
-   System Reference Document Copyright 2000-2003, Wizards of the Coast, Inc.; Authors Jonathan Tweet, Monte Cook, Skip Williams, Rich Baker, Andy Collins, David Noonan, Rich Redman, Bruce R. Cordell, John D. Rateliff, Thomas Reid, James Wyatt, based on original material by E. Gary Gygax and Dave Arneson.
-   Castles & Crusades: Players Handbook, Copyright 2004, Troll Lord Games; Authors Davis Chenault and Mac Golden.
-   Castles & Crusades: Monsters Product Support, Copyright 2005, Troll Lord Games.
-   The Basic Fantasy Field Guide Copyright © 2010 Chris Gonnerman and Contributors.
-   Basic Fantasy Role-Playing Game Copyright © 2006-2015 Chris Gonnerman.
-   0 Level Spells:  A Basic Fantasy Supplement Copyright © 2009, 2020 Sidney Parham, Nazim Karaca, R. Kevin Smoot, ckutalik, steveman, Svankensen, Mike West, and Chris Gonnerman.
-   Alignment:  A Basic Fantasy Supplement Copyright © 2006 Todd Roe.
-   Armor and Shields: A Basic Fantasy Supplement Copyright © 2010 Jeff Johnson.
-   Background Skills: A Basic Fantasy Supplement Copyright © 2009, 2018-2021 Omer Golan-Joel.
-   Equipment Emporium: A Basic Fantasy Supplement Copyright © 2010-2018 Joe Ludlum, R. Kevin Smoot, and Alan Vetter
-   Combat Options:  A Basic Fantasy Supplement Copyright © 2007-2018 Chris Gonnerman, Luigi Castellani, and R. Kevin Smoot
-   Secondary Skills:  A Basic Fantasy Supplement Copyright © 2007, 2019 Ray Allen