# ניהול מפגשים

## מפלצות נודדות

*הייתה לנו התבונה להביא איתנו מספר שקים גדולים, ומילאנו אותם במהירות במטבעות ואבני חן מתחת לסרקופג. ללא עיכוב נוסף יצאנו לדרך, נחושים להגיע למדרגות אל פני השטח ואז לחזור למורגנפורט. אבל זה לא יכול היה להיות כל כך קל...*

*בדרך פנימה, ברתל סייר לפנינו ולקחנו את הזמן, כל הזמן מחפשים מפלצות. בדרך החוצה, זרקנו את הזהירות לרוח, נעים במהירות מלאה כשברתל צופה מאחורינו. כך קרה שמורנינגסטאר ואני פניתי בפינה וכמעט דרכנו על השורה הראשונה של סיור גובלינים!*

*שוב נתפסתי לא מוכנה, אבל כך גם הגובלינים. מורנינגסטאר הגיבה במהירות רבה יותר, והכתה את הראשונה מבין המפלצות הקטנות. אולי תחשבו שפרלמנט היה רעיון טוב יותר, אבל כבר ניסינו את זה עם הגובלינים האלה ללא הצלחה... אז לא יכולתי להאשים את האלף על כך שהכתה קודם ושאלה שאלות אחר כך.*

*הרמתי את החרב המוזהבת וצללתי לקרב...*

## מפגשים במבוך

מלבד מפלצות "ממוקמות", מבוכים בדרך כלל מכילים מפלצות נודדות. מנחת המשחק עשויה ליצור טבלאות מפלצות נודדות מיוחדות למבוכים ספציפיים, או שניתן להשתמש בטבלאות המפלצות הנודדות הכלליות (להלן).

במבוך ממוצע, מפגש עם מפלצת נודדת יתרחש בגלגול של 1 על 1d6; מנחת המשחק צריכה לבדוק פעם כל 3 תורות. הנסיבות של מבוך מסוים עשויות לדרוש סיכויים גבוהים יותר או בדיקות מפלצות נודדות תכופות יותר (או אולי פחות תכופות).


```{ojs}

import {generalTableSelect, highlightTableRow} from "../custom.js"

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#dungeon-encounters-1", 
generalTableSelect([1,12,0],[[ 1 , 1 ],[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12]]))})

```

:::{#dungeon-encounters-1}

|  1d12 | דרגה 1               | דרגה 2                   | דרגה 3               |
|------------|-----------------------|---------------------------|-----------------------|
| 1          | דבורה, ענקית          | חיפושית, מפציץ ענקית      | נמלה, ענקית           |
| 2          | גובלין                | זבוב, ענק                 | קוף, טורף            |
| 3          | ג'לי, ירוק*           | גול                       | חיפושית, טיגריס ענקית |
| 4          | קובולד               | גנול                      | באגביר               |
| 5          | חבורת דמויות מנחה: הרפתקן | ג'לי, אפור               | דופלגנגר             |
| 6          | חבורת דמויות מנחה: שודד | הובגובלין                | גרגויל*              |
| 7          | אורק                  | איש לטאה                  | ג'לי, זכוכית         |
| 8          | סטריג'                | חבורת דמויות מנחה: הרפתקן | ליקנתרופ, עכברוש-אדם* |
| 9          | שלד                   | נחש, צפע בור              | עוג                  |
| 10         | נחש, קוברה           | עכביש, אלמנה שחורה ענקית | צל*                  |
| 11         | עכביש, סרטן ענק       | איש לטאה, תת-קרקעי        | תולעת זרועות         |
| 12         | זאב                   | זומבי                     | ווייט*               |

:::


```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#dungeon-encounters-2", 
generalTableSelect([1,12,0],[[ 1 , 1 ],[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12]]))})

```

:::{#dungeon-encounters-2}

| 1d12 | דרגה 4-5              | דרגה 6-7               | דרגה 8+               |
|-----------|------------------------|-------------------------|------------------------|
| 1         | דוב, מערה              | בזיליסק                | בזיליסק, גדול*        |
| 2         | קציליה, ענקית         | ג'לי, שחור             | כימרה                 |
| 3         | קוקטריס               | קציליה, ענקית          | רמאי, גדול            |
| 4         | דופלגנגר              | רמאי                   | ענק, גבעה             |
| 5         | ג'לי, אפור            | הידרה                  | ענק, אבן              |
| 6         | כלב גיהנום            | מפלצת חלודה*          | הידרה                 |
| 7         | מפלצת חלודה*          | ליקנתרופ, טיגריס-אדם* | ג'לי, שחור            |
| 8         | ליקנתרופ, זאב-אדם*    | מומיה*                 | ליקנתרופ, חזיר-אדם*  |
| 9         | מינוטאור              | ינשוף-דוב              | תולעת סגולה           |
| 10        | ג'לי, אדמדם*          | עקרב, ענק              | סלמנדרה, להבה*       |
| 11        | ינשוף-דוב             | ספקטר*                 | סלמנדרה, קרח*        |
| 12        | רפא*                  | טרול                   | ערפד*                 |

:::

## מפגשים בשטח פתוח

מנחת המשחק צריכה לבדוק מפגשים אקראיים בשטח הפתוח בערך כל ארבע שעות של זמן משחק; זה מתורגם יפה לשלושה בדיקות לילה ושלושה בדיקות יום. אם השחקנים שלך בוחרים לעמוד בשלוש משמרות לילה, פשוט בדקי עבור כל משמרת; ביום, בדקי בוקר, אחר הצהריים וערב.

כדי לבדוק מפגש בשטח הפתוח, גלגלי 1d6; בגלגול של 1, מתרחש מפגש. אם מצוין מפגש בשטח הפתוח, גלגלי 2d8 בטבלה המתאימה למטה. מנחת המשחק צריכה לחשוב היטב על איך המפגש מתרחש; בדקי הפתעה מראש, ואם המפלצת לא מופתעת, ניתן לשקול שהיא הייתה לה זמן להתארגן למארב (לפי שיקול דעתה של המנחה).

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#wilderness-encounters-1", 
generalTableSelect([2,8,0],[[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12],[ 13, 13],[ 14, 14], [ 15, 15],[ 16, 16]]))})

```

:::{#wilderness-encounters-1}

| 2d8 | מדבר או שומם          | ערבה               | שטחים מיושבים       |
|-----|-------------------------|---------------------|-----------------------|
| 2   | דרקון, מדבר            | דרקון, מישורים     | דרקון, ענן            |
| 3   | כלב גיהנום            | טרול               | גול                   |
| 4   | ענק, אש                | זבוב, ענק          | באגביר               |
| 5   | תולעת סגולה           | עקרב, ענק          | גובלין                |
| 6   | זבוב, ענק              | חבורת דמויות מנחה: שודד | קנטאור               |
| 7   | עקרב, ענק              | אריה               | חבורת דמויות מנחה: שודד |
| 8   | גמל                    | חזיר בר, פראי      | חבורת דמויות מנחה: סוחר |
| 9   | עכביש, טרנטולה ענקית  | חבורת דמויות מנחה: סוחר | חבורת דמויות מנחה: עולה רגל |
| 10  | חבורת דמויות מנחה: סוחר | זאב                | חבורת דמויות מנחה: אציל |
| 11  | בז                     | דבורה, ענקית       | כלב                   |
| 12  | חבורת דמויות מנחה: שודד | גנול               | גרגויל*              |
| 13  | עוג                    | גובלין             | גנול                  |
| 14  | גריפון                 | חיה מהבהבת        | עוג                   |
| 15  | גנול                   | זאב, אימתני        | מינוטאור              |
| 16  | דרקון, הרים           | ענק, גבעה          | ערפד*                |

:::

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#wilderness-encounters-2", 
generalTableSelect([2,8,0],[[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12],[ 13, 13],[ 14, 14], [ 15, 15],[ 16, 16]]))})

```

:::{#wilderness-encounters-2}

| (2d8) | **ג'ונגל**          | **הרים או גבעות**                | **אוקיינוס**                      |
|-------|---------------------|----------------------------------|-----------------------------------|
| 2     | דרקון, ירוק         | דרקון, לבן                       | דרקון, ים                         |
| 3     | חבורת דמויות מנחה: שודד | רוק (1d6: 1-3 גדול, 4-5 ענק, 6 ענק) | הידרה                            |
| 4     | גובלין              | רמאי                             | לוויתן, זרע                       |
| 5     | הובגובלין           | ליקנתרופ, זאב-אדם*              | תנין, ענק                         |
| 6     | מרבה רגליים, ענק    | אריה הרים                        | סרטן, ענק                         |
| 7     | נחש, פיתון ענק      | זאב                              | תמנון, ענק                        |
| 8     | פיל                  | עכביש, סרטן ענק                 | כריש, מאקו                        |
| 9     | אנטילופה            | בז                               | כריש, שור                         |
| 10    | יגואר                | אורק                             | חבורת דמויות מנחה: סוחר          |
| 11    | סטריג'              | עטלף, ענק                        | חבורת דמויות מנחה: שודד ים (פיראט) |
| 12    | חיפושית, טיגריס ענקית | בז, ענק                          | כריש, לבן גדול                    |
| 13    | קציליה, ענקית       | ענק, גבעה                        | רוק (1d8: 1-5 ענק, 6-8 ענק)       |
| 14    | צל*                 | כימרה                            | בת ים                             |
| 15    | חבורת דמויות מנחה: סוחר | זאב, אימתני                     | נחש ים                            |
| 16   | ליקנתרופ, טיגריס-אדם* | דרקון, הרים | נחש ים |
:::

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#wilderness-encounters-3", 
generalTableSelect([2,8,0],[[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12],[ 13, 13],[ 14, 14], [ 15, 15],[ 16, 16]]))})

```

:::{#wilderness-encounters-3}

| (2d8) | **נהר או גדת נהר** | **ביצה**                     | **יער או חורש**     |
|-------|--------------------|-------------------------------|-----------------------|
| 2     | דרקון, שחור        | דרקון, שחור                   | דרקון, ירוק          |
| 3     | דג, פיראניה ענקית  | צל*                           | אליקורן (ראה חד-קרן) |
| 4     | סטריג'             | טרול                          | טריאנט               |
| 5     | דג, בס ענק         | לטאה, דרקו ענקית              | אורק                 |
| 6     | חבורת דמויות מנחה: סוחר | מרבה רגליים, ענקית           | חזיר בר, פראי        |
| 7     | איש לטאה           | עלוקה, ענקית                  | דוב, שחור            |
| 8     | תנין               | איש לטאה                      | בז, ענק              |
| 9     | צפרדע, ענקית       | תנין                          | אנטילופה             |
| 10    | דג, שפמנון ענק     | סטריג'                        | זאב                  |
| 11    | חבורת דמויות מנחה: שודד ים | אורק                           | עוג                  |
| 12    | טרול               | קרפד, ענק (ראה צפרדע, ענקית) | דוב, גריזלי          |
| 13    | יגואר              | טרוגלודיט                     | זאב, אימתני          |
| 14    | ניקסה              | ורד דמים                      | ענק, גבעה            |
| 15    | טרמיט מים, ענק     | עץ תליין                      | ינשוף-דוב            |
| 16    | דרקון, ירוק        | בזיליסק                       | חד-קרן               |

:::

## מפגשים בעיר, עיירה או כפר

חשוב שמנחת המשחק תזכור שבניגוד לסביבות מבוך או שטח פתוח, ערים, עיירות וכפרים הם מקומות עמוסים. במהלך היום, רוב העיירות יהיו עם אנשים ברחובות יותר או פחות כל הזמן; היעדר אנשים ברחובות הוא לעיתים קרובות סימן למשהו מעניין. בלילה, רוב העיירה תהיה חשוכה ושקטה, והמפגשים יהיו בעיקר עם גנבים או טיפוסים מפוקפקים אחרים; אבל ליד מקומות אכילה (או שתייה) פופולריים, עדיין סביר להיתקל באנשים מכל הסוגים. על המנחה לוודא שתיאוריה של סביבת העיירה מבהירים זאת; כמובן, זה גם יקשה על השחקנים לזהות מפגשים "אמיתיים".

המנחה מעודדת ליצור טבלאות מפגשים משלה לכל עיר, עיירה או כפר שנוצרו (או להקצות מפגשים בדרכים אחרות אם רצוי); עם זאת, סט של טבלאות מפגשים "גנריות" מסופק להלן עבור אותם זמנים שבהם הכנה כזו לא הושלמה. גלגלי 2d6 בטבלה שלהלן כדי לקבוע איזה סוג של מפגש מתרחש; תיאור של כל סוג מפגש מופיע מתחת לטבלה.


```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#city-encounters", 
generalTableSelect([2,6,0],[[ 2 , 2 ],[ 3 , 3 ],[ 4 , 4 ],[ 5 , 5 ],[ 6 , 6 ],[ 7 , 7 ],[ 8 , 8 ],[ 9 , 9 ],[ 10, 10],[ 11, 11],[ 12, 12]]))})

```

:::{#city-encounters}

| (2d6) | מפגש ביום | מפגש בלילה |
|---|------|------|
| 2 | דופלגנגר | דופלגנגר |
| 3 | אציל | צל* |
| 4 | גנב | כנופיית גיוס |
| 5 | בריון | קבצן |
| 6 | משמר העיר | גנב |
| 7 | סוחר | בריון |
| 8 | קבצן | סוחר |
| 9 | כוהן | עכברוש ענק |
| 10 | שכיר חרב | משמר העיר |
| 11 | קוסם | קוסם |
| 12 | ליקנתרופ, עכברוש-אדם* | ליקנתרופ, עכברוש-אדם* |

:::

מפגשי **קבצן** יתחילו לעיתים קרובות עם קבצן יחיד שמתקרב לחבורה, אך בדרך כלל יהיו 2d4 קבצנים באזור, ואם אחד מחברי החבורה נותן משהו לקבצן הראשון, האחרים יסתערו על החבורה כמו זבובים. כל קבצן הוא בעל סיכוי של 90% להיות אדם רגיל, ו-10% להיות גנב בדרגה 1, ייתכן שהוא סוקר עבור גילדת הגנבים או כנופיה מקומית.

מפגשי **בריון** יהיו עם 2d4 צעירים קשוחים; לכל אחד יש סיכוי של 70% להיות אדם רגיל, ו-30% להיות לוחם בדרגה 1. בריונים בדרך כלל נראים בלתי חמושים, תלויים ביכולת הלחימה שלהם בקרב (אך שומרים פגיון או חרב קצרה מוסתרת, לשימוש במקרה שהקרב לא לטובתם). בריונים יכולים להיות קצת בלתי צפויים, כך שהמנחה עשויה לרצות להשתמש בגלגול תגובה כדי לקבוע את מצב הרוח של המנהיג.

מפגשי **משמר העיר** יהיו עם 2d6 שומרים, כולם לוחמים בדרגה 1 חוץ ממנהיג הכיתה, שיהיה בדרגה 2 עד 4. הם יתעמתו עם דמויות שנראות "חשודות", אך בדרך כלל יזדקקו לסיבה טובה לפני שינסו לעצור או להפריע לדמויות השחקנים.

מפגשי **דופלגנגר** ייראו, כמובן, כמו סוג אחר של מפגש; המנחה צריכה לגלגל שוב כדי לקבוע במה הדופלגנגר מתחזה. ייתקלו ב-1d6 דופלגנגרים; כל חברי קבוצה נוספים יהיו בני אדם שאינם יודעים שהם נוסעים בחברת מפלצות משנות צורה. אם החבורה "מעניינת" את הדופלגנגרים, אחת או יותר מהמפלצות ינסו לעקוב אחריהם ולהחליף חבר חבורה (כמתואר בתיאור המפלצת). במקרים רבים, חבורות דמויות השחקן לא יגלו את טבעו האמיתי של המפגש עד הרבה יותר מאוחר.

מפגשי **עכברוש ענק** יכללו בדרך כלל סמטאות, המזחים או מקומות "נמוכים" אחרים. עכברושים בדרך כלל אינם מסוכנים אלא אם כן מתגרים בהם, אך אם מופתעים הם עשויים לתקוף. ראו את תיאור המפלצת לפרטים על סוג מפגש זה.

מפגשי **ליקנתרופ, עכברוש-אדם** ייראו כמו סוג אחר של מפגש, או מפגש "רגיל" אחר או מפגש עכברוש ענק (תלוי בנסיבות). עכברושי-אדם הם פחדנים ולא יתקפו חבורה בגודל שווה או גדול יותר.

מפגשי **שכיר חרב** יכללו 2d6 חברים מחברת שכירי חרב, העוסקים בעסק כלשהו. מנהיג שכירי חרב עשוי להציע משרה לדמויות שחקן מסוג לוחם אם יש להן מוניטין כלשהו.

**סוחרים** הם תכונה נפוצה בעיירות, וייתכן שייתקלו בהם מבצעים כל סוג של עסק. כמו במפגשי שכירי חרב, סוחרים עשויים להציע עבודות לדמויות שחקן מעניינות, במיוחד לאלה עם מוניטין טוב. ראו **יצירת חבורת דמויות מנחה**, להלן, לפרטים על סוג מפגש זה. (סוחר בעיירה עשוי שלא להיות עם פמליה מלאה כפי שמתואר להלן; המנחה צריכה להשתמש בשיקול דעתה ביצירת המפגש.)

**אצילים** שנתקלים בהם עשויים גם להציע משרות לדמויות שחקן, או אולי להציע פרס עבור משימה מסוכנת. דמויות שחקן עם מוניטין רע עשויות להיתקל בעימות, להורות לעזוב את העיר, או אפילו להיעצר אם האציל יכול לקרוא למשמר העיר. (ראו **יצירת חבורת דמויות מנחה**, להלן, לפרטים על סוג מפגש זה.) אציל בעיירה עשוי שלא להיות עם פמליה מלאה כפי שמתואר להלן; המנחה צריכה להשתמש בשיקול דעתה ביצירת המפגש.

**כנופיות גיוס** יכללו 2d6 לוחמים, כולם בדרגה 1 חוץ מאחד או שני מנהיגים בדרגה 2 עד 5. הם יהיו חמושים בנשק קהה או ייתכן שיילחמו בידיים חשופות, שכן מטרתם היא ללכוד ולא להרוג דמויות שחקן; עם זאת, סביר להניח שלפחות חלק מחברי כנופיית הגיוס יהיו עם פגיונות או חרבות על גופם למקרה שיתפתח קרב רציני. כנופיית גיוס לא תתעמת עם חבורה בגודל שווה או גדול יותר אלא אם כן החבורה נראית מוחלשת, שיכורה וכו'. אם החבורה מפסידה, הם יתעוררו על סיפון ספינה בים או במחנה צבאי (תלוי אם מלחים או חיילים לכדו אותם), בלתי חמושים וחסרי אונים מול שוביהם.

מפגשי **כוהן** יהיו בדרך כלל דומים לקבוצת עולי רגל (ראו **יצירת חבורת דמויות מנחה**, להלן, לפרטים), אם כי הקבוצה שנתקלה בה לא תהיה גדולה כמו זו שתיתקל בה בשטח הפתוח. בדרך כלל ייתקלו בכוהן יחיד בדרגה 1 עד 4, מלווה ב-1d4 מאמינים.

מפגשי **צל** בעיירה יהיו דומים מאוד למפגש זה מתחת לאדמה; ראו את תיאור המפלצת לפרטים.

מפגשי **גנב** יהיו עם קבוצה של 1d6 גנבים, בדרך כלל מחופשים לאנשי עיירה רגילים או לפעמים כקבצנים. גנב אחד בקבוצה יהיה בדרגה 2 עד 4, בעוד האחרים יהיו בדרגה 1 בלבד. הם ינסו לגנוב מהחבורה, כמובן, אלא אם כן יושגחו היטב.

מפגשי **קוסם** יכללו קוסם בדרגה 4 עד 7, מלווה ב-1d4-1 שוליות בדרגה 1. המנחה חייבת להחליט על האופי ומצב הרוח של הקוסם.

## יצירת חבורת דמויות מנחה

### **הרפתקנים**

חבורת הרפתקנים של דמויות מנחה תכלול בדרך כלל 4-8 דמויות, כדלקמן: 1d3 לוחמים, 1d2 גנבים, 1d2 כוהנים, ו-1d2-1 קוסמים. בדרך כלל הדמויות יהיו כולן בדרגות דומות; לאחר שהוחלט על הדרגה הממוצעת של החבורה, ייתכן שתרצי להפוך כמה מהדמויות לדרגות נמוכות יותר (כדי לשקף את ה"תחליפים" הרגילים שמובאים כאשר חלק מהדמויות מתות).

על מנחת המשחק לבחור את הגזע/ים של ההרפתקנים דמויות המנחה בהתאם לאזור שבו הם נמצאים (או מגיעים ממנו). כנראה ש-80% או יותר מההרפתקנים הם בני אדם, 10% הם גמדים, 6% הם בני-מחצית וה-4% הנותרים הם אלפים. אם חבורת ההרפתקנים של דמויות המנחה היא רעה, המנחה עשויה לבחור להחליף חלק מחברי החבורה במפלצות דמויות אדם כמו אורקים, הובגובלינים או גנולים.

החבורה עשויה להיות יריבה לדמויות השחקן, מתחרה על אותם אוצרות, או שהם עשויים להיות אויבים ממש, שודדים מרושעים שדמויות השחקן חייבות להביס. כמובן, ייתכן שההרפתקנים דמויות המנחה הם בעלי ברית או ידידותיים לדמויות השחקן, אך זה עשוי להקל מדי על השחקנים.

### **שודדים, בריונים ושודדי דרכים**

חבורת שודדים תכלול בדרך כלל 2d12 לוחמים בדרגה 1 ו-1d6 גנבים בדרגה 1, בהנהגת לוחם או גנב בדרגה 2 עד 5 (1d4+1) או על ידי אחד מכל סוג (אם ישנם 11 או יותר חברים בדרגה 1 בסך הכל). בשטח הפתוח, לשודדים יהיו בדרך כלל סוסים או רכבים אחרים המתאימים לשטח (גנובים, כמובן) וכן שריון קל, חרבות וקשתות או רובי קשת. קבעי פריטים קסומים כפי שניתן להלן רק למנהיגים; לחברים הרגילים לא יהיו בדרך כלל פריטים קסומים.

במאורה או במחבוא שלהם, לחבורת שודדים יהיה בדרך כלל אוצר מסוג A (ללא פריטים קסומים שכן הם כבר ייווצרו באמצעות הכללים שלהלן).

### **שודדי ים ופיראטים**

ההבדל בין שודדי ים לפיראטים הוא במידה רבה שאלה של איך הם רוצים להיקרא; איך שלא תקראי להם, הם מקבילי מים לשודדים, תוקפים ספינות אחרות או פושטים על עיירות חוף לשם ביזה.

חבורת שודדי ים תכלול 3d8 לוחמים בדרגה 1, בהנהגת לוחם בדרגה 3 עד 6 (1d4+2) ו-1d3 לוחמים בדרגה 2 עד 5. כולם יהיו מנוסים בטיפול בספינות, כמובן. הם יהיו בלתי משוריינים או משוריינים רק בעור, ויהיו חמושים בחרבות וקשתות או רובי קשת.

פיראטים ימיים עשויים להופיע במספרים גדולים יותר, אך מספר המנהיגים יהיה דומה לזה שניתן לעיל. יצירת פריטים קסומים רק למנהיגים כפי שמתואר להלן. ספינה מלאה בפיראטים או שודדי ים תכיל אוצר מסוג A, ללא פריטים קסומים (מאחר שפריטים קסומים כבר ייגרלו עבור דמויות המנחה); האוצר עשוי שלא להיות על הספינה, שכן פיראטים לעיתים קרובות מעדיפים לקבור את אוצרותיהם באיים. במקרה כזה, לקפטן או לאחד מעוזריו תהיה מפה לאוצר המובילה למיקום האוצר.

### **סוחרים**

סוחרים חייבים לעיתים קרובות להעביר את סחורותיהם דרך אזורי שטח פתוח. בערך חצי מהזמן (50%), חבורת סוחרים יבשתית תובל על ידי סוחר עשיר יחיד; חבורות סוחרים אחרות יכללו 1d4+1 סוחרים פחות עשירים שהתאגדו יחד למען ביטחונם. יהיו 2d4 עגלות (אך לפחות אחת לכל סוחר) הנמשכות על ידי סוסים או פרדים. כל עגלה מונעת על ידי נהג שהוא אדם רגיל, בדרך כלל בלתי משוריין וחמוש בפגיון או חרב קצרה. השיירה תעסיק 1d4+2 לוחמים בדרגה ראשונה ו-1d4 לוחמים בדרגה שנייה כשומרים.

אם ייתקלו בים, חבורת סוחרים תכלול בדרך כלל ספינה יחידה בבעלות או שכורה על ידי סוחר יחיד. לספינה יהיה צוות של 2d8+8 אנשי צוות רגילים, שהם אנשים רגילים, בלתי משוריינים וחמושים באלות, פגיונות או חרבות קצרות; הקפטן, הסגן הראשון וקצינים אחרים נלקחים ממספר זה. ספינות גדולות עשויות לדרוש צוותים גדולים יותר. 1d4+2 לוחמים בדרגה ראשונה ו-1d4 לוחמים בדרגה שנייה יהיו על הסיפון כשומרים, בדיוק כמו בשיירה.

מלבד הסחורות היקרות אך ללא ספק מגושמות המועברות על ידי שיירת הסוחרים או הספינה, לחבורה כזו יהיה גם אוצר מסוג A, ללא פריטים קסומים; הוא עשוי להיות בחזה אחד, או מפוזר בין העגלות.

### **אצילים**

חבורת אצילים תכלול אציל (כמובן), ייתכן מלווה בבעל או באישה (גם הם אצילים, כמובן) ו/או אחד או יותר ילדים. לכל אציל מבוגר יהיה לפחות מלווה אחד (עוזר, גבירה בהמתנה, וכו').

אצילים מדרגה נמוכה יותר (כגון ברונים) יהיו בעלי עגלה או כרכרה אחת, הנמשכת על ידי סוסים משובחים; אצילים מדרגה גבוהה יותר יהיו בעלי שתי עגלות או יותר. האציל עשוי להיות רכוב על סוס מלחמה, אם כי הוא או היא עשויים לבחור לרכב בכרכרה חלק מהזמן. לכל כרכרה או עגלה יהיה נהג, שבמקרה זה יהיה לוחם בדרגה 1 עם שריון שרשראות וחרב ארוכה. לפחות שני לוחמים רכובים בדרגות 1 עד 4 יהיו עם האציל כמאבטחים; שוב, אצילים מדרגה גבוהה יותר יהיו בעלי יותר מאבטחים. המאבטחים יהיו בדרך כלל חמושים בחרבות ארוכות ואולי גם ברמחים, משוריינים בשריון לוחות, וסוסי המלחמה שלהם יהיו בדרך כלל משוריינים בשריון שרשראות. קביעת המספר המדויק של המאבטחים נתונה לשיקול דעתה של מנחת המשחק במקרה זה. כמובן, הסיכויים הרגילים לפריטים קסומים חלים כאן.

אציל בדרך כלל ייסע עם מעט כסף להוצאות; יש לגלגל אוצר מסוג A כדי לייצג זאת. במקרה זה, אל תוותרו על הפריטים הקסומים, שכן אצילים יהיו בדרך כלל עשירים יותר מהחבורה הממוצעת של בני אדם.

אצילים הם בדרך כלל (70%) בני אדם רגילים; אחרת, גלגלו 1d10: 1-6 מציין לוחם, 7-8 מציין קוסם, 9 מציין כוהן, ו-10 מציין גנב. (אצילים כוהניים הם בישופים, ארכיבישופים וכדומה.) גלגלו 2d4-1 כדי לקבוע את הדרגה של כל אציל "בעל מקצוע".

### **עולי רגל**

חבורת עולי רגל בדרכה אל (או מ) אתר דתי חשוב או פעילות דתית. חבורה כזו תובל על ידי 1d4 כוהנים בדרגות 1-4 (גלגלו עבור כל אחד).

שאר החבורה היא די אקראית בטבעה; רוב קבוצות עולי הרגל כוללות 3d6 בני אדם רגילים (או נשים אם הדת מאפשרת לנשים לצאת למסעות עלייה לרגל), 1d6 לוחמים בדרגות 1-4 (גלגלו עבור כל אחד) עם שריון שרשראות וחרב ארוכה, ו-1d4 גנבים בדרגות 1-4 (כל אחד מהם עשוי להיות אדם דתי אמיתי, או אולי פשוט במנוסה). יש גם סיכוי של 50% לקוסם אחד בדרגות 1-4 להיות עם החבורה.

עולי רגל בדרך כלל נוסעים קל, נושאים תיק אחד כל אחד והולכים או רוכבים על פרדות או סוסים. חבורת עולי הרגל תביא ככל הנראה מנחות כלשהן ליעדם; צרו אוצר מסוג A למטרה זו. אם מצוינים פריטים קסומים, הם ככל הנראה לא ישמשו על ידי אף אחת מהדמויות המנחות שכן הם כבר הוקדשו לאל או לפנתיאון.

### **פריטים קסומים לדמויות מנחות**

לדמויות מנחות יהיו בדרך כלל פריטים קסומים ביחס למקצוען ולדרגתן; הניחו סיכוי של 5% לכל דרגה שלכל לוחם, גנב או כוהן תהיה נשק קסום או שריון קסום (גלגלו עבור נשק ושריון בנפרד עבור כל דמות מנחה). ללא קשר לדרגה, גלגול של 96-00 ייחשב ככישלון. לקוסמים יהיה טבעת הגנה (גלגלו את הבונוס כרגיל עבור הפריט) על גלגול של 4% לכל דרגה, ופגיון קסום או מטה הליכה על גלגול של 3% לכל דרגה.

בנוסף, הניחו סיכוי של 2% לכל דרגה שלכל דמות תהיה שיקוי, ו-3% לכל דרגה שכוהן או קוסם יהיו בעלי מגילה כלשהי.

לבסוף, סכמו את הדרגות של כל חברי החבורה, והשתמשו במספר זה כסיכוי באחוזים שיימצא פריט קסום מגוון ביניהם. אם הגלגול מצליח, חלקו את המספר לשניים וגלגלו שוב; אם הגלגול השני מצליח, נמצאים שני פריטים כאלה. אם לחבורה יש יותר מ-3 חברים, ייתכן שתרצו לחלק את המספר שוב לשניים ולגלגל עבור פריט שלישי כזה. הקצו את הפריט או הפריטים הקסומים המגוונים לחברי החבורה שנראים הכי מתאימים, או גלגלו באקראי אם אינכם יכולים להחליט.

### **חבורות דמויי-אדם**

מניחים לעיל שחבורות דמויות מנחה יהיו בני אדם, או בעיקר כך; אך מנחת המשחק עשויה לבחור להציג חבורות של אלפים, גמדים או בני-מחצית מדי פעם. באופן כללי, חבורה של דמויי-אדם תהיה הומוגנית... חבורת אלפים תכלול את כל האלפים, למשל. אם ייתקלו בשטח של גזע אחר, חבורת דמויי-האדם עשויה לכלול מדריך שנשכר להוביל אותם ליעדם. לדוגמה, חבורת האלפים שהוזכרה לעיל עשויה לשכור מדריך אדם שיעזור להם בעת נסיעה דרך ארץ בני אדם.

מנחת המשחק עשויה פשוט להשתמש בנתונים שניתנו לעיל בעת יצירת חבורות כאלה. דבר אחד שמנחת המשחק חייבת להחליט הוא האם כללי "בני אדם רגילים" חלים על דמויי-אדם... האם יש "אלפים רגילים" למשל? החלטה זו נתונה למנחת המשחק. אם יש דמויות כאלה, יהיו להן את אותן יכולות גזעיות כמו לשאר בני גזען, אך יילחמו עם בונוס תקיפה של +0 בדיוק כמו בני אדם רגילים. אם אין דמויות כאלה בעולם המשחק, פשוט החליפו לוחמים בדרגה 1 עבור בני האדם הרגילים המפורטים לעיל.

## התמודדות עם שחקנים

### אפשרויות יצירת דמות

כללי יצירת הדמות הסטנדרטיים קוראים לגלגל 3d6 עבור כל ערך תכונה בסדר. שחקנים עשויים להתלונן שהם לא יכולים ליצור את סוג הדמויות שהם רוצים לשחק. הנה כמה אפשרויות שתוכלו לבחור מהן אם תרצו להקל על השחקנים שלכם. שימו לב שהשחקנים לא יכולים לדרוש את האפשרויות הללו; זו החלטה טהורה של מנחת המשחק.

**החלפת נקודות:** אפשרו לשחקן "להעביר" נקודות מערך תכונה אחד לאחר, בקצב של -2 לנקודה אחת לכל +1 שנוסף לאחר. הערך המרבי הוא עדיין 18 (או המקסימום הגזעי אם נמוך יותר), ואין לאפשר לשחקן להוריד אף ערך מתחת ל-9.

**החלפת ערכים:** אפשרו לשחקן להחליף כל שני ערכי תכונה, פעם אחת לכל דמות.

**הערבוב המלא:** אפשרו לשחקן לסדר את ששת ערכי התכונה כפי שהוא או היא רוצים. זה מאפשר את ההתאמה האישית המקסימלית לשחקן, אך מצד שני ייתכן שתמצאו שכל דמויות השחקנים בקמפיין שלכם מתחילות להיראות דומות מאוד. זה לא נדיר ששחקנים "משליכים" את הסטטיסטיקה הנמוכה ביותר בכריזמה, למשל.

### דמויות חסרות תקווה

לפעמים שחקן יגלגל עבור ערכי תכונה, יסתכל על הערכים שגלגל, ויכריז על הדמות "חסרת תקווה". כמובן, אין לדרוש משחקן לשחק דמות עם פחות מ-9 בארבעת הערכים הראשונים, שכן כל ארבעת המקצועות לא יהיו זמינים לדמות זו. עם זאת, את כמנחת המשחק עשויה לבחור לאפשר לשחקן לגלגל מחדש דמות עם ערכים שהם בסך הכל מתחת לממוצע גם אם הדמות לא "חסרת תקווה" כפי שזה.

הנה הצעה חלופית: אפשרו לשחקן "להפוך" את כל הערכים שלו על ידי חיסורם מ-21. זה יהפוך גלגול של 15 (+1 בונוס) ל-6 (-1 עונש) אך יהפוך גלגול של 3 (-3 עונש) ל-18 (+3 בונוס). זה יוביל לדמות שהייתה לה בעיקר עונשים להפוך לאחת עם בעיקר בונוסים. אם זה מותר, **כל הערכים חייבים להיות הפוכים**, לא רק הרעים! עשיית זאת מבטיחה שהדמות תהיה ניתנת למשחק ועדיין מאפשרת את האפשרות של כמה ערכי עונש.

כמובן, אפשר לגלגל את כל הערכים הממוצעים, כך שלדמות לא יהיו בונוסים או עונשים ולא תזכה בכל תועלת מהפיכת הערכים. הבחירה כאן צריכה להיות של השחקן; אם הוא רוצה לגלגל מחדש את כל הערכים, מנחת המשחק צריכה כנראה לאפשר זאת.

### רכישת לחשים

לכוהנים יש יתרון ברור על פני קוסמים, בכך שבאופן תיאורטי יש להם גישה לכל לחש של כל דרגה שהם יכולים להטיל. עם זאת, שימו לב שכוהנים מוגבלים בבחירת הלחשים שלהם על בסיס האלוהות, האמונה או האתוס שלהם; לדוגמה, כוהן של אלת הריפוי לא צריך להיות מופתע שהאלוהות שלו מסרבת להעניק לחשי ריפוי הפוכים. אם כוהן מתפלל ללחש שאינו מותר, מנחת המשחק עשויה לבחור להעניק לדמות לחש אחר, או לחלופין (אם האלוהות כועסת) לא להעניק לחש כלל עבור ה"חריץ" הזה.

קוסמים מתחילים את המשחק כשהם יודעים שני לחשים, **קריאת קסם** ועוד אחד (אלא אם כן מנחת המשחק מעניקה יותר לחשים התחלתיים). בכל פעם שהדמות עולה בדרגה, היא זוכה ביכולת להטיל יותר לחשים; בנוסף, בכל דרגה שנייה הקוסם זוכה בגישה ללחשים בדרגה הבאה (עד שכל הדרגות זמינות). עם זאת, קבלת היכולת להטיל את הלחשים הללו לא בהכרח אומרת שהקוסם לומד מיד לחשים חדשים.

קוסמים יכולים ללמוד לחשים על ידי לימוד מקוסם אחר, או על ידי חקר ספר הלחשים של קוסם אחר. אם לומדים, לחש יכול להילמד ביום אחד; חקר ספר הלחשים של קוסם אחר לוקח יום אחד לכל דרגת לחש. בכל מקרה, הלחש שנלמד חייב להיות מועתק לספר הלחשים של הקוסם עצמו, בעלות של 500 מטבעות זהב לכל דרגת לחש מועתקת.

קוסם יכול להוסיף לחש חדש של כל דרגה שהוא יכול להטיל בכל עת; עם זאת, לחשים בדרגות גבוהות יותר לא יכולים להילמד או להתווסף לספר הלחשים של הקוסם. הקוסם חייב למצוא מורה או לרכוש עבודה עיונית (כגון ספר לחשים של קוסם אחר) כדי ללמוד לחשים חדשים, והעלות של זה היא בנוסף לעלויות שניתנו לעיל. לעיתים קרובות קוסם ישמור על קשר עם המורה המקורי שלו, שילמד את הדמות לחשים חדשים בחינם או בתמורה לשירותים. לפעמים שני קוסמים יסכימו להחליף לחשים ידועים. במקרים רבים האפשרות היחידה העומדת לרשות הקוסם תהיה לשלם לקוסם אחר (לעיתים קרובות דמות מנחה) בין 100 ל-1000 מטבעות זהב לכל דרגת לחש בתמורה להכשרה כזו.

קוסמים יכולים גם ליצור לחשים חדשים לחלוטין (או לשנות לחשים קיימים); ראו את כללי מחקר הקסם למטה לפרטים.

### מגבלות נשק ושריון

לכמה גזעים ומקצועות יש מגבלות נשק ו/או שריון המוטלות עליהם. מה קורה כאשר שחקן מצהיר שדמותו עומדת להשתמש בנשק אסור או ללבוש שריון אסור?

**כוהנים:** האיסור על נשקים חדים הוא עניין של אמונה עבור כוהנים. לכן, אם כוהן משתמש בנשק אסור, הוא או היא מאבדים מיד את הגישה ללחשים שלהם וכן את הכוח להבריח את האל-מתים. כוהן דמות מנחה בדרגה גבוהה יותר מאותה אמונה חייב להקצות משימה כלשהי לעבריין שצריכה להיות מושלמת כדי שהכוהן שנפל יכפר וישיב את כוחותיו. אם אין חרטה, הדמות משתנה לצמיתות מכוהן ללוחם. חשבו מחדש את דרגת הדמות, והחילו את סך נקודות הניסיון הנוכחי על טבלת הלוחם כדי לקבוע זאת. נקודות הפגיעה ובונוס התקיפה נשארים זהים; שנו את בונוס התקיפה רק לאחר שהושגה דרגה חדשה כלוחם, וגלגלו קוביות פגיעה של לוחם כרגיל כאשר דרגות מושגות.

**קוסמים:** דמויות אלו פשוט אינן מאומנות בשום נשק מלבד אלו המותרים להן בדרך כלל, ועליהן לסבול מעונש תקיפה של -5 כאשר הן משתמשות בנשק אסור. קוסם בשריון אינו יכול להטיל לחשים כלל; כל ניסיון כזה ייכשל, והלחש יאבד.

**גנבים:** לבישת שריון כבד יותר, מגביל יותר ו/או רועש יותר משריון עור מונעת את השימוש בכל יכולות הגנב, כולל יכולת התקיפה בהתגנבות. גנבים יכולים לבחור ללבוש שריון כזה, אך זה רק הופך אותם לתירוץ גרוע ללוחם.

**גמדים ובני-מחצית:** דמויות אלו מנועות משימוש בנשקים גדולים, בעיקר בשל קומתם הקטנה ומשקלם היחסי הנמוך. קשה להניף נשק כשהנשק מנסה להניף אותך. אם דמות כזו מנסה להשתמש בנשק אסור, מנחת המשחק יכולה להחיל עונש תקיפה של -5 בהתבסס על הקושי בשימוש בנשק, או לחלופין להכריז על הניסיון כלא מוצלח, לפי שיקול דעתה.

### שיפוט משאלות

משאלות הן אחד הדברים הפוטנציאליים ביותר להפרת האיזון במשחק. עם משאלה מנוסחת בקפידה, דמות שחקן יכולה לבצע שינויים מרחיקי לכת ודרמטיים בעולם המשחק, ואולי אף לשכתב את ההיסטוריה. לפני שאת מאפשרת לדמויות השחקן במשחק שלך גישה אפילו למשאלה אחת, חשבי כיצד תתמודדי עם זה.

משאלות מוענקות על ידי מגוון ישויות. אפילו כאשר משאלה מגיעה ממכשיר (טבעת או חרב, למשל), ישות חוץ-ממדית כלשהי, אל או שד או כל דבר אחר, שמה את המשאלה במכשיר. משאלה תיטה לקדם את מטרות הישות המעניקה; אם המעניק הוא אפריטי מרושע, למשל, הוא ינסה לעוות את המשמעות או הכוונה של המשאלה כך שהיא לא תבצע באמת את מה שדמות השחקן רוצה. מצד שני, אם המעניק הוא אחת מהכוחות הטובים, הוא יעניק את המשאלה כפי שהתכוון כל עוד דמות השחקן אינה חמדנית או נקמנית.

איזון המשחק הוא הנושא המרכזי שיש לקחת בחשבון. שימוש במשאלה כדי לרפא את כל הקבוצה, להעביר את כולם ללא שגיאה למקום רחוק, או להימנע או לשחזר קרב קטסטרופלי, הוא סביר. משאלה שדמות תוחזר לחיים ולבריאות היא סבירה, אך משאלה שלא רק מחזירה אלא גם משפרת את הדמות אינה סבירה.

באופן כללי, משאלה מוענקת לפחות בדיוק מילולי... יש למלא את מילות המשאלה. החריג הוא משאלות שאינן סבירות למטרות איזון המשחק; הן עדיין מפורשות לפחות באופן מילולי, אך עשויות להיות מוענקות רק באופן חלקי. בדוגמה האחרונה לעיל, למשל, הכוח המעניק כנראה יחזיר את הדמות לחיים ולבריאות אך יתעלם מה"שיפורים" שביקשו.

## חוקים אופציונליים

### מוות וגסיסה

החוקים קובעים כי, באפס נקודות פגיעה, הדמות מתה. אם זה קשה מדי עבורך, הנה מספר גישות לשינוי המצב:

**החייאת מתים:** הגישה הראשונה אינה משנה את החוקים כלל. סדרי את העניינים כך שדמויות שנהרגו בהרפתקה יוכלו להיות **מוחיות** בקלות (אך בעלות משמעותית). זה לא רק "מטפל" בבעיית התמותה, אלא גם סופג עודף אוצר, מונע מדמויות השחקן להיות עשירות מדי מכדי להתעניין בהרפתקאות. זה גם נוטה לתגמל את הזהירים (מכיוון שהם שומרים על זהבם לעיתים קרובות יותר).

מה אם לדמויות אין מספיק כסף כשהן מתות כדי להרשות לעצמן להיות **מוחיות**? אפשרי למוסד הדתי המקומי **להחיות** הרפתקנים מתים בתמורה לשעבודם... כלומר, ההרפתקנים, לאחר שהוחזרו לחיים, חייבים לכנסייה או למקדש את הכסף שהיה עולה להחיותם, *או שירות שווה ערך*. כך, למנהיגים הדתיים המקומיים תהיה מאגר מוכן של הרפתקנים לביצוע משימות מסוכנות עבורם.

אבל ההרפתקן(ים) מתים... איך הם יכולים להסכים לשעבוד? ישנן שתי אפשרויות: הכוהנים יכולים להשתמש ב**דבר עם המתים** כדי להשיג הסכמה, או שההרפתקנים יכולים לחתום על הסכם עם הכנסייה לפני יציאתם להרפתקה המסוכנת הפוטנציאלית. האחרון עשוי אפילו להיחשב כנוהל סטנדרטי במקומות מסוימים.

**גלגול הצלה נגד מוות:** השינוי הראשון בפועל בחוק הוא לאפשר לדמויות שהופחתו לאפס נקודות פגיעה לגלגל הצלה נגד קרן מוות כדי להימנע ממוות. אם הגלגול נכשל, הדמות מתה מיד, בדיוק כמו בחוקים הרגילים. אם הגלגול מצליח, הדמות נשארת בחיים למשך 2d10 סיבובים; אם הפצעים של הדמות נחבשים (או שהיא מקבלת קסם ריפוי) בתוך פרק זמן זה, המוות נמנע. הדמות נשארת מחוסרת הכרה למשך כל 2d10 הסיבובים שגולגלו, או מתה אם לא טופלה או מתעוררת אם הפצעים שלה נחבשו.

חבישת הפצעים של הדמות הגוססת מייצבת אותה באפס נקודות פגיעה. ריפוי לא-קסום ידרוש שבוע מלא כדי לשחזר את נקודת הפגיעה הראשונה; לאחר מכן, הריפוי מתקדם בקצב הרגיל.

ריפוי קסום ישחזר את הדמות לכלל שנגולל בגלגול קוביית הריפוי (עד למקסימום הרגיל כמובן).

שימי לב שכל מטיל לחשים שהופחת לאפס נקודות פגיעה ושורד לאחר מכן מאבד את כל הלחשים המוכנים שנותרו.

חוק זה עשוי להיות משולב עם ההצעות תחת החייאת מתים, לעיל.

**נקודות פגיעה שליליות:** במקום לעצור באפס נקודות פגיעה, עקבי אחרי המספר השלילי הנוכחי. בסוף כל סיבוב לאחר שהוא או היא נופלים, הדמות מאבדת נקודת פגיעה נוספת. אם מגיעים לסך של -10, הדמות מתה. לפני שהנקודה הזו מושגת, הדמות עשויה לקבל חבישת פצעים ו/או ריפוי קסום, מה שייצב את הדמות. הדמות הפצועה לא תוכל לזוז יותר מכמה רגליים ללא עזרה, לא להילחם ולא להטיל לחשים, עד שנקודות הפגיעה שלה יהיו שוב מעל לאפס. חוק זה *לא* צריך להיות משולב עם אפשרות גלגול הצלה נגד מוות.

כמו עם חוק **גלגול הצלה נגד מוות**, מטילי לחשים ששורדים לאחר שהופחתו לאפס או לנקודות פגיעה שליליות מאבדים את כל הלחשים המוכנים הנוכחיים.

כאופציה נוספת, מנחת המשחק עשויה לבחור להשתמש במספר שלילי השווה לערך החוסן של הדמות במקום -10 ישר.

### רעל "גלגל או תמות"

רעלים, כפי שמתוארים בקטעי המפגש והמפלצות, הורגים דמויות באופן מיידי. מנחות משחק עשויות לגלות שזה הופך את שיעור התמותה של דמויות השחקן לגבוה מדי. מצד שני, רעלים **צריכים** להיות מפחידים. הנה חוק אופציונלי שעשוי להקל מעט על המצב מבלי להסיר לחלוטין את הפחד מהרעל:

כאשר מצוין רעל "גלגל או תמות", הקורבן חייב לגלגל הצלה נגד רעל או לסבול נזק של 1d6 לכל סיבוב במשך 6 סיבובים, החל מהסיבוב שלאחר החשיפה לרעל; זהו ממוצע של 21 נקודות נזק, אך אפילו דמות בדרגה ראשונה עשויה לשרוד עם שילוב של מזל וקסם ריפוי. כמובן, מנחת המשחק יכולה ליצור רעלים השונים מהנתונים הללו. אם חוק **נקודות פגיעה שליליות** האופציונלי נמצא בשימוש, מומלץ להאריך את משך הרעל ל-10 סיבובים (ממוצע של 35 נקודות).

### הענקת נקודות ניסיון עבור אוצר שנצבר

מנחת המשחק יכולה גם להקצות נקודות ניסיון עבור אוצר שנצבר, בקצב של 1 מטבע זהב = 1 נק"נ. זה אופציונלי; מנחות שרוצות לקדם את השחקנים לדרגות גבוהות יותר במהירות עשויות לבחור לעשות זאת, בעוד אלו המעדיפות קצב איטי יותר צריכות לוותר על כך. אם מוענק ניסיון עבור אוצר, יש להעניק אותו רק עבור אוצר שנרכש והוחזר למקום בטוח. לחלופין, מנחת המשחק עשויה לדרוש שהאוצר יושקע באימון כדי שייחשב לניסיון. זו דרך יעילה מאוד להסרת עודף אוצר מהקמפיין.

### גלגולי תכונות

יהיו פעמים שבהן דמות שחקן תנסה לעשות משהו במשחק שנראה שאין לו חוק שמכסה אותו. בחלק מהמקרים הללו, התכונה היחידה שיש לדמות שנראית מתאימה עשויה להיות ערך תכונה. הנה שיטה מוצעת לביצוע גלגולים נגד ערכי תכונות שנותנת עדיין סיכויים טובים יותר לדמויות בדרגות גבוהות יותר:

השחקן מגלגל 1d20 ומוסיף את בונוס התכונה שלו או שלה עבור הערך שמנחת המשחק חושבת שהוא המתאים ביותר, וכן כל בונוס או עונש מצבי שמנחת המשחק מקצה. התייעצי בטבלה הבאה. אם הסכום שגולגל שווה או גבוה מהמספר המטרה הנתון, הגלגול הוא הצלחה.

| **דרגה** | **מטרה** |
|------|-------|
| דמות מנחה או 1 | 17 |
| 2-3 | 16 |
| 4-5 | 15 |
| 6-7 | 14 |
| 8-9 | 13 |
| 10-11 | 12 |
| 12-13 | 11 |
| 14-15 | 10 |
| 16-17 | 9 |
| 18-19 | 8 |
| 20 | 7 |

### הכנת לחשים מהזיכרון

לפעמים קוסם ירצה להכין לחשים, אך ספר הלחשים שלו או שלה עשוי להיות לא זמין; זה כולל כאשר הספר נהרס או נגנב וכן זמנים שבהם הקוסם נלכד או נכלא.

קוסם יכול תמיד להכין **קריאת קסם** מהזיכרון. לחשים אחרים דורשים גלגול תבונה, כפי שתואר לעיל, עם דרגת הלחש כעונש על גלגול הקובייה.

כישלון מתיש את משבצת הלחש המוכנה, בדיוק כאילו הוכנה בהצלחה ואז הוטלה; כך שאם קוסם בדרגה 5 מנסה להכין **כדור אש** מהזיכרון, ונכשל, לא יהיו לו לחשים בדרגה 3 לאותו יום.

### יכולות גנב

חלק מהשחקנים של גנבים עשויים לרצות יותר שליטה על יכולות הגנב שלהם. אם תבחני את טבלת יכולות הגנב, תגלי את סודה: מדרגות 2-9, הגנב משתפר ב-30 אחוזים (בסך הכל) בכל דרגה; מדרגות 10-15, 20 אחוזים; ומדרגה 16 ואילך, 10 אחוזים. אם ברצונך לאפשר התאמה אישית של הגנב, פשוט אפשרי לשחקן להקצות את הנקודות כרצונו או רצונה במקום לעקוב אחר הטבלה. אפשרי לא יותר מ-10 אחוזים להוסיף לכל יכולת גנב בודדת לכל עליית דרגה. שימי לב גם ששום יכולת גנב לא יכולה להיות מוגברת מעל 99 אחוזים.

## מחקר קסום

### חוקים כלליים למחקר

בשלב מסוים קוסם או כוהן עשויים לרצות להתחיל ליצור חפצים קסומים או להמציא לחשים. זה נקרא **מחקר קסום**. עבור כל מחקר, קוסם חייב שיהיה לו מגדל או מעבדה, בעוד כוהן דורש מקדש או כנסייה מקודשים כראוי לאמונתו או אמונתה. בנוסף, תהיה עלות ליצירת כל פריט, זמן מינימלי הנדרש ליצירתו, וסיכוי נתון להצלחה. אם הגלגול נכשל, בדרך כלל הזמן והכסף מבוזבזים ויש להתחיל את התהליך מחדש מההתחלה; עם זאת, התייעצי בחוקים המפורטים להלן עבור חריגים.

*בכמעט כל המקרים, על מנחת המשחק לבצע את הגלגול הזה בסודיות.* ישנם מצבים רבים שבהם הדמות (או השחקן) לא צריכים לדעת אם הגלגול נכשל בפועל, או אם מנחת המשחק החליטה שהמחקר בלתי אפשרי עבור הדמות. מנחת המשחק עשויה להחליט לספר לשחקן שהמחקר בלתי אפשרי אם הגלגול מצליח; אם הגלגול נכשל, זה כל מה שהשחקן צריך לדעת.

באופן כללי, כוהנים יכולים ליצור רק חפצים קסומים המשחזרים את ההשפעות של לחשי כוהנים; כוהנים יכולים גם ליצור נשקים ושריונות מכושפים, אפילו כאלה שהם עצמם לא יכולים להשתמש בהם (מכיוון שהם עשויים ליצור נשקים או שריונות עבור מאמינים אחרים של אמונתם). קוסמים יכולים ליצור כל סוג של חפץ קסום למעט אלה המשחזרים לחשי כוהנים שאין להם לחש קוסם מקביל.

הזמן המושקע במחקר קסום חייב להיות ימי עבודה של שמונה שעות עם הפסקות שאינן נמשכות יותר מיומיים. הפסקות ארוכות יותר יגרמו לכישלון אוטומטי של הפרויקט.

מנחת המשחק יכולה, אם היא רוצה, להעניק נקודות ניסיון לדמויות שמסיימות בהצלחה מחקר קסום. מומלץ שהקצב של פרסים כאלה יהיה 1 נק"נ לכל 10 מטבעות זהב שהושקעו במחקר. פרס זה יכול להינתן עבור כל מחקר, או רק עבור יצירת חפצים קסומים, או לא בכלל אם מנחת המשחק מעדיפה להדגיש הרפתקאות למטרות קידום.

### מחקר לחשים

מחקר לחשים חדשים הוא הסוג הנפוץ ביותר של מחקר קסום. קוסם יכול לחקור לחש סטנדרטי, ובכך להסיר את הצורך במורה או מקור; לחלופין, כוהן או קוסם יכולים לחקור לחש חדש לחלוטין. כמובן, אף דמות לא יכולה להמציא או לחקור לחש בדרגה גבוהה יותר ממה שהיא יכולה להטיל.

אם הדמות ממציאה לחש באופן מוחלט, מנחת המשחק חייבת לקבוע את דרגת הלחש ולשפוט אם הלחש אפשרי "כמו שהוא". מנחת המשחק לא חייבת לספר לשחקן אם הלחש אפשרי, ולמעשה זה עשוי להיות עדיף.

העלות למחקר לחש היא 1,000 מטבעות זהב לכל דרגת לחש עבור לחשים "סטנדרטיים", או 2,000 מטבעות זהב לכל דרגת לחש עבור לחשים חדשים שהומצאו; בכל מקרה, נדרש שבוע לכל דרגת לחש כדי להשלים את המחקר. הסיכוי להצלחה הוא 25%, בתוספת 5% לכל דרגת הדמות, פחות 10% לכל דרגת הלחש; הסיכוי המרבי להצלחה הוא 95%.

אם גלגול המחקר מצליח, הדמות יכולה להוסיף את הלחש לספר הלחשים שלה (אם היא קוסם) או יכולה לאחר מכן להתפלל עבור הלחש (אם היא כוהנת). במקרה של כישלון, הכסף והזמן מבוזבזים לשווא. כוהנים של אותו אל, אמונה או אתוס יכולים ללמד זה את זה את התפילות הנדרשות לגישה ללחשים חדשים; זה לוקח שעה אחת לכל דרגת לחש. ההליך להחלפת לחשים עם קוסמים אחרים כבר הוסבר (תחת רכישת לחשים, לעיל).

כאמור לעיל, מנחת המשחק עשויה להחליט שלחש חדש מוצע אינו "נכון" עבור הקמפיין שלה; חזק מדי, נמוך מדי בדרגה, וכו'. במקום לספר לשחקן זאת, ישנן שתי אסטרטגיות שניתן להשתמש בהן.

ראשית, מנחת המשחק עשויה להחליט לשנות את הלחש. אם הגלגול מצליח, מנחת המשחק מציגה לשחקן גרסה מתוקנת של הלחש, מותאמת כפי שנראה לה נחוץ למטרות איזון המשחק.

החלופה, המתאימה יותר כאשר מנחת המשחק מאמינה שהלחש צריך להיות בדרגה גבוהה יותר ממה שהדמות יכולה להטיל, היא לבצע את הגלגול בכל מקרה. אם הגלגול נכשל, זה כל מה שהשחקן צריך לדעת; אך אם הוא מצליח, מנחת המשחק צריכה אז להראות לשחקן את הגרסה המתוקנת של הלחש ולהסביר שהדמות יכולה לנסות שוב כאשר היא מגיעה לדרגה גבוהה מספיק כדי להטיל אותו. במקרה זה, מנחת המשחק עשויה לאפשר לדמות להפחית או את הזמן או את העלות בחצי כאשר המחקר מתבצע שוב בדרגה גבוהה יותר.

### מחקר חפצים קסומים

כל דמות שמעוניינת ליצור חפצים קסומים חייבת לדעת את כל הלחשים (אם ישנם) שיש להטמיע בחפץ. חפצים שמייצרים השפעות שאינן תואמות אף לחש ידוע עשויים לדרוש מחקר נוסף (כדי להמציא את הלחש הלא ידוע) אם מנחת המשחק רוצה בכך.

חלק מהחפצים הקסומים דורשים רכיבים מיוחדים שאי אפשר בדרך כלל לקנות. רכיבים מיוחדים יכולים לשמש רק פעם אחת בפרויקט כזה. לדוגמה, מנחת המשחק עשויה לדרוש את עורו של מפזר כדי ליצור **גלימת העתקה**, או רוק של דרקון אדום כדי ליצור **שרביט כדורי אש**. שימי לב שיש חוקים ספציפיים לרכיבים תחת חפצים קסומים אחרים, להלן.

דרישות רכיבים מיוחדים הן לחלוטין לפי שיקול דעתה של מנחת המשחק, ומשמשות בדרך כלל להאטת יצירת חפצים קסומים חזקים שעלולים להפר את האיזון של הקמפיין. זה גם דרך טובה להוביל את המטיל (ואת קבוצתו) להרפתקאות מסוכנות.

### סיכוי להצלחה

אלא אם כן נאמר אחרת להלן, הסיכוי הבסיסי להצלחה ביצירת חפץ קסום הוא 15% בתוספת 5% לכל דרגת המטיל, בתוספת התבונה המלאה של המטיל (אם הוא קוסם) או החוכמה (אם הוא כוהן). כך, מטיל בדרגה 9 עם דרישה עיקרית של 15 יש לו סיכוי בסיסי של 75%.

### מגילות לחשים

מטיל לחש יכול ליצור מגילה המכילה כל לחש שיש לו גישה אליו (עבור קוסם, לחשים בספר הלחשים שלו; עבור כוהן, כל לחש שהדמות עשויה להתפלל עבורו בהצלחה). העלות היא 500 מטבעות זהב לכל דרגת לחש, והזמן הנדרש הוא יום אחד לכל דרגת לחש.

הפחיתי את הסיכוי להצלחה בהתבסס על דרגת הלחש הנכתב, בקצב של -10% לכל דרגה.

אם הגלגול נכשל, הכישוף של המגילה נכשל; עם זאת, אם המטיל מנסה שוב לכתוב את אותו הלחש, או העלות או הזמן מופחתים בחצי (לפי בחירת הדמות).

### חפצים חד-פעמיים אחרים

מגילות (מלבד מגילות לחשים), שיקויים, וכמה חפצים אחרים (כגון **מטה הביטול**) הם חפצים חד-פעמיים. חפצים אלה יכולים להיווצר על ידי קוסמים או כוהנים בדרגה 7 ומעלה.

הסיכוי להצלחה הוא כפי שניתן עבור מגילות, לעיל, כאשר החפץ הנוצר משחזר לחש ידוע (או כאשר מנחת המשחק מחליטה שיש ליצור לחש, כפי שתואר לעיל). עבור סוגים אחרים של חפצים, מנחת המשחק צריכה להקצות דרגת לחש כפי שהיא רואה לנכון, והעלות והזמן הנדרשים מוכפלים (כפיצוי על המחקר או הידע הנדרש עבור חפצים המשחזרים לחשים). הזמן הנדרש הוא שבוע אחד בתוספת יום אחד לכל דרגת לחש (או שווה ערך), והעלות להטלת הכישוף על החפץ היא 50 מטבעות זהב לכל דרגת לחש, לכל יום.

שיקויים הם מקרה מיוחד; הדמות היוצרת שיקוי יכולה ליצור מנה גדולה, המורכבת מכמה מנות, שניתן לבקבק בבקבוקים נפרדים או לשלב בבקבוק גדול יותר. עבור כל מנה נוספת הנוצרת באותו זמן, הפחיתי את הסיכוי להצלחה ב-5% והגדילי את הזמן הנדרש ביום אחד. שימי לב שהגדלת הזמן הנדרש תגדיל ישירות את העלות. אם הגלגול ליצירת החפץ נכשל, כל המנה מתקלקלת.

### חפצים קסומים קבועים

יצירת חפצים קסומים קבועים (טבעות, נשקים, שרביטים, מטות, ורוב החפצים הקסומים המגוונים) דורשת קוסם או כוהן בדרגה 9 ומעלה.

כאשר מכשפים חפץ עם יכולות מרובות, כל יכולת של החפץ דורשת גלגול נפרד להצלחה; הגלגול הראשון שנכשל מסיים את תהליך הכישוף. חפץ כזה עדיין יבצע את הכוחות או ההשפעות שכבר הוטלו עליו בהצלחה, אך לא ניתן להוסיף לו כישופים נוספים.

חפצים קסומים קבועים, כולל נשקים (מתוארים בפירוט להלן), חייבים להיווצר מחפצים באיכות גבוהה. עלותם של חפצים כאלה תהיה בדרך כלל פי עשרה מהעלות הרגילה עבור חפץ כזה.

### כישוף נשקים

העלות הבסיסית לכישוף נשק או שריון היא 1,000 מטבעות זהב לכל נקודת בונוס. עבור נשקים עם שני בונוסים, חלקי את הבונוס הגדול יותר בחצי (אל תעגלי) והוסיפי את הבונוס הקטן יותר; כך, **חרב +1, +3 נגד דרקונים** תעלה 2,500 מטבעות זהב לכישוף. כישוף נשק לוקח שבוע אחד בתוספת שני ימים לכל נקודת בונוס; כך, החרב המתוארת תדרוש שנים עשר ימים לכישוף.

הפחיתי את הסיכוי להצלחה ב-10% כפול הבונוס; כך, **חרב +1** תפחית את הסיכוי הבסיסי ב-10%, בעוד **חרב +1, +3 נגד דרקונים** המתוארת לעיל תפחית את הסיכוי הבסיסי ב-25%. יתר על כן, ניתן להגדיל את הסיכוי להצלחה ב-25% על ידי הכפלת העלות והזמן הנדרשים (החלטה זו חייבת להיות מוכרזת לפני ביצוע הגלגול).

עבור נשקים שיש להם כוחות נוספים, שלבי את הכללים לעיל עם הכללים ליצירת חפצים קבועים. כל הכישופים חייבים להיות מיושמים ב"סשן" כישוף אחד.

### חפצים קסומים אחרים

לחפצים קסומים יכולים להיות מספר **מאפיינים**. כל מאפיין שמתווסף לחפץ קסום מגדיל את העלות ואת הזמן הנדרש, ומפחית את הסיכוי להצלחה. המאפיינים הם כדלקמן:

**יוצר השפעה של לחש או דמוי לחש**: זהו המאפיין הבסיסי של כל החפצים הקסומים שאינם נשקים. העלות הבסיסית של כישוף זה היא 500 מטבעות זהב לכל דרגת לחש; הזמן הנדרש הוא חמישה ימים בתוספת שני ימים לכל דרגה. אם לחפץ הקסום יש מספר השפעות של לחש או דמוי לחש, הוסיפי את העלות והזמן יחד. הסיכוי להצלחה מופחת ב-5% לכל דרגת לחש.

**יש לו מספר מטענים**: זה כולל, כמובן, שרביטים ומטות, אך מספר חפצים קסומים אחרים יהיו גם בעלי מטענים. לכל השפעה של לחש או דמוי לחש יש בדרך כלל מאגר מטענים נפרד (אך ראו להלן). הטבלה הבאה מציגה את רמות המטען המקסימליות השונות ואת העלות, הזמן וההתאמות לסיכוי הנלוות:

| רמת מטען | עלות לכל מטען | מטענים ליום | סיכוי |
|-------|--------|-------|-------|
| 2-3 | +150 מטבעות זהב | 1 | - 5% |
| 4-7 | +125 מטבעות זהב | 2 | - 10% |
| 8-20 | +100 מטבעות זהב | 3 | - 20% |
| 21-30 | +75 מטבעות זהב | 4 | - 30% |

בעת שימוש בטבלה לעיל, אל תחשבי את המטען הראשון לצורכי עלות או זמן. שימי לב שכל מאגר מטענים נפרד בחפץ חייב להיות מחושב בנפרד.

**החפץ ניתן לטעינה מחדש:** חשבי את העלות והזמן הנוספים, ואת הקנס לסיכוי להצלחה, עבור חפצים הניתנים לטעינה מחדש ככפול מהנתונים מהטבלה לעיל; כך, יצירת חפץ הניתן לטעינה מחדש עם 3 מטענים תעלה 600 מטבעות זהב יותר במקום 300 מטבעות זהב יותר, ותיקח שני ימים לכל מטען (או ארבעה ימים נוספים); הסיכוי להצלחה מופחת ב-10% במקום 5%.

**החפץ מטעין את עצמו:** יצירת חפץ המטעין את עצמו היא יקרה; יש ליישם את ההתאמות הבאות לעלות המטען, הזמן והסיכוי עבור חפצים המטעינים את עצמם אוטומטית. שימי לב שחפצים המטעינים את עצמם אינם "ניתנים לטעינה מחדש" במובן שהם לא יכולים להיות נטענים מחדש אלא על ידי עצמם.

| קצב טעינה | עלות | זמן | סיכוי |
|-------|--------|-------|-------|
| 1 ליום | x 3 | x 2 | - 10% |
| הכל ליום | x 5 | x 3 | - 30% |
| הכל לשבוע | x 4 | x 2 | - 20% |

**המטענים הם גנריים:** משמעות הדבר היא שכל ההשפעות של החפץ שואבות כוח מאותו מאגר מטענים; רוב המטות של קוסמים נמצאים בקטגוריה זו. חפצים עם מטענים גנריים ניתנים לטעינה מחדש אוטומטית; אין ליישם את ההתאמות הרגילות עבור תכונה זו. במקום זאת, יש לשלב את העלויות הרגילות עבור מאגרי המטענים של כל השפעה (שכולן חייבות להיות עם אותו מספר מטענים), ולאחר מכן לחלק את עלות המטען, הזמן וההתאמות לסיכוי לשניים. כך, שתי השפעות המשתפות מאגר אחד עולות כמו השפעה אחת עם מאגר אחד.

**החפץ יכול לשמש כל מקצוע:** כברירת מחדל, חפצים קסומים יכולים לשמש רק את המקצוע שיצר אותם; כך ש**שרביט כדורי אש** ניתן לשימוש בדרך כלל רק על ידי קוסמים, או **מטה ריפוי** רק על ידי כוהנים. תכונה זו מאפשרת לחפץ לשמש כל מקצוע של דמות, וכוללת הקצאת מילים ופקודות פשוטות לחפץ. הוספת תכונה זו עולה 1,000 מטבעות זהב לכל השפעה. שימי לב שלא כל ההשפעות של החפץ חייבות להיות מכוסות; ניתן ליצור חפץ שבו חלק מההשפעות יכולות לשמש כל מקצוע, אך השפעות אחרות יכולות לשמש רק את מקצוע היוצרת.

**החפץ פועל באופן רציף או אוטומטי:** תכונה זו מחליפה הן את המטענים והן את תכונות השימוש בחפץ. החפץ פועל בכל פעם שהוא נלבש כראוי, או מופעל אוטומטית כאשר נדרש. **טבעת עמידות לאש** היא דוגמה טובה; גם **טבעת היעלמות** נמצאת בקטגוריה זו. הוספת תכונה זו מכפילה את העלות והזמן הסופיים פי חמישה ומחילה קנס של 40% על סיכוי ההצלחה.

כל תכונה המיושמת על חפץ קסום תדרוש חומר יקר ערך, נדיר ו/או קסום לתמיכה בכישוף. לדוגמה, שרביט כדורי אש כולל השפעת לחש המופעלת על ידי מטענים; אלו שתי תכונות יחסית רגילות, כך שהקוסם היוצר את החפץ מציע עץ נדיר עבור המוט ואודם בשווי 1,000 מטבעות זהב עבור הקצה. המנחה עשויה, כמובן, לדרוש משהו נדיר או יקר יותר אם החפץ הקסום חזק במיוחד.

ניתן להפחית את העלות הבסיסית של תכונת השפעת לחש ב-25% על ידי החלת מגבלות על היכולת. לדוגמה, **טבעת כישוף דריאדה** היא דוגמה להשפעת לחש **כישוף אדם** מוגבלת, שתהיה זכאית להנחה. זה לא משפיע על סיכוי ההצלחה או על הזמן הנדרש.

נשקים שאמורים להיות מוקסמים בכוחות נוספים מעבר לבונוס הרגיל דורשים שילוב של כללי הקסם לנשק הסטנדרטיים עם הכללים שניתנו לעיל. בצעי את הקסם לנשק תחילה; אם הוא מצליח, אז הדמות המקסמת את הנשק חייבת מיד (בתוך יומיים, כפי שהוסבר קודם) להתחיל בתהליך הקסם של הכוח הדמוי לחש. כישלון של ההליך השני אינו פוגע בקסם הנשק.

### חפצים מקוללים

חלק מהחפצים המקוללים, כמו מגילות מקוללות, נוצרים כך במיוחד על ידי מטילת הלחשים. הקושי ביצירת חפץ כזה הוא בערך כמו הקושי ביצירת מגילת לחש של **הטלת קללה**.

חפצי קסם מקוללים אחרים עשויים להיות תוצאה של ניסיון כושל ליצור חפץ שימושי. המנחה חייבת להחליט האם פרויקט מחקר כושל ייצור בפועל חפץ מקולל.


