# שכירים

דמויות שחקן לפעמים ירצו או יצטרכו לשכור דמויות מנחה (דמויות שאינן של שחקן) שיעבדו עבורן. ישנן מספר קטגוריות של דמויות מנחה זמינות לשכירה, כדלקמן:

### עוזרים

עוזר נמצא בקרבה רבה למעסיק שלו. עוזרים נשכרים עבור חלק מהאוצר (בדרך כלל לפחות 15% מההכנסה של המעסיק) בתוספת הוצאות (נשק, שריון, מנות קרב וציוד בסיסי המסופקים על ידי המעסיק). עוזרים בדרך כלל נאמנים מאוד ומוכנים לקחת סיכונים סבירים; בפועל, הם הסוג היחיד של שכירים שילווה בדרך כלל דמות שחקן לתוך מבוך, מאורה או חורבה.

שכירת עוזר מעורבת יותר מאשר שכירת דמויות מנחה אחרות. ראשית, דמות השחקן חייבת לפרסם מודעה לעוזר, בדרך כלל על ידי שכירת כרוז, תליית מודעות במקומות ציבוריים, או בקשה (ואולי תשלום) לדמויות מנחה כמו בעלי פונדקים או בעלי מסבאות כדי שיפנו עוזרים פוטנציאליים לדמות השחקן. זה תלוי במנחה להחליט מה יש לעשות, ועד כמה פעילויות אלו מצליחות.

אם דמות השחקן מצליחה, דמות מנחה אחת או יותר יופיעו להתראיין. המנחה צריכה לשחק את הראיון עם השחקן, ולאחר שכל ההצעות ניתנו וכל השאלות נשאלו, יש לבצע גלגול תגובה. כדי לבדוק את תגובת העוזר הפוטנציאלי, המנחה מגלגלת 2d6 ומוסיפה את הבונוס לכריזמה של דמות השחקן. בנוסף, המנחה עשויה להחיל כל התאמות שהיא מרגישה שהן מתאימות (בונוס של +1 עבור תשלום גבוה מהממוצע או הצעת חפץ קסום כמו **חרב +1**, או עונש אם דמות השחקן מציעה תנאים גרועים). הגלגול נקרא כדלקמן:

```{ojs}

import {generalTableSelect2, highlightTableRowRet} from "../custom.js"

viewof reaction = Inputs.button("גלגל בטבלה", {value: 0, reduce: () => highlightTableRowRet("#reaction-roll", generalTableSelect2([2,6,0],[[2,2],[3,5],[6,8],[9,11],[12,12]]))})
md`2d6: ${reaction}`
```

:::{#reaction-roll}

| **גלגול קוביות מותאם** | **תוצאה** |
|---|---|
| 2 או פחות | סירוב, -1 על גלגולים נוספים |
| 3-5 | סירוב |
| 6-8 | נסה שוב |
| 9-11 | קבלה |
| 12 או יותר | קבלה, +1 לנאמנות |

:::

**סירוב, -1 על גלגולים נוספים** פירושו שכל גלגולי התגובה הנוספים שנעשו כלפי דמות השחקן בעיירה או באזור הנתון יהיו בעונש של -1 בשל מילים לא נעימות שנאמרו על ידי דמות המנחה לחבריו. אם דמות השחקן מנסה שוב בעיירה אחרת, העונש לא חל.

אם תוצאה של **נסה שוב** מתגלגלת, העוזר הפוטנציאלי מהסס, וזקוק לשכנוע נוסף; דמות השחקן חייבת "להמתיק" את העסקה כדי לקבל גלגול נוסף, כמו על ידי הצעת תשלום נוסף, חפץ קסום וכו'. אם דמות השחקן לא מציעה הצעה טובה יותר, יש להתייחס ל**נסה שוב** כתוצאה של **סירוב**.

**נאמנות:** לכל העוזרים יש ערך נאמנות, שהוא בדרך כלל 7 בתוספת הבונוס לכריזמה של המעסיק (או העונש). ערך הנאמנות משמש בדיוק כמו ערך המורל של מפלצות או שכירי חרב.

אם גלגול בדיקת נאמנות שנעשה בקרב הוא 2 טבעי, הנאמנות של העוזר עולה ב-+1 נקודה. שימו לב שנאמנות של 12 היא פנטית... העוזר יעשה כמעט כל דבר שדמות השחקן מבקשת, ולעולם לא יברח בקרב. עם זאת, המנחה עדיין צריכה להחיל עונשים כאשר דמות השחקן מורה לעוזר לעשות משהו שנראה מאוד מסוכן, מה שהופך בדיקה כושלת לאפשרית.

בנוסף, המנחה צריכה לגלגל בדיקת נאמנות עבור כל עוזר בסוף כל הרפתקה, לאחר חלוקת האוצר, כדי לקבוע אם העוזר יישאר עם דמות השחקן. המנחה עשויה להחיל התאמות לגלגול זה, כנראה לא יותר משתי נקודות פלוס או מינוס, אם העוזר מתוגמל באופן מיוחד טוב או גרוע.

**מספר מקסימלי של עוזרים:** דמות שחקן יכולה לשכור לכל היותר 4 עוזרים, מותאם על ידי הבונוס או העונש לכריזמה של הדמות. כל ניסיונות לשכור יותר ממספר זה של עוזרים ייתקלו בסירובים אוטומטיים.

**דרגת העוזרים:** בדרך כלל, עוזרים פוטנציאליים יהיו בדרגה של חצי מהדרגה של המעסיק (או פחות). כך, דמות בדרגה ראשונה לא יכולה לשכור עוזרים, דמויות בדרגה שנייה יכולות לשכור רק דמויות בדרגה ראשונה, וכן הלאה. כמובן, אין דרך לעוזרים לדעת ישירות את הדרגה של המעסיק, ולא למעסיק לדעת את הדרגה של העוזר הפוטנציאלי; אבל המנחה בדרך כלל צריכה לאכוף כלל זה למטרות איזון המשחק. לא צריך להיות מפתיע שדמויות בדרגה ראשונה לא יכולות לשכור עוזרים, שכן אין להן מוניטין עדיין.

**ניסיון לעוזרים:** בניגוד לדמויות מנחה אחרות שנשכרות, עוזרים כן צוברים ניסיון כמו הרפתקנים אחרים; עם זאת, מכיוון שהם תחת פיקוד של דמות שחקן, רק מחצית מנקודות הניסיון מוקצה לכל עוזר. ראו [התקדמות דמות](advancement.qmd#advancement).

### מומחים

מומחים הם דמויות מנחה שניתן לשכור על ידי דמויות שחקן לביצוע משימות שונות. מומחים לא יוצאים להרפתקאות או מסכנים את חייהם בלחימה במפלצות, נטרול מלכודות או כל אחד מהדברים המסוכנים האחרים שדמויות שחקן ועוזרים עשויים לעשות. במקום זאת, מומחים מבצעים שירותים שדמויות השחקן בדרך כלל לא יכולות לבצע בעצמן, כמו תכנון והקמת טירות, אילוף חיות או תפעול ספינות.

דמות שחקן מוגבלת במספר המומחים שהיא יכולה לשכור רק על ידי כמות הכסף שהם עולים; כריזמה לא משפיעה על כך.

**אלכימאי:** *1,000 מטבעות זהב לחודש.* דמויות אלו נשכרות בדרך כלל עבור אחת משתי סיבות: להכין שיקויים, או לסייע לקוסם במחקר קסום.

אלכימאי יכול לייצר שיקוי, בהינתן החומרים הנדרשים ודוגמה או נוסחה כתובה לשיקוי, באותו זמן ובאותו עלות כמו קוסם. הם יכולים גם לחקור שיקויים חדשים, אך בעלות כפולה בזמן ובחומרים כמו קוסם. עיינו בכללים עבור [מחקר קסום](gm01.qmd#magical-research) לפרטים.

לחילופין, קוסם המבקש ליצור חפצי קסם מסוימים עשוי להעסיק אלכימאי כעוזר. במקרה זה, האלכימאי מוסיף 15% לסיכוי ההצלחה של הקוסם.

**מאלף חיות:** *250 עד 750 מטבעות זהב לחודש.* דמויות המבקשות לרכוב על היפוגריפים או להעסיק קופים טורפים כשומרים יזדקקו לעזרתו של מאלף חיות. העלות הנמוכה ביותר לעיל היא עבור מאלף חיות ממוצע, המסוגל לאלף סוג אחד של חיה "רגילה" כמו קופים טורפים; אלו המסוגלים לאלף יותר מסוג אחד של חיה, או לאלף יצורים מפלצתיים כמו היפוגריפים, יקרים יותר לשכירה. המנחה חייבת להחליט כמה זמן לוקח לאלף חיה; במקרים מסוימים, אילוף חיות עשוי לקחת שנים, עובדה שדמויות השחקן עשויות למצוא לא נוחה כמו גם יקרה. מאלף חיות אחד יכול לאלף ולנהל לא יותר מ-5 חיות בו זמנית, אם כי ברוב המקרים ברגע שחיה מאולפת במלואה, אם היא מוכנסת לשירות מיד, לא יהיה צורך במאלף החיות לטפל בה יותר.

**שריונאי (או נפח נשק):** *100 עד 500 מטבעות זהב לחודש.* דמויות השוכרות שכירי חרב, או שיש להן עוקבים חמושים וממוגנים לטפל בהם, יזדקקו לשירותיו של שריונאי. באופן כללי, עבור כל 50 לוחמים מועסקים, נדרש שריונאי אחד לטפל בציוד שלהם. הציוד של השריונאי לא כלול בעלויות הניתנות לעיל, אך עלות תחזוקת שוליותיו כלולה; לרוב דמויות אלו יהיו 1d4 שוליות המסייעים.

שריונאים או נפחי נשק במחיר גבוה יותר עשויים להישכר לסיוע בייצור נשק או שריונות קסומים; במקרה זה, הדמות שנשכרה תהיה מומחה בייצור סוג מסוים של שריון או נשק, ותדרוש מחיר גבוה יותר (כמוצג לעיל). דמויות אלו לעיתים רחוקות יסכימו לבצע את העבודה השגרתית של תחזוקת נשק ושריון עבור יחידה צבאית.

**מהנדס:** *750 מטבעות זהב לחודש.* כל דמות שחקן המבקשת לבנות מבצר, ספינה או כל מבנה רגיל אחר תזדקק למהנדס. פרויקטים גדולים עשויים לדרוש מספר מהנדסים, לפי שיקול דעתה של המנחה.

**מלומד:** *1,500 מטבעות זהב לחודש.* מלומדים הם מומחים בידע עתיק ונדיר. לרבים מהמלומדים יש תחומי עניין מסוימים, מוגבלים או ממוקדים מאוד (לדוגמה, "הגירות האלפים בעידן השני"), אך גם אלו ידעו או תהיה להם גישה להרבה עובדות. העלות המצוינת היא המינימום הנדרש לתחזוקת מלומד עם ספרייתו, אוספיו וכו'. אם הפטרון של המלומד שואל שאלה קשה, עשויות להיות עלויות נוספות עבור חומרים או מחקר כדי לענות עליה.

**צוות ספינה:** *מיוחד.* צוות לכלי שיט ימי כולל מספר סוגי דמויות. לכל הפחות, נדרש צוות של מלחים וקפטן; חותרים יידרשו על סיפון גליאות, ונווט נדרש על סיפון ספינות היוצאות מטווח ראייה מהחוף.

העלויות לחודש עבור כל סוג של דמות ניתנות להלן:

| סוג מלח | עלות   |
|-------------|--------|
| קפטן     | 300 מטבעות זהב |
| נווט   | 200 מטבעות זהב |
| מלח      | 10 מטבעות זהב  |
| חותר       | 3 מטבעות זהב   |

באופן כללי, כל הדמויות הללו הם אנשים רגילים, ואינם ממוגנים; הם בדרך כלל יהיו חמושים באלות, פגיונות או חרבות קצרות. דמויות שחקן עם רקע מתאים עשויות לשמש כקפטן, אך אלא אם כן יש להן ניסיון כקפטן ספינה, הן יתקשו לזכות בכבוד מהמלחים הרגילים (הורידו את המורל של מלחים רגילים אלו ב-2 אם הם מונהגים על ידי קפטן חסר ניסיון).

### שכירי חרב

שכירי חרב הם לוחמים שכירים. הם נשכרים בדרך כלל ביחידות קטנות כמו מחלקות: 32 עד 48 לוחמים, מחולקים לשניים עד ארבעה כיתות של חיילים; כל כיתה מונהגת על ידי רב-טוראי, בעוד שהמחלקה מונהגת על ידי סגן בתוספת סמל. מחלקות מצטרפות יחד לחברות, שכל אחת מהן מורכבת בדרך כלל משתיים עד חמש מחלקות ומונהגות על ידי קפטן עם סמל כעוזרו (נקרא **סמל ראשון**).

מכיוון ששכירי חרב הם כמעט תמיד חיילים ותיקים, שכיר החרב הממוצע הוא לוחם בדרגה 1; 10% מהרב-טוראים ו-50% מהסמלים הם בדרגה 2. סגן שכיר חרב יהיה בדרך כלל בדרגה 2, בעוד קפטן יהיה בדרגה 2 עד 4 והסמל הראשון שלו יהיה בדרגה 2 או 3. יחידות שכירי חרב גדולות יותר יהיו בדרך כלל מעבר להישג ידן של דמויות שחקן עד שהן יגיעו לדרגות גבוהות למדי, והן נשארות לפרטי המנחה.

שכירי חרב כמעט אף פעם לא ייכנסו למבוך, מאורה או חורבה, לפחות עד שהיא נוקתה לחלוטין. במקום זאת, הם משמשים במערכות צבאיות חיצונית; דמויות שחקן בדרגות גבוהות עשויות לשכור שכירי חרב להגן או לעזור להגן על טירותיהן או אחוזותיהן האחרות.

שכירי חרב המתגוררים במבצר של דמות שחקן דורשים 60 מטר מרובע כל אחד אך עולים 25% פחות לחודש, מכיוון שזה מכוסה על ידי מגוריהם ומזונם. (שכירי חרב אלפים, לעומת זאת, דורשים 150 מטר מרובע כל אחד כדי להפחית את שכרם, מכיוון שהם דורשים תנאי מחיה טובים יותר.) ראו את סעיף **מבצר** לפרטים נוספים.

סטטיסטיקות ניתנות להלן עבור סוגי שכירי החרב הנפוצים ביותר; הסטטיסטיקות הן עבור דמויות בדרגה ראשונה, ויש להתאים אותן כאשר מצוינות דמויות בדרגות גבוהות יותר (כפי שניתן לעיל). במיוחד, יש להכפיל את העלות הנתונה של כל שכיר חרב בדרגתו. העלויות המפורטות הן במטבעות זהב לחודש.

:::{.column-page-right}

| סוג שכיר חרב           | עלות | ציוד                                           | מורל      |  
|------------------------|:----:|:----------------------------------------------|:---------:|
| רגלי קל, אדם           | 2    | שריון עור, מגן וחרב ארוכה                     | 8         |
| רגלי קל, אלף           | 8    | שריון עור, מגן וחרב ארוכה                     | 8         |
| רגלי קל, אורק          | 1    | שריון עור וחנית                               | 7         |
| רגלי כבד, אדם          | 3    | שריון שרשרת, מגן וחרב ארוכה                   | 8         |
| רגלי כבד, גמד          | 6    | שריון שרשרת, מגן וחרב קצרה                    | 9         |
| רגלי כבד, אורק         | 2    | שריון שרשרת, מגן וחרב קצרה                    | 8         |
| קשת, אדם               | 5    | שריון עור, קשת קצרה וחרב קצרה                 | 8         |
| קשת, אלף               | 15   | שריון שרשרת, קשת קצרה וחרב קצרה               | 8         |
| קשת, אורק              | 3    | שריון עור, קשת קצרה וחרב קצרה                 | 8         |
| רובה קשת, אדם          | 5    | שריון שרשרת, רובה קשת וחרב קצרה               | 8         |
| רובה קשת, גמד          | 12   | שריון לוחות, רובה קשת וחרב קצרה               | 9         |
| קשת ארוכה, אדם         | 9    | שריון שרשרת, קשת ארוכה וחרב קצרה              | 8         |
| קשת ארוכה, אלף         | 20   | שריון שרשרת, קשת ארוכה וחרב ארוכה             | 8         |
| פרש קל, אדם            | 10   | שריון עור, מגן, רומח וחרב ארוכה               | 8         |
| פרש קל, אלף            | 22   | שריון עור, רומח, קשת קצרה וחרב ארוכה          | 8         |
| פרש בינוני, אדם        | 15   | שריון שרשרת, מגן, רומח וחרב ארוכה             | 8         |
| פרש בינוני, אלף        | 33   | שריון שרשרת, רומח, קשת קצרה וחרב ארוכה        | 9         |
| פרש כבד, אדם           | 20   | שריון לוחות, מגן, רומח וחרב ארוכה             | 8         |

::: 
