# הקדמה {.unnumbered}

**זכויות יוצרים © 2006-2026 כריס גונרמן – כל הזכויות שמורות**

**משחק התפקידים בייסיק פנטזי**: 
מהדורה רביעית, גרסה 128

כל החומרים הטקסטואליים במסמך זה, כמו גם כל המפות, התוכניות, הדיאגרמות, התרשימים והטפסים הכלולים בו, מופצים תחת תנאי **רישיון Creative Commons Attribution-ShareAlike 4.0 International License**. רוב יצירות האמנות האחרות המוצגות הן רכושם של האמנים המקוריים ונעשה בהן שימוש באישור. שימו לב שאינכם רשאים לפרסם או להפיץ עבודה זו כפי שהיא ללא אישור מהאמנים המקוריים; עליכם להסיר את כל יצירות האמנות שאינן ברישיון לפני שתעשו זאת. ניתן לצפות בטקסט המלא של הרישיון בכתובת:

https://creativecommons.org/licenses/by-sa/4.0/

חלק מהטקסט ששימש בפיתוח מסמך זה נלקח מוויקיפדיה, והיה במקור ברישיון Creative Commons Attribution-ShareAlike 3.0.

קרדיטים מתוך ה-PDF:

::: {.column-screen-inset-right}


|     |    |
|:----|:----|
| תורמים: | Ray Allen, William D. Smith, Jr., Nick Bogan, Evan Moore, Stuart Marshall, Emiliano Marchetti, Antonio Eleuteri, Luigi Castellani, Michael Hensley, Nazim N. Karaca, Arthur Reyes, Todd Roe, Jim Bobb, R. Kevin Smoot, Rachel Ghoul, Tom Hoyt, James Michael Spahn, Matt Sluis, Russ Westbrook, Martin Serena, Joe Ludlum, Aaron G. Motta, and Gabe Fua | 
| איור עטיפה: | Erik Wilson |
| איורים: | Erik Wilson, Steve Zieser, Matt Finch, Dan Dalton, Luigi Castellani, Nick Bogan, Mike Hill, Kevin Cook, Sean Stone, Brian "Glad" Thomas, Tomas Arfert, Andy "ATOM" Taylor, Jason Braun, Martin "Wulfgarn" Siesto, Brian DeClercq, Martin Serena, Cory "Shonuff" Gelnett, Alexander Cook, Bruce Ripple, Gabe Fua, John Simcoe, LuckyCrafts, Jeremy Putnam, Francisco Chavez, William Henry Dvorak, Tony Grant Gittoes, Jose Kercado, Jody Claunch, Terance Crosby, S. Ender Thiel, Colin Richards, John Fredericks, Piotr Klimkowicz, Evan Griffiths, Hadrien Riel-Salvatore, and Benedikt Noir | 
| הגהה: | Tonya Allen, Daryl Burns, James Roberts, Serge Petitclerc, Benedict Wolf, Onno Tasler, Peter Cook, Derrick "Omote" Landwehr, Wes Brown, Troy Gravil, Garrett Rooney, K. David Ladage, James Lemon, Martin Serena, Joe Carruthers, Jonathan Nichol, Alister Fa, Joel Davis, Hadrien Riel-Salvatore, Mark Mealman, Alan Vetter, Jim Michnowicz, Timothy P. Fox, Piotr Klimkowicz, Daniel Collins, Thorin Schmidt, and feveredmonk | 
| בודקי משחק: | Taylor Gonnerman, Alan Jett, Mike Brantner, Steve Zieser, Allan Zieser, Jonathon Foster, Adam Young, Michael Young, Jason Schmidt, Doug Wilson, Jessica Abramson, Tonya Allen, Bryan Christian, Chuck Schoonover, Natalie Schoonover, Brianna Schoonover, Jason Brentlinger, Chris Wolfmeyer, Josh Eaton, Audra Brentlinger, Tim McAfee, Ike Borden, Cody Drebenstedt, Joseph BierFauble, Emily Drebenstedt, John Lopez, Pedro Pablo Miron Pozo, Robert Odom, Sergio I. Nemirovsky, Will E. Sanders, Brian Scalise, Timothy J. Kuhn, and Jeanne Mayer Mitchell |

: {tbl-colwidths="[25,75]"}
:::

כמה כלים שכדאי לבדוק:

- [אינדקס מפלצות](monstersTab.qmd)
- [כלים אינטראקטיביים](appendix_interactive.qmd)
- [יוצר מבוכים](appendixMapmaker.qmd)


אתר זה נוצר בידי John Atom (jmhimara). כל הקוד והתוכן הייחודי שלו מופצים אף הם תחת **רישיון Creative Commons Attribution-ShareAlike 4.0 International License**.

תורגם לעברית ע"י **איתי אגמון**
