# חפצי קסם

קבעי את סוג הפריט שנמצא על ידי גלגול בטבלה הבאה:

```{ojs}

import {generalTableSelect, highlightTableRow} from "../custom.js"

viewof form = Inputs.form(
  {
    button1: Inputs.button("כלשהו", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[1,25],[26,35],[36,55],[56,85],[86,90],[91,95],[96,100]]))}),
    button2: Inputs.button("נשק או שריון", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[1,70], [71,100]]))}),
    button3: Inputs.button("כלשהו חוץ מנשק", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[-2,-1],[1,12],[13,40],[41,79],[80,86],[87,93],[94,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 15% 30% 30%;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })


```

::: {#armor-weapon-table}

| **פריט כלשהו** | **נשק או שריון** | **כל פריט מלבד נשק** | **סוג פריט** |
|----|----|----|----| 
| 01-25 | 01-70 |  | נשק |
| 26-35 | 71-00 | 01-12 | שריון |
| 36-55 |  | 13-40 | שיקוי |
| 56-85 |  | 41-79 | מגילה |
| 86-90 |  | 80-86 | טבעת |
| 91-95 |  | 87-93 | שרביט, מטה או מקל |
| 96-00 |  | 94-00 | חפצי קסם שונים |

:::

## נשקי קסם

ראשית, גלגלי d% בטבלה הבאה כדי לקבוע את סוג הנשק:

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#weapon-type-table", 
generalTableSelect([1,100,0],[[1,2],[3,9],[10,11],[12,19],[20,27],[28,31],[32,35],[36,43],[44,47],[48,59],[60,65],[66,79],[80,81],[82,83],[84,86],[87,94],[95,95],[96,96],[97,97],[98,100]]))})

```

:::{#weapon-type-table}

| **d%** | **סוג נשק** |
|----|-----|
| 01-02 | גרזן גדול |
| 03-09 | גרזן קרב |
| 10-11 | גרזן יד |
| 12-19 | קשת קצרה |
| 20-27 | חץ לקשת קצרה |
| 28-31 | קשת ארוכה |
| 32-35 | חץ לקשת ארוכה |
| 36-43 | בריח קל |
| 44-47 | בריח כבד |
| 48-59 | פגיון |
| 60-65 | חרב קצרה |
| 66-79 | חרב ארוכה |
| 80-81 | סימיטר |
| 82-83 | חרב דו-ידנית |
| 84-86 | פטיש מלחמה |
| 87-94 | אלה |
| 95 | מקבת |
| 96 | נשק מוט |
| 97 | קליע קלע |
| 98-00 | חנית |

:::

לאחר מכן, גלגלי בטבלאות תוסף הנשק. אם התוצאה מורה לגלגל בטבלת האויב המיוחד או בטבלת היכולת המיוחדת, פעלי לפי ההוראות המתאימות; בדרך כלל, אם נדרשים כמה גלגולים בטבלת היכולת המיוחדת, יש להתעלם מהגלגולים הנוספים.
```{ojs}

Inputs.form(
  {
    button1: Inputs.button("d% קרב פנים אל פנים", {value: 0, 
        reduce: () => highlightTableRow("#melee-missile-weapon", 
            generalTableSelect([1,100,0],[[1,40],[41,50],[51,55],[56,57],[58,58],[59,75],[76,85],[86,95],[96,98],[99,100]]))}),
    button2: Inputs.button("d% קליעים", {value: 0, 
        reduce: () => highlightTableRow("#melee-missile-weapon", 
            generalTableSelect([1,100,0],[[1,46],[47,58],[59,64],[-2,-1],[-2,-1],[65,82],[83,94],[-2,-1],[95,98],[99,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 30% 30% ;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })

```

:::{#melee-missile-weapon}

| **d% קרב פנים אל פנים** | **d% קליעים** | **תוסף נשק** |
|--------------|----------------|------------------------------|
| 01-40        | 01-46          | +1                           |
| 41-50        | 47-58          | +2                           |
| 51-55        | 59-64          | +3                           |
| 56-57        |                | +4                           |
| 58           |                | +5                           |
| 59-75        | 65-82          | +1, +2 נגד אויב מיוחד       |
| 76-85        | 83-94          | +1, +3 נגד אויב מיוחד       |
| 86-95        |                | גלגלי שוב + יכולת מיוחדת    |
| 96-98        | 95-98          | מקולל, -1*                   |
| 99-00        | 99-00          | מקולל, -2*                   |

:::

\* אם התקבל נשק מקולל יחד עם יכולת מיוחדת, התעלמי מגלגול היכולת המיוחדת.

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#special-enemy-table", 
generalTableSelect([1,6,0],[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]]))})

```

:::{#special-enemy-table}

| **1d6** | **אויב מיוחד** |
|---------|-------------------|
| 1       | דרקונים |
| 2       | מכושפים |
| 3       | ליקנתרופים |
| 4       | בעלי יכולת התחדשות |
| 5       | מטילי לחשים |
| 6       | אל-מתים |

:::

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#special-ability-table", 
generalTableSelect([1,20,0],[[1,9],[10,11],[12,12],[13,16],[17,19],[20,20]]))})

```

:::{#special-ability-table}

| **1d20** | **יכולת מיוחדת** |
|----|----|
| 01-09 | מטיל את הלחש אור לפי פקודה |
| 10-11 | הקסמת איש |
| 12 | מנקז אנרגיה |
| 13-16 | להבות לפי פקודה |
| 17-19 | איתור עצמים |
| 20 | משאלות |

:::

## שריון קסום

קבעי את הסוג ואת התוסף של כל פריט שריון קסום באמצעות הטבלאות שלהלן.

```{ojs}

Inputs.form(
  {
    button1: Inputs.button("d% סוג שריון", {value: 0, 
        reduce: () => highlightTableRow("#magic-armor-table", 
            generalTableSelect([1,100,0],[[1,9],[10,28],[29,43],[44,100]]))}),
    button2: Inputs.button("d% תוסף שריון", {value: 0, 
        reduce: () => highlightTableRow("#magic-armor-table", 
            generalTableSelect([1,100,0],[[1,50],[51,80],[81,90],[91,95],[92,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 40% 40% ;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })

```

:::{#magic-armor-table}

| **d%** | **סוג שריון** | **d%** | **תוסף שריון** |
|--------|----------------|--------|------------------|
| 01-09  | שריון עור | 01-50  | +1 |
| 10-28  | שריון שרשראות | 51-80  | +2 |
| 29-43  | שריון לוחות | 81-90  | +3 |
| 44-00  | מגן | 91-95  | מקולל \* |
|        |      | 96-00  | מקולל, דירוג שריון 11 \*\* |

:::

\* אם התקבל שריון מקולל, גלגלי שוב והפכי את התוסף (למשל, -1 במקום +1).

\*\* לשריון זה דירוג שריון 11, אך בבדיקה הוא נראה כשריון +1.

## שיקויים

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#potions-random-table", 
generalTableSelect([1,100,0],[[1,3], [4,6], [7,8], [9,11], [12,13], [14,16], [17,19], [20,22], [23,25], [26,32], [33,35], [36,39], [40,43], [44,47], [48,51], [52,55], [56,59], [60,63], [64,68], [69,72], [73,76], [77,80], [81,84], [85,86], [87,89], [90,97], [98,100]]))})

```

:::{#potions-random-table}

| **d%** | **סוג** |
|--------|---------|
| 01-03  | שמיעה על חושית |
| 04-06  | ראייה על חושית |
| 07-08  | חסינות לקור |
| 09-11  | שליטה בחיה |
| 12-13  | שליטה בדרקון |
| 14-16  | שליטה בענק |
| 17-19  | שליטה באדם |
| 20-22  | שליטה בצמח |
| 23-25  | שליטה באל-מת |
| 26-32  | אשליה |
| 33-35  | הקטנה |
| 36-39  | חסינות לאש |
| 40-43  | מעוף |
| 44-47  | צורה גזית |
| 48-51  | כוחו של ענק |
| 52-55  | גדילה |
| 56-59  | ריפוי |
| 60-63  | גבורה |
| 64-68  | היעלמות מעין |
| 69-72  | אי-פגיעות |
| 73-76  | ריחוף |
| 77-80  | אריכות ימים |
| 81-84  | תע"ח |
| 85-86  | רעל |
| 87-89  | שינוי עצמי |
| 90-97  | מהירות |
| 98-00  | מציאת אוצר |

:::

## מגילות

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#scrolls-table", 
generalTableSelect([1,100,0],[[1,3], [4,6], [7,8], [9,9 ], [10,15], [16,20], [21,25], [26,29], [30,32], [33,34], [35,35  ], [36,40], [41,46], [47,56], [57,61], [62,75], [76,85], [86,89], [90,92], [93,100]]))})

```

:::{#scrolls-table}

| **d%** | **סוג כללי** |
|----|----|
| 01-03 | מגילת לחשי כוהן (לחש 1) |
| 04-06 | מגילת לחשי כוהן (2 לחשים) |
| 07-08 | מגילת לחשי כוהן (3 לחשים) |
| 09 | מגילת לחשי כוהן (4 לחשים) |
| 10-15 | מגילת לחשי קוסם (לחש 1) |
| 16-20 | מגילת לחשי קוסם (2 לחשים) |
| 21-25 | מגילת לחשי קוסם (3 לחשים) |
| 26-29 | מגילת לחשי קוסם (4 לחשים) |
| 30-32 | מגילת לחשי קוסם (5 לחשים) |
| 33-34 | מגילת לחשי קוסם (6 לחשים) |
| 35 | מגילת לחשי קוסם (7 לחשים) |
| 36-40 | מגילה מקוללת |
| 41-46 | הגנה מיסודנים |
| 47-56 | הגנה מליקנתרופים |
| 57-61 | הגנה מקסם |
| 62-75 | הגנה מאל-מתים |
| 76-85 | מפה לאוצר מסוג A |
| 86-89 | מפה לאוצר מסוג E |
| 90-92 | מפה לאוצר מסוג G |
| 93-00 | מפה ל־1d4 חפצי קסם |

:::

## טבעות

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#rings-table", 
generalTableSelect([1,100,0],[[1,6],[7,12],[13,19],[20,30],[31,33],[34,44],[45,57],[58,66],[67,70],[71,71],[72,73],[74,75],[76,81],[82,83],[84,90],[91,97],[98,98],[99,100]]))})

```

:::{#rings-table}

| **d%** | **סוג** |
|----|----|
| 01-06 | שליטה בחיה |
| 07-12 | שליטה באדם |
| 13-19 | שליטה בצמח |
| 20-30 | אשליה |
| 31-33 | זימון ג'יני |
| 34-44 | חסינות לאש |
| 45-57 | היעלמות מעין |
| 58-66 | הגנה +1 |
| 67-70 | הגנה +2 |
| 71 | הגנה +3 |
| 72-73 | התחדשות |
| 74-75 | אחסון לחשים |
| 76-81 | החזרת לחשים |
| 82-83 | טלקינזיס |
| 84-90 | הליכה על מים |
| 91-97 | חולשה |
| 98 | משאלות |
| 99-00 | ראיית רנטגן |

:::

## שרביטים, מטות ומקלות

```{ojs}

Inputs.button("גלגלי בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#wands-table", 
generalTableSelect([1,100,0],[[1,8],[9,13],[14,17],[18,28],[29,30],[31,34],[35,35],[36,40],[41,45],[46,50],[51,55],[56,60],[61,65],[66,73],[74,79],[80,84],[85,92],[93,100]]))})

```

:::{#wands-table}

| **d%** | **סוג** |
|----|----|
| 01-08 | מקל ביטול |
| 09-13 | מטה נחש |
| 14-17 | מטה פיקוד |
| 18-28 | מטה ריפוי |
| 29-30 | מטה כוח |
| 31-34 | מטה הכאה |
| 35 | מטה קוסמות |
| 36-40 | שרביט קור |
| 41-45 | שרביט גילוי אויבים |
| 46-50 | שרביט פחד |
| 51-55 | שרביט כדורי אש |
| 56-60 | שרביט אשליה |
| 61-65 | שרביט חזיזי ברק |
| 66-73 | שרביט גילוי קסם |
| 74-79 | שרביט שיתוק |
| 80-84 | שרביט שינוי צורה |
| 85-92 | שרביט גילוי דלתות סודיות |
| 93-00 | שרביט גילוי מלכודות |

:::

## חפצי קסם שונים

תתי-טבלאות אפקטים
d%
תת-טבלה
01-57
תת-טבלת אפקטים 1
58-00
תת-טבלת אפקטים 2

### **תתי-טבלאות אפקטים**

| d%    | תת-טבלה          |
|-------|-------------------|
| 01-57 | תת-טבלת אפקטים 1 |
| 58-00 | תת-טבלת אפקטים 2 |

### **תת-טבלת אפקטים 1**

| d%    | אפקט             | צורה |
|-------|--------------------|------|
| 01    | פיצוץ              | G    |
| 02-05 | היטמעות            | F    |
| 06-13 | חסינות לקור        | F    |
| 14-17 | הבנה               | E    |
| 18-22 | שליטה בחיה         | C    |
| 23-29 | שליטה באדם         | C    |
| 30-35 | שליטה בצמח         | C    |
| 36-37 | אומץ               | G    |
| 38-40 | הטעיה              | F    |
| 41-52 | אשליה              | A    |
| 53-55 | זימון ג'יני        | C    |
| 56    | אבדון              | G    |
| 57-67 | חסינות לאש         | F    |
| 68-80 | היעלמות מעין       | F    |
| 81-85 | ריחוף              | B    |
| 86-95 | תע"ח               | C    |
| 96-97 | בהלה              | G    |
| 98-00 | ראייה חודרת        | D    |

### **תת-טבלת אפקטים 2**

| d%    | אפקט                         | צורה |
|-------|-------------------------------|------|
| 01-07 | הגנה +1                      | F    |
| 08-10 | הגנה +2                      | F    |
| 11    | הגנה +3                      | F    |
| 12-14 | הגנה מניקוז אנרגיה           | F    |
| 15-20 | הגנה מצפייה מרחוק            | F    |
| 21-23 | התחדשות                      | C    |
| 24-29 | צפייה מרחוק                  | H    |
| 30-32 | צפייה מרחוק, משופרת          | H    |
| 33-39 | מהירות                       | B    |
| 40-42 | אחסון לחשים                  | C    |
| 43-50 | החזרת לחשים                  | F    |
| 51-69 | תנועה חרישית                 | B    |
| 70-72 | טלקינזיס                     | C    |
| 73-74 | טלפתיה                       | C    |
| 75-76 | שיעתוק                       | C    |
| 77-78 | ראיית אמת                    | D    |
| 79-88 | הליכה על מים                 | B    |
| 89-99 | חולשה                        | C    |
| 00    | משאלות                       | C    |

גלגלי בטבלה הראשונה למעלה כדי לבחור תת-טבלה, ואז
גלגלי שוב בתת-הטבלה שנבחרה כדי לקבוע את
האפקט המדויק. לבסוף, גלגלי בעמודה המצוינת של
טבלת הצורה כדי לקבוע את הצורה הפיזית של הפריט.

### צורת הפריט

::: {.table-responsive .column-screen-right}

|                     | A     | B     | C     | D     | E     | F     | G     | H     |
|---------------------|-------|-------|-------|-------|-------|-------|-------|-------|
| פעמון (או פעמונית)  | 01-02 |       |       |       |       |       | 01-17 |       |
| חגורה או אבנט       | 03-05 |       |       |       |       | 01-07 |       |       |
| מגפיים              | 06-13 | 01-25 |       |       |       |       |       |       |
| קערה                | 14-15 |       |       |       |       |       |       | 01-17 |
| גלימה               | 16-28 |       |       |       |       | 08-38 |       |       |
| כדור בדולח או כדור  | 29-31 |       |       |       |       |       |       | 18-67 |
| תופים               | 32-33 |       |       |       |       |       | 18-50 |       |
| קסדה                | 34-38 |       |       |       | 01-40 |       |       |       |
| קרן                 | 39-43 |       |       |       |       |       | 51-00 |       |
| עדשה                | 44-46 |       |       | 01-17 |       |       |       |       |
| מראה                | 47-49 |       |       | 18-17 |       |       |       | 68-00 |
| תליון               | 50-67 | 26-50 | 01-40 | 18-50 | 41-80 | 39-50 |       |       |
| טבעת                | 68-00 | 51-00 | 41-00 | 51-00 | 81-00 | 51-00 |       |       |

:::

### פריטים נדירים

| d%    | סוג                                      |
|-------|-------------------------------------------|
| 01-05 | שק טורף                                  |
| 06-20 | שק אחסון                                 |
| 21-32 | מגפי מסע וקפיצה                          |
| 33-47 | מטאטא מעופף                              |
| 48-57 | מכשיר לזימון יסודנים (ראו למטה)         |
| 58-59 | בקבוק עפרית                              |
| 60-64 | שטיח מעופף                               |
| 65-81 | כפפות כוחו של עוג                        |
| 82-86 | אבנט כוחו של ענק                         |
| 87-88 | מראת כליאה                               |
| 89-00 | חבל טיפוס                                |

## מכשירים לזימון יסודנים

עייני במידע על [יסודנים](monstersAll.qmd#elemental) לפני שתבחרי באקראי אחד מהפריטים הללו, משום שייתכן שלא תרצי לאפשר את כל סוגי היסודנים בקמפיין שלך.

| 1d8 | סוג                                      |
|-----|-------------------------------------------|
| 1   | קערה לזימון יסודני מים                   |
| 2   | אגן אש לזימון יסודני אש                  |
| 3   | מבער קטורת לזימון יסודני אוויר           |
| 4   | כור היתוך לזימון יסודני מתכת             |
| 5   | פטיש עץ לזימון יסודני עץ                 |
| 6   | לוח שיש לזימון יסודני קור                |
| 7   | מקל לזימון יסודני ברק                    |
| 8   | אבן לזימון יסודני אדמה                   |


## הסבר על חפצי קסם

### שימוש בחפצי קסם

כדי להשתמש בחפץ קסם יש להפעיל אותו, אף שלעיתים ההפעלה פירושה פשוט לענוד טבעת על האצבע. חפצים מסוימים, לאחר שלובשים או עונדים אותם, פועלים באופן מתמיד.

חפצים רבים מופעלים פשוט באמצעות שימוש בהם. לדוגמה, דמות צריכה לשתות שיקוי, להניף חרב, לחצוץ באמצעות מגן כדי להדוף מכה בקרב, לענוד טבעת או ללבוש גלימה. הפעלתם של חפצים אלה היא בדרך כלל ישירה ומובנת מאליה. אין פירוש הדבר שאם השתמשת בחפץ כזה, אתה יודע אוטומטית מה הוא מסוגל לעשות. עליך לדעת (או לפחות לשער) מה החפץ מסוגל לעשות, ולאחר מכן להשתמש בו כדי להפעיל אותו, אלא אם התועלת ממנו מתקבלת אוטומטית, כגון משתיית שיקוי או מהנפת חרב.

אם שיטת ההפעלה אינה מצוינת בתיאור חפץ הקסם ואינה משתמעת מטבעו, הניחי שנדרשת מילת פקודה כדי להפעילו. הפעלה באמצעות מילת פקודה פירושה שדמות אומרת את המילה והחפץ מופעל. אין צורך בידע מיוחד נוסף.

מילת פקודה יכולה להיות מילה אמיתית, אך במקרה כזה המחזיק בחפץ מסתכן בהפעלתו בשוגג כאשר הוא אומר את המילה בשיחה רגילה. לעיתים קרובות יותר, מילת הפקודה היא מילה חסרת משמעות לכאורה, או מילה או ביטוי משפה עתיקה שאינה בשימוש עוד. שימי לב שבחפצי קסם רבים יש לאחוז ביד, או לטפל בהם או לענוד אותם בדרך מיוחדת, כדי להשתמש בהם; הסיכון להפעלה מקרית קטן יותר בחפצים כאלה.

לימוד מילת הפקודה של חפץ עשוי להיות קל (לעיתים המילה חקוקה על החפץ עצמו), או קשה ולדרוש את שירותיו של קוסם רב-עוצמה או מלומד, או אמצעי גילוי אחר.

רק הדמות המחזיקה בחפץ קסם או עונדת אותו רשאית להפעילו. דמות שפיה נסתם או שהושתקה אינה יכולה להפעיל חפץ קסם הדורש מילת פקודה.

כאשר מתגלה פריט שריון, פריט לבוש או תכשיט קסום (כולל טבעת), הגודל אינו בדרך כלל בעיה. פריטים כאלה מתאימים את עצמם באורח קסום ללובשים קטנים כבני-מחצית ועד גדולים כבני אדם. אפקט זה נקרא **התאמה**. המנחה רשאית ליצור פריטים "פרימיטיביים" חסרי כוח זה אם תרצה בכך.

בדרך כלל ניתן ללבוש, לענוד או לשאת רק חפץ קסם אחד מכל סוג בכל זמן נתון. לדוגמה, דמות יכולה בדרך כלל ללבוש רק חליפת שריון אחת, לענוד מחרוזת אחת ולשאת מגן אחד בכל פעם. במקרה של טבעות, דמות רשאית לענוד טבעת קסומה אחת בכל יד. אם דמות לובשת או עונדת יותר פריטים מסוג מסוים מכפי שנהוג או מעשי, הפריטים בדרך כלל לא יפעלו בשל הפרעה הדדית; לדוגמה, ענידת שתי טבעות על אותה יד תגרום בדרך כלל לכך ששתיהן לא יפעלו. **עם זאת, שימי לב** שלא ניתן להשתמש במגבלה זו כדי להשבית חפצי קסם מקוללים. לדוגמה, ענידת טבעת מקוללת תמנע ענידה ושימוש בטבעת קסומה אחרת באותה יד, אך ענידת טבעת קסומה שנייה לא תסיר את הקללה.

### נשקים קסומים

נשקים קסומים נוצרים עם מגוון כוחות ובדרך כלל מסייעים לאוחז בהם בקרב. התוסף של נשק קסום חל על כל גלגולי ההתקפה והנזק המתבצעים באמצעותו.

**מטיל אור לפי פקודה:** בשליפת הנשק ובאמירת מילת פקודה, האוחז בו רשאי לגרום לו לזהור; לאחר מכן הוא מפיץ אור ברדיוס זהה לזה של הלחש **אור**. החזרת הנשק לנדן, הנחתו או אמירת מילת הפקודה שוב מבטלות את האפקט. ניתן להשתמש בכוח זה ללא הגבלה.

**הקסמת איש:** כוח זה מאפשר לאוחז להטיל **הקסמת איש** פעם ביום, כאילו הטיל את הלחש קוסם בדרגה 8, באמצעות הנפת הנשק, אמירת מילת פקודה ומבט ביצור המטרה. (אין צורך שיצור המטרה ייצור קשר עין עם האוחז.) יצור המטרה זכאי לגלגולי הצלה כפי שמתואר בתיאור הלחש.

**מנקז אנרגיה:** נשק בעל כוח זה מנקז דרגה אחת של אנרגיית חיים בפגיעה, כמתואר תחת **ניקוז אנרגיה** בפרק **מפגשי קרב**; ניתן לנקז עד 2d4 דרגות, ולאחר מכן הנשק מאבד כוח זה אך שומר על יתר האפקטים והתוספים הקסומים שלו.

**להבות לפי פקודה:** כאשר ניתנת הפקודה, הנשק מתעטף באש. האש אינה פוגעת באוחז. האפקט נמשך עד שניתנת הפקודה שוב, או עד שהנשק מושמט או מוחזר לנדן. בעת שהוא בוער, כל נזק שהנשק גורם נחשב לנזק אש, ובעת לחימה בטרולים, טריאנטים וביצורים אחרים הפגיעים במיוחד לאש מתווסף לנזק תוסף +1 נוסף (בנוסף לתוסף הרגיל של הנשק). הנשק מפיץ אור ובוער כלפיד.

**איתור עצמים:** כוח זה מאפשר לאוחז להטיל את הלחש **איתור עצם** פעם ביום, כאילו הטיל אותו קוסם בדרגה 8.

**אויב מיוחד:** נשקים אלה נוצרו כדי להילחם בסוג מסוים של יצור, כפי שנקבע בטבלת היכולת המיוחדת. בעת שימוש נגד אותו אויב, התוסף השני המצוין חל במקום הראשון; כך, חרב +1, +3 נגד אל-מתים מעניקה +1 לגלגולי התקפה ונזק נגד חולדות ענקיות, אך +3 לגלגולי התקפה ונזק נגד זומבים.

**משאלות:** נשקים בעלי כוח זה יכולים להעניק 1d4 משאלות. המנחה חייבת להכריע בכל משאלה, והנחיות לכך מופיעות בפרק **המנחה**. לאחר שכל המשאלות מומשו, הנשק מאבד כוח זה אך שומר על יתר תוספיו וכוחותיו.

**נשקים מקוללים** גורמים לאוחז בהם מחסר לגלגולי ההתקפה, כפי שנקבע בטבלת תוסף הנשק. הקללה מונעת מן הדמות המקוללת להיפטר מהנשק. הקללה יכולה ללבוש אחת משתי צורות: אובססיה או ייסור. המנחה רשאית לבחור באיזו מהן להשתמש.

**אובססיה:** ללא קשר לחומרת המחסר, הדמות האוחזת בנשק תאמין שהמחסר הוא למעשה תוסף ותסרב להשתמש בכל נשק אחר בקרב. רק הלחש **הסרת קללה** יכול לשחרר דמות מנשק כזה; אולם מכיוון שהדמות מאמינה שזהו הנשק הקסום הטוב ביותר אי פעם, היא זכאית לגלגול הצלה נגד לחשים כדי להתנגד.

**ייסור:** הדמות יודעת שהנשק מקולל ברגע שהיא משתמשת בו בקרב; אולם כל ניסיון להשליך אותו נכשל, משום שהנשק מופיע באורח קסום שוב בידה בכל פעם שהיא מנסה לשלוף נשק אחר. במקרה זה, הלחש **הסרת קללה** הדרוש לשחרור הדמות מהנשק יפעל ללא התנגדות (כלומר, ללא גלגול הצלה).

### שריון קסום

שריון קסום (כולל מגנים) מעניק ללובש הגנה קסומה משופרת. בדרך כלל, שריון קסום מעניק את דירוג השריון הרגיל לסוגו, בתוספת תוסף השריון הקסום, כפי שנקבע בטבלת השריון הקסום; לדוגמה, שריון לוחות +2 מעניק דירוג שריון 19.

ישנם שני סוגים של **שריון מקולל**: שריון מקולל -1 ושריון מקולל עם דירוג שריון 11. דירוג השריון של הסוג הראשון מופחת בהתאם למחסר שהתקבל; לדוגמה, שריון לוחות -1 מעניק דירוג שריון 16. הסוג השני גרוע בהרבה: ללא קשר לסוג השריון, הוא מעניק דירוג שריון 11 בלבד. תוספים מזריזות וממגן עדיין חלים.

לא ניתן להסיר שריון מקולל מהלובש לאחר שהקללה הוכחה, כלומר לאחר שהלובש נפגע בקרב. לאחר שהקללה נכנסה לתוקף, רק הלחש **הסרת קללה**, או קסם רב-עוצמה יותר (כגון משאלה), יאפשר ללובש להסיר את השריון. השריון יתגלה כקסום, כמו כל שריון קסום אחר; לא ניתן לגלות את הקללה בשום אמצעי מלבד לבישת השריון בקרב.

### שיקויים

שיקוי הוא מרקחת בעלת אפקט דמוי-לחש, המשפיע רק על השותה. אלא אם צוין אחרת, שיקוי מעניק את יתרונותיו למשך 1d6+6 תורות (גם אם משכו של לחש קשור ארוך או קצר יותר).

**שמיעה על חושית:** שיקוי זה מאפשר לשותה לשמוע קולות באזור אחר באמצעות אוזניו של יצור חי באותו אזור, במרחק של עד 18 מטרים. מלבד זאת, אפקט זה פועל בדיוק כמו הלחש **ראייה על חושית**.

**ראייה על חושית:** שיקוי זה מעניק לשותה את האפקט של הלחש **ראייה על חושית**.

**חסינות לקור:** שיקוי זה מעניק לשותה את כוחו של הלחש **חסינות לקור**.

**שליטה בחיה:** שיקוי זה פועל כמו שיקוי **שליטה באדם**, אך משפיע רק על חיות רגילות שאינן קסומות.

**שליטה בדרקון:** שיקוי זה פועל כמו שיקוי **שליטה באדם**, אך משפיע רק על דרקונים.

**שליטה בענק:** שיקוי זה פועל כמו שיקוי **שליטה באדם**, אך משפיע רק על ענקים.

**שליטה באדם:** שיקוי זה מאפשר לשותה להקסים אדם, דמוי-אדם או הומנואיד באמצעות מבט בו. האפקט פועל כמו הלחש **הקסמת איש**. אם היצור מתנגד להקסמה, השותה רשאי לנסות להקסים עד 2 מטרות נוספות לפני שכוחו של השיקוי מתכלה.

**שליטה בצמח:** שיקוי זה מעניק לשותה שליטה בצמח אחד או יותר, או ביצורי צמח, בתוך שטח ריבועי שצלעו 3 מטרים, הנמצא במרחק של עד 15 מטרים. צמחים רגילים מונפשים, מקבלים קצב תנועה של 3 מטרים ומצייתים לפקודות השותה. אם ניתנת להם פקודה לתקוף, רק הצמחים הגדולים ביותר יכולים לגרום נזק ממשי; הם תוקפים עם תוסף התקפה +0 וגורמים 1d4 נקודות נזק בכל פגיעה. יצורי צמח מושפעים שנכשלים בגלגול הצלה נגד לחשים יכולים להבין את השותה ומתנהגים כאילו הם נתונים להשפעת הלחש **הקסמת מפלצת**.

**שליטה באל-מת:** שיקוי זה מעניק לשותה שליטה ב־3d6 קוביות פגיעה של אל-מתים. ניתן לגלגל גלגול הצלה נגד לחשים כדי להתנגד לאפקט. אל-מתים חסרי תבונה מצייתים לפקודות השותה במדויק; אל-מתים בעלי רצון חופשי מתנהגים כאילו הם נתונים להשפעת הלחש **הקסמת איש**.

**אמונת שווא:** שיקוי מקולל זה ייראה, אם ייבדק או ינותח, כאחד השיקויים האחרים (מלבד רעל). לאחר שתייתו, השותה יאמין לזמן קצר שקיבל את יתרונותיו של השיקוי ה"אחר", אך אמונת השווא תיחשף במהירות...

**הקטנה:** שיקוי זה מקטין את השותה ואת כל הפריטים שהוא לובש או נושא ל־1/12 מגובהם המקורי (כך שדמות שגובהה 1.8 מטרים תהיה בגובה 15 ס"מ). משקלו של השותה מחולק ב־1,728; כתוצאה מכך, לוחם חמוש ישקול פחות מ־70 גרם. היצור המושפע אינו יכול לבצע התקפה יעילה נגד יצור הגדול מחתול בית, אך ייתכן שיוכל לחמוק מתחת לדלתות או לתוך סדקים, ויש לו סיכוי של 90% לנוע בלי להתגלות, הן מבחינת קול והן מבחינת ראייה.

**חסינות לאש:** שיקוי זה מעניק לשותה את כוחו של הלחש **חסינות לאש**.

**מעוף:** לחש זה מעניק את כוחו של הלחש **מעוף**.

**צורה גזית:** השותה וכל ציודו הופכים לבלתי-מוחשיים, ערפיליים ושקופים למחצה. הוא נעשה חסין לכלי נשק שאינם קסומים, ויש לו דירוג שריון 22 נגד כלי נשק קסומים. השותה אינו יכול לתקוף או להטיל לחשים בעת שהוא בצורת גז. הוא גם מאבד יכולות על-טבעיות בעת שהוא בצורת גז. יצור בצורת גז יכול לעוף בקצב של 3 מטרים ולעבור דרך חורים קטנים או פתחים צרים, ואפילו דרך סדקים, כל עוד אפקט השיקוי נמשך. רוחות משפיעות על היצור הגזי, והוא אינו יכול להיכנס למים או לנוזלים אחרים. לא ניתן לתפעל חפצים בצורה זו, גם לא חפצים שנישאו בעת שתיית השיקוי. השותה אינו יכול לחזור לצורתו החומרית כרצונו, אלא חייב להמתין עד שאפקט השיקוי יפוג; עם זאת, ניתן לשתות את השיקוי בשלישים, ובמקרה כזה כל מנה נמשכת 1d4+1 תורות.

**כוחו של ענק:** שיקוי זה מעניק לשותה את כוחו של ענק. למשך האפקט, השותה מקבל תוסף +5 לגלגולי התקפה ונזק באמצעות כלי נשק לקרב פנים אל פנים או כלי נשק מושלכים, ויכול להשליך סלעים גדולים כפי שעושה ענק אבן.

**גדילה:** השותה שיקוי זה, יחד עם כל הציוד שהוא לובש או נושא, גדל לגובה כפול מהרגיל ולמשקל הגדול פי 8 מהרגיל. הדמות המוגדלת נחשבת כבעלת כוחו של ענק אבן, אך ללא היכולת להשליך סלעים, ומקבלת תוסף +5 לגלגולי התקפה ונזק.

**ריפוי:** השותה שיקוי זה מקבל ריפוי של 1d6+1 נקודות פגיעה, כמו הלחש **ריפוי פצעים קלים**.

**גבורה:** שיקוי זה משפר את יכולת הלחימה של השותה. לוחמים בדרגה נמוכה מ־3 מקבלים תוסף התקפה +3 וכן 3 קוביות פגיעה. לוחמים בדרגות 4 עד 5 מקבלים תוסף התקפה +2 ו־2 קוביות פגיעה. לוחמים בדרגה 6 או 7 מקבלים תוסף התקפה +1 וקוביית פגיעה אחת. לוחמים בדרגה 8 ומעלה, וכן דמויות שאינן לוחמים, אינם מקבלים קוביות פגיעה, אך עדיין מקבלים תוסף התקפה +1. קוביות הפגיעה המתקבלות הן זמניות בלבד, ונזק שהדמות סופגת מופחת מהן תחילה; קוביות פגיעה שנותרות כאשר אפקט השיקוי פג פשוט אובדות.

**היעלמות מעין:** שיקוי זה הופך את השותה לבלתי נראה, כמו הלחש **היעלמות מעין**. ניתן לשתות את השיקוי בשלישים, ובמקרה כזה כל מנה נמשכת 1d4+1 תורות.

**אי-פגיעות:** שיקוי זה מעניק תוסף +2 לדירוג השריון.

**ריחוף:** שיקוי זה מעניק את כוחו של הלחש **ריחוף**.

**אריכות ימים:** השותה שיקוי זה נעשה צעיר יותר ב־1d10 שנים.

**תע"ח:** שיקוי זה מעניק את כוחו של הלחש בעל אותו השם.

**רעל:** אין זה שיקוי כלל, אלא מלכודת. השותה חייב להצליח בגלגול הצלה נגד רעל או למות, גם אם שתה לגימה אחת בלבד.

**שינוי עצמי:** שיקוי זה מעניק את כוחו של הלחש בעל אותו השם.

**מהירות:** שיקוי זה מעניק לשותה את יתרונותיו של הלחש **האצה**.

**מציאת אוצר:** השותה שיקוי זה יודע מיד את הכיוון ואת המרחק המשוער למטמון האוצר הגדול ביותר ברדיוס כדורי של 90 מטרים. שיקוי זה מזהה במפורש פלטינה, זהב, אלקטרום, כסף ונחושת; הוא אינו מזהה אבני חן וחפצי קסם.

### מגילות

רוב המגילות מכילות קסם כלשהו המופעל כאשר קוראים אותן, וניתן להשתמש בו פעם אחת בלבד; האותיות נשרפות ונעלמות עם קריאת המילים.

**מגילות לחשים** מוקסמות בלחש אחד או יותר של כוהן או של קוסם, ולעולם לא בלחשים משני הסוגים על אותה מגילה. ניתן להשתמש בכל לחש פעם אחת בלבד, אף שכמובן אותו לחש עשוי להופיע כמה פעמים על מגילה אחת. השתמש בטבלה שלהלן כדי לקבוע את עוצמתו של כל לחש במגילה. רק כוהן רשאי להשתמש במגילת לחשי כוהן, ורק קוסם רשאי להשתמש במגילת לחשי קוסם.

קוסמים חייבים להטיל **קריאת קסם** על מגילת לחשים לפני שיוכלו להשתמש בה. יש להטיל את הלחש על כל מגילה פעם אחת בלבד, ולאחר מכן האפקט נמשך ללא הגבלת זמן. אם קוסם מנסה להטיל לחש ממגילה ואינו מכיר את הלחש, יש סיכוי של 10% שהלחש ייכשל. אם לחש במגילה הוא בעוצמה גבוהה יותר מעוצמת הלחש הגבוהה ביותר שהקוסם מסוגל להטיל, הוסף 10% לסיכוי הכישלון עבור כל עוצמת לחש של הפרש. לדוגמה, אאורה, קוסמת בדרגה 3, מנסה להטיל **שינוי עצמי** ממגילה. אאורה מסוגלת להטיל לכל היותר לחשים בעוצמה 2. **שינוי עצמי** הוא לחש בעוצמה 4, ולכן לאאורה יש סיכוי כישלון של 10% משום שאינה מכירה את הלחש, ועוד 20% בשל ההפרש בין העוצמה המרבית שלה, 2, לבין עוצמת הלחש, 4; בסך הכול 30%.

מגילות לחשי כוהן כתובות בשפה רגילה, משום שאינן אלא תפילות שהוקסמו במיוחד, ולכן הכוהן צריך רק להכיר את השפה שבה כתובה המגילה כדי להשתמש בה. כוהנים כפופים לאותו סיכוי כישלון כמו קוסמים, מלבד המחסר של 10% בשל אי-הכרת הלחש, שאינו חל עליהם.

#### מגילות לחשים: עוצמת לחש

| **d%** | **עוצמת לחש** |
|---|----|
| 01-30 | 1 |
| 31-55 | 2 |
| 56-75 | 3 |
| 76-88 | 4 |
| 89-97 | 5 |
| 98-00 | 6 |

**מגילה מקוללת** מטילה קללה כלשהי על מי שקורא אותה. אין צורך לקרוא אותה במלואה; למעשה, די במבט חטוף בטקסט כדי להטיל את הקללה. ייתכן שיותר גלגול הצלה וייתכן שלא, לפי החלטת המנחה, אף שבדרך כלל יש לאפשר גלגול הצלה נגד לחשים. המנחה מוזמנת לגלות יצירתיות בעת יצירת קללות; הלחש **הטלת קללה**, ההיפוך של **הסרת קללה**, יכול לשמש השראה, אך מגילות מקוללות יכולות להכיל קללות חזקות או יצירתיות יותר, לפי שיקול דעתה של המנחה.

**מגילות הגנה** ניתנות לקריאה בידי דמות מכל מקצוע, בתנאי שהיא יכולה לקרוא את השפה שבה כתובה המגילה (ראו את ההערות תחת **שפה** בסעיף **דמות** לפרטים). כאשר קוראים מגילת הגנה, היא יוצרת מעגל הגנה ברדיוס של 3 מטרים סביב הקורא, המונע מן היצורים שהמגילה מגינה מפניהם להיכנס. המעגל נע עם הקורא. כל יצור שאינו מן הסוג שהמגילה מגינה מפניו רשאי להיכנס, ובכלל זה, כמובן, בעלי בריתו של קורא המגילה; גם הם מוגנים כל עוד הם נשארים לחלוטין בתוך המעגל. אם יצור כלשהו בתוך המעגל מבצע התקפת פנים אל פנים נגד אחד היצורים שהמגילה מגינה מפניהם, המעגל נשבר ואותם יצורים רשאים לתקוף בחופשיות. מגילות הגנה רגילות פועלות במשך 2 תורות לאחר קריאתן.

**מגילות הגנה מקסם** הן מיוחדות, משום שהן מגינות מפני לחשים וחפצי קסם ולא מפני יצורים. שום אפקט קסום אינו יכול לחצות את מעגל ההגנה ברדיוס של 3 מטרים, בשום כיוון, במשך 1d4 תורות. כמו במגילות ההגנה האחרות, המעגל שיוצרת מגילה זו נע עם הקורא.

**מפות אוצר** אינן קסומות בדרך כלל. על המנחה ליצור אותן, אף שהיא רשאית לדחות את יצירת המפה עד שהדמויות יוכלו להשתמש בה בפועל. האוצר המצוין במפה יהיה מוגן בדרך כלל בידי מפלצת כלשהי, לפי בחירת המנחה.

### טבעות

טבעת היא חישוק מתכת עגול הנענד על האצבע (לא יותר מטבעת אחת בכל יד), ובעל כוח דמוי-לחש, לעיתים קרובות אפקט קבוע המשפיע על העונד.

**שליטה בחיה:** העונד טבעת זו יכול להקסים עד 6 קוביות פגיעה של חיות. האפקט פועל בדומה ללחש **הקסמת איש**, אך משפיע רק על חיות (כולל חיות בגודל ענק, אך לא יצורים פנטסטיים או יצורים שתבונתם גבוהה מזו של כלב או חתול). העונד יכול להפעיל את הכוח כרצונו נגד כל חיה שהוא יכול לראות בטווח של 18 מטרים. הוא רשאי לסיים בכל עת את האפקט על יצור נשלט אחד או יותר, כדי "לשחרר" מספיק קוביות פגיעה לשליטה במטרה חדשה.

**שליטה באדם:** העונד טבעת זו יכול להטיל את הלחש **הקסמת איש** על כל מטרה שהוא יכול לראות בטווח של 18 מטרים. הוא יכול להשתמש בכוח זה כרצונו פעם אחת בכל סיבוב, אך אינו יכול לשלוט ביותר מ־6 קוביות פגיעה של יצורים בכל זמן נתון. עם זאת, הוא רשאי לסיים בכל עת את האפקט על יצור נשלט אחד או יותר, כדי "לשחרר" מספיק קוביות פגיעה לשליטה במטרה חדשה.

**שליטה בצמח:** העונד טבעת זו יכול ליצור כרצונו אפקט שווה ערך לזה של **שיקוי שליטה בצמח**, המשפיע על צמחים או יצורי צמח שהוא יכול לראות בטווח של 18 מטרים. האפקט נמשך כל עוד העונד נשאר בטווח של 18 מטרים מהצמחים או מיצורי הצמח. ניתן לגלגל גלגול הצלה בדיוק כפי שמתואר בשיקוי.

**אמונת שווא:** טבעת זו נראית כטבעת מסוג אחר (גלגלי שוב בטבלת הטבעות כדי לקבוע את הסוג). כל העונד אותה מאמין שהיא פועלת ומתנהג בהתאם; לדוגמה, דמות המאמינה שהיא עונדת **טבעת היעלמות מעין** תאמין שהיא אכן בלתי נראית. בניגוד לשיקוי בעל אותו שם, אפקט הטבעת אינו מתבטל כאשר העונד סופג נזק; למעשה, הדרך היחידה לשחרר דמות מחפץ מקולל זה היא באמצעות הלחש **הסרת קללה**.

**זימון ג'יני:** טבעת זו משמשת כשער מיוחד שבאמצעותו ניתן לזמן ג'יני מסוים ממישור יסוד האוויר. כאשר משפשפים את הטבעת, הג'יני מופיע בסיבוב הבא. הג'יני מציית לעונד הטבעת ומשרת אותו בנאמנות, אך לא יותר משעה אחת ביום. אם הג'יני של הטבעת נהרג, הטבעת נעשית לא קסומה וחסרת ערך.

**חסינות לאש:** העונד טבעת זו זוכה להגנה שמעניק הלחש **חסינות לאש**, אך ההגנה פועלת באופן מתמיד.

**היעלמות מעין:** באמצעות הפעלת טבעת כסף פשוטה זו, העונד יכול ליהנות מ**היעלמות מעין**, כמו הלחש. אם אפקט ההיעלמות מעין מתבטל, כמתואר בלחש, לא ניתן להפעיל את הטבעת מחדש במשך תור שלם. בכל מקרה אחר, אפקט ההיעלמות מעין נמשך 24 שעות.

**הגנה:** טבעת זו מעניקה הגנה קסומה מתמדת בצורת תוסף לדירוג השריון של העונד, בין +1 ל־+3 כפי שמוצג בטבלה. תוסף זה חל גם על גלגולי ההצלה של העונד.

**התחדשות:** טבעת זו מעניקה לעונד את כוח ההתחדשות, בדיוק כפי שמתואר בתיאור הטרול, כולל החולשה לנזק מחומצה ומאש. עם זאת, רק נזק שהדמות סופגת בעת ענידת הטבעת מתחדש.

**אחסון לחשים:** טבעת אחסון לחשים מכילה מספר לחשי קוסם שהעונד יכול להטיל. דרגת המטיל של כל לחש שווה לדרגה המזערית הנדרשת להטלתו. דמות מכל מקצוע יכולה לענוד טבעת זו ולהשתמש בה, אך רק קוסם המטיל לתוכה את הלחש המתאים יכול לטעון אותה מחדש. השתמש בטבלה שלהלן כדי לקבוע כמה לחשים היא מכילה ומהן עוצמותיהם. יש לטעון מחדש טבעת אחסון לחשים באותם לחשים שהוכנסו לתוכה בעת יצירתה; לדוגמה, טבעת אחסון לחשים המכילה 2 לחשים, **כדור אש** ו**מעוף**, יכולה להיטען מחדש רק באותם 2 לחשים. הטבעת מוסרת לעונד באורח קסום את שמות כל הלחשים המאוחסנים בה. טבעת שנמצאה במטמון אוצר עשויה להיות טעונה במלואה, ריקה או טעונה חלקית, לפי בחירת המנחה.

| **d%** | **מספר לחשים** | **d%** | **עוצמת הלחש** |
|----|----|----|----|
| 01-24 | 1 | 01-30 | 1 |
| 25-48 | 2 | 31-55 | 2 |
| 49-67 | 3 | 56-75 | 3 |
| 68-81 | 4 | 76-85 | 4 |
| 82-91 | 5 | 86-97 | 5 |
| 92-96 | 6 | 98-00 | 6 |
| 97-00 | 7 |  |  |

**החזרת לחשים:** טבעת זו מחזירה אל המטיל לחשים המוטלים ישירות על העונד, אך לא לחשים בעלי אפקט אזורי; כך, הלחש **עצירת איש** יוחזר, אך לא **כדור אש**. הטבעת תחזיר עד 2d6 לחשים לפני שכוחה יתכלה.

**טלקינזיס:** העונד טבעת זו יכול להשתמש בכוחו של הלחש **טלקינזיס**, כאילו הטיל אותו קוסם בדרגה 12. ניתן להשתמש באפקט כרצונו כמה פעמים ביום, אך הוא נמשך רק כל עוד העונד מתרכז בו.

**הליכה על מים:** טבעת זו מאפשרת לעונד ללכת על כל נוזל כאילו היה קרקע מוצקה. ניתן לחצות בקלות בוץ, שמן, שלג, חול טובעני, מים זורמים, קרח ואפילו לבה, משום שרגלי העונד מרחפות 2.5 עד 5 סנטימטרים מעל פני השטח. לבה מותכת עדיין גורמת לעונד נזק מחום, משום שהוא עדיין קרוב אליה. העונד יכול ללכת, לרוץ או לנוע בדרך אחרת על פני השטח כאילו היה קרקע רגילה.

**חולשה:** כל העונד טבעת זו מקולל; ערך הכוח שלו מופחת מיד ל־3. ניתן להסיר את הטבעת רק באמצעות הלחש **הסרת קללה**.

**משאלות:** טבעת משאלות מכילה כוח המאפשר להעניק משאלות לעונד. כאשר הטבעת נמצאת, נותרות בה 1d4 משאלות. המנחה חייבת להכריע בכל המשאלות, והנחיות לכך מופיעות בפרק **המנחה**.

**ראיית רנטגן:** לפי פקודה, טבעת זו מעניקה לעונד את היכולת לראות לתוך חומר מוצק ודרכו. טווח הראייה הוא 6 מטרים, והעונד רואה כאילו הוא מביט במשהו באור רגיל, גם כשאין כל תאורה. ראיית הרנטגן יכולה לחדור דרך 30 סנטימטרים של אבן, 2.5 סנטימטרים של מתכת רגילה או עד 1 מטר של עץ או עפר. חומרים עבים יותר, או יריעה דקה של עופרת או זהב, חוסמים את הראייה. ניתן להשתמש בטבעת 3 פעמים ביום, וכל שימוש נמשך לכל היותר תור אחד, או עד שהעונד מפסיק להתרכז.

### שרביטים, מטות ומקלות

שרביט הוא מקל קצר, בדרך כלל באורך 30 עד 45 סנטימטרים, שהוטמע בו הכוח להטיל לחש מסוים או ליצור אפקט דמוי-לחש. שרביט חדש מכיל 20 מטענים, וכל שימוש בו מכלה מטען אחד; בשרביט שנמצא במטמון אוצר נותרו 2d10 מטענים. אם שרביט יוצר אפקט השווה ללחש, הנח שהלחש פועל כאילו הטיל אותו מטיל בדרגה 6, או בדרגת המטיל המזערית הנדרשת להטלת הלחש, הגבוהה מביניהן, אלא אם צוין אחרת. בדרך כלל רק קוסמים יכולים להשתמש בשרביטים. גלגולי הצלה מתבצעים כרגיל, אך בעמודת שרביטי הקסם במקום בעמודת הלחשים.

מטה מכיל מספר אפקטים שונים של לחשים, שלעיתים קרובות קשורים זה לזה. מטה חדש מכיל 30 מטענים, וכל שימוש בו מכלה מטען אחד או יותר. במטה שנמצא במטמון אוצר נותרו 3d10 מטענים. אפקטי לחשים שיוצר מטה פועלים כאילו הטיל אותם מטיל בדרגה 8, או בדרגת המטיל המזערית הנדרשת להטלת הלחש, הגבוהה מביניהן, אלא אם צוין אחרת. רק קוסמים יכולים להשתמש במטות, אלא אם צוין אחרת. גלגולי הצלה נגד קסם ממטה מתבצעים בעמודת הלחשים.

מקל הוא פריט הדומה לשרביט מלכותי, בעל כוח מיוחד שאינו דומה לזה של שום לחש מוכר. בדרך כלל דמות מכל מקצוע יכולה להשתמש במקל.

**מקל ביטול:** מקל מטיל אימה זה הוא אסונם של חפצי קסם, משום שמגעו מרוקן חפץ מכל תכונותיו הקסומות. אם החפץ מוחזק בידי יצור, נדרש גלגול התקפה כדי לגעת בו. לאחר שהמקל מרוקן חפץ, הוא עצמו נעשה שביר ואי אפשר להשתמש בו שוב. ניתן להשיב את כוחם של חפצים שרוקנו רק באמצעות **משאלה**.

**מטה נחש:** פריט זה הוא מטה הליכה +1. כאשר כוהן משתמש בו, הוא יכול לפקוד על המטה להפוך לנחש חונק בפגיעה מוצלחת, במקום לגרום נזק. הנחש כורך את גופו סביב מטרה בגודל אדם לכל היותר ומחזיק בה בחוזקה במשך 1d4 תורות, אלא אם המטרה מצליחה בגלגול הצלה נגד לחשים. הנחש אינו תוקף בדרך אחרת ואינו גורם נזק. המשתמש יכול להשיב אליו את הנחש בכל עת; במקרה כזה הוא חוזר לידו ושב לצורת מטה. הוא שב לצורת מטה גם כאשר משך האפקט מסתיים או כאשר גלגול ההצלה מצליח. לנחש דירוג שריון 15, קצב תנועה של 6 מטרים לסיבוב ו־20 נקודות פגיעה. כל הנזק שספג נרפא לחלוטין כאשר הוא שב לצורת מטה; אם הוא נהרג בצורת נחש, הקסם נהרס והוא הופך למקל שבור. ניתן להשתמש במטה מספר בלתי מוגבל של פעמים ביום; אין לו מטענים והוא אינו צורך מטענים.

**מטה פיקוד:** מטה זה יכול להטיל את הלחשים **הקסמת איש** ו**הקסמת מפלצת**, וכן להעניק כוח שווה ערך לזה של **שיקוי שליטה בצמח**. כל אחד מהשימושים מכלה מטען אחד.

**מטה ריפוי:** מטה זה יכול לרפא 1d6+1 נקודות פגיעה עבור כל מטען שמנוצל, כמו הלחש **ריפוי פצעים קלים**. לחלופין, באמצעות ניצול 2 מטענים, המטה יכול להטיל **ריפוי מחלה**. רק כוהן יכול להשתמש במטה זה.

**מטה כוח:** זהו חפץ קסם רב-עוצמה, בעל יכולות התקפיות והגנתיות. בדרך כלל בראשו משובצת אבן חן נוצצת, וגופו ישר וחלק. יש לו את הכוחות הבאים, שכל אחד מהם עולה מטען אחד בכל שימוש: **חזיז ברק** הגורם 6d6 נזק, **כדור אש** הגורם 6d6 נזק, **חרוט קור** כמו שרביט הקור הגורם 6d6 נזק, **אור תמידי** ו**טלקינזיס** כמו הטבעת, הנמשך לכל היותר 1d6 תורות. המטה הוא גם מטה הליכה +2, וניתן להשתמש בו בדיוק כמו **מטה הכאה**. אפשר לבצע באמצעות מטה כוח מכת גמול; לשם כך על האוחז לשבור אותו. כל המטענים שנותרו במטה משתחררים מיד ברדיוס של 9 מטרים וגורמים 1d6 נזק עבור כל מטען שנותר; גלגול הצלה נגד לחשים מפחית את הנזק בחצי. כל מי שנמצא באזור, כולל האוחז, מושפע.

לאחר שכל מטעניו של המטה נוצלו, הוא נשאר מטה הליכה +2. לאחר שהתרוקן ממטענים, לא ניתן להשתמש בו לביצוע מכת גמול.

**מטה הכאה:** למטה זה אין תוסף התקפה, אך הוא נחשב לנשק +1 לעניין סוגי המפלצות שבהן הוא מסוגל לפגוע; בשימוש זה דמות מכל מקצוע יכולה להשתמש בו. ניתן להשתמש בכוחו העיקרי של המטה רק כאשר כוהן אוחז בו: באמצעות אמירת מילת פקודה, הכוהן יכול ליצור אפקט הדומה ללחש **הכאה**. ניצול מטען אחד מוסיף 1d6 נזק לפגיעה הבאה של המטה; ניצול 2 מטענים מוסיף 2d6 נזק, וניצול 3 מטענים מוסיף 3d6 נזק. אם המטה אינו פוגע בהצלחה לאחר אמירת מילת הפקודה, האפקט מתפוגג לאחר תור אחד.

**מטה קוסמות:** מטה זה שווה ערך ל**מטה כוח** המתואר לעיל, ובנוסף יש לו הכוחות הבאים: **היעלמות מעין**, **מעבר קיר**, **קורים** ו**זימון יסודנים** כמו הלחש, אך הוא מזמן יסודני מטה כמתואר בפרק **מפלצות**. כל אחד מכוחות אלה מכלה מטען אחד כאשר הוא מופעל.

**שרביט קור:** שרביט זה יוצר פרץ קור חרוטי הגורם 6d8 נזק; גלגול הצלה נגד שרביטי קסם מפחית את הנזק בחצי. החרוט מתרחב מקצה השרביט, ורוחבו מגיע ל־9 מטרים במרחק 12 מטרים ממנו.

**שרביט גילוי אויבים:** האפקט של שרביט זה גורם לכל אויביו של המשתמש בטווח של 18 מטרים לזהור באור לבן-ירקרק במשך סיבוב אחד. גם אויבים מוסתרים או בלתי נראים זוהרים כך ונחשפים, אך אויבים המוסתרים לחלוטין מן העין, כגון מאחורי קיר, לא ייראו לעיני המשתמש. "אויב" הוא כל יצור החושב לפגוע במשתמש או מתכוון לעשות זאת בדרך אחרת. בנוסף, כל המפלצות האל-מתות והיצירים המונפשים בטווח זוהרים כך ללא קשר לכוונותיהם, למחשבותיהם או להיעדרן.

**שרביט פחד:** שרביט זה יוצר את האפקט של הלחש **גרימת פחד**, ההיפוך של הלחש **סילוק פחד**.

**שרביט כדורי אש:** שרביט זה יוצר **כדורי אש**, בדיוק כמו הלחש **כדור אש**, וגורם 6d6 נזק.

**שרביט אשליה:** שרביט זה מאפשר למשתמש ליצור אשליות השוות לאפקט של הלחש **חזיון תעתועים**.

**שרביט חזיזי ברק:** שרביט זה יוצר **חזיזי ברק**, בדיוק כמו הלחש **חזיז ברק**, וגורם 6d6 נזק.

**שרביט גילוי קסם:** שרביט זה מעניק למשתמש כוח שווה ערך ללחש **גילוי קסם**.

**שרביט שיתוק:** שרביט זה יוצר את האפקט של הלחש **עצירת איש**.

**שרביט שינוי צורה:** שרביט זה יכול לשמש להטלת **שינוי עצמי** או **שינוי אחר**.

**שרביט גילוי דלתות סודיות:** שרביט זה מעניק למשתמש כוח הדומה ללחש **מציאת מלכודות**, אך מגלה דלתות סודיות במקום מלכודות.

**שרביט גילוי מלכודות:** שרביט זה מעניק למשתמש כוח שווה ערך ללחש **מציאת מלכודות**.

### חפצי קסם שונים

חפצי קסם אלה יכולים להופיע בכמה צורות ולהעניק מגוון אפקטים. כאשר קובעים פריט כזה באקראי, קובעים תחילה את האפקט (כפי שמוסבר בטבלאות שלמעלה), ולאחר מכן מגלגלים את הצורה בטבלה נפרדת. בדרך כלל, שמו של פריט כזה נכתב כ־[**צורה**] של [**אפקט**]; לדוגמה, **גלימת חסינות לאש**.

בפריטים שצורתם מיועדת ללבישה או לענידה, ניתן להשתמש בו־זמנית רק במספר הרגיל של פריטים כאלה: לכל היותר 2 טבעות (אחת בכל יד), גלימה אחת, זוג מגפיים אחד, קסדה אחת ותליון אחד. אם דמות לובשת או עונדת 2 פריטים המעניקים אותו אפקט מתמשך, כגון **חסינות לקור** או **הגנה**, רק אחד מהם יפעל. אם הפריטים מעניקים אפקט בעוצמות שונות, כגון **גלימת הגנה +1** ו־**טבעת הגנה +3**, רק הפריט החזק יותר יפעל (במקרה זה, הטבעת).

הטבלאות בעמוד 167 מספקות צורות רגילות לחפצי קסם שונים, אך המנחה אינה מוגבלת כלל למה שמופיע בטבלת צורת הפריט. ניתן ליצור פריטים בצורות שאינן מותרות שם בדרך כלל, ואף בצורות שאינן מופיעות בטבלה כלל.

### אפקטים של חפצי קסם שונים

**פיצוץ**: כאשר מנגנים בפריט זה (בהתאם לצורתו), הוא יוצר פרץ קול עוצמתי הממלא חרוט שאורכו 3 מטרים ורוחבו 0.5 מטר בבסיסו. הנמצאים באזור האפקט סופגים 2d6 נקודות נזק ומתחרשים למשך תור שלם. גלגול הצלה מוצלח נגד קרן מוות מפחית את הנזק בחצי ואת משך החירשות לסיבוב אחד.

ניתן להשתמש בפריט גם כדי לפגוע במבנים, ביצורים וכדומה או להרוס אותם. הכפילי את הנזק המפורט לעיל כאשר משתמשים בפריט נגד מבנה. כללי [מבצר](gm02.qmd#strongholds) בפרק המנחה מספקים הנחיות נוספות בנושא.

**היטמעות**: הלובש פריט זה נעשה כמעט בלתי נראה, ויש לו סיכוי של 80% לנוע בלי להתגלות. אם צופים מבחינים בו, ניתן לתקוף אותו ללא מחסר משמעותי.

**חסינות לקור**: הלובש פריט זה זוכה להגנה שמעניק הלחש **חסינות לקור**, אך ההגנה פועלת באופן מתמיד.

**הבנה**: הלובש פריט זה מקבל את היכולת לקרוא כל שפה, כולל כל צורה של כתב קסום. היכולת לקרוא קסם אינה מעניקה ללובש יכולות קסומות, אך כאשר קוסם לובש את הפריט, הוא זוכה באופן מתמיד לאפקט של **קריאת קסם**. שימי לב שכאשר קוראים טקסטים שאינם קסומים, המגבלות המתוארות בלחש **קריאת שפות** חלות גם על פריט זה.

**שליטה בחיה**: הלובש פריט זה יכול להקסים עד 6 קוביות פגיעה של חיות. האפקט פועל בדומה ללחש [הקסמת חיה](allSpells.qmd#הקסמת-חיה), ומשפיע רק על חיות (כולל חיות בגודל ענק, אך לא יצורים פנטסטיים או יצורים שתבונתם גבוהה מזו של כלב או חתול). הלובש יכול להפעיל את הכוח כרצונו ולבחור כמטרה כל חיה שהוא יכול לראות בטווח של 18 מטרים. הוא רשאי לסיים בכל עת את האפקט על יצור נשלט אחד או יותר כדי "לשחרר" מספיק קוביות פגיעה לשליטה במטרה חדשה.

**שליטה באדם**: הלובש פריט זה יכול להטיל את הלחש [הקסמת איש](allSpells.qmd#הקסמת-איש) על כל מטרה שהוא יכול לראות בטווח של 18 מטרים. הוא יכול להשתמש בכוח זה כרצונו פעם אחת בכל סיבוב. אם הלובש רוצה להשפיע על יותר מהומנואיד אחד, הלובש אינו יכול לשלוט ביותר מ־6 קוביות פגיעה או דרגות של הומנואידים בו־זמנית. עם זאת, הוא רשאי לסיים בכל עת את האפקט על יצור נשלט אחד או יותר כדי "לשחרר" מספיק קוביות פגיעה או דרגות לשליטה במטרה חדשה.

**שליטה בצמח**: הלובש פריט זה יכול ליצור כרצונו אפקט שווה ערך לזה של **שיקוי שליטה בצמח**, המשפיע על צמחים או על יצורי צמח שהוא יכול לראות בטווח של 18 מטרים. האפקט נמשך כל עוד הלובש נשאר בטווח של 18 מטרים מהצמחים או מיצורי הצמח. ניתן לגלגל גלגול הצלה בדיוק כפי שמתואר בשיקוי.

**אומץ**: כאשר מנגנים בפריט זה, כל הדמויות והיצורים הידידותיים למשתמש בטווח של 18 מטרים מושפעים כאילו הוטל עליהם הלחש [סילוק פחד](allSpells.qmd#סילוק-פחד).

**הטעיה**: פריט זה מעניק ללובש את כוחו של ה[מטעה](monstersAll.qmd#מטעה-פנתרהידרה). כל תוקף מאמין שהלובש נמצא במרחק של 1 מטר ממיקומו האמיתי, ולכן ההתקפה הראשונה של התוקף מחטיאה תמיד. לאחר מכן, התוקף סובל מחסר -2 לכל גלגולי ההתקפה. טבעת זו אינה משפיעה על יצורים חסרי תודעה, על יצירים כגון גלמים או פסלים חיים, או על אל-מתים מכל סוג. יצורים חיים שאינם חסרי תודעה מושפעים גם אם אינם משתמשים בראייה כדי לכוון אל הלובש.

**אמונת שווא**: כל העונד פריט זה מאמין שמדובר בסוג אחר של חפץ קסם מועיל ומתנהג בהתאם; לדוגמה, אם דאריון מאמין שהוא עונד **טבעת היעלמות מעין**, הוא יאמין שהוא אכן בלתי נראה. בניגוד לשיקוי בעל אותו שם, אפקט הפריט אינו מתבטל כאשר העונד סופג נזק; למעשה, הדרך היחידה לשחרר דמות מחפץ מקולל זה היא באמצעות הלחש [הסרת קללה](allSpells.qmd#הסרת-קללה).

**זימון ג'יני**: לכל פריט מסוג זה קשור ג'יני מסוים, המזומן אל מיקומו של הלובש כאשר הוא משפשף את הפריט בעודו לובש אותו. הג'יני מופיע בסיבוב הבא, מגן על הלובש, משרת אותו ומציית לו. הג'יני משרת לכל היותר שעה אחת ביום, וניתן לזמנו לכל היותר פעם אחת ביום. אם הג'יני הקשור לפריט נהרג, הטבעת מאבדת את כל תכונותיה הקסומות.

**אבדון**: כאשר מנגנים בפריט זה (בהתאם לצורתו), הוא מנפיש שלדים או זומבים כאילו באמצעות הלחש [הנפשת מתים](allSpells.qmd#הנפשת-מתים). כך ניתן ליצור עד 3d6 קוביות פגיעה של אל-מתים משרידים הנמצאים ברדיוס של 18 מטרים מהדמות שהפעילה את הפריט. אם באזור האפקט נמצאים גם שרידים שלדיים וגם שרידים בשרניים, שלדים יונפשו בעדיפות על פני זומבים. אם המשתמש הוא קוסם או כוהן, ניתן לשלוט באל-מתים שנוצרו כל עוד הדמות מחזיקה בפריט. אם המשתמש הוא לוחם או גנב, האל-מתים שנוצרו אינם נשלטים ותוקפים כל יצור חי בקרבת מקום. ניתן להשתמש בפריט פעם אחת ביום, אך בכל זמן נתון לא יכולים להתקיים יותר מ־18 קוביות פגיעה של אל-מתים שנוצרו באמצעותו.

**חסינות לאש**: הלובש פריט זה זוכה להגנה שמעניק הלחש [חסינות לאש](allSpells.qmd#חסינות-לאש), אך ההגנה פועלת באופן מתמיד.

**היעלמות מעין**: הלובש פריט זה יכול להיעלם מעין לפי פקודה, כמו בלחש [היעלמות מעין](allSpells.qmd#היעלמות-מעין). אם אפקט ההיעלמות מעין מתבטל, כמתואר בלחש, לא ניתן להפעיל מחדש את הפריט במשך תור שלם. בכל מקרה אחר, אפקט ההיעלמות מעין נמשך 24 שעות.

**ריחוף**: הלובש פריט זה יכול לרחף כרצונו, כמו בלחש **ריחוף**, באמצעות ריכוז. אין הגבלה על משך השימוש בפריט זה.

**תע"ח**: כל הלובש פריט זה זוכה לגישה לגרסה קבועה של הלחש [תע"ח](allSpells.qmd#תעח). הכוח זמין תמיד, אך מופעל רק לאחר שהלובש מקדיש סיבוב שלם לריכוז בו, ונמשך עד שהוא מפסיק להשתמש בו. ניתן להפעיל את האפקט כמה פעמים ביום שירצה הלובש.

**בהלה**: כאשר מנגנים בפריט זה (בהתאם לצורתו), כל היצורים הנמצאים במרחק של יותר מ־6 מטרים מהמשתמש, אך לא יותר מ־36 מטרים ממנו, חייבים להצליח בגלגול הצלה נגד לחשים או להיות מושפעים כאילו הוטל עליהם הלחש [גרימת פחד](allSpells.qmd#סילוק-פחד).

**ראייה חודרת**: לפי פקודה, וכל עוד הלובש מתרכז בכך, פריט זה מעניק את הכוח לראות דרך חומר מוצק כאילו היה שקוף כזכוכית. טווח האפקט הוא עד 6 מטרים, והלובש רואה כאילו הוא נמצא באור רגיל, גם אם הוא למעשה בחשכה מוחלטת.

חומרים מסוימים חוסמים את האפקט. הלובש יכול לראות דרך לכל היותר 1 מטר של עץ או אדמה, 30 סנטימטרים של אבן או 2.5 סנטימטרים של רוב המתכות. שכבה של זהב או עופרת, גם אם אינה עבה יותר מרדיד, חוסמת את האפקט לחלוטין.

ניתן להשתמש בפריט 3 פעמים ביום, וכל שימוש נמשך לכל היותר תור אחד.

**הגנה**: הלובש פריט בעל כוח זה מקבל את התוסף המפורט, בין +1 ל־+3, לדירוג השריון שלו כל עוד הטבעת נענדת. תוסף זה חל גם על גלגולי ההצלה של הלובש.

**הגנה מניקוז אנרגיה**: לפריט זה יש כוח לספוג ולנטרל התקפות ניקוז אנרגיה, לחשי מוות או אפקטי מוות (כגון קטילת חיים), וקללות שהיו משפיעים אחרת על הלובש. כאשר הפריט נמצא, יש בו 2d6 מטענים. כל דרגה שלילית, קללה או לחש שנספגים מכלים מטען אחד. כאשר מטעני הפריט מתכלים, הוא מתפורר לנצנוצים זהובים ונעלם.

**הגנה מצפייה מרחוק**: הלובש פריט זה חסין לכל צורה של צפייה מרחוק, לרבות כדורי בדולח, ראייה על חושית, שמיעה על חושית וכל אמצעי אחר לאיתור או לריגול מרחוק, וכן לכל צורה של קריאת מחשבות. דמויות אחרות הנמצאות בטווח של 9 מטרים מהלובש חסינות גם הן לצפייה מרחוק, אך לא לקריאת מחשבות.

**התחדשות**: פריט זה מעניק ללובש את כוח ההתחדשות, בדיוק כפי שמתואר בתיאור הטרול בעמוד 151, כולל החולשה לנזק מחומצה ומאש. שימי לב שפריט זה מרפא רק נזק שנגרם בעת לבישתו; לבישת הפריט אינה מרפאה נזק קודם.

**צפייה מרחוק**: ניתן להשתמש בפריט זה כדי לרגל אחר אנשים או מקומות אחרים, ללא תלות במרחק. רק קוסמים יכולים להשתמש בפריט צפייה מרחוק. ניתן להשתמש בו 3 פעמים ביום, עד תור אחד בכל פעם. סיכויי ההצלחה בשימוש בפריט צפייה מרחוק מוצגים להלן. כאשר הסיכוי הכולל הוא 100% ומעלה, אין צורך בגלגול.

| **היכרות וקשר** | **סיכוי** |
|----|-----|
| היכרות עקיפה (שמע על המטרה) | 25% |
| היכרות ישירה (ראה את המטרה בקצרה) | 55% |
| היכרות מעמיקה (מכיר את המטרה היטב) | 95% |
| חפץ או בגד של המטרה | +25% |
| חלק גוף, קווצת שיער, פיסת ציפורן וכדומה | +50% |

רק המשתמש בפריט רואה את התמונה. בדרך כלל לא נשמע קול. ללחשים **גילוי קסם**, **גילוי רוע** ו**תע"ח** יש סיכוי של 3% לכל דרגה של מטיל הלחש לפעול כראוי כאשר משתמשים בהם באמצעות פריט צפייה מרחוק.

**צפייה מרחוק משופרת**: פריט זה פועל בדיוק כמו פריט צפייה מרחוק רגיל, כמתואר לעיל, אך גם מאפשר למשתמש לשמוע את כל הקולות במקום הנצפה כאילו היה שם.

**מהירות**: הלובש פריט זה יכול להפעיל אותו באמצעות מילת פקודה, או באמצעות הקשת העקבים זה בזה אם הפריט הוא זוג מגפיים, ולקבל את האפקט של הלחש [האצה](allSpells.qmd#האצה). הוא יכול לסיים את האפקט באותו אופן. ניתן להשתמש באפקט במשך 10 סיבובים בסך הכול בכל יום.

**אחסון לחשים**: פריטים נחשקים אלה מכילים כל אחד מספר לחשים שהלובש יכול להטיל. רובם מכילים לחשי קוסם, אך 1 מתוך 10 מכיל במקומם לחשי כוהן. *אין פריט שיכול להכיל לחשים משני הסוגים!* כל לחש המאוחסן בפריט מוטל כאילו הטיל אותו מטיל לחש בדרגה הנמוכה ביותר המסוגל בדרך כלל להטיל אותו, אך בכל מקרה לא בדרגה נמוכה מ־6.

דמות מכל מקצוע יכולה ללבוש פריט זה ולהשתמש בו, אך ניתן לטעון אותו מחדש רק באמצעות הטלת הלחש המתאים לתוכו. השתמשי בטבלה שלהלן כדי לקבוע כמה לחשים הוא מכיל ומהן עוצמותיהם. יש לטעון מחדש פריט אחסון לחשים באותם לחשים שהוכנסו לתוכו בעת יצירתו; לדוגמה, **תליון אחסון 2 לחשים** המכיל **כדור אש** ו**מעוף** יכול להיטען מחדש רק באותם 2 לחשים.

הלובש אחד מהפריטים האלה יודע אוטומטית את שמות הלחשים המאוחסנים בו, אך אינו מקבל ידע מפורט על אופן פעולתו של כל לחש. אם הלובש אינו קוסם ואין קוסם זמין שייעץ לו, הוא עלול להתקשות להשתמש בפריט בהצלחה ובבטחה.

פריט מסוג זה שנמצא במטמון אוצר עשוי להיות טעון במלואו, ריק או טעון חלקית, לפי בחירת המנחה.

| d%    | מספר לחשים | d%    | עוצמת הלחש |
|-------|--------------|-------|----------------|
| 01-24 | 1            | 01-30 | 1              |
| 25-48 | 2            | 31-55 | 2              |
| 49-67 | 3            | 56-75 | 3              |
| 68-81 | 4            | 76-85 | 4              |
| 82-91 | 5            | 86-97 | 5              |
| 92-96 | 6            | 98-00 | 6              |
| 97-00 | 7            |       |                |

**החזרת לחשים**: פריט זה מחזיר אל המטיל לחשים המוטלים ישירות על הלובש, אך לא לחשים בעלי אפקט אזורי; כך, הלחש [עצירת איש](allSpells.qmd#עצירת-איש) יוחזר, אך לא [כדור אש](allSpells.qmd#כדור-אש). הפריט יחזיר עד 2d6 לחשים לפני שכוחו יתכלה.

**תנועה חרישית**: הלובש פריט זה יכול לנוע בשקט כמעט בכל סביבה, ויש לו סיכוי של 90% להצליח בתנועה חרישית, כמו יכולת הגנב בעלת אותו שם.

**טלקינזיס**: הלובש פריט זה יכול להשתמש בכוחו של הלחש [טלקינזיס](allSpells.qmd#טלקינזיס), כאילו הטיל אותו קוסם בדרגה 12. ניתן להשתמש באפקט כמה פעמים ביום שירצה הלובש, אך הוא נמשך רק כל עוד הוא מתרכז בו.

**טלפתיה**: ניתן להפעיל פריט זה 3 פעמים ביום באמצעות מילת הפקודה שלו. לאחר הפעלתו, הוא מעניק ללובש את כוחו של נוסח מיוחד של הלחש [תע"ח](allSpells.qmd#תעח), שטווחו 27 מטרים ומשכו תור אחד. במהלך זמן זה, הלובש יכול לשלוח מחשבות לתודעתו של כל יצור שאת מחשבותיו הוא כבר קורא, וכך לתקשר איתו.

**שיעתוק**: לפי פקודה, הלובש פריט זה יכול להטיל את הלחש [שיעתוק](allSpells.qmd#שיעתוק) כאילו הטיל אותו קוסם בדרגה 12. ניתן להשתמש בכוח זה עד 3 פעמים ביום.

**ראיית אמת**: 3 פעמים ביום, פריט זה יכול להעניק למשתמש את כוחו של הלחש [ראיית אמת](allSpells.qmd#ראיית-אמת). כל שימוש נמשך לכל היותר תור אחד.

**הליכה על מים**: פריט זה מאפשר ללובש ללכת על כל נוזל כאילו היה קרקע מוצקה. ניתן לחצות בקלות בוץ, שמן, שלג, חול טובעני, מים זורמים, קרח ואפילו לבה, משום שרגלי הלובש מרחפות 2.5 עד 5 סנטימטרים מעל פני השטח. לבה מותכת עדיין גורמת ללובש נזק מחום, משום שהוא עדיין קרוב אליה. הלובש יכול ללכת, לרוץ או לנוע בדרך אחרת על פני השטח כאילו היה קרקע רגילה.

**חולשה**: כל הלובש פריט זה מקולל; ערך הכוח שלו מופחת מיד ל־3. ניתן להסיר את הפריט רק באמצעות הלחש **הסרת קללה**.

**משאלות**: פריט זה מכיל כוח המאפשר להעניק משאלות ללובש. כאשר הטבעת נמצאת, נותרות בה 1d4 משאלות. המנחה חייבת להכריע בכל המשאלות, והנחיות לכך מופיעות בפרק **המנחה**.

### פריטים נדירים

**שק טורף**: פריט זה נראה בכל בדיקה כשק אחסון רגיל, ואכן בתחילה הוא פועל בדיוק כמו **שק אחסון**. אולם כל החפצים המונחים בתוכו נעלמים לעד 1d6+6 תורות לאחר מכן. השק ממשיך לשקול כפי ששקל לאחר שהחפצים הוכנסו לתוכו, כלומר עשירית ממשקלם הכולל, עד שהוא נפתח ומתגלה כריק.

**שק אחסון**: פריט זה הוא שק שנראה ברוחב של כ־0.6 מטר ובעומק של כ־1.2 מטר. הוא נפתח אל מרחב חוץ־ממדי ויכול להכיל הרבה יותר מכפי שנראה אפשרי: משקל של עד 225 ק"ג ונפח של עד כ־2,000 ליטר. השק שוקל עשירית ממשקלם הכולל של החפצים המאוחסנים בו. כל חפץ שמאחסנים בשק חייב לעבור דרך הפתח, שהיקפו כ־1.2 מטר.

ניקוב השק או קריעתו הורסים את הקסם שלו וגורמים לכל תכולתו ללכת לאיבוד לעד. אם הופכים את השק מבפנים החוצה, כל תכולתו נשפכת החוצה. השק אינו ניזוק, אך אינו פועל עד שהופכים אותו שוב לצדו הנכון. יצורים חיים המוכנסים לתוכו נחנקים בתוך תור אחד, למעט יצורים העמידים לחנק, לפי החלטת המנחה. לא ניתן למלא את השק מעבר למגבלת הנפח שלו, משום שחפצים עודפים פשוט אינם נכנסים לתוכו; אולם אם מעמיסים בו יותר מ־225 ק"ג ולאחר מכן מרימים אותו, הוא נקרע.

כדי להוציא חפץ מסוים מן השק, נושא השק חייב להקדיש סיבוב לחיפוש, ובמהלכו אינו יכול לנוע.

**מגפי מסע וקפיצה**: מגפיים אלה מאפשרים ללובש לבצע קפיצות אדירות, עד לגובה של 3 מטרים ו/או למרחק של 9 מטרים. הם משפרים את תנועתו במידה כזו שקצב התנועה שלו ביבשה גדל גם הוא ב־3 מטרים נוספים לסיבוב.

**מטאטא מעופף**: מטאטא זה יכול לעוף באוויר עד 9 שעות ביום, בחלוקה לפי רצון בעליו. המטאטא יכול לשאת 90 ק"ג ולעוף בקצב תנועה של 12 מטרים לסיבוב, או לשאת עד 180 ק"ג בקצב תנועה של 9 מטרים לסיבוב. נוסף על כך, המטאטא יכול לנוע לבדו אל כל יעד שבעליו מציין, כל עוד לבעלים יש היכרות טובה עם מיקומו ועם מבנהו. כאשר נאמרת מילת הפקודה, המטאטא מגיע אל בעליו ממרחק של עד 275 מטרים.

**בקבוק עפרית**: פריט זה עשוי להיראות כבקבוק מעוטר, ולעיתים כמנורת קסם. ניתן להפעילו פעם ביום, באמצעות פתיחתו אם הוא בצורת בקבוק או באמצעות שפשופו אם הוא בצורת מנורה. כאשר הוא מופעל, עשן פורץ ממנו ומתגבש לעפרית.

העפרית המשתחרר היה לכוד בבקבוק ונאלץ לשרת את מי שמפעיל אותו. אולם עפרית ששהה בבקבוק זמן רב מדי עלול לאבד את שפיותו. במקרה כזה הוא פותח בהתקפה מטורפת על מי שהפעיל את הבקבוק ונעלם כאשר המשתמש בבקבוק או העפרית מת. למרבה המזל, יש סיכוי של 1 מתוך 10 בלבד לכך.

מן הצד האחר, יש גם סיכוי של 1 מתוך 10 שהעפרית של הבקבוק מסוגל להעניק למשתמש 3 משאלות. במקרה זה העפרית אינו מעניק שום שירות אחר, ולאחר הפעלתו אינו יכול לחזור לבקבוק עד שהמשתמש מבקש משאלה. כל משאלה נוספת דורשת הפעלה נוספת, ולאחר הענקת המשאלה האחרונה העפרית נעלם לעד.

גלגלי 1d10 כאשר הבקבוק מופעל בפעם הראשונה. בתוצאה 1 העפרית מטורף, ואילו בתוצאה 0 יש לו 3 משאלות להעניק. אם לא התקבלה אף אחת מתוצאות אלה, העפרית משרת את המשתמש עד שעה אחת ביום במשך 101 ימים, ולאחר מכן הוא משתחרר ונעלם. שימי לב שלאחר ההפעלה הראשונה, כל יום שעובר נספר כחלק מ־101 הימים, בין שהמשתמש מפעיל את הבקבוק ובין שלא.

**שטיח מעופף**: פריט זה נראה כשטיח מפואר מן הסוג שניתן למצוא בטירת מלך. הוא מסוגל לעוף ונושא את העומדים עליו כאילו עמדו על משטח מוצק. שטיח מעופף הוא בדרך כלל בגודל 1.5 על 2.5 מטרים, ויכול לשאת עד 225 ק"ג בקצב תנועה של 30 מטרים לסיבוב, או עד 450 ק"ג, כושר הנשיאה המרבי שלו, בקצב תנועה של 15 מטרים לסיבוב. שטיח מעופף יכול לעוף בכל מהירות עד למהירותו המרבית ולרחף לפי פקודה.

**כפפות כוחו של עוג**: כפפות עור עבות אלה מעניקות ללובש תוסף כוח +4 במקום תוסף הכוח שלו. יש ללבוש את שתי הכפפות כדי שהקסם יפעל.

**אבנט כוחו של ענק**: אבנט עור רחב זה מעניק ללובש את כוחו של ענק. כל עוד הוא נלבש, הלובש מקבל תוסף כוח +5 במקום תוסף הכוח שלו, ויכול להשליך סלעים גדולים כפי שעושה ענק אבן.

**מראת כליאה**: פריט זה עשוי להיראות כמראה עומדת מכל סגנון, או כמראה גדולה יותר. זוהי מלכודת קסומה שניתן להפעיל או לנטרל באמצעות אמירת מילת פקודה ולאחריה "הפעל" או "נטרל".

כאשר המראה פעילה, כל דמות או יצור הנמצאים בטווח של 9 מטרים ממנה ורואים את השתקפותם חייבים להצליח בגלגול הצלה נגד לחשים או להישאב בגופם אל תוך המראה, יחד עם כל החפצים שהם לובשים או נושאים. הקורבן מוכנס לאחד מ־20 תאים מטאפיזיים בתוך המראה. הלכודים במראה אינם אלא השתקפויות ואינם מסוגלים לבצע שום פעולה. הדמות האחרונה שאמרה את מילת הפקודה של המראה חסינה לכוחה, וכך גם אל-מתים, יצירים וכל יצור חסר עיניים.

דמות האומרת את מילת הפקודה ולאחר מכן קוראת במספרו של תא גורמת להשתקפותו של שוכן התא להופיע במראה. היצור הלכוד יכול לנוע ולדבר, אך אינו יכול להטיל לחשים או לבצע כל פעולה ממשית אחרת. הדמות השולטת רשאית לחקור את הקורבן הלכוד, אך המראה אינה כופה עליו להשיב או לומר אמת. הדמות השולטת יכולה בכל עת לומר שוב את מילת הפקודה ולאחריה "חזור", והקורבן מוחזר לתאו; לחלופין, היא יכולה לומר את מילת הפקודה ולאחריה "צא" כדי לשחרר את הקורבן, המופיע כשהוא עומד לצדה.

אם כל התאים מלאים כאשר יצור נשאב אל המראה, תא אחד נבחר באקראי ומתרוקן, והיצור ששוחרר מופיע במקום שבו עמד היצור שנלכד. היצור ששוחרר מוגן מפני המראה במשך תור אחד, ולאחר מכן הוא עלול להילכד בה שוב. כל הקורבנות משתחררים מיד אם המראה נשברת.

**חבל טיפוס**: חבל זה, שאורכו 15 מטרים וקוטרו כ־1.25 סנטימטרים, מסוגל לשאת עד 1,350 ק"ג אם הוא קשור לנקודת עיגון בטוחה. כאשר המשתמש אוחז בקצה אחד של החבל ואומר את מילת הפקודה, החבל מתעורר לחיים ונע כנחש בקצב של 3 מטרים לסיבוב, בכל כיוון שהמשתמש מורה לו. החבל מסוגל אף להתיישר למצב אנכי לחלוטין אם הוא מצווה לעשות זאת. ניתן להורות לו לקשור את עצמו לכל נקודת עיגון שבהישג יד; מכיוון שהמשתמש חייב להמשיך לאחוז בקצה אחד של החבל, הוא יכול להגיע למרחק של עד 15 מטרים מאותה נקודה. לחבל אין כוח ממשי, ולכן הוא אינו יכול להרים משקל או לשאתו אם אינו קשור לנקודת עיגון.

### מכשירים לזימון יסודנים

כל המכשירים האלה מעניקים את הכוח לזמן יסודן ולשלוט בו. כאמור, ייתכן שהמנחה תבחר לאפשר רק סוגים מסוימים של יסודנים, ולכן לא כל המכשירים האלה יהיו זמינים בקמפיין שלך.

כאשר אחד המכשירים האלה מופעל בהתאם לכללי הזימון המתוארים בערך המפלצת יסודן בעמוד 88, מופיע יסודן מן הסוג המתאים ומציית לפקודות המזמן.

**קערה לזימון יסודני מים**: מכשיר זה הוא בגודל של קערת פונץ', ועשוי ממתכות יקרות המשובצות באבני חן. כדי להפעילו, יש למלא אותו במים טריים, לפחות ליטר אחד, ולומר את מילות הפקודה החקוקות סביב שפתו. ההפעלה נמשכת סיבוב שלם.

**אגן אש לזימון יסודני אש**: מכשיר זה נראה כאגן אש קטן: קערת מתכת בעלת רגליים ודפנות דמויות כלוב, שגובהה כ־45 סנטימטרים. אגני אש נועדו להכיל אש. כדי להפעיל את המכשיר, יש להבעיר אש באגן ולומר את מילות הפקודה החקוקות סביב רצועת שפתו. ההפעלה נמשכת סיבוב שלם.

**מבער קטורת לזימון יסודני אוויר**: מכשיר זה נראה כמבער קטורת מעוטר אך רגיל, מעין קערה בעלת מכסה מחורר ושרשרת המשמשת להרמת המכשיר ולנענועו. מכשירים כאלה משמשים בדרך כלל בפולחן, אך מכשיר זה נועד למטרה אחרת. כדי להפעילו, יש להניח קטורת בקערה, להדליק אותה ולכסות את הקערה, ולאחר מכן לומר את מילות הפקודה החקוקות סביב שפת המכסה. ההפעלה נמשכת סיבוב שלם.

**כור היתוך לזימון יסודני מתכת**: מכשיר זה נראה ככור היתוך קטן, כלי פתוח המשמש להמסת מתכת. כדי להפעילו, יש להניח אותו על משטח מוצק ועמיד דיו לחום ולומר את מילות הפקודה החקוקות סביב שפת המכסה. ההפעלה נמשכת סיבוב שלם.

כור ההיתוך מתחמם מאוד כל עוד יסודן המתכת נוכח. הוא גורם 2d8 נקודות נזק לכל דמות המעזה לגעת בו בידיים חשופות, ו־2d6 נקודות נזק גם לדמות הלובשת שריון או כפפות רגילות מבד או מעור. לאחר השימוש נדרש לכור תור שלם כדי להתקרר.

**פטיש עץ לזימון יסודני עץ**: זהו פטיש עץ מן הסוג שבו משתמשים בנאים להחדרת יתדות. ניתן להשתמש בו כנשק, אך הוא נשק גרוע למדי: הוא גורם 1d4 נקודות נזק בפגיעה ואינו נחשב לנשק קסום. כדי להפעילו, יש לאחוז בו ביד ולומר את מילות הפקודה החקוקות על אחד מצדי ראש הפטיש. ההפעלה נמשכת סיבוב שלם.

**לוח שיש לזימון יסודני קור**: מכשיר זה הוא לוח שיש עגול שקוטרו כ־23 סנטימטרים ועוביו כ־2 סנטימטרים. כדי להפעילו, יש להניח אותו כשהוא מאוזן על משטח מוצק ויציב ולשפוך עליו נאד מלא במים טריים. כאשר המים נוגעים בבסיס, הם קופאים באורח קסום לפסל קטן של יסודן קור. לאחר מכן יש לומר את מילות הפקודה החקוקות סביב שפת הלוח. ההפעלה נמשכת סיבוב שלם.

**מקל לזימון יסודני ברק**: מכשיר זה נראה כמקל נחושת שעוביו כ־2 סנטימטרים ואורכו כ־0.6 מטר, ובראשו כדור ענבר מלוטש. פני המקל ירוקים, חלקים ומלוטשים, בשל שכבה דקה של ירוקת, אך המתכת אינה מחוררת או פגומה מן הקורוזיה. כדי להפעילו, יש לאחוז בו ביד ולומר את מילות הפקודה החקוקות לאורכו. ההפעלה נמשכת סיבוב שלם.

**אבן לזימון יסודני אדמה**: מכשיר זה הוא אבן מסותתת בגסות אך מלוטשת היטב, שניתן לראות בה עורק או מקבץ של אבנים יקרות או יקרות למחצה. כדי להפעילו, המשתמש צריך לאחוז בו בשתי ידיו ולומר את מילות הפקודה החקוקות באזור החלק ביותר של האבן. ההפעלה נמשכת סיבוב שלם.
