# גזעי דמויות

## גמדים

**תיאור:** גמדים הם גזע נמוך ומוצק; גובהם של גמדים וגמדות הוא 120 סנטימטרים ומשקלם הוא סביב ה-55 ק"ג. שיערם הארוך והזקנים העבים שלהם הם בצבע חום כהה, אפור או שחור. הם גאים מאוד בזקניהם, ולעיתים קולעים או מפצלים אותם. עורם נע בין בהיר לאדמדם. לגמדים מבנה גוף חסון ושרירי. הם קשוחים ועמידים, עם יכולת לעמוד בקשיים גדולים. גמדים הם בדרך כלל מעשיים, עקשנים ואמיצים. הם יכולים להיות גם מהורהרים, חשדנים ורכושניים. תוחלת חייהם היא בין שלוש לארבע מאות שנה.

**מגבלות:** גמדים יכולים להיות [כוהנים](class.qmd#cleric), [לוחמים](class.qmd#fighter), או [גנבים](class.qmd#thief). הם נדרשים להיות בעלי חוסן מינימלי של 9. בשל נטייתם הכללית להיות קודרים, הם לא יכולים להיות בעלי כריזמה גבוהה מ-17. הם אינם יכולים להשתמש בנשקים ארוכים יותר מ-120 סנטימטרים (במיוחד חרבות דו-ידניות, נשקי מוט וקשתות ארוכות).

**יכולות מיוחדות:** לכל הגמדים יש [זיוונות](dungeonAdventures.qmd#darkvision) בטווח של 20 מטר, והם מסוגלים לגלות מעברים משופעים, מלכודות, קירות נעים ובנייה חדשה בגלגול של 1-2 ב-1d6; יש לבצע חיפוש לפני שניתן לבצע את הגלגול הזה.

**גלגולי הצלה:** גמדים מקבלים תוסף +4 נגד קרן מוות או רעל, שרביטי קסם, שיתוק או הפיכה לאבן, ולחשים, ו-+3 נגד נשיפת דרקון.

## אלפים

**תיאור:** אלפים הם גזע דק, כאשר גובה שני המינים הוא מטר וחצי ומשקלם 60 ק"ג. לרובם שיער כהה, עם מעט או ללא שיער גוף או פנים. עורם חיוור, ויש להם אוזניים מחודדות ותווי פנים עדינים. אלפים הם גמישים וחינניים. יש להם ראייה ושמיעה חדה. אלפים הם בדרך כלל סקרנים, נלהבים, בטוחים בעצמם ולעיתים יהירים. תוחלת חייהם הטיפוסית היא תריסר מאות או יותר.

**מגבלות:** אלפים יכולים להיות [כוהנים](class.qmd#cleric), [לוחמים](class.qmd#fighter), [קוסמים](class.qmd#magic-users), או [גנבים](class.qmd#thief); הם גם רשאים לשלב את מקצועות הלוחם והקוסם, ואת מקצועות הקוסם והגנב (ראו [מקצועות משולבים](class.qmd#combination-classes)). הם נדרשים להיות בעלי תבונה מינימלית של 9. בשל טבעם העדין בדרך כלל, הם לא יכולים להיות בעלי חוסן גבוה מ-17. אלפים לעולם לא מגלגלים קוביות גדולות יותר מקוביות בעלות שש פאות (d6) לנקודות פגיעה.

**יכולות מיוחדות:** לכל האלפים יש [זיוונות](dungeonAdventures.qmd#darkvision) בטווח של 20 מטר. הם מסוגלים למצוא דלתות סודיות לעיתים קרובות יותר מהרגיל (1-2 ב-1d6 במקום 1 ב-1d6 הרגיל). אלף כל כך חד עין שיש לו סיכוי של 1 ב-1d6 למצוא דלת סודית במבט חטוף. אלפים חסינים להתקפת השיתוק של גולים. בנוסף, הם פחות סבירים להיות מופתעים בקרב, ומפחיתים את סיכוי ההפתעה ב-1 ב-1d6.

**גלגולי הצלה:** אלפים מקבלים תוסף +1 נגד שיתוק או הפיכה לאבן, ו-+2 נגד שרביטי קסם ולחשים.

## בני-מחצית

**תיאור:** בני-מחצית הם אנשים קטנים ומעט מוצקים שגובהם מגיע ל-90 סנטימטרים ומשקלם כ-30 ק"ג. יש להם שיער חום מתולתל על ראשם ורגליהם, אך לעיתים רחוקות יש להם שיער פנים. הם בדרך כלל בעלי עור בהיר, לעיתים עם לחיים אדמדמות. בני-מחצית הם קשוחים להפליא לגודלם הקטן. הם זריזים ונמרצים, מסוגלים לנוע בשקט ולהישאר מאוד דוממים. הם בדרך כלל הולכים יחפים. בני-מחצית הם בדרך כלל חברותיים, צנועים ובעלי טבע טוב. הם חיים כמאה שנה.

**מגבלות:** בני-מחצית יכולים להיות [כוהנים](class.qmd#cleric), [לוחמים](class.qmd#fighter), או [גנבים](class.qmd#thief). הם נדרשים להיות בעלי זריזות מינימלית של 9. בשל גודלם הקטן, הם לא יכולים להיות בעלי כוח גבוה מ-17. בני-מחצית לעולם לא מגלגלים קוביות גדולות יותר מקוביות בעלות שש פאות (d6) לנקודות פגיעה ללא קשר למקצוע. בני-מחצית אינם יכולים להשתמש בנשקים גדולים, וחייבים להשתמש בנשקים בינוניים בשתי ידיים.

**יכולות מיוחדות:** בני-מחצית מדויקים במיוחד עם כל סוגי הנשקים לטווח, ומקבלים בונוס תקיפה של +1 כאשר הם משתמשים בהם. כאשר הם מותקפים בקרב פנים אל פנים על ידי יצורים גדולים יותר מאדם, בני-מחצית מקבלים בונוס של +2 לדירוג השריון שלהם. בני-מחצית הם מהירי מחשבה, ולכן מוסיפים +1 לגלגולי היוזמה. בחוץ, בשטח היער המועדף עליהם, הם מסוגלים להסתתר ביעילות רבה; כל עוד הם נשארים דוממים, יש רק סיכוי של 10% שהם יזוהו. גם בתוך מבוכים או בשטח שאינו מועדף עליהם, הם מסוגלים להסתתר כך שיש רק סיכוי של 30% לזיהוי. שימו לב שגנב בן-מחצית יגלגל רק פעם אחת, תוך שימוש ביכולת הגנב או ביכולת בן-המחצית, לפי מה שעדיף.

**גלגולי הצלה:** בני-מחצית מקבלים תוסף +4 נגד קרן מוות או רעל, שרביטי קסם, שיתוק או הפיכה לאבן, ולחשים, ו-+3 נגד נשיפת דרקון.

## בני אדם

**תיאור:** בני אדם מגיעים במגוון רחב של צורות וגדלים; על מנחת המשחק להחליט אילו סוגי בני אדם חיים בעולם המשחק. גובה גבר ממוצע ובריא הוא 180 סנטימטרים ומשקלים כ-80 ק"ג. רוב בני האדם חיים כ-75 שנה.

**מגבלות:** בני אדם יכולים להיות בכל מקצוע יחיד. אין להם דרישות מינימום או מקסימום לערכי תכונות.

**יכולות מיוחדות:** בני אדם לומדים במהירות יוצאת דופן, ומקבלים בונוס של 10% לכל נקודות הניסיון שהם מרוויחים.

**גלגולי הצלה:** בני אדם הם ה"סטנדרט", ולכן אין להם בונוסים לגלגולי הצלה.

