# לחשים


מספר הלחשים מכל עוצמה שכוהן או קוסם יכולים להטיל ביום מוצג בטבלה המתאימה בסעיף [דמויות](class.qmd#character-classes). כל יום, בדרך כלל בבוקר, מטילי לחשים מכינים לחשים כדי להחליף את אלו שהשתמשו בהם. כוהנים עושים זאת באמצעות תפילה, בעוד קוסמים חייבים ללמוד מתוך ספרי הלחשים שלהם. לחשים שהוכנו ולא נוצלו נשארים מיום ליום; רק אלו שהוטלו בפועל חייבים להיות מוחלפים. מטיל לחש יכול תמיד לבחור לבטל לחש מוכן (בלי להטילו) כדי להכין לחש אחר מאותה עוצמה.

מטילי לחשים חייבים להחזיק לפחות יד אחת חופשית ולהיות מסוגלים לדבר כדי להטיל לחשים; לכן, קשירה והשתקה של מטיל לחש הן דרך יעילה למנוע ממנו להטיל לחשים. בקרב, הטלת לחש אורכת בדרך כלל אותו זמן כמו ביצוע התקפה. אם מטיל לחש מותקף (גם אם לא נפגע) או נדרש לבצע גלגול הצלה (בין אם הצליח ובין אם לא) במספר היוזמה שבו הוא מטיל לחש, הלחש נכשל ונאבד. כיוצא דופן ספציפי, שני מטילי לחשים המשחררים את לחשיהם זה על זה באותו מספר יוזמה יצליחו שניהם בהטלה; מטיל לחש אחד יכול להפריע לאחר עם לחש רק אם יש לו יוזמה טובה יותר, והוא בוחר לעכב את הטלת הלחש עד *ממש לפני* המטיל האחר.

חלק מהלחשים הם הפיכים; לחשים כאלה מוצגים עם כוכבית אחרי השם.


## לחשי כוהן

כוהנים מקבלים את לחשיהם באמצעות אמונה ותפילה. כל יום, בדרך כלל בבוקר, כוהן חייב להתפלל לפחות 3 תורות כדי להכין לחשים. כמובן, ייתכן שעל הכוהן להתפלל יותר מכך כדי להישאר בחסדי האל שלו.

מכיוון שהם מקבלים את לחשיהם באמצעות תפילה, כוהן יכול להכין כל לחש בכל עוצמה שהוא מסוגל להטיל. עם זאת, במקרים מסוימים האל של הכוהן עשוי להגביל את זמינותם של לחשים מסוימים; לדוגמה, אל המוקדש לריפוי עשוי לסרב להעניק לחשי ריפוי הפוכים.


::: {.callout-tip icon=false collapse=true}

### עוצמה 1, כוהן

::: {.callout-note icon=false collapse=true}

### ריפוי פצעים קלים*

כוהן 1

טווח: מגע

משך: מיידי

לחש זה מרפא 1d6+1 נקודות פגיעה באמצעות מגע במטרה.

בהיפוך, לחש זה הופך ל**גרימת פצעים קלים**, הגורם ל־1d6+1 נקודות פגיעה למטרה. במקרה זה נדרש גלגול התקפה; אם ההתקפה מחטיאה, הלחש מתבזבז.

יצורים אל־מתים מושפעים באופן הפוך: הם סופגים נזק מ**ריפוי פצעים קלים** ונרפאים על ידי **גרימת פצעים קלים**.

:::

::: {.callout-note icon=false collapse=true}

### גילוי רוע*

טווח: 20 מ'

כוהן 1, קוסם 2

משך: סיבוב אחד/דרגה

לחש זה מאפשר למטיל לגלות רוע; באופן ספציפי, המטיל יכול לגלות יצורים בעלי כוונות רעות, חפצי קסם בעלי השפעות רעות, ואולי יצורים חוצניים בעלי טבע רע. דמויות רגילות, אפילו "רעות", אינן ניתנות לגילוי על ידי לחש זה, שכן רק רוע חזק במיוחד ניתן לגילוי. המטיל רואה את היצורים או החפצים ה"רעים" מוקפים בזוהר ברור, אך הזוהר אינו נראה על ידי אף אחד אחר.

ההגדרה המדויקת של רוע נתונה להחלטת המנחה. שימי לב כי פריטים כמו מלכודות רגילות או רעלים אינם "רעים", ולכן אינם ניתנים לגילוי על ידי לחש זה.

בהפוך, לחש זה הופך ל**גילוי טוב**, הפועל בדיוק כפי שתואר לעיל ביחס לגילוי כישופים "טובים", יצורים מלאכיים, וכדומה.

:::

::: {.callout-note icon=false collapse=true}

### גילוי קסם

טווח: 20 מ'

כוהן 1, קוסם 1

משך: 2 תורות

המטיל של לחש זה מסוגל לגלות חפצים או יצורים מכושפים או תחת השפעת לחש בטווח הנתון באמצעות ראייה, ורואה אותם מוקפים באור זוהר חיוור. רק המטיל רואה את הזוהר. יצורים או חפצים נעלמים מעין אינם ניתנים לגילוי על ידי לחש זה, אך ההקרנות של קסם ההיעלמות ייראו כערפל זוהר אמורפי, מה שעשוי לאפשר למטיל (ורק לו) לתקוף את היצור הנעלם בעונש של -2 לגלגולי התקפה בלבד.

:::

::: {.callout-note icon=false collapse=true}

### אור

טווח: 40 מ'

כוהן 1, קוסם 1

משך: 6 תורות + 1/דרגה

לחש זה יוצר אור בעוצמה של לפיד, המאיר ברדיוס של 9 מטרים סביב נקודה או חפץ מטרה. אם הלחש מוטל על אזור, האור קבוע במקומו; אם הוא מוטל על חפץ, האור נע יחד איתו. אור זה אינו פועל בתוך אזור של חושך קסום.

בהיפוך, **אור** הופך ל**חושך**, ויוצר אזור חשוך בהתאם לאמור לעיל. חושך זה חוסם זיוונות ומבטל מקורות אור רגילים.

לחש אור יכול לנטרל ולבטל לחש חושך של מטיל באותה דרגה או נמוכה יותר (ולהיפך). במקרה זה, שני הלחשים נפסקים מיד, ורמת האור חוזרת למצבה הקודם.

כל גרסה של לחש זה יכולה לשמש לעיוור יריב על ידי הטלתה על איברי הראייה שלו. המטרה רשאית לגלגל גלגול הצלה נגד קרן מוות כדי להימנע מההשפעה; אם ההצלה מצליחה, הלחש אינו פועל. כאשר הלחש משמש לעיוור, הוא אינו משפיע על האזור (כלומר, אינו יוצר אור או חושך סביב המטרה).

:::

::: {.callout-note icon=false collapse=true}

### הגנה מרוע*

כוהן 1, קוסם 1

טווח: מגע

משך: 1 תור/דרגה

לחש זה מגן על המטיל או על יצור שנגע בו המטיל ("הנושא") מרוע; באופן ספציפי, הלחש מגן מפני יצורים מזומנים, יצורים עם כוונות רעות משמעותיות, ויצורים חוץ-מישוריים בעלי טבע רע. מחסום קסום ברדיוס של 0.5 מטרים בלבד נוצר סביב הנושא. המחסום נע עם הנושא, ומספק שלושה סוגים ספציפיים של הגנה קסומה מפני התקפות או אפקטים אחרים שניסו היצורים המושפעים נגד הנושא.

ראשית, הנושא מקבל בונוס של +2 לדירוג השריון שלו, ובונוס דומה של +2 על כל גלגולי ההצלה. שנית, המחסום חוסם כל ניסיון להקסים או לשלוט בנושא, או להחזיק את הנושא (כמו עם **בקבוק קסם**). ניסיונות כאלה פשוט נכשלים במהלך משך הלחש הזה. עם זאת, יש לציין שיצור שמקבל הגנה זו לאחר שהוחזק אינו נרפא מההחזקה.

שלישית, כל היצורים המזומנים והיצורים החוץ-מישוריים בעלי טבע רע אינם יכולים לגעת פיזית בנושא. התקפות על ידי יצורים כאלה באמצעות נשקיהם הטבעיים פשוט נכשלות. אפקט זה מבוטל אם הנושא מבצע כל סוג של התקפה פיזית (אפילו עם נשק טווח) על כל יצור מושפע, אך שאר תכונות הלחש ממשיכות לפעול.

בהיפוך, לחש זה הופך ל**הגנה מטוב**. הוא פועל בכל הדרכים כפי שתואר לעיל, למעט שיצורים "טובים" נשמרים במרחק, במקום "רעים".

:::

::: {.callout-note icon=false collapse=true}

### טיהור מזון ומים

כוהן 1

טווח: 3 מ'

משך: מיידי

לחש זה הופך מזון או מים מזוהמים לטהורים ובטוחים לאכילה או לשתייה. רעל מנוטרל וריקבון מתהפך באמצעות לחש זה. עם זאת, הלחש אינו מגן מפני ריקבון עתידי, ואינו משפיע על שיקויים קסומים (כולל, למרבה הצער, **שיקויי רעל**). מים לא קדושים, אם הם קיימים במערכה שלך, נהרסים בעת הטלת לחש זה. הלחש משפיע על כ־1 ק"ג מזון ו/או שתייה לכל דרגת מטיל; יש לציין כי ליטר מים או שתייה דומה שוקלים 1 ק"ג.

:::

::: {.callout-note icon=false collapse=true}

### סילוק פחד

טווח: מגע (40 מ')

כוהן 1

משך: מיידי (2 תורות)

לחש זה מרגיע את היצור שבו נוגע המטיל. אם יצור המטרה נתון לפחד קסום, הוא רשאי לגלגל גלגול הצלה נוסף נגד לחשים כדי להתנגד לפחד, עם בונוס של +1 לכל דרגת מטיל.

בהיפוך, לחש זה הופך ל**גרימת פחד**, הגורם ליצור אחד בטווח של 40 מטרים להיבהל; אם המטרה נכשלת בגלגול הצלה נגד לחשים, היא בורחת למשך 2 תורות. יצורים בעלי 6 קוביות פגיעה או יותר חסינים לאפקט זה.

:::

::: {.callout-note icon=false collapse=true}

### חסינות לקור

טווח: מגע

כוהן 1

משך: 1 סיבוב/דרגה

לחש זה הופך את המטיל, או כל יצור חי שבו הוא נוגע, לחסין לחלוטין לקור רגיל. הלחש גם מעניק הגנה מפני קור קסום או עליון, כגון נשיפת דרקון קרח או לחש **סופת קרח**. באופן ספציפי, הלחש מעניק ליצור המוגן בונוס של +3 לכל גלגולי ההצלה נגד השפעות כאלה, ומפחית כל נזק שנגרם לחצי (כך שלמשל גלגול הצלה מוצלח נגד נשיפת דרקון קרח מפחית את הנזק לרבע מהרגיל, ואפילו אם גלגול ההצלה נכשל, היצור המוגן סופג רק חצי מהנזק).

:::

:::

::: {.callout-tip icon=false collapse=true}

### עוצמה 2, כוהן

::: {.callout-note icon=false collapse=true}

### ברכה

טווח: רדיוס 15 מ'

כוהן 2

משך: 1 דקה/דרגה

לחש זה נותן למטיל הלחש ולבעלי בריתו בתוך רדיוס של 15 מטרים בונוס של +1 על כל גלגולי ההתקפה, בדיקות מורל (למפלצות או דמויות שאינן שחקן שבעלות ברית עם מטיל הלחש), וגלגולי הצלה נגד כל סוג של **פחד** קסום. מטילים בדרגה 7 או יותר מעניקים בונוס של +2 להתקפות ולגלגולי הצלה נגד **פחד**, אך בונוס המורל נשאר +1.

ההיפוך של **ברכה** נקרא **קללה**. יריבים המצויים ברדיוס של 15 מטרים הופכים לפחדנים וחסרי בטחון, מה שגורם להם לסבול מעונש של -1 על גלגולי ההתקפה, בדיקות המורל, וגלגולי הצלה נגד כל סוג של **פחד** קסום. מטילים בדרגה 7 או יותר מעניקים עונש של -2 להתקפות ולגלגולי הצלה נגד **פחד**, אך עונש המורל נשאר -1.

:::

::: {.callout-note icon=false collapse=true}

### הקסמת חיה

טווח: 20 מ'

כוהן 2

משך: דרגה + 1d4 סיבובים

```{ojs}
// function rolld4() {
//   var randomNumber = Math.floor(Math.random() * 4) + 1;
//   return randomNumber;
// }

import {rolld4} from "../custom.js"

viewof click = Inputs.button("גלגל 1d4", {value: 0, reduce: () => rolld4()})
```

1d4 = ${click}

לחש זה מאפשר למטיל להקסים חיה אחת או יותר, בדומה ל**הקסמת איש**, בקצב של 1 קוביית פגיעה לכל דרגת מטיל. המטיל בוחר אילו חיות מושפעות תחילה מתוך קבוצה מעורבת; קוביות פגיעה עודפות אינן מנוצלות. לא ניתן גלגול הצלה לחיות רגילות או לחיות ענקיות, אך יצורים בעלי טבע פנטסטי יותר (לפי קביעת המנחה) מקבלים גלגול הצלה נגד לחשים כדי להתנגד. כאשר משך הלחש פג, החיות חוזרות מיד להתנהגות רגילה.

לחש זה אינו מעניק למטיל אמצעי תקשורת מיוחדים עם החיות המושפעות. בשילוב עם **שיחת חיות**, הוא הופך לשימושי יותר.

:::

::: {.callout-note icon=false collapse=true}

### מציאת מלכודות

טווח: 10 מ'

כוהן 2

משך: 3 תורות

לחש זה מאפשר למטיל לגלות מלכודות, הן מכניות והן קסומות. כאשר המטיל נמצא בטווח של 10 מטרים ממלכודת, היא נראית לו כזוהרת בהילה ירקרקה-כחולה חלשה. עם זאת, הלחש אינו מגלה סכנות טבעיות כגון חול טובעני, בולענים או קירות סלע לא יציבים. הלחש גם אינו מעניק למטיל את הידע הדרוש לנטרול המלכודת, או מידע על סוגה או טבעה.

:::

::: {.callout-note icon=false collapse=true}

### עצירת איש

טווח: 50 מ'

כוהן 2, קוסם 3

משך: 2d8 תורות

לחש זה משתק כל יצור דמוי-אדם חי (לא אל-מת), כפי שמוגדר ב**הקסמת איש**. יצורים גדולים מעוג אינם מושפעים מלחש זה. מטרות הלחש מודעות ויכולות לנשום, אך אינן יכולות לנוע, לפעול או לדבר. גלגול הצלה נגד לחשים מאפשר להתנגד לאפקט. ניתן להטיל את הלחש על יצור אחד, אשר סופג מחסר של 2- לגלגול ההצלה, או על קבוצה; במקרה זה, 1d4 יצורים בקבוצה עשויים להיות מושפעים.

יצור משותק במים אינו יכול לשחות ועלול לטבוע. יצור מעופף שמשותק באוויר אינו יכול להמשיך לעוף ונופל לקרקע.

:::

::: {.callout-note icon=false collapse=true}

### חסינות לאש

טווח: מגע

כוהן 2

משך: סיבוב/דרגה

לחש זה הופך את המטיל, או כל יצור חי שבו הוא נוגע, לחסין לחלוטין לחום או לאש רגילים. הלחש גם מעניק הגנה מפני חום או אש קסומים או עליונים, כגון נשיפת דרקון או לחש **כדור אש**. באופן ספציפי, הלחש מעניק ליצור המוגן בונוס של +3 לכל גלגולי ההצלה נגד השפעות כאלה, ומפחית כל נזק שנגרם לחצי (כך שלמשל גלגול הצלה מוצלח נגד לחש **כדור אש** מפחית את הנזק לרבע מהרגיל, ואפילו אם גלגול ההצלה נכשל, היצור המוגן סופג רק חצי מהנזק).

:::

::: {.callout-note icon=false collapse=true}

### שקט ברדיוס 5 מ'

כוהן 2

טווח: 100 מ'

משך: 2 סיבובים/דרגה

לחש זה יוצר אזור כדורי ברדיוס של 5 מטרים שבו קול אינו עובר. יצורים בתוך האזור אינם יכולים להפיק או לשמוע קול, וקול גם אינו יוצא מהאזור; יצורים מחוצה לו אינם שומעים את הנמצאים בתוכו. אפקט זה מונע תקשורת מילולית, וכן הטלת לחשים.

ניתן להטיל את האפקט על אזור קבוע, על חפץ (וכך להפוך אותו לנייד), או על יצור. מטרה שאינה מעוניינת מקבלת גלגול הצלה נגד לחשים כדי לבטל את האפקט. אם חפץ שבחזקת יצור הוא המטרה, אותו יצור מקבל גם הוא גלגול הצלה.

הלחש יכול לשמש כהגנה מפני התקפות או קסמים הדורשים שמיעה של הקורבן, שכן אפקטים כאלה אינם פועלים אל תוך האזור או מתוכו.

:::

::: {.callout-note icon=false collapse=true}

### שיחת חיות

כוהן 2

טווח: מיוחד

משך: 1 תור/4 דרגות

לחש זה מאפשר למטיל לדבר עם חיה בודדת ולהבין אותה (בגודל רגיל או ענק, אך לא קסומה או מפלצתית), כל עוד היא נמצאת בטווח ראייה ויכולה לשמוע אותו. המטיל יכול להחליף את החיה עמה הוא מדבר פעם אחת בכל סיבוב.

הלחש אינו משנה את תגובת החיה או את גישתה כלפי המטיל; יש לבצע גלגול תגובה כרגיל כדי לקבוע זאת. המנחה צריכה להבטיח שאופן הדיבור של החיה ישקף את האינטליגנציה והטבע שלה.

:::

::: {.callout-note icon=false collapse=true}

### פטיש רוחני

טווח: 10 מ'

כוהן 2

משך: 1 סיבוב/דרגה

לחש זה יוצר פטיש מלחמה עשוי כוח טהור, התוקף פעם אחת בכל סיבוב אויב שנבחר על ידי המטיל בטווח. הפטיש גורם ל־1d6 נקודות פגיעה לכל פגיעה, בתוספת 1+ לכל שלוש דרגות מטיל (עד למקסימום של +5). הוא משתמש בבונוס ההתקפה הרגיל של המטיל, נחשב כנשק קסום, ולכן יכול לפגוע ביצורים שנפגעים רק מנשקים קסומים.

אם הפטיש יוצא מטווח הלחש, אם המטיל מאבד קשר עין איתו, או אם המטיל מפסיק להנחות אותו, הפטיש נעלם. הפטיש אינו יכול להיות מותקף או להיפגע מהתקפות פיזיות, אך **ביטול קסם**, **התפוררות** או **מטה ביטול** מבטלים אותו.

:::

:::

::: {.callout-tip icon=false collapse=true}

# עוצמה 3, כוהן

::: {.callout-note icon=false collapse=true}

### אור תמידי*

טווח: 100 מ'

כוהן 3, קוסם 2

משך: שנה/דרגה

לחש זה יוצר אזור כדורי של אור, בעוצמה של אור יום מלא עד רדיוס של 10 מטרים, ובעוצמה פחותה עד רדיוס של 18 מטרים. ניתן להטיל את הלחש על חפץ, על נקודה באוויר, או על יצור, כמו בלחש **אור**, עד לטווח של 100 מטרים מהמטיל. הלחש נמשך שנה לכל דרגה של המטיל.

כמו בלחש **אור**, ניתן להשתמש בלחש זה כדי לעוור יצור על ידי הטלתו על איברי הראייה שלו. המטרה רשאית לגלגל גלגול הצלה נגד קרן מוות; אם ההצלה מצליחה, הלחש מוטל בנקודה באוויר ממש מאחורי המטרה. אם ההצלה נכשלת, המטרה עיוורת וסופגת עונש של -4 לגלגולי ההתקפה שלה.

הלחש ההפוך, **חושך תמידי**, יוצר אזור של היעדר מוחלט של אור, ומתגבר על מקורות אור רגילים. ניתן להשתמש בו לעיוור באותו אופן כמו אור תמידי.

:::

::: {.callout-note icon=false collapse=true}

### ריפוי עיוורון*

טווח: מגע

כוהן 3

משך: מיידי

לחש זה מאפשר למטיל לרפא יצור הסובל מעיוורון, בין אם נגרם מפציעה או מקסם (כולל **אור** או **אור תמידי**). עיוורון שנגרם מקללה אינו ניתן לריפוי בלחש זה.

בהיפוך, לחש זה הופך ל**גרימת עיוורון**, הגורם ליצור חי שנוגעים בו להתעוור. נדרש גלגול התקפה כדי לגעת במטרה, ולא מתאפשר גלגול הצלה. יצורים עיוורים סובלים מהמחסרים המתוארים ב[חירשות ועיוורון](combat.qmd#חירשות-ועיוורון).

:::

::: {.callout-note icon=false collapse=true}

### ריפוי מחלה*

טווח: מגע

כוהן 3

משך: מיידי

לחש זה מרפא את כל המחלות ומחסל את כל הטפילים הפוגעים ביצור המטרה. מחלה קסומה או מיוחדת אחרת (לפי קביעת המנחה) עשויה שלא להיות מושפעת מהלחש, או לדרוש מטיל בדרגה מסוימת כדי לרפאה. הסרת מחלה או טפיל אינה מונעת הדבקה מחדש אם הקורבן נחשף שוב לגורם.

בהיפוך, לחש זה הופך ל**גרימת מחלה**, הגורם ליצור חי שנוגעים בו לסבול ממחלה מחלישה ומסכנת חיים למשך 1d10 ימים. נדרש גלגול התקפה כדי לגעת במטרה, ולא מתאפשר גלגול הצלה. המטרה סובלת ממחסר של 2- לגלגולי התקפה, דירוג שריון וגלגולי הצלה. בזמן שהקורבן חולה, הוא אינו נהנה מריפוי טבעי של נקודות פגיעה או מהשבת נקודות חוסן, ואינו יכול להכין לחשים או לנוע במהירות ריצה.

בסוף כל יום שבו דמות נגועה ביצעה מאמץ (כגון לחימה, נסיעה, עבודה או מחקר קסום), עליה לגלגל גלגול הצלה נגד לחשים או לספוג 1d6 נקודות פגיעה. כאשר משך הלחש מסתיים, הדמות המושפעת, אם היא עדיין בחיים, נרפאת מהמחלה ויכולה לשוב לרפא נזק ולהשיב נקודות חוסן, וכן להכין לחשים כרגיל.

:::

::: {.callout-note icon=false collapse=true}

### גדילת חיות

כוהן 3

טווח: 18 מ'+3 מ'/דרגה

משך: 1 תור/דרגה

לחש זה גורם לחיה לגדול לכפליים מגודלה הרגיל ולפי שמונה ממשקלה הרגיל. היצור המושפע גורם לנזק כפול מהרגיל בכל התקפותיו הפיזיות, ודירוג השריון הטבעי הקיים שלו גדל ב-2. כושר הנשיאה של החיה גם מוכפל. חיות לא ידידותיות רשאיות לגלגל הצלה נגד לחשים כדי להתנגד ללחש זה; בדרך כלל, חיות מבויתות לא ינסו להתנגד לו, אם כי הן עשויות להתבלבל או להיכנס לפאניקה לאחר מכן (לפי שיקול דעתה של המנחה).

כל הציוד הנלבש או הנישא על ידי החיה מוגדל באופן דומה על ידי הלחש, אם כי שינוי זה אינו משפיע על התכונות הקסומות של ציוד כזה. כל פריט מוגדל שעוזב את החזקת היצור המוגדל חוזר מיד לגודלו הרגיל.

הלחש אינו מעניק אמצעי פיקוד או שליטה על החיות המוגדלות.

:::

::: {.callout-note icon=false collapse=true}

### איתור עצם

טווח: 100 מ'

כוהן 3, קוסם 2

משך: סיבוב/דרגה

לחש זה מעניק למטיל ידע על מיקומו של חפץ. על המטיל להכיר את החפץ היטב או להיות מסוגל לדמיין אותו בבירור (צפייה בציור או תמונה מדויקת מספיקה לכך). ניתן לאתר חפץ כללי; אם יותר מחפץ אחד כזה נמצא בטווח, הלחש מוביל את המטיל אל הקרוב ביותר.

חפצים ייחודיים או יוצאי דופן ניתנים לאיתור רק אם למטיל יש ידע ממקור ראשון (לא באמצעות חיזוי כמו **ראייה על חושית** או **כדור בדולח**). הלחש אינו יכול לשמש לאיתור יצורים מכל סוג. שכבה דקה מאוד של עופרת או זהב המקיפה את החפץ מונעת את איתורו.

:::

::: {.callout-note icon=false collapse=true}

### הסרת קללה*

טווח: 10 מ'

כוהן 3, קוסם 4

משך: מיידי

לחש זה מסיר כל קללה רגילה הפוגעת ביצור. הוא אינו מסיר בדרך כלל את הקללה מפריט קסום כמו חרב או חליפת שריון, אך דמות המושפעת מפריט מקולל מסוג זה תשתחרר ממנו למשך זמן מספיק כדי להשליך את הפריט (לפחות תור).

חלק מהקללות המיוחדות קשות יותר להסרה, ועשויות לדרוש מטיל לחש בדרגה מינימלית מסוימת. מעט מאוד קללות שנוצרו על ידי ישויות אלוהיות ניתנות להסרה באמצעות לחש זה.

ההיפוך של הלחש הזה, **הטלת קללה**, מאפשר למטיל הלחש להטיל קללה על הנושא. גלגול הצלה נגד לחשים מאפשר להתנגד. המטיל חייב לבחור אחת משלוש ההשפעות הבאות:

* הפחתה של 4- לציון תכונה (מינימום 1).

* עונש של 4- על גלגולי תקיפה וגלגולי הצלה.

* בכל סיבוב קרב, יש למטרה סיכוי של 50% לפעול כרגיל; אחרת, היא אינה נוקטת בפעולה.

המטיל יכול גם להמציא קללה משלו, אך היא אינה יכולה להיות חזקה יותר מאלו שתוארו לעיל. הקללה המוטלת אינה ניתנת לביטול, אך ניתן להסירה באמצעות לחש **הסרת קללה**.

:::

::: {.callout-note icon=false collapse=true}

### דיבוב מתים

טווח: 3 מ'

כוהן 3

משך: 3 סיבובים/דרגה

באמצעות לחש זה המטיל גורם לגופה של יצור אינטליגנטי להתעורר ולענות על שאלותיו. לא משנה כמה זמן הגופה מתה, אך היא חייבת להיות שלמה בעיקרה, עם לפחות פה שלם כדי לענות. הגופה תענה על מקסימום שאלה אחת לכל שתי דרגות של המטיל; אם הזמן פג, כל השאלות הנותרות אובדות. הגופה יודעת רק את מה שידעה בחייה; זה כולל את השפות שידעה. לכן, המטיל חייב לחלוק שפה עם הנפטר כדי לקבל תשובות.

התשובות הניתנות נלקחות מידע "מוטבע" בגופה במהלך החיים; המטיל אינו מתקשר למעשה עם רוח היצור הנפטר. הגופה אינה יכולה לשמור מידע חדש שניתן לה, ואינה זוכרת אף מקרה קודם של תקשורת באמצעות לחש זה.

התשובות הניתנות עשויות שלא להיות מועילות מסיבות שונות. אם הגופה הכירה את המטיל כשהייתה בחיים, או אם המטיל הוא חבר בקבוצה שהנפטר לא חיבב, היא עשויה לבחור לשקר או להטעות. אם המטיל שואל שאלות אישיות, או שאלות המרמזות כי הוא עשוי לפעול נגד האינטרסים שהיו לגופה בחייה, היא כמעט בוודאות תנסה להטעות.

אם הגופה הועלתה באמצעות לחש זה בתוך שבעת הימים האחרונים, הלחש ייכשל. יצורים אל-מתים (כולל שרידים של יצורים אל-מתים מובסים) אינם יכולים להיות מושפעים מלחש זה.

:::

::: {.callout-note icon=false collapse=true}

### הכאה

טווח: מגע

כוהן 3

משך: 1 סיבוב/דרגה

לחש זה מעניק לנשק אחד את היכולת לגרום ל-1d6 נקודות נזק נוספות. נזק נוסף זה מוחל על כל התקפה מוצלחת למשך הלחש. הוא אינו מספק בונוס התקפה, אך אם מוטל על נשק רגיל, הלחש מאפשר לפגוע במפלצות שנפגעות רק על ידי נשקים קסומים; רק 1d6 נקודות הנזק הקסום מוחלות על מפלצת כזו.

:::

:::

::: {.callout-tip icon=false collapse=true}

# עוצמה 4, כוהן

::: {.callout-note icon=false collapse=true}

### הנפשת מתים

טווח: 10 מ'

כוהן 4, קוסם 5

משך: מיוחד

הטלת לחש זה גורמת לשרידי יצורים מתים אחד או יותר לקום כשלדים או זומבים מונפשים. מפלצות אל-מתים אלו נשארות עד שהן נהרגות, ומצייתות לפקודותיו המילוליות של מטיל הלחש. הטלה אחת של לחש זה יכולה להנפיש מספר קוביות פגיעה של אל-מתים השווה לפי 2 מדרגת היכולת של מטיל הלחש, ולא יותר. לשלדים מונפשים יש קוביות פגיעה השוות למספר שהיה ליצור בחייו; עבור שלדים של בני גזעי דמויות שחקן, משמעות הדבר היא קוביית פגיעה אחת, ללא קשר לדרגת הדמות של המת. לזומבים יש קוביית פגיעה אחת יותר מאשר ליצור שהיה בחייו.

סוג המפלצות שנוצר תלוי במצב השרידים. גופה שלמה יחסית יכולה לקום רק כזומבי, בעוד ששרידי שלד שלמים יחסית יכולים להיות מונפשים רק כשלד. מטיל הלחש בוחר אילו שרידים להנפיש בעת הטלת הלחש, בכל מקרה שבו יש יותר גופות ממה שהוא יכול להנפיש.

שום דמות אינה יכולה לשלוט בדרך כלל ביותר קוביות פגיעה של אל-מתים מפי 4 מדרגתה, ללא קשר למספר הפעמים שבהן הלחש הזה מוטל.

:::

::: {.callout-note icon=false collapse=true}

### יצירת מים

טווח: 3 מ'

כוהן 4

משך: קבוע

לחש זה יוצר 4 ליטרים של מים לכל דרגת מטיל. יש לוודא כי כלי קיבול אחד או יותר זמינים בעת ההטלה. המים שנוצרים באמצעות לחש זה דומים למי גשם נקיים. הערה: מים שוקלים 1 ק"ג לכל ליטר.

:::

::: {.callout-note icon=false collapse=true}

### ריפוי פצעים קשים*

כוהן 4

טווח: מגע

משך: מיידי

לחש זה פועל בדיוק כמו **ריפוי פצעים קלים**, אלא שהוא מרפא 2d6 נקודות נזק, ועוד נקודה לכל דרגת מטיל. ההפוך, **גרימת פצעים קשים**, פועל גם הוא בדיוק כמו **גרימת פצעים קלים**, אלא שהוא גורם ל 2d6 בתוספת 2 נקודות לכל דרגת מטיל.

:::

::: {.callout-note icon=false collapse=true}

### ביטול קסם

טווח: 40 מ'

כוהן 4, קוסם 3

משך: מיידי

המטיל יכול להשתמש בלחש זה כדי לסיים לחשים מתמשכים שהוטלו על יצור או חפץ, או לסיים לחשים מתמשכים (או את האפקטים שלהם) בתוך אזור קובייתי שצלעו 6 מטרים. על המטיל לבחור אם להשפיע על יצור או חפץ, או על אזור.

כאשר הלחש מכוון ליצורים, כל אפקטי הלחשים (כולל אפקטים מתמשכים של שיקויים) עשויים להתבטל. כאשר הוא מוטל על אזור, כל האפקטים הללו בתוך האזור עשויים להתבטל. כל לחש או אפקט שדרגת המטיל שלו שווה או נמוכה מדרגת המטיל של **ביטול קסם** מסתיים אוטומטית. אפקטים שנוצרו על ידי מטילים בדרגה גבוהה יותר עשויים שלא להתבטל; עבור כל דרגה שבה דרגת המטיל של האפקט גבוהה מדרגת המטיל של הלחש, יש סיכוי של 5% לכישלון. לדוגמה, מטיל בדרגה 10 המנסה לבטל אפקט שנוצר על ידי מטיל בדרגה 14 מתמודד עם סיכוי כישלון של 20%.

ישנם לחשים שלא ניתן לסיים באמצעות ביטול קסם; במיוחד כל קללה, כולל אלו שנוצרו על ידי **הטלת קללה** (ההיפוך של **הסרת קללה**) וכן על ידי חפצים מקוללים.

:::

::: {.callout-note icon=false collapse=true}

### ניטרול רעל

טווח: מגע

כוהן 4

משך: מיידי

לחש זה מנטרל כל רעל ביצור או בחפץ שבו נוגע המטיל. יצור מורעל אינו סובל עוד מתופעות הרעל; אם הלחש מוטל על יצור שמת מרעל במהלך 10 הסיבובים האחרונים, הוא מוחזר לחיים עם נקודת פגיעה אחת. אם הלחש מוטל על חפץ רעיל (נשק, מלכודת וכו'), הרעל מנוטרל לצמיתות.

בהיפוך, לחש זה הופך ל**רעל**. על המטיל לבצע גלגול התקפה; אם ההתקפה פוגעת, המטרה חייבת לגלגל גלגול הצלה נגד רעל או למות. המגע של המטיל נותר רעיל למשך סיבוב אחד לכל דרגת מטיל, או עד לשימוש (כלומר, רק יצור אחד יכול להיות מושפע מהלחש ההפוך).

:::

::: {.callout-note icon=false collapse=true}

### הגנה מרוע ברדיוס 3 מ'*

כוהן 4, קוסם 3

טווח: מגע

משך: 1 תור/דרגה

לחש זה פועל בדיוק כמו **הגנה מרוע**, אך ברדיוס של 3 מטרים במקום 0.5 מטרים. כל מי שנמצא בתוך הרדיוס מקבל את ההגנה; יצורים שעוזבים וחוזרים, או נכנסים לאחר שהלחש הוטל, מקבלים גם הם את ההגנה.

בהיפוך, לחש זה הופך ל**הגנה מטוב ברדיוס 3 מ'**, ופועל כמו הצורה ההפוכה של **הגנה מרוע**, אך ברדיוס של 3 מטרים במקום 0.5 מטרים.

:::

::: {.callout-note icon=false collapse=true}

### דיבור עם צמחים

טווח: 6 מ'

כוהן 4

משך: 1 תור

לחש זה מאפשר למטיל לדבר ולהבין כל צמח בודד (בין אם צמח רגיל או יצור צמחי מונפש). המנחה צריכה לזכור שלצמחים רגילים יש תחושה מוגבלת של סביבתם, ורובם לעולם אינם זזים מהמקום שבו נבטו. הלחש אינו משנה את תגובת הצמח או את גישתו כלפי המטיל; עם זאת, צמחים רגילים בדרך כלל יתקשרו בחופשיות עם המטיל, שכן אין להם דבר חשוב אחר לעשות. יצורי צמחים נוטים להיות מעט יותר אינטליגנטיים, ויש להשתמש בגלגול תגובה כדי לקבוע כיצד יצורים כאלה מגיבים לדברי המטיל.

:::

::: {.callout-note icon=false collapse=true}

### הפיכת מקלות לנחשים

טווח: 40 מ'

כוהן 4

משך: 6 תורות

לחש זה הופך מקלות עץ רגילים ל-1d4 קוביות פגיעה של נחשים רגילים (לא ענקיים) לכל 4 דרגות של המטיל. (ראו את קטע **מפלצות** לפרטים על סוגי [נחשים](monstersAll.qmd#נחש-עכסן-ענק).) הנחשים מצייתים לפקודות המטיל. כאשר הם נהרגים, מבוטלים או כשהלחש פג, הנחשים חוזרים לצורתם המקורית כמקלות. "מקלות" קסומים, כמו מטות מכושפים, אינם יכולים להיות מושפעים.

:::

:::

::: {.callout-tip icon=false collapse=true}

# עוצמה 5, כוהן

::: {.callout-note icon=false collapse=true}

### תקשור עם מישור חיצוני

טווח: עצמי

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מכניס את המטיל לקשר עם אלוהותו הפטרונית או עם משרת חוץ־מישורי שלה, אשר משיב על שאלה אחת של כן או לא לכל דרגת מטיל. הטקס להטלת הלחש נמשך תור אחד.

הישות עמה מתקשרים אינה בהכרח כל־יודעת, ואף שהיא נחשבת לבת־ברית של המטיל, היא עשויה שלא לענות באופן ברור או מלא. פרטים אלו נתונים לשיקול דעת המנחה.

:::

::: {.callout-note icon=false collapse=true}

### יצירת מזון

טווח: 3 מ'

כוהן 5

משך: קבוע

לחש זה יוצר מזון בכמות המספיקה להאכיל עד 3 אנשים או סוס אחד לכל דרגת מטיל למשך יום אחד. מזון זה נותר אכיל למשך יום אחד בלבד, אך ניתן להאריך זאת ביום נוסף באמצעות הטלת **טיהור מזון ומים** עליו (וניתן לחזור על כך שוב ושוב, כך שהמזון יישמר ללא הגבלת זמן). המזון שנוצר באמצעות לחש זה מזין ומשביע, אך תפל למדי.

:::

::: {.callout-note icon=false collapse=true}

### ביטול רוע

טווח: מגע

כוהן 5

משך: סיבוב/דרגה

לחש עוצמתי זה מסייע למטיל בהתמודדות עם יצורים מהמישורים התחתונים (להלן "יצורים רשעים").

ראשית, דירוג השריון של המטיל משתפר ב-4 נקודות כאשר הוא מותקף על ידי יצורים רשעים. אפקט זה נמשך עד לסיום הלחש, בין אם בשל פקיעת משך הזמן ובין אם עקב שימוש באחד מהאפקטים הבאים.

עם גלגול התקפה מוצלח, המטיל יכול להחזיר יצור רשע למישורים התחתונים. לשם כך עליו להיות בטווח קרב פנים אל פנים. היצור רשאי לגלגל גלגול הצלה נגד לחשים כדי להתנגד. כל גלגול התקפה מוצלח למטרה זו מסיים את אפקטי הלחש, בין אם היצור הצליח בגלגול ההצלה ובין אם לא.

לחלופין, באמצעות נגיעה ביצור, חפץ או אזור מושפעים, המטיל יכול לבטל מיד כל לחש או אפקט קסום דומה שהוטל על ידי היצור הרשע. אין צורך בגלגול עבור אפקט זה, אלא אם המטרה היא יצור שאינו מסכים; במקרה כזה נדרש גלגול התקפה כדי לגעת בו. הלחשים היחידים שלא ניתן לסיים בדרך זו הם אלו שחסינים ל**ביטול קסם**. נגיעה מוצלחת מסיימת את הלחש, ללא קשר לשאלה אם אפקט רשע כלשהו אכן בוטל.


:::

::: {.callout-note icon=false collapse=true}

### מגיפת חרקים

טווח: 90 מ'+9 מ'/דרגה

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מזמן נחיל ארבה אחד לכל 3 דרגות מטיל, עד למקסימום של 6 נחילים בדרגה 18. ראי [נחיל חרקים](monstersAll.qmd#נחיל-חרקים) בסעיף **מפלצות** להשפעות הנחיל. כפי שמוסבר שם, נחיל חרקים רגיל תופס שטח רציף השווה לשלוש קוביות של 3 מטרים; כל הנחילים המזומנים באמצעות לחש זה חייבים להיות רציפים זה לזה, כך שהם יוצרים בפועל נחיל גדול אחד. המטיל יכול למתוח אותם בקו, לעצב אותם כבלוק, או לסדר אותם בצורה מפותלת.

הנחילים המזומנים נותרו למשך הזמן המצוין לעיל, או עד שהם נהרסים, לפי המוקדם. המטיל יכול לזמן אותם גם באזורים שבהם כבר נמצאים יצורים. לאחר הזימון, הנחילים נייחים עד שהם נעלמים או נהרסים, והם תוקפים כל יצור הנמצא בשטחם.

:::

::: {.callout-note icon=false collapse=true}

### משימה*

טווח: 1.5 מ'/דרגה

כוהן 5

משך: מיוחד

לחש זה מחייב יצור חי לבצע פעולה או שירות מסוים, או להימנע מביצוע פעולה מסוימת. יצור המטרה חייב להיות מסוגל לשמוע ולהבין את המטיל, אחרת אינו מושפע. הלחש נכשל אוטומטית אם נעשה בו שימוש כדי לחייב יצור לבצע פעולה שהיא בבירור הרס עצמי.

גלגול הצלה נגד לחשים מאפשר למטרה שאינה מעוניינת להתנגד למשימה בעת הטלת הלחש. עם זאת, המטרה עשויה לבחור לקבל את המשימה, בדרך כלל כחלק מעסקה עם המטיל לביצוע שירות כלשהו. לאחר שהושפעה מהלחש, המטרה חייבת לציית להוראות המטיל ללא הגבלת זמן; אם המשימה היא לבצע פעולה מסוימת, הלחש מסתיים כאשר הפעולה הושלמה.

לכל 24 שעות שבהן יצור מושפע אינו מציית למשימה (או נמנע מלציית לה), הוא סופג 3d6 נקודות פגיעה. נזק זה אינו יכול להרוג את המטרה; אם הנזק היה אמור להרוג אותה, גלגלו 1d4 לקביעת מספר נקודות הפגיעה שנותרו ליצור (בדומה ללחש **פגיעה**, ההפך של **ריפוי כל**).

אם המשימה שהוטלה על נושא הלחש פתוחה או אינה ניתנת להשלמה, הנושא עדיין מחויב לנסות לבצע אותה, אך הלחש מסתיים לכל היותר לאחר יום אחד לכל דרגת מטיל.

יצורים בעלי תבונה גבוהה במיוחד עשויים לנסות לעקוף את ההוראות; המנחה תקבע את תוצאות ניסיונות כאלה.

משימה (וכל האפקטים שלה) יכולה להסתיים באמצעות לחש **הסרת קללה** שמוטל על ידי מטיל בדרגה הגבוהה ב־2 דרגות או יותר מדרגת המטיל המקורי, או באמצעות משאלה, או באמצעות ההפך של לחש זה. **ביטול קסם** אינו משפיע על לחש משימה.

:::

::: {.callout-note icon=false collapse=true}

### החייאת מתים*

טווח: מגע

כוהן 5

משך: מיידי

לחש זה מחזיר לחיים יצור אנושי שנפטר (כפי שמוגדר ב**הקסמת איש**). המטיל יכול להחיות רק יצור שלא היה מת יותר ימים ממספר דרגותיו. רוח המטרה חייבת להיות מוכנה לחזור; אם היא כלואה או מוחזקת בכל דרך שהיא, הלחש נכשל. הלחש נכשל גם אם המטרה מתה מזקנה, שכן הגוף אינו יכול לשוב לחיים. באופן דומה, יצורים אל-מתים אינם מושפעים מלחש זה.

גוף המטרה חייב להיות שלם דיו כדי לתמוך בחיים. כל הפצעים נרפאים, גם אם היו חמורים, אך חלקי גוף חסרים אינם משוחזרים. רעלים ומחלות רגילים נרפאים בתהליך ההחייאה, אך מחלות קסומות וקללות אינן מוסרות.

יצורים שהוחזרו מהמתים תמיד סובלים מאובדן כלשהו. דמויות מאבדות דרגה אחת לצמיתות (כלומר, מאבדות דרגה בפועל ומופחתות למספר המינימלי של נקודות ניסיון הדרוש לדרגה הקודמת). דמויות בדרגה 1 מופחתות למעמד אדם רגיל; אם כבר היו אדם רגיל, הן מאבדות נקודת חוסן אחת. אובדנים אלה קבועים, אך הדמות יכולה לעלות דרגות מחדש כרגיל. (דמויות שהופחתו לאדם רגיל חייבות לצבור 1,000 נקודות ניסיון כדי לחזור לדרגה 1).

מפלצות (אורקים, גובלינים וכדומה) מאבדות קוביית פגיעה אחת, או מופחתות ל-½ קוביית פגיעה אם הייתה להן אחת בלבד. מפלצות שכבר יש להן ½ קוביית פגיעה מופחתות לנקודת פגיעה אחת. אובדנים אלה בדרך כלל קבועים, אך המנחה עשויה לאפשר ליצורים בשירות דמות שחקן להתאושש באמצעות צבירת 1,000 נקודות ניסיון לכל קוביית פגיעה. יש להתייחס ליצורים כאלה כעוזרים לצורך זה.

בעת ההחייאה, למטרה יש 1 נקודת פגיעה לכל דרגה או קוביית פגיעה (לפי הערך המופחת הנוכחי שלה), עם מינימום של 1. דמות שמתה עם לחשים מוכנים אינה חוזרת עם לחשים מוכנים.

ההיפוך של לחש זה, **המתת חיים**, הורג מיד יצור שנוגעים בו (מכל סוג) אלא אם כן הצליח בגלגול הצלה נגד לחשים. אם ההצלה מצליחה, הקורבן סופג 2d6 נקודות נזק במקום זאת. נדרש גלגול התקפה כדי להשתמש בלחש זה בקרב.

:::

::: {.callout-note icon=false collapse=true}

### ראיית אמת

טווח: מגע

כוהן 5

משך: 1 סיבוב/דרגה

לחש זה מעניק למטרה את היכולת לראות את הדברים כפי שהם באמת. הנושא רואה דרך חושך רגיל וקסום, מבחין בדלתות סודיות, מזהה את המיקום המדויק של יצורים או חפצים מוסטי מיקום, רואה דרך תחפושות רגילות או קסומות, רואה יצורים וחפצים בלתי נראים, רואה דרך אשליות, ומבחין בצורה האמיתית של דברים ששונו, הוסבו או הומרו. טווח הראייה הוא 40 מטרים.

עם זאת, ראיית אמת אינה חודרת חפצים מוצקים ואינה מעניקה ראיית רנטגן או יכולת דומה. היא אינה מבטלת הסתרה, כולל זו הנגרמת על ידי ערפל וכדומה. בנוסף, אפקטים של הלחש אינם ניתנים לשיפור באמצעים קסומים מוכרים; לא ניתן להשתמש בראיית אמת דרך **כדור בדולח** או בשילוב עם **ראייה על־חושית**.

:::

::: {.callout-note icon=false collapse=true}

### קיר אש

טווח: 50 מ'

כוהן 5, קוסם 4

משך: 1 סיבוב/דרגה (או מיוחד)

לחש זה יוצר יריעת להבות אנכית באזור שהמטיל בוחר: קיר באורך של עד 6 מטרים לכל דרגת מטיל, או טבעת ברדיוס של עד 1.5 מטרים לכל דרגת מטיל. המטיל יכול לבחור ליצור קיר קטן יותר. גובה הקיר הוא עד 6 מטרים. כל הקיר חייב להיות בטווח.

הקיר יכול לפלוט חום מצד אחד או משני צדדיו, לפי בחירת המטיל בעת ההטלה. לאחר יצירתו, הקיר אינו נע ואינו משתנה.

כל יצור הנמצא עד 6 מטרים מהצד החם של הקיר סופג 1d4 נקודות פגיעה בכל סיבוב, או 2d4 נקודות אם הוא במרחק של עד 3 מטרים. הנזק נגרם בסיבוב שבו הלחש מוטל ובכל סיבוב לאחר מכן. מעבר דרך הקיר גורם ל־2d6 נקודות פגיעה, בתוספת 1 לכל דרגת מטיל, גם אם הצד שממנו נכנס היצור אינו צד חם.

יצורים אל-מתים סופגים נזק כפול מהערכים המפורטים לעיל.

אם הקיר נוצר במקום שבו נמצאים יצורים, כל יצור סופג נזק כאילו עבר דרכו; גלגול הצלה נגד לחשים מאפשר להפחית את הנזק כך שייחשב כאילו היצור נמצא במרחק של 3 מטרים מהקיר.

המטיל יכול לשמור על הלחש ללא הגבלת זמן באמצעות ריכוז (בגבולות סבירים של סיבולת), או להטיל אותו למשך 1 סיבוב לכל דרגה, לפי בחירתו.

:::

:::

::: {.callout-tip icon=false collapse=true}

# עוצמה 6, כוהן

::: {.callout-note icon=false collapse=true}

### הנפשת חפץ

טווח: 30 מ' + 3 מ'/דרגה

כוהן 6

משך: 1 סיבוב/דרגה

לחש זה מאפשר למטיל הלחש להנפיש חפצים שבדרך כלל הם דוממים, כך שיוכלו לנוע ואף להיראות כחיים. חפצים להנפשה אינם יכולים להיות ברשותו (נלבשים או נישאים) של שום יצור, וחייבים להיות לא-קסומים מטבעם. מטיל הלחש יכול להנפיש חפץ אחד לכל דרגה, עד למקסימום של 10 ק"ג לכל דרגת מטיל (כלומר 120 ק"ג בדרגה 12, 130 ק"ג בדרגה 13, וכן הלאה).

חפצים אלו משמשים בדרך כלל לתקיפת אויבי מטיל הלחש, והמנחה חייבת להחליט על יעילותם בקרב. באופן כללי, חפצים מונפשים תוקפים באמצעות אותו בונוס תקיפה כמו מטיל הלחש. חפצים קטנים או קלים אינם גורמים יותר מ-1d4 נזק לכל פגיעה, בעוד שחפצים גדולים ו/או כבדים יותר גורמים 1d6 או 1d8 נזק, לפי שיקול דעת המנחה. במקרה מיוחד, כלי נשק מונפשים גורמים נזק לפי גלגול הקובייה הרגיל לסוג הנשק, אך לא יותר מ-1d8. לחפצים מונפשים יש קצב תנועה של 3 מטרים, ובדרך כלל הם חייבים לנוע במגע עם הקרקע (הליכה, קפיצה, זחילה או כל דרך אחרת שנראית מתאימה למנחה).

:::

::: {.callout-note icon=false collapse=true}

### מחסום להבים

טווח: 30 מ'

כוהן 6

משך: 1 סיבוב/דרגה

לחש זה יוצר מחסום של להבים מעופפים, מסתובבים ומנצנצים. המטיל יכול לבחור מחסום בגובה של עד 6 מטרים, המתפרס לאורך של עד 6 מטרים לכל דרגת מטיל, או מחסום בצורת טבעת בגובה של עד 6 מטרים וברדיוס של עד 1.5 מטרים לכל 2 דרגות מטיל מלאות (כך 9 מטרים בדרגה 12 או 13, 10.5 מטרים בדרגה 14 או 15, וכן הלאה).

אם יצור כלשהו עובר דרך המחסום, הוא סופג 1d6 נקודות פגיעה לכל דרגת מטיל, עד למקסימום של 15d6. גלגול הצלה מוצלח נגד קרן מוות מפחית את הנזק לחצי.

המטיל יכול לזמן את המחסום גם באזור שבו כבר נמצאים יצורים; במקרה זה, כל היצורים הללו נפגעים כאילו עברו דרכו, אך גלגול הצלה מוצלח נגד קרן מוות מציין שהיצור נמנע מכל נזק על ידי קפיצה לצד אחד של המחסום, לפי בחירתו.

כל התקפה מטווח העוברת דרך מחסום להבים סובלת מעונש של -4 לגלגול התקפה.

:::

::: {.callout-note icon=false collapse=true}

### מציאת השביל

טווח: מגע

כוהן 6

משך: 1 תור/דרגה

לחש זה מעניק למטיל, או לנושא אחר שבו הוא נוגע, את היכולת למצוא את המסלול הטוב והקצר ביותר ליעד שהמטיל בוחר. על המטיל להכיר במידה מסוימת את היעד; כל מקום שבו ביקר אי פעם ניתן לאיתור, וכן מיקומים שתוארו לו. אפילו ידיעת שם המקום (אם יש לו שם) מספיקה כדי שהלחש יפעל.

הלחש פועל היטב גם בתוך מבנים ואף מתחת לאדמה, כפי שהוא פועל בשטח פתוח. עם זאת, **מציאת השביל** פועל ביחס למיקומים, ולא לחפצים או ליצורים. הוא יכול להוביל רק ליעד הנמצא באותו מישור קיום שבו נמצא המטיל בעת ההטלה; מגבלה זו עשויה להיות משמעותית אם המטיל (והנושא, אם יש) נמצא במרחב סגור או מבודד.

הנושא חש את הכיוון הכללי של היעד, וכן יודע את המסלול הטוב ביותר להגיע אליו. הוא חש כל פנייה ויודע באילו דרכים או מסדרונות לבחור כאשר מתעוררות אפשרויות (אך לא מראש). הלחש מתגבר גם על מכשולים כגון דלתות סודיות; הנושא ירגיש בהן ויידע כיצד לפתוח אותן, וכן יקבל את הידע של סיסמאות או קודים ברגע המתאים.

הלחש תמיד בוחר את המסלול הטוב ביותר. לדוגמה, אם הדרך הקצרה ביותר דורשת שימוש במפתח שאין לנושא, הלחש יבחר דרך אחרת, ככל הנראה ארוכה יותר אם קיימת. אם אין דרך חלופית, הנושא יובל לדלת הנעולה ויבין שעליו למצוא דרך לעבור בעצמו.

הלחש מסתיים כאשר הנושא מגיע ליעד, או כאשר משך הזמן מסתיים, לפי המוקדם מביניהם. אם משך הזמן מסתיים לפני ההגעה, הנושא עשוי עדיין לזכור את הכיוון הכללי ליעד, אך לא יידע עוד את הדרך.

:::

::: {.callout-note icon=false collapse=true}

### ריפוי כל*

טווח: מגע

כוהן 6

משך: קבוע

לחש זה מאפשר למטיל לרפא כמעט לחלוטין פצעים, מחלות ומצוקות אחרות של יצור חי יחיד. במגע, המטיל מרפא עיוורון, חירשות, **בלבול**, מחלה, **רפיסות מוח**, חנק, בחילה ורעל. כל נקודות הפגיעה, למעט 1d4, מוחזרות לנושא אם הוא פצוע. אובדן נקודות תכונה מוחזר במלואו, אך רק אם ניתן היה להשיבו גם ללא לחש זה; אובדן קבוע אינו מוחזר. ניקוז אנרגיה אינו מושפע מהלחש.

בהיפוך, לחש זה הופך ל**פגיעה**, הפוגע ביצור שנוגעים בו כך שנותרות לו 1d4 נקודות פגיעה בלבד. במקרה זה על המטיל לבצע גלגול התקפה; אם ההתקפה מחטיאה, הלחש מתבזבז. אם לקורבן נותרות פחות נקודות פגיעה מהתוצאה, הוא סופג לפחות נקודת פגיעה אחת (וזהו המקרה היחיד שבו **פגיעה** עשוי להרוג יצור).

בדרך כלל, שני הלחשים משפיעים רק על יצורים חיים. כאשר הם משמשים נגד יצור אל־מת, **ריפוי כל** פועל כמו **פגיעה**, ולהפך. מבנים וגלמים אינם מושפעים מאף אחד מהלחשים.

:::

::: {.callout-note icon=false collapse=true}

### הצמחת איברים

טווח: מגע

כוהן 6

משך: קבוע

לחש זה גורם לאיברי גוף כרותים של הנושא (אצבעות, בהונות, ידיים, רגליים, זרועות, רגליים, זנבות, או אפילו ראשים של יצורים רב-ראשיים), עצמות שבורות ואיברים הרוסים לצמוח מחדש. אם האיברים הכרותים נמצאים ונוגעים ביצור בעת ההטלה, הצמיחה מושלמת בתוך סיבוב אחד; אחרת, נדרש תור אחד להשלמתה.

הלחש גם מרפא 3d8 נקודות נזק. הצמחת איברים אינה משפיעה על יצורים שאינם חיים או על מבנים (כולל אל-מתים).


:::

::: {.callout-note icon=false collapse=true}

### השבה

טווח: מגע

כוהן 6

משך: קבוע

כל הטלת לחש מסירה דרגה שלילית אחת מיצור שסבל מניקוז אנרגיה. בדרגה 16 ניתן להסיר שתי דרגות שליליות. ראו את הכללים לניקוז אנרגיה (בקטע [מפגש](combat.qmd#ניקוז-אנרגיה)) לפרטים נוספים.

לחלופין, ניתן להשתמש בלחש זה כדי לשחזר נקודות תכונה שנוקזו. אם הלחש מוטל על דמות שסבלה מאובדן זמני של נקודות תכונה, הוא משחזר מיד עד 1d4 נקודות לכל תכונה שנוקזה. אם מדובר באובדן קבוע, ניתן לשחזר נקודה אחת בלבד.

השבה אינה משחזרת דרגות שאבדו עקב מוות (כמתואר בלחש **החייאת מתים**).

:::

::: {.callout-note icon=false collapse=true}

### דיבור עם מפלצות

כוהן 6

טווח: מיוחד

משך: 1 תור/5 דרגות

לחש זה מאפשר למטיל לדבר ולהבין כל מפלצת חיה בודדת שנמצאת בטווח ראייתו ויכולה לשמוע אותו. המטיל יכול להחליף את המפלצת איתה הוא מדבר כרצונו, פעם אחת לכל סיבוב. אחרים שיכולים להבין את השפה המדוברת על ידי מפלצת המטרה (אם יש כאלה) יוכלו להבין את המטיל. הלחש אינו משנה את תגובת המפלצת או את גישתה כלפי המטיל. מפלצות חסרות תודעה, יצורי צמחים ויצורים אל-מתים אינם מושפעים מלחש זה.


:::

::: {.callout-note icon=false collapse=true}

### מילת החזרה

טווח: עצמי (מיוחד)

כוהן 6

משך: מיידי

עם אמירת מילה אחת, לחש זה מעביר את המטיל למקום מקלט שיועד מראש בעת הכנת הלחש. המקום חייב להיות מוכר היטב למטיל (כפי שמוסבר עבור **שיעתוק**) כדי שניתן יהיה לייעד אותו כך. לחש זה אינו יכול להעביר את המטיל מעבר למישור הקיום הנוכחי שלו.

המטיל יכול להביא עמו חפצים או יצורים במשקל כולל של עד 135 ק"ג, ועוד 45 ק"ג לכל דרגה מעל 10. המטיל חייב להיות במגע עם כל החפצים ו/או היצורים המועברים (עם זאת, יצורים יכולים להיות במגע זה עם זה, כל עוד לפחות אחד מהם במגע עם המטיל).

יצורים שאינם רוצים אינם יכולים להיות מועברים בלחש זה, וגם לא חפצים שברשותם. אם המטיל או אחד מנוסעיו מחזיקים בחפץ שגם מוחזק על ידי יצור שאינו רוצה, האחרון רשאי לשמור על החפץ באמצעות גלגול הצלה מוצלח נגד לחשים.

:::

:::

## לחשי קוסם

קוסמים מטילים לחשים דרך הפעלת ידע ורצון. הם מכינים לחשים על ידי לימוד ספרי הלחשים שלהם; לכל קוסם יש ספר לחשים משלו, המכיל את הנוסחאות הקסומות לכל לחש שלמד. ספרי הלחשים כתובים בכתב קסום שרק מי שכתב אותו יכול לקרוא, או באמצעות הלחש **קריאת קסם**. כל קוסם מתחיל את המשחק כשהוא יודע **קריאת קסם**, והוא מושרש עד כדי כך שניתן להכין אותו גם ללא ספר לחשים.

קוסם יכול להכין לחשים רק לאחר מנוחה (כלומר, שינה טובה בלילה), והוא זקוק לתור אחד לכל שלוש עוצמות לחשים (מעוגל כלפי מעלה). לחשים שהוכנו ולא נוצלו ביום הקודם אינם אובדים. לדוגמה, קוסם בדרגה 3 שמכין את כל שלושת הלחשים הזמינים שלו (שני לחשים מעוצמה 1 ואחד מעו 2) מכין סך כולל של 4 עוצמות לחשים, ולכן זקוק ל-2 תורות (4 מחולק ב-3 ומעוגל כלפי מעלה).

חוקים לרכישת לחשים חדשים נמצאים בפרק המנחה.


::: {.callout-tip icon=false collapse=true}

# עוצמה 1, קוסם

::: {.callout-note icon=false collapse=true}

### הקסמת איש

טווח: 10 מ'

קוסם 1

משך: מיוחד

לחש זה גורם להומנואיד (כולל בני גזעי דמויות שחקן וכן יצורים כמו אורקים, גובלינים, גנולים וכדומה) בעלי 4 קוביות פגיעה או פחות לראות במטיל הלחש חבר קרוב, מושא אהבה או לפחות בעל ברית מהימן. דמויות (דמויות שחקן או דמויות מנחה) עשויות להיות מושפעות ללא קשר לדרגתן.

גלגול הצלה נגד לחשים מבטל את האפקט. אם העוינות כבר החלה או שהמטרה מרגישה מאוימת על ידי המטיל, היא מקבלת בונוס של +5 לגלגול ההצלה.

מטיל הלחש אינו שולט ישירות במטרה; במקום זאת, הוא נותן לה הוראות בעל פה, בכתב או באמצעות מחוות. הוראות בעל פה פועלות רק אם המטרה והמטיל חולקים שפה משותפת, ואותה מגבלה חלה על הוראות כתובות. תפיסת המטיל בעיני המטרה אינה בשליטתו; המנחה צריכה לקבוע כיצד הנושא תופס את יחסו למטיל.

המטרה מקבלת גלגול הצלה חדש בכל יום אם תבונתה 13 או יותר, בכל שבוע אם תבונתה 9–12, או בכל חודש אם תבונתה 8 או פחות. המנחה חייבת לקבוע את ערך התבונה של מפלצות הומנואידיות.

:::

::: {.callout-note icon=false collapse=true}

### גילוי קסם

טווח: 20 מ'

כוהן 1, קוסם 1

משך: 2 תורות

המטיל של לחש זה מסוגל לגלות חפצים או יצורים מכושפים או תחת השפעת לחש בטווח הנתון על ידי ראייה, ורואה אותם מוקפים באור זוהר חיוור. רק המטיל רואה את הזוהר. יצורים או חפצים נעלמים מעין לא ניתנים לגילוי על ידי לחש זה, אך ההקרנות של קסם ההיעלמות ייראו כערפל זוהר אמורפי, מה שעשוי לאפשר למטיל (רק) לתקוף את היצור הנעלם בעונש תקיפה של -2 בלבד.

:::

::: {.callout-note icon=false collapse=true}

### דיסקית מעופפת

טווח: 0

קוסם 1

משך: 5 תורות +1/דרגה

הטלת לחש זה גורמת להופעת פלטפורמה בלתי נראית של כוח קסום. קוטרה כ-1 מטר, ועובייה כ-3 סנטימטרים במרכזה. היא יכולה לשאת משקל מרבי של 250 ק"ג. (שימו לב שליטר מים שוקל כ-1 ק"ג.) הדיסקית צפה בגובה הקרקע, בגובה מותני המטיל.

הדיסקית נשארת במקומה כל עוד היא בטווח של 3 מטרים מהמטיל, ועוקבת אחריו בקצב תנועתו אם הוא מתרחק ממנה. ניתן לדחוף את הדיסקית לפי הצורך כדי למקם אותה, אך היא תתבטל אם תתרחק יותר מ-3 מטרים מהמטיל. כאשר משך הלחש פג, הדיסקית נעלמת ומפילה את מה שנישא עליה אל המשטח שמתחת.

יש להעמיס את הדיסקית כך שהפריטים המונחים עליה יהיו נתמכים כראוי, אחרת הם ייפלו. לדוגמה, הדיסקית יכולה לשאת יותר מ-230 ק"ג של מים, אך המים חייבים להיות בתוך חבית או מיכל סביר אחר שניתן להניח על הדיסקית. באופן דומה, ערימת מטבעות רופפת תחליק ותתפזר, וחלקם ייפלו עם כל צעד שהמטיל עושה; אך שק גדול מלא מטבעות, קשור כראוי, יישאר יציב.

:::

::: {.callout-note icon=false collapse=true}

### עצירת פתח

טווח: 30 מ'+3 מ'/דרגה

קוסם 1

משך: 1 סיבוב/דרגה

לחש זה נועל פתח כגון דלת, שער, חלון או תריס העשוי מחומרי בנייה רגילים ולא קסומים; הפתח נחשב כסגור ונעול היטב למשך הלחש. ניתן לפתוח את הפתח לפני סיום הלחש באמצעות **פריצה**, הטלה מוצלחת של **ביטול קסם**, או על ידי השמדת הפתח (מה שעשוי לדרוש יותר זמן ממשך הלחש).

:::

::: {.callout-note icon=false collapse=true}

### אור

טווח: 40 מ'

כוהן 1, קוסם 1

משך: 6 תורות + 1/דרגה

לחש זה יוצר אור בעוצמה של לפיד, המאיר ברדיוס של 9 מטרים סביב נקודה או חפץ מטרה. אם הלחש מוטל על אזור, האור קבוע במקומו; אם הוא מוטל על חפץ, האור נע יחד איתו. אור זה אינו פועל בתוך אזור של חושך קסום.

בהיפוך, **אור** הופך ל**חושך**, ויוצר אזור חשוך בהתאם לאמור לעיל. חושך זה חוסם זיוונות ומבטל מקורות אור רגילים.

לחש אור יכול לנטרל ולבטל לחש חושך של מטיל באותה דרגה או נמוכה יותר (ולהיפך). במקרה זה, שני הלחשים נפסקים מיד, ורמת האור חוזרת למצבה הקודם.

כל גרסה של לחש זה יכולה לשמש לעיוור יריב על ידי הטלתה על איברי הראייה שלו. המטרה רשאית לגלגל גלגול הצלה נגד קרן מוות כדי להימנע מההשפעה; אם ההצלה מצליחה, הלחש אינו פועל. כאשר הלחש משמש לעיוור, הוא אינו משפיע על האזור (כלומר, אינו יוצר אור או חושך סביב המטרה).

:::

::: {.callout-note icon=false collapse=true}

### קליע קסם

טווח: 30 מ'+3 מ'/דרגה

קוסם 1

משך: מיידי

לחש זה משגר קליע של אנרגיה קסומה מאצבעו של המטיל לעבר מטרה הנראית לו לפחות חלקית, ופוגע בה ללא החטאה, תוך גרימת 1d6+1 נקודות פגיעה. לא ניתן לכוון לחלקים מסוימים של יצור. חפצים דוממים אינם מושפעים מהלחש.

לכל 3 דרגות מטיל מעבר לדרגה 1 נורה קליע נוסף: שניים בדרגה 4, שלושה בדרגה 7, ארבעה בדרגה 10, ועד חמישה קליעים בדרגה 13 או יותר. כאשר נורים מספר קליעים, המטיל יכול לכוון אותם ליצור אחד או למספר יצורים, אך כל קליע פוגע במטרה אחת בלבד. יש לקבוע את המטרות לפני גלגול הנזק.

:::

::: {.callout-note icon=false collapse=true}

### פה קסום

טווח: 10 מ'

קוסם 1

משך: מיוחד

לחש זה יוצר אשליה מתוכנתת פשוטה על חפץ דומם בטווח. כאשר הלחש מופעל, מופיע פה על החפץ והוא משמיע הודעה בקול רם. הלחש יכול להישאר ללא הגבלת זמן, אך מסתיים לאחר הפעלה (כלומר, ההודעה נמסרת בדרך כלל פעם אחת).

אורך ההודעה הוא עד שלוש מילים לכל דרגת מטיל. המטיל יכול לשלב הפסקות, אך כל ההודעה חייבת להימסר בתוך תור אחד. קול ההודעה יכול להיות בכל עוצמה שאדם רגיל מסוגל להפיק. הקול דומה לקולו של המטיל במידה מספקת לזיהוי על ידי מכריו, אך אינו זהה.

הפה האשלייתי נע כאילו הוא מדבר את ההודעה, ונשאר גלוי גם בזמן הפסקות. אם הלחש מוטל על ייצוג אמנותי של יצור בעל פה (כגון ציור או פסל), נראה כאילו פיו של הייצוג מונפש.

לחש זה אינו יכול לשמש להפעלת חפצים קסומים בעלי מילות פקודה, ואינו מפעיל אפקטים קסומים אחרים.

על המטיל לקבוע את תנאי ההפעלה של הלחש. התנאים יכולים להיות פשוטים או מורכבים, אך חייבים להתבסס על ראייה ושמיעה בלבד; ללחש אין חושים אחרים. ללחש אין תבונה, וניתן להטעות אותו באמצעות תחפושות או אשליות. הלחש מסוגל לראות בחושך רגיל, אך לא בחושך קסום, ואינו יכול לזהות יצורים בלתי נראים או לראות דרך דלתות, קירות או וילונות אטומים. התגנבות או שקט קסום מונעים הפעלות שמיעתיות. כמו כן, הלחש אינו יכול לזהות מקצוע, דרגה, תכונות או מאפיינים שאינם גלויים לעין.

טווח החישה של ההפעלה הוא 3 מטרים לכל דרגת מטיל; קולות, מראות או פעולות מעבר לטווח זה אינם מפעילים את הלחש.

:::

::: {.callout-note icon=false collapse=true}

### הגנה מרוע*

כוהן 1, קוסם 1

טווח: מגע

משך: 1 תור/דרגה

לחש זה מגן על המטיל או על יצור שנגע בו המטיל ("הנושא") מרוע; באופן ספציפי, הלחש מגן מפני יצורים מזומנים, יצורים עם כוונות רעות משמעותיות, ויצורים חוץ-מישוריים בעלי טבע רע. מחסום קסום ברדיוס של 0.5 מטרים בלבד נוצר סביב הנושא. המחסום נע עם הנושא, ומספק שלושה סוגים ספציפיים של הגנה קסומה מפני התקפות או אפקטים אחרים שניסו היצורים המושפעים נגד הנושא.

ראשית, הנושא מקבל בונוס של +2 לדירוג השריון שלו, ובונוס דומה של +2 על כל גלגולי ההצלה. שנית, המחסום חוסם כל ניסיון להקסים או לשלוט בנושא, או להחזיק את הנושא (כמו עם **בקבוק קסם**). ניסיונות כאלה פשוט נכשלים במהלך משך הלחש הזה. עם זאת, יש לציין שיצור שמקבל הגנה זו לאחר שהוחזק אינו נרפא מההחזקה.

שלישית, כל היצורים המזומנים והיצורים החוץ-מישוריים בעלי טבע רע אינם יכולים לגעת פיזית בנושא. התקפות על ידי יצורים כאלה באמצעות נשקיהם הטבעיים פשוט נכשלות. אפקט זה מבוטל אם הנושא מבצע כל סוג של התקפה פיזית (אפילו עם נשק טווח) על כל יצור מושפע, אך שאר תכונות הלחש ממשיכות לפעול.

בהיפוך, לחש זה הופך ל**הגנה מטוב**. הוא פועל בכל הדרכים כפי שתואר לעיל, למעט שיצורים "טובים" נשמרים במרחק, במקום "רעים".

:::

::: {.callout-note icon=false collapse=true}

### קריאת שפות

טווח: 0

קוסם 1

משך: מיוחד

לחש זה מעניק למטיל את היכולת לקרוא כמעט כל שפה כתובה. ניתן להטיל אותו באחד משלושה מצבים:

במצב הראשון, הלחש מאפשר למטיל לקרוא כל מספר של יצירות כתובות במגוון שפות. מצב זה נמשך תור אחד לכל דרגת מטיל.

במצב השני, הלחש מאפשר למטיל לקרוא ספר או כרך אחד. מצב זה נמשך 3 שעות לכל דרגת מטיל.

במצב השלישי, הלחש מאפשר למטיל לקרוא מגילה לא קסומה או מסמך חד-דף אחר. מצב זה קבוע.

לחש זה אינו פועל על טקסטים קסומים, כגון מגילות לחשים או ספרי לחשים; ראי **קריאת קסם** עבור הלחש המתאים למקרים אלה.

הלחש מעניק את היכולת לקרוא, אך אינו מאיץ את קצב הקריאה ואינו מעניק הבנה של מושגים שמעבר ליכולתו של המטיל. בנוסף, כדי שהלחש יפעל, חייב להיות לפחות יצור חי אחד המסוגל לקרוא את השפה הנתונה באותו מישור. הידע אינו מועתק ממוחו של היצור; עצם קיומו הוא שמאפשר ללחש לפעול.

:::

::: {.callout-note icon=false collapse=true}

### קריאת קסם

טווח: 0

קוסם 1

משך: קבוע

כאשר הלחש מוטל על טקסט קסום, כגון ספר לחשים או מגילת לחשים של קוסם, הוא מאפשר למטיל לקרוא אותו. הטלת הלחש על טקסט מקולל תפעיל בדרך כלל את הקללה. כל הקוסמים מתחילים את המשחק כשהם יודעים לחש זה, וניתן להכינו גם אם הקוסם איבד גישה לספר הלחשים שלו.

:::

::: {.callout-note icon=false collapse=true}

### מגן

טווח: עצמי

קוסם 1

משך: 5 סיבובים + 1/דרגה

הלחש יוצר דיסקית בלתי נראית דמוית מגן המרחפת לפני המטיל. היא מבטלת התקפות **קליע קסם** המכוונות למטיל, ומשפרת את דירוג השריון שלו ב־+3 נגד התקפות קרב פנים אל פנים וב־+6 נגד נשקי קליעים. שיפור דירוג השריון אינו חל על התקפות שמגיעות מאחורי המטיל, אך **קליעים קסומים** נדחים מכל הכיוונים.

:::

::: {.callout-note icon=false collapse=true}

### הרדמה

טווח: 30 מ'

קוסם 1

משך: 5 סיבובים/דרגה

לחש זה מרדים מספר יצורים בעלי 3 קוביות פגיעה או פחות, או יצור אחד בעל 4 קוביות פגיעה, לשינה קסומה. יצורים בעלי 5 קוביות פגיעה או יותר אינם מושפעים. המטיל בוחר נקודה בתוך הטווח, והיצורים במרחק של עד 10 מטרים ממנה עשויים להיות מושפעים. כל יצור באזור רשאי לגלגל גלגול הצלה נגד לחשים כדי להתנגד.

יצורים ישנים ניתנים לפגיעה כרגיל. פגיעה מעירה את היצור, והוא עשוי לפעול בסיבוב הבא. טפיחה או ניעור מעירים את היצור בתוך 1d4 סיבובים, אך רעשים רגילים אינם מעירים אותו.

הלחש אינו משפיע על יצורים מחוסרי הכרה, מבנים או אל-מתים.

כאשר משך הלחש פג, היצורים מתעוררים מיד. עם זאת, בסביבה נוחה ושקטה, הם עשויים להמשיך לישון לפי החלטת המנחה.

:::

::: {.callout-note icon=false collapse=true}

### פיתומות

טווח: 20 מ'

קוסם 1

משך: 1 תור/דרגה

לחש זה גורם לקולו של המטיל להישמע כאילו הוא מגיע ממיקום אחר בטווח, כגון נישה חשוכה או פסל. המטיל יכול לבחור מיקום חדש בכל סיבוב, ויכול להפסיק את הלחש זמנית מבלי לסיים אותו, ואז להפעילו מחדש בכל עת במהלך משך הלחש.

:::

:::

<!-- -------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# עוצמה 2, קוסם

::: {.callout-note icon=false collapse=true}

### אור תמידי*

טווח: 100 מ'

כוהן 3, קוסם 2

משך: שנה/דרגה

לחש זה יוצר אזור כדורי של אור, בעוצמה של אור יום מלא עד רדיוס של 10 מטרים, ובעוצמה פחותה עד רדיוס של 18 מטרים. ניתן להטיל את הלחש על חפץ, על נקודה באוויר, או על יצור, כמו בלחש **אור**, עד לטווח של 100 מטרים מהמטיל. הלחש נמשך שנה לכל דרגה של המטיל.

כמו בלחש **אור**, ניתן להשתמש בלחש זה כדי לעוור יצור על ידי הטלתו על איברי הראייה שלו. המטרה רשאית לגלגל גלגול הצלה נגד קרן מוות; אם ההצלה מצליחה, הלחש מוטל בנקודה באוויר ממש מאחורי המטרה. אם ההצלה נכשלת, המטרה עיוורת וסופגת עונש של -4 לגלגולי ההתקפה שלה.

הלחש ההפוך, **חושך תמידי**, יוצר אזור של היעדר מוחלט של אור, ומתגבר על מקורות אור רגילים. ניתן להשתמש בו לעיוור באותו אופן כמו אור תמידי.

:::

::: {.callout-note icon=false collapse=true}

### גילוי רוע*

טווח: 20 מ'

כוהן 1, קוסם 2

משך: סיבוב אחד/דרגה

לחש זה מאפשר למטיל לגלות רוע; באופן ספציפי, המטיל יכול לגלות יצורים בעלי כוונות רעות, חפצי קסם בעלי השפעות רעות, ואולי יצורים חוצניים בעלי טבע רע. דמויות רגילות, אפילו "רעות", אינן ניתנות לגילוי על ידי לחש זה, שכן רק רוע חזק במיוחד ניתן לגילוי. המטיל רואה את היצורים או החפצים ה"רעים" מוקפים בזוהר ברור, אך הזוהר אינו נראה על ידי אף אחד אחר.

ההגדרה המדויקת של רוע נתונה להחלטת המנחה. שימי לב כי פריטים כמו מלכודות רגילות או רעלים אינם "רעים", ולכן אינם ניתנים לגילוי על ידי לחש זה.

בהפוך, לחש זה הופך ל**גילוי טוב**, הפועל בדיוק כפי שתואר לעיל ביחס לגילוי כישופים "טובים", יצורים מלאכיים, וכדומה.


:::

::: {.callout-note icon=false collapse=true}

### גילוי נעלם מעין

טווח: 20 מ'

קוסם 2

משך: תור אחד/דרגה

באמצעות לחש זה המטיל מסוגל לראות יצורים או חפצים נעלמים מעין בטווח הנתון, ורואה אותם כצורות שקופות.


:::

::: {.callout-note icon=false collapse=true}

### היעלמות מעין

טווח: מגע

קוסם 2

משך: מיוחד

לחש זה גורם ליצור שנגעו בו (שיכול להיות המטיל) להפוך לבלתי נראה, ואינו ניתן לגילוי באמצעות ראייה רגילה או זיוונות. ניתן לגלות יצורים בלתי נראים באמצעות חושים שאינם חזותיים.

כל החפצים שנלבשו או נישאו על ידי המטרה בעת ההטלה הופכים גם הם לבלתי נראים. חפץ שמונח הופך מיד לגלוי; חפצים שנאספים לאחר מכן אינם הופכים לבלתי נראים. אם חפץ גלוי מוסתר לחלוטין בתוך בגד, תרמיל או מיכל אחר של המטרה, באופן שבו לא היה נראה אילו הייתה גלויה, הוא הופך לבלתי נראה כאילו היה ברשותה בעת ההטלה.

הטלת לחש זה על אחר הופכת את המטרה לבלתי נראית גם למטיל. דמויות בלתי נראות עשויות להתנגש או למעוד זו בזו. הלחש נמשך עד 24 שעות, אלא אם הסתיים קודם לכן. הוא מסתיים מיד אם המטרה תוקפת או מטילה לחש. פעולות אחרות אינן מסיימות אותו בדרך כלל. המטרה יכולה לסיים את הלחש כרצונה.

חפצים פולטי אור יכולים להיות בלתי נראים, אך האור עצמו נשאר גלוי. גשם, אבק, צבע או חומרים גלויים אחרים יכולים לחשוף יצור בלתי נראה.

:::

::: {.callout-note icon=false collapse=true}

### פריצה

טווח: 10 מ'

קוסם 2

משך: מיוחד

לחש זה פותח דלתות תקועות, נעולות, חסומות או תחת השפעת **מנעול מכשפים**. הוא פותח גם דלתות סודיות, וכן קופסאות או תיבות נעולות או בעלות מנגנון פתיחה מורכב. הלחש משחרר גם ריתוכים, אזיקים או שרשראות (בתנאי שהם משמשים לסגירת דבר שניתן לפתוח).

אם משתמשים בלחש לפתיחת דלת תחת **מנעול מכשפים**, הלחש אינו מסיר את ה**מנעול מכשפים**, אלא משעה את פעולתו למשך תור אחד. בכל המקרים האחרים, הדלת אינה ננעלת מחדש ואינה חוזרת להיות תקועה מעצמה. לחש פריצה אינו מרים שערים ואינו מפעיל מנגנונים דומים, ואינו משפיע על חבלים, גפנים וכדומה.

כל הטלה מבטלת אמצעי נעילה אחד של הדלת או החפץ. לדוגמה, דלת שהיא גם נעולה וגם תקועה תיפתח אך תישאר תקועה; הטלה נוספת של הלחש תפתח אותה לחלוטין.

:::

::: {.callout-note icon=false collapse=true}

### ריחוף

טווח: מגע

קוסם 2

משך: תור אחד/דרגה

כאשר הלחש מוטל, המטיל או יצור או חפץ אחד שבו הוא נוגע מתחילים לרחף. הריחוף מאפשר למטיל לגרום לנושא לעלות או לרדת בקצב של עד 6 מטרים לסיבוב.

אם יצור המטרה אינו מוכן, על המטיל לבצע גלגול התקפה כדי לגעת בו; גם אם ההתקפה פוגעת, המטרה רשאית לגלגל גלגול הצלה נגד לחשים כדי להתנגד לקסם. אם המטרה היא חפץ המוחזק על ידי יצור שאינו מוכן, נדרשים גלגול התקפה וגלגול הצלה דומה. חפצים שאינם מוחזקים מושפעים אוטומטית כאשר נוגעים בהם.

המטיל שולט בנושא המרחף מנטלית. אם המטיל מפסיק לשלוט בו, הוא נשאר בגובהו הנוכחי עד לסיום הלחש, ואז נופל.

ריחוף אינו מעניק תנועה אופקית, אך הנושא אינו קבוע במקום. ניתן להזיזו באמצעות דחיפה או גרירה (למשל בעזרת חבל). יצור מרחף יכול למשוך את עצמו לאורך קיר או תקרה, או באמצעות חבל המחובר לעצם מוצק. תנועה כזו מתבצעת בדרך כלל במחצית מהירות ההליכה. עם זאת, הנושא אינו יכול לשנות את גובהו בעצמו.

כאשר יצור מרחף תוקף ברוב כלי הנשק, הוא אינו יציב. התקיפה הראשונה מתבצעת במחסר של 1- לגלגול התקפה, והמחסר גדל ב־1- נוסף בכל סיבוב, עד למקסימום של 5-. אם היצור נמנע מלתקוף במשך סיבוב מלא, המחסר חוזר ל־1- בסיבוב הבא. מגבלה זו בדרך כלל אינה משפיעה על הטלת לחשים בזמן ריחוף.

:::

::: {.callout-note icon=false collapse=true}

### איתור עצם

טווח: 100 מ'

כוהן 3, קוסם 2

משך: סיבוב/דרגה

לחש זה מעניק למטיל ידע על מיקומו של חפץ. על המטיל להכיר את החפץ היטב או להיות מסוגל לדמיין אותו בבירור (צפייה בציור או תמונה מדויקת מספיקה לכך). ניתן לאתר חפץ כללי; אם יותר מחפץ אחד כזה נמצא בטווח, הלחש מוביל את המטיל אל הקרוב ביותר.

חפצים ייחודיים או יוצאי דופן ניתנים לאיתור רק אם למטיל יש ידע ממקור ראשון (לא באמצעות חיזוי כמו **ראייה על חושית** או **כדור בדולח**). הלחש אינו יכול לשמש לאיתור יצורים מכל סוג. שכבה דקה מאוד של עופרת או זהב המקיפה את החפץ מונעת את איתורו.

:::

::: {.callout-note icon=false collapse=true}

### תע"ח

טווח: 18 מ'

קוסם 2

משך: תור אחד/דרגה

לחש זה מאפשר למטיל לשמוע (ואולי גם לראות, אם המטרה מדמיינת) את המחשבות השטחיות של יצור חי אחד או יותר בטווח. על המטיל לבחור כיוון או מטרה גלויה, ולאחר מכן להתרכז במשך תור אחד כדי “להאזין” למחשבות. בכל תור הוא יכול לבחור כיוון חדש. המטיל יכול להפסיק להאזין ולחדש זאת מאוחר יותר, כל עוד משך הלחש לא פג.

יצור המטרה בדרך כלל אינו מודע לכך שמאזינים למחשבותיו, אך יצור הנמצא כבר תחת אפקט טלפתי דומה יבחין בכך מיד ויוכל לחוש את כיוון המטיל.

סלע בעובי העולה על 5 סנטימטרים, או שכבה דקה אפילו מאוד של עופרת או זהב, חוסמים את הלחש. יצורים אל־מתים, יצורים חסרי מוח ומבנים כגון גלמים חסינים לאפקט זה.

:::

::: {.callout-note icon=false collapse=true}

### בבואת ראי

טווח: עצמי

קוסם 2

משך: תור אחד/דרגה

לחש זה מאפשר למטיל ליצור כפילויות אשלייתיות מרובות (הנקראות דמויות) שנראות מסתובבות ונעות סביב המטיל וסביב עצמן כמעט כל הזמן, ולכן רוב היצורים אינם יכולים לקבוע מי האמיתי. סך של 1d4 דמויות ועוד דמות אחת לכל שלוש דרגות מטיל (מקסימום שמונה דמויות בסך הכל) נוצרות.

הדמויות מחקות את פעולות המטיל, כולל הטלת הלחשים, שתיית שיקויים, ריחוף, וכדומה, בדיוק כפי שהמטיל עושה. הדמויות תמיד נראות בדיוק כמו המטיל.

כל יריב שתוקף או מטיל לחשים ישירות על המטיל תמיד יפגע בדמות במקום זאת. תקיפה של דמות משמידה אותה, בין אם גלגול ההתקפה מצליח ובין אם לא, כמו גם כל לחש התקפה המכוון לאחת. לחשים בעלי השפעה אזורית אינם מכוונים ישירות למטיל, ולכן נראים משפיעים על כל הדמויות בדיוק כפי שהם משפיעים על המטיל; לדוגמה, אם המטיל נתון ל**כדור אש**, כל הדמויות ייראו פצועות בדיוק כפי שהמטיל היה.

:::

::: {.callout-note icon=false collapse=true}

### חזיון תעתועים

טווח: 50 מ'

קוסם 2

משך: ריכוז

לחש זה יוצר אשליה חזותית של חפץ, יצור (או קבוצה קטנה של יצורים), או אפקט אחר, כפי שמדמיין המטיל, עד לגודל מרבי של 6x6x6 מטרים. האשליה אינה יוצרת קול, ריח, מרקם או טמפרטורה. המטיל יכול להנפיש את הדימוי בגבולות שטח ההשפעה. הדימוי נמשך כל עוד המטיל מתרכז.

אם הלחש משמש ליצירת אשליה של יצור אחד או יותר, דירוג השריון שלהם הוא 11, והם נעלמים אם נפגעו בקרב. נזק שנגרם על ידי מפלצות, לחשים וכדומה הנוצרים באמצעות לחש זה אינו אמיתי; יצורים ש"נהרגו" או שנראה כי הושבתו מתעוררים ללא פגע (לפחות מלחש זה) לאחר 2d8 סיבובים. הנזק האשלייתי שווה לנזק הרגיל של כל התקפה מדומה.

ניסיון ליצור יותר יצורים ממספר דרגות המטיל מעניק לכל הצופים בעלי תבונה ממוצעת לפחות גלגול הצלה מיידי נגד לחשים כדי לזהות את היצורים כאשליות. מי שמצליח בגלגול אינו מושפע עוד מכל פעולה של האשליות מאותו רגע ואילך. המנחה רשאית להעניק גלגול הצלה דומה בכל פעם שהיא סבורה שהאשליה עשויה להיחשף, במיוחד אם השחקן מתאר אשליה שאינה סבירה או שאינה מתוכננת היטב.

:::

::: {.callout-note icon=false collapse=true}

### קורים

טווח: 3 מ'/דרגה

קוסם 2

משך: 2 תורות/דרגה

לחש זה יוצר נפח של חוטים דביקים הדומים לקורי עכביש, אך גדולים ועבים הרבה יותר. הלחש ממלא נפח של עד 230 מטרים מעוקבים (שווה ערך לשמונה קוביות של 3x3x3 מטרים). הקורים חייבים להיות מחוברים לעצמים מוצקים סמוכים כגון קירות, עמודים וכדומה; כל חלק שאינו נתמך קורס ונעלם. בתוך מגבלה זו, המטיל יכול לבחור כל סידור של קורים, עד לגבולות הטווח והנפח. המטיל יכול לבחור ליצור נפח קטן יותר.

יצורים הנמצאים בתוך הקורים בעת הטלת הלחש, וכן כל מי שנכנס לאזור לאחר מכן, מסתבכים. כל יצור כזה מגלגל גלגול הצלה נגד קרן מוות; יצור שמצליח יכול לנוע דרך הקורים, אך מהירותו מופחתת לחצי. יצורים אלה אינם יכולים להטיל לחשים או לבצע התקפות רגילות; פעולות אחרות נתונות להחלטת המנחה. כאשר יצור מסובך יוצא מתחום הקורים, הוא חוזר לפעול כרגיל.

יצורים שנכשלים בגלגול ההצלה מסובכים לחלוטין ולכודים. הם אינם יכולים לנוע, להטיל לחשים, לבצע התקפות רגילות או כל פעולה פיזית אחרת, אך יכולים לדבר. יצורים בעלי כוח 13 או יותר (או 4 קוביות פגיעה או יותר) עשויים להשתחרר; בכל סיבוב, יצורים כאלה רשאים לגלגל גלגול הצלה נוסף נגד קרן מוות. יצורים בעלי כוח 12 או פחות (או פחות מ־4 קוביות פגיעה) שנכשלו בגלגול ההצלה הראשוני נותרים לכודים עד שמשך הלחש מסתיים או שהקורים מוסרים בדרך אחרת.

התקפות נגד יצור לכוד על ידי יצור מחוץ לקורים אינן מלכדות את התוקף, כל עוד אין צורך להיכנס לקורים כדי להגיע למטרה.

הקורים דליקים; כל שימוש באש גורם לקובייה של 3 מטרים להישרף בתוך סיבוב אחד, וקוביות סמוכות נשרפות בסיבוב הבא, וכן הלאה. אם חלק מהקורים הופך לבלתי נתמך, הוא קורס ונעלם כפי שתואר לעיל.

יצורים הלכודים בקורים הבוערים סופגים 2d4 נקודות פגיעה כאשר הקובייה שבה הם נמצאים נשרפת, ולאחר מכן הם חופשיים מהקורים.

:::

::: {.callout-note icon=false collapse=true}

### מנעול מכשפים

טווח: 6 מ'

קוסם 2

משך: קבוע

לחש זה סוגר ונועל באופן קסום דלת, שער, חלון או תריס מעץ, מתכת או אבן. הקסם גורם לפתח להיחשב כסגור ונעול כרגיל. הלחש נמשך ללא הגבלת זמן. **פריצה** יכולה לשמש לפתיחת הפתח מבלי לסיים את הלחש, ו**ביטול קסם** יכול לשמש לסיומו לצמיתות. המטיל יכול לפתוח בקלות את הדלת או כל פתח אחר מבלי לסיים את הלחש, וכך גם קוסם שדרגתו גבוהה ב־3 דרגות או יותר מדרגת המטיל.

:::

:::

<!-- ------------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# עוצמה 3, קוסם

::: {.callout-note icon=false collapse=true}

### ראייה על־חושית

טווח: 20 מ'

קוסם 3

משך: 12 תורות

לחש זה מאפשר למטיל לראות אזור אחר דרך עיניו של יצור חי הנמצא בו. על המטיל לציין כיוון ומרחק משוער, עד לטווח של 20 מטרים. אם אין יצור מתאים באזור, הלחש נכשל. לא מתאפשר גלגול הצלה, ויצור המטרה אינו מודע לכך שהוא משמש לכך.

המטיל יכול לבחור יצור מטרה אחר לאחר שחלף תור אחד לפחות, וכך לצפות במיקומים שונים. אם יצור המטרה יוצא מטווח הלחש, הקשר אובד; במקרה זה, המטיל יכול לבחור מטרה אחרת.

:::

::: {.callout-note icon=false collapse=true}

### זיוונות

טווח: מגע

קוסם 3

משך: שעה אחת/דרגה

הנושא מקבל [זיוונות](dungeonAdventures.qmd#זיוונות) בטווח של 20 מטרים למשך הלחש.

:::

::: {.callout-note icon=false collapse=true}

### ביטול קסם

טווח: 40 מ'

כוהן 4, קוסם 3

משך: מיידי

המטיל יכול להשתמש בלחש זה כדי לסיים לחשים מתמשכים שהוטלו על יצור או חפץ, או לסיים לחשים מתמשכים (או את האפקטים שלהם) בתוך אזור קובייתי שצלעו 6 מטרים. על המטיל לבחור אם להשפיע על יצור או חפץ, או על אזור.

כאשר הלחש מכוון ליצורים, כל אפקטי הלחשים (כולל אפקטים מתמשכים של שיקויים) עשויים להתבטל. כאשר הוא מוטל על אזור, כל האפקטים הללו בתוך האזור עשויים להתבטל. כל לחש או אפקט שדרגת המטיל שלו שווה או נמוכה מדרגת המטיל של **ביטול קסם** מסתיים אוטומטית. אפקטים שנוצרו על ידי מטילים בדרגה גבוהה יותר עשויים שלא להתבטל; עבור כל דרגה שבה דרגת המטיל של האפקט גבוהה מדרגת המטיל של הלחש, יש סיכוי של 5% לכישלון. לדוגמה, מטיל בדרגה 10 המנסה לבטל אפקט שנוצר על ידי מטיל בדרגה 14 מתמודד עם סיכוי כישלון של 20%.

ישנם לחשים שלא ניתן לסיים באמצעות ביטול קסם; במיוחד כל קללה, כולל אלו שנוצרו על ידי **הטלת קללה** (ההיפוך של **הסרת קללה**) וכן על ידי חפצים מקוללים.

:::

::: {.callout-note icon=false collapse=true}

### כדור אש

טווח: 30 מ'+3 מ'/דרגה

קוסם 3

משך: מיידי

הטלת לחש זה גורמת לגחלת זוהרת זעירה בגודל אפונה לעוף מאצבעו המורה של המטיל, ובכך נקבע כיוון תעופתה. הגחלת נעה במהירות חץ ומתפוצצת ללהבות הממלאות כדור ברדיוס של 6 מטרים כאשר היא מגיעה למרחק שנבחר על ידי המטיל (עד לטווח המרבי), או מוקדם יותר אם היא פוגעת במשטח מוצק או נוזלי. יצורים הנמצאים בתחום הלהבות סופגים נזק של 1d6 נקודות פגיעה לכל דרגת מטיל; גלגול הצלה נגד לחשים מפחית את הנזק לחצי.

בדרך כלל אין צורך בגלגול בעת הטלת לחש זה, אך אם המטיל מנסה להעביר את הגחלת דרך חריץ או פתח קטן אחר, עליו לבצע גלגול התקפת קליעים (ללא התאמות טווח) כדי לפגוע בו; כישלון מציין שכדור האש פוגע במשטח סמוך ומתפוצץ שם.

חפצים או חומרים דליקים בתחום האזור בדרך כלל יידלקו, ועשויים להיהרס (בהתאם להחלטת המנחה). מתכות בעלות נקודת התכה נמוכה, כגון זהב, כסף, עופרת, נחושת או ברונזה, עשויות להתרכך לזמן קצר ולכן להתעוות, אך הלהבות אינן נמשכות זמן מספיק כדי להמיס פריטי מתכת, אלא אם הם קטנים מאוד (למשל, שרשרת זהב דקה).

למרות שכדור האש מפעיל מעט מאוד כוח או לחץ בעת הפיצוץ, הוא עדיין עשוי להרוס מחסומים חלשים או דליקים; אם זה קורה (בהחלטת המנחה), כדור האש ממשיך להתפשט במרחב שמעבר למחסום שנהרס.

:::

::: {.callout-note icon=false collapse=true}

### מעוף

טווח: מגע

קוסם 3

משך: 1 תור/דרגה

נושא הלחש יכול לעוף במהירות השווה לקצב התנועה הקרקעי הרגיל שלו (כפי שמותאם לעומס). הוא יכול לעלות במהירות השווה למחצית מתנועתו, ולרדת במהירות כפולה, עם אותה יכולת תמרון כמו בתנועה על הקרקע. תעופה תחת השפעת לחש זה דורשת ריכוז הדומה להליכה, ולכן הנושא יכול לתקוף או להטיל לחשים כרגיל. הנושא אינו יכול להסתער או לרוץ, ואינו יכול לשאת משקל העולה על העומס המרבי שלו.

אם משך הלחש מסתיים בעוד הנושא באוויר, הקסם דועך בהדרגה, והנושא יורד בקצב של 30 מטרים לסיבוב במשך 1d10 סיבובים. אם הוא מגיע לקרקע בזמן זה, הוא נוחת בבטחה; אחרת, הוא נופל את שאר המרחק וסופג נזק נפילה רגיל. עם זאת, אם הלחש מסתיים עקב **ביטול קסם** או אפקטים דומים, הנושא נופל מיד. עבור כל נפילה כזו, ראי [נזק מנפילה](combat.qmd#נזק-מנפילה) לפרטים נוספים.

:::

::: {.callout-note icon=false collapse=true}

### האצה*

טווח: 9 מ'+3 מ'/דרגה

קוסם 3

משך: 1 סיבוב/דרגה

לחש זה מאיץ את פעולותיהם של יצור אחד לכל דרגת מטיל. היצורים המושפעים נעים ופועלים פי שניים מהר יותר מהרגיל: קצב התנועה שלהם מוכפל, והם מבצעים פי שניים התקפות לכל סיבוב. הטלת לחשים אינה מואצת, וגם לא השימוש בפריטים קסומים כמו שרביטים, שניתן להשתמש בהם רק פעם אחת לכל סיבוב. אפקטים של האצה או מהירות אינם מצטברים; יש ליישם רק את האפקט החזק או הארוך ביותר.

בקרב, נושא הלחש מבצע סיבוב מלא של פעולות (תנועה ולאחר מכן תקיפה) ביוזמה הרגילה שלו; לאחר שכל הלוחמים פעלו, הוא רשאי לבצע סיבוב נוסף של פעולות באותו אופן. אם שניים או יותר לוחמים נמצאים תחת השפעת הלחש, יש להשתמש באותם ערכי יוזמה כדי לקבוע את סדר פעולותיהם בסיבובים ה"נוספים".

בהיפוך, האצה הופכת ל**האטה**. יצורים מושפעים נעים בחצי מהירות, תוקפים בחצי מהתדירות (בדרך כלל, כל סיבוב שני), ומבצעים חצי תנועה רגילה בכל סיבוב. יצורי מטרה רשאים לגלגל גלגול הצלה נגד לחשים כדי להימנע מהאפקט. האצה והאטה מבטלים זה את זה.

:::

::: {.callout-note icon=false collapse=true}

### עצירת איש

טווח: 50 מ'

כוהן 2, קוסם 3

משך: 2d8 תורות

לחש זה משתק כל יצור דמוי-אדם חי (לא אל-מת), כפי שמוגדר ב**הקסמת איש**. יצורים גדולים מעוג אינם מושפעים מלחש זה. מטרות הלחש מודעות ויכולות לנשום, אך אינן יכולות לנוע, לפעול או לדבר. גלגול הצלה נגד לחשים מאפשר להתנגד לאפקט. ניתן להטיל את הלחש על יצור אחד, אשר סופג מחסר של 2- לגלגול ההצלה, או על קבוצה; במקרה זה, 1d4 יצורים בקבוצה עשויים להיות מושפעים.

יצור משותק במים אינו יכול לשחות ועלול לטבוע. יצור מעופף שמשותק באוויר אינו יכול להמשיך לעוף ונופל לקרקע.

:::

::: {.callout-note icon=false collapse=true}

### היעלמות מעין ברדיוס 3 מ'

קוסם 3

טווח: מגע

משך: תור אחד/דרגה

המטרה הופכת לבלתי נראית כמו בלחש **היעלמות מעין**, וכל היצורים הנמצאים במרחק של עד 3 מטרים ממנה בעת ההטלה (חברי הקבוצה) הופכים גם הם לבלתי נראים. בניגוד ללחש הבסיסי, חברי הקבוצה יכולים לראות זה את זה כרגיל.

אם חבר קבוצה תוקף או מטיל לחש, הוא הופך לגלוי, אך שאר החברים נשארים בלתי נראים. אם הנושא המקורי מבצע פעולה שמסיימת את ההיעלמות, הלחש מסתיים עבור כל הקבוצה. חבר שהפך לגלוי אינו יכול עוד לראות חברים שנותרו בלתי נראים. התרחקות מעבר ל-3 מטרים מהמטרה מסיימת את ההשפעה עבור אותו חבר; חזרה לטווח אינה מחזירה אותה.

:::

::: {.callout-note icon=false collapse=true}

###  חזיז ברק

טווח: 30 מ' + 3 מ'/דרגה

קוסם 3

משך: מיידי

הטלת לחש זה יוצרת ברק דק ובהיר, בעובי כחוט, היוצא מאצבעו המורה של המטיל ומצביע על כיוון התקדמותו. הברק נע במהירות חץ עד שהוא מגיע למרחק שנבחר על ידי המטיל (אך לא מעבר לטווח המרבי), או פוגע במשטח מוצק או נוזלי; אז הוא מתרחב לברק מלא הממשיך עוד 20 מטרים. הברק נע לאורך נתיב ברוחב של 1.5 מטרים ומקפץ; אף שאינו באמת ברוחב זה, לצורכי משחק הוא נחשב כאילו היה.

יצורים הנמצאים בנתיב הברק סופגים נזק של 1d6 נקודות פגיעה לכל דרגת מטיל; גלגול הצלה נגד לחשים מפחית את הנזק לחצי.

אם הברק פוגע בגוף מים, הוא מתפרץ בנקודת הפגיעה כפי שתואר לעיל, אך בתוך נפח המים שנפגע הוא מתפשט כמו כדור אש לרדיוס של עד 6 מטרים, במקום לפעול כפי שהוא פועל באוויר. אם הלחש מוטל מתחת למים, הברק מתפרץ באותו אופן, אך מקצה אצבעו המושטת של המטיל.

הברק מצית חומרים דליקים וגורם נזק לחפצים בדרכו. הוא עשוי לפגוע גם במתכות בעלות נקודת התכה נמוכה; מתכות כגון זהב, כסף, עופרת, נחושת או ברונזה עשויות להתרכך לזמן קצר ולכן להתעוות, אך הברק אינו נמשך זמן מספיק כדי להמיס חפצי מתכת, אלא אם הם קטנים מאוד (למשל, שרשרת זהב דקה).

אם הנזק שנגרם למחסום שובר או חודר אותו, הברק עשוי להמשיך מעבר למחסום אם טווח הלחש מאפשר זאת; אחרת, הוא עשוי לחזור מן המחסום לכיוון המטיל, או לנוע בכיוון אקראי לפי החלטת המנחה. יצורים שכבר נפגעו מהברק אינם סופגים נזק נוסף אם הם נפגעים ממנו שוב.

:::

::: {.callout-note icon=false collapse=true}

### הגנה מרשע ברדיוס 3 מ'*

כוהן 4, קוסם 3

טווח: מגע

משך: 1 תור/דרגה

לחש זה פועל בדיוק כמו **הגנה מרוע**, אך עם רדיוס של 3 מטרים במקום רדיוס של 0.5 מטרים. כל מי שנמצא בתוך הרדיוס מקבל את ההגנה; אלו שעוזבים ואז חוזרים, או שנכנסים לאחר שהלחש הוטל, מקבלים גם הם את ההגנה.

בהיפוך, לחש זה הופך ל**הגנה מטוב ברדיוס 3 מ'**, ופועל בדיוק כמו הצורה ההפוכה של **הגנה מרוע**, למעט שהוא מכסה רדיוס של 3 מטרים סביב המטרה במקום רדיוס רגיל של 0.5 מטרים.

:::

::: {.callout-note icon=false collapse=true}

### הגנה מקליעים רגילים

קוסם 3

טווח: עצמי

משך: 1 תור/דרגה

המטיל מוגן לחלוטין מפני התקפות של קליעים קטנים ולא קסומים. לכן, חצים קסומים, סלעים מושלכים וכדומה אינם נחסמים, אך כל מספר של חצים רגילים, כדורי קלע, בריחי רובה קשת, פגיונות מושלכים וכדומה יידחו. קליעים רגילים הנורים מקשתות קסומות נחשבים כקליעים קסומים לצורך לחש זה.

:::

::: {.callout-note icon=false collapse=true}

### נשימת מים

טווח: מגע

קוסם 3

משך: 2 שעות/דרגה

לחש זה מעניק ליצורים חיים שבהם נוגע המטיל (כולל המטיל, אם ירצה) את היכולת לנשום מתחת למים. ניתן לחלק את משך הלחש באופן שווה בין מספר מטרות, אם המטיל נוגע בהן בזו אחר זו. המטרות אינן מאבדות את היכולת לנשום אוויר.

:::

:::

<!-- ----------------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# עוצמה 4, קוסם

::: {.callout-note icon=false collapse=true}

### הקסמת מפלצת

טווח: 10 מ'

קוסם 4

משך: מיוחד

לחש זה פועל כמו **הקסמת איש**, אך אינו מוגבל לפי סוג או גודל היצור. מפלצות אל-מתים אינן מושפעות, וכן יצורים כמו גלמים וכל יצור חסר תודעה (כגון ג'לי מכל סוג). לחש זה יכול להשפיע על 3d6 קוביות פגיעה של יצורים בעלי 3 קוביות פגיעה או פחות, או על יצור אחד בעל יותר מ-3 קוביות פגיעה. גלגולי הצלה נעשים כפי שמתואר בלחש **הקסמת איש**.

:::

::: {.callout-note icon=false collapse=true}

### בלבול

טווח: 100 מ'

קוסם 4

משך: 2 סיבובים+1/דרגה

לחש זה גורם לעד 3d6 יצורים חיים בתוך מעגל ברדיוס של 9 מטרים סביב נקודת המטרה להיות מבולבלים. יצורים מבולבלים אינם מסוגלים לקבוע בעצמם את פעולותיהם. כל יצור רשאי לגלגל גלגול הצלה נגד לחשים כדי להתנגד לאפקט. עבור כל יצור שלא הצליח בגלגול ההצלה, גלגלו על הטבלה הבאה במספר היוזמה שלו בכל סיבוב כדי לקבוע את פעולתו.

```{ojs}

import {confusionTable, highlightTableRow} from "../custom.js"

viewof gemJewel3 = Inputs.button("גלגלו על הטבלה", {value: 0, reduce: () => highlightTableRow("#confusion-table", confusionTable())})

```

<br>

::: {#confusion-table}

|| d10 | התנהגות |
|-----|-----|
| 1 | פועל כרגיל |
| 2 | נע לכיוון המטיל, ותוקף אם ניתן |
| 3--5 | אינו עושה דבר מלבד אולי למלמל |
| 6--7 | נע במהירות הרחק מהמטיל |
| 8--10 | תוקף את היצור הקרוב ביותר, בין אם הוא חבר או אויב |


:::

אם היצור אינו יכול לבצע את הפעולה שהתקבלה, המנחה עוברת לשורה הבאה בטבלה (וחוזרת לראש הטבלה במידת הצורך) עד שנמצאת פעולה אפשרית. אם יצור מבולבל מותקף, הוא משיב להתקפה בהתאם ליוזמה שלו (מאוחר יותר באותו סיבוב, או בסיבוב הבא אם כבר פעל), ללא קשר לתוצאה שהתקבלה בטבלה.

:::

::: {.callout-note icon=false collapse=true}

### דלת מימדית

טווח: 3 מ'

קוסם 4

משך: מיידי

המטיל יכול להעביר מיד את עצמו או יצור מטרה יחיד בטווח לכל נקודה במרחק של עד 60 מטרים ועוד 6 מטרים לכל דרגת מטיל. המטיל או יצור המטרה מגיעים תמיד בדיוק לנקודה הרצויה, בין אם המטיל מדמיין את היעד או מציין כיוון ומרחק. מטרה שאינה מסכימה רשאית לגלגל הצלה נגד לחשים כדי להימנע מההעברה.

כל דבר שנלבש או נישא על ידי המטיל או יצור המטרה מועבר גם הוא, כולל דמות או יצור אחר אם המועבר מסוגל לשאת אותו. אם נקודת היעד נמצאת בתוך עצם מוצק, הלחש נכשל.


:::

::: {.callout-note icon=false collapse=true}

### גדילת צמחים*

טווח: 40 מ'

קוסם 4

משך: קבוע

לחש זה גורם לצמחייה רגילה מכל סוג בטווח להפוך לעבה ומגודלת. שטח ההשפעה נקבע על ידי מטיל הלחש, אך אינו יכול לעלות על 300 מטרים מרובעים (שטח של 3x100 מטרים או שווה ערך) לכל 5 דרגות מטיל. הצמחים הופכים לסבוכים בצפיפות, ודמויות או יצורים הרוצים לעבור דרכם חייבים לחתוך או להידחק דרכם בכוח. כל התנועה בתוך השטח המושפע מוגבלת ללא יותר מ-1.5 מטרים לסיבוב עבור יצורים קטנים מגודל ענק; יצורים בגודל ענק מוגבלים למחצית מקצב התנועה הרגיל.

לחש זה אינו יכול להיכנס לתוקף באזור שאין בו צמחים כלל. כל יצור צמח מונפש המושפע מלחש זה רשאי לגלגל הצלה נגד לחשים כדי להתנגד; אם גלגול זה נכשל, הוא מושפע כמו ב**גדילת חיות** לעיל.

הצורה ההפוכה, **כיווץ צמחים**, יכולה לשמש כדי להפוך אזורים מגודלים לנגישים. שטח ההשפעה זהה לגרסה הרגילה. יצורי צמח מונפשים בדרך כלל אינם מושפעים מלחש זה, אך אם יצורים כאלה כבר הוגדלו על ידי **גדילת צמחים**, לחש זה מבטל את האפקט. במקרה זה מותר גלגול הצלה נגד לחשים כדי להתנגד.

שתי הצורות של לחש זה הן קבועות עד שיבוטלו, או על ידי הצורה ההפוכה של הלחש או על ידי **ביטול קסם**.

:::

::: {.callout-note icon=false collapse=true}

### שטח דמיוני

קוסם 4

טווח: 120 מ' + 12 מ'/דרגה

משך: 12 תורות/דרגה

לחש זה גורם לנפח של 10x10x10 מטרים לכל דרגת מטיל של שטח חיצוני להיראות כסוג שונה של שטח (למשל שדה כיער, עשבייה כמדבר וכדומה). הטלת הלחש דורשת תור מלא.

השטח המושפע נראה, נשמע ומריח כמו הסוג החדש של השטח. מבנים, ציוד ויצורים בתוך האזור אינם מוסתרים ואינם משנים את מראם. גלגול הצלה נגד לחשים מאפשר לראות דרך האשליה, אך רק אם היצורים מנסים באופן פעיל לעשות זאת.

:::

::: {.callout-note icon=false collapse=true}

### סופת קרח

טווח: 90 מ'+9 מ'/דרגה

קוסם 4

משך: 1 סיבוב

לחש זה יוצר סופת שלג וברד עוצמתית ברדיוס של 6 מטרים סביב נקודה שנבחרת על ידי המטיל, למשך סיבוב מלא. הסופה גורמת ל־5d6 נקודות פגיעה לכל יצור בתחום; גלגול הצלה נגד לחשים מפחית את הנזק לחצי. הסופה ממלאת נפח אנכי של 12 מטרים, כך שיצורים הנמצאים מעל גובה זה אינם מושפעים. יצורים בעלי עמידות טבעית לקור סופגים חצי נזק (או רבע נזק אם הצליחו בגלגול ההצלה).

הראות בתוך הסופה גרועה מאוד, ולכן רוב היצורים סופגים עונש של -2 לגלגול התקפה. מהירות התנועה מופחתת לחצי, וריצה אינה אפשרית; יצור שמנסה לרוץ נופל ונשאר על הקרקע עד לסיום הלחש. גם תעופה אינה אפשרית, וכל יצור מעופף בתחום נופל לקרקע. עונש של -20% חל על כל גלגולי האזנה של יצורים בתחום הסופה.

כאשר הלחש מסתיים, הברד והקרח שנוצרו על ידי הסופה נעלמים כאילו לא היו.

:::

::: {.callout-note icon=false collapse=true}

### שינוי המוני

טווח: 30 מ' + 3 מ'/דרגה

קוסם 4

משך: שעה אחת/דרגה

לחש זה גורם ל־1d4+1 יצורים בגודל אדם (או קטנים יותר) לכל 4 דרגות מטיל להיראות כתופעות טבעיות של הסביבה (למשל עצים ביער, נטיפים במערה, אלמוגים מתחת למים, סלעים וכדומה). כל היצורים שיש להסוות חייבים להיות בטווח של 40 מטרים מהמטיל בעת הטלת הלחש. רק יצורים שהמטיל בוחר מושפעים, ורק אם הם מוכנים לכך. המטיל יכול לכלול גם את עצמו.

היצורים מוסתרים מיצורים אחרים העוברים באזור כל עוד הם נותרים דוממים. אם יצור מושפע זז או תוקף, האשליה מסתיימת עבורו בלבד, בעוד שאר היצורים נותרים מוסתרים. המטיל יכול לסיים את הלחש מוקדם באמצעות אמירת מילה אחת. האשליה יכולה להסתיים גם באמצעות **ביטול קסם**.

:::

::: {.callout-note icon=false collapse=true}

### שינוי אחר

טווח: 9 מ'

קוסם 4

משך: קבוע

לחש זה מאפשר למטיל לשנות יצור מטרה אחד לצורה אחרת של יצור חי. הצורה הנבחרת אינה יכולה להיות בעלת יותר קוביות פגיעה מדרגת המטיל, ואינה יכולה להיות חסרת גוף או גזית. בניגוד ל**שינוי עצמי**, המטרה המוסבת מקבלת גם את התכונות המנטליות וההתנהגותיות, כל ההתקפות הפיזיות, וכן יכולות מיוחדות, על־טבעיות או דמויות לחש של הצורה החדשה, בנוסף לתכונותיה הפיזיות. אם הצורה החדשה פחות אינטליגנטית באופן משמעותי, המטרה עשויה לשכוח את חייה הקודמים.

ליצור המטרה נשאר אותו מספר נקודות פגיעה כפי שהיה לו קודם, ללא קשר לקוביות הפגיעה של הצורה החדשה. יצורים חסרי גוף או גזיים חסינים ללחש זה. יצור בעל יכולת שינוי צורה (כגון דופלגנגר) יכול לחזור לצורתו הטבעית לאחר סיבוב אחד.

ציוד שנלבש או נישא נופל אם הצורה החדשה אינה יכולה להשתמש בו. אם פריטים כאלה עלולים להזיק פיזית לצורה החדשה, השינוי מואט כך שהם ייפלו ללא נזק לפריטים וללא פגיעה ביצור המטרה. אם המנחה קובעת שפריט כלשהו אינו ניתן להסרה בדרך זו, עליה להחליט על התוצאה.

מטרה שאינה מעוניינת רשאית לגלגל גלגול הצלה נגד שינוי; הצלחה מבטלת את הלחש. הלחש נמשך עד לביטולו או עד שהיצור נהרג, ואז המטרה חוזרת לצורתה המקורית.

:::

::: {.callout-note icon=false collapse=true}

### שינוי עצמי

טווח: עצמי

קוסם 4

משך: שעה אחת/דרגה

לחש זה מאפשר למטיל להשתנות לצורה אחרת של יצור חי. הצורה הנבחרת אינה יכולה להיות בעלת יותר קוביות פגיעה מדרגת המטיל, ואינה יכולה להיות חסרת גוף או גזית.

המטיל מקבל את התכונות הפיזיות של הצורה הנבחרת, אך שומר על תכונותיו המנטליות והרוחניות. הוא מקבל את דירוג השריון ואת כל ההתקפות הפיזיות של הצורה, אך אינו מקבל יכולות מיוחדות, על־טבעיות או דמויות לחש. נשיפת דרקון היא יכולת מיוחדת; לכן, אם המטיל בוחר בצורת דרקון, הוא יכול להשתמש בהתקפות הטפרים, הנשיכה והזנב, אך לא בנשיפה.

אם הצורה הנבחרת מסוגלת לדבר ולבצע מחוות מתאימות (לפי קביעת המנחה), המטיל יכול להטיל לחשים בצורתו החדשה.

ציוד שנלבש או נישא נופל אם הצורה החדשה אינה יכולה להשתמש בו. אם פריט כזה עלול להזיק פיזית לצורה החדשה, השינוי מואט כך שהפריט ייפול ללא נזק וללא פגיעה במטיל. אם המנחה קובעת שפריט אינו ניתן להסרה בדרך זו, הלחש נכשל.

המטיל יכול להישאר בצורתו החדשה עד למשך שעה אחת לכל דרגה, או לסיים את הלחש מוקדם לפי רצונו.

:::

::: {.callout-note icon=false collapse=true}

### הסרת קללה*

טווח: 10 מ'

כוהן 3, קוסם 4

משך: מיידי

לחש זה מסיר כל קללה רגילה הפוגעת ביצור. הוא אינו מסיר בדרך כלל את הקללה מפריט קסום כמו חרב או חליפת שריון, אך דמות המושפעת מפריט מקולל מסוג זה תשתחרר ממנו למשך זמן מספיק כדי להשליך את הפריט (לפחות תור).

חלק מהקללות המיוחדות קשות יותר להסרה, ועשויות לדרוש מטיל לחש בדרגה מינימלית מסוימת. מעט מאוד קללות שנוצרו על ידי ישויות אלוהיות ניתנות להסרה באמצעות לחש זה.

ההיפוך של הלחש הזה, **הטלת קללה**, מאפשר למטיל הלחש להטיל קללה על הנושא. גלגול הצלה נגד לחשים מאפשר להתנגד. המטיל חייב לבחור אחת משלוש ההשפעות הבאות:

* הפחתה של 4- לציון תכונה (מינימום 1).

* עונש של 4- על גלגולי תקיפה וגלגולי הצלה.

* בכל סיבוב קרב, יש למטרה סיכוי של 50% לפעול כרגיל; אחרת, היא אינה נוקטת בפעולה.

המטיל יכול גם להמציא קללה משלו, אך היא אינה יכולה להיות חזקה יותר מאלו שתוארו לעיל. הקללה המוטלת אינה ניתנת לביטול, אך ניתן להסירה באמצעות לחש **הסרת קללה**.

:::

::: {.callout-note icon=false collapse=true}

### קיר אש

טווח: 50 מ'

כוהן 5, קוסם 4

משך: 1 סיבוב/דרגה (או מיוחד)

לחש זה יוצר יריעת להבות אנכית באזור שהמטיל בוחר: קיר באורך של עד 6 מטרים לכל דרגת מטיל, או טבעת ברדיוס של עד 1.5 מטרים לכל דרגת מטיל. המטיל יכול לבחור ליצור קיר קטן יותר. גובה הקיר הוא עד 6 מטרים. כל הקיר חייב להיות בטווח.

הקיר יכול לפלוט חום מצד אחד או משני צדדיו, לפי בחירת המטיל בעת ההטלה. לאחר יצירתו, הקיר אינו נע ואינו משתנה.

כל יצור הנמצא עד 6 מטרים מהצד החם של הקיר סופג 1d4 נקודות פגיעה בכל סיבוב, או 2d4 נקודות אם הוא במרחק של עד 3 מטרים. הנזק נגרם בסיבוב שבו הלחש מוטל ובכל סיבוב לאחר מכן. מעבר דרך הקיר גורם ל־2d6 נקודות פגיעה, בתוספת 1 לכל דרגת מטיל, גם אם הצד שממנו נכנס היצור אינו צד חם.

יצורים אל-מתים סופגים נזק כפול מהערכים המפורטים לעיל.

אם הקיר נוצר במקום שבו נמצאים יצורים, כל יצור סופג נזק כאילו עבר דרכו; גלגול הצלה נגד לחשים מאפשר להפחית את הנזק כך שייחשב כאילו היצור נמצא במרחק של 3 מטרים מהקיר.

המטיל יכול לשמור על הלחש ללא הגבלת זמן באמצעות ריכוז (בגבולות סבירים של סיבולת), או להטיל אותו למשך 1 סיבוב לכל דרגה, לפי בחירתו.

:::

::: {.callout-note icon=false collapse=true}

### עין המכשף

טווח: 70 מ'

קוסם 4

משך: 6 תורות

לחש זה יוצר "עין" קסומה בלתי נראית שדרכה המטיל יכול לראות. לעין יש זיוונות, אך מעבר לכך היא רואה כפי שהמטיל רואה. ניתן ליצור אותה בכל נקודה שהמטיל יכול לראות, עד לטווח של 70 מטרים, ולאחר מכן היא יכולה לנוע בקצב של 12 מטרים לסיבוב לפי רצון המטיל. העין אינה מתרחקת יותר מ־70 מטרים מהמטיל.

העין אינה יכולה לעבור דרך עצמים מוצקים, אך מכיוון שגודלה כגודל עין אנושית, היא יכולה לעבור דרך פתחים קטנים בקוטר של לפחות 3 סנטימטרים. המטיל חייב להתרכז כדי להשתמש בעין.

:::

:::

<!-- ---------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# עוצמה 5, קוסם

::: {.callout-note icon=false collapse=true}

### הנפשת מתים

טווח: 10 מ'

כוהן 4, קוסם 5

משך: מיוחד

הטלת לחש זה גורמת לשרידי יצורים מתים אחד או יותר לקום כשלדים או זומבים מונפשים. מפלצות אל-מתים אלו נשארות עד שהן נהרגות, ומצייתות לפקודותיו המילוליות של מטיל הלחש. הטלה אחת של לחש זה יכולה להנפיש מספר קוביות פגיעה של אל-מתים השווה לפי 2 מדרגת היכולת של מטיל הלחש, ולא יותר. לשלדים מונפשים יש קוביות פגיעה השוות למספר שהיה ליצור בחייו; עבור שלדים של בני גזעי דמויות שחקן, משמעות הדבר היא קוביית פגיעה אחת, ללא קשר לדרגת הדמות של המת. לזומבים יש קוביית פגיעה אחת יותר מאשר ליצור שהיה בחייו.

סוג המפלצות שנוצר תלוי במצב השרידים. גופה שלמה יחסית יכולה לקום רק כזומבי, בעוד ששרידי שלד שלמים יחסית יכולים להיות מונפשים רק כשלד. מטיל הלחש בוחר אילו שרידים להנפיש בעת הטלת הלחש, בכל מקרה שבו יש יותר גופות ממה שהוא יכול להנפיש.

שום דמות אינה יכולה לשלוט בדרך כלל ביותר קוביות פגיעה של אל-מתים מפי 4 מדרגתה, ללא קשר למספר הפעמים שבהן הלחש הזה מוטל.

:::

::: {.callout-note icon=false collapse=true}

### ענן מוות

טווח: 30 מ'+3 מ'/דרגה

קוסם 5

משך: 6 סיבובים/דרגה

לחש זה יוצר ענן של גז רעיל בגודל 6x6x6 מטרים, הנע בקצב של 3 מטרים לסיבוב תחת שליטת המטיל (כל עוד הוא מתרכז בו). הגז הורג מיד כל יצור בעל 3 קוביות פגיעה או דרגות או פחות שבא עמו במגע; יצורים בעלי 4 קוביות פגיעה או דרגות או יותר חייבים לגלגל גלגול הצלה נגד רעל או למות. הענן נותר למשך כל משך הלחש, גם אם המטיל מפסיק להתרכז בו.


:::

::: {.callout-note icon=false collapse=true}

### זימון יסודן

טווח: 70 מ'

קוסם 5

משך: מיוחד

פתח למישור היסודות של אוויר, אדמה, אש או מים נפתח, ומאפשר למטיל הלחש לזמן יסודן מאותו מישור. עייני בערך [יסודן](monstersAll.qmd#יסודן) בסעיף המפלצות לפרטים נוספים על הסוגים הזמינים ועל תכונותיהם. לכל היותר יסודן אחד מכל סוג יכול להיות מזומן על ידי המטיל ביום נתון.

מרגע שהיסודן מופיע, הוא משרת את המזמן ללא הגבלת זמן, כל עוד המטיל מתרכז אך ורק בשליטה ביצור; הטלת לחשים, לחימה, או תנועה מעבר למחצית הקצב הרגיל גורמות לאובדן ריכוז.

המזמן, בעת שליטה ביסודן, יכול לשחרר אותו למישור המקורי שלו כרצונו. במהלך קרב, השחרור מתבצע בתורו של המטיל. אם המטיל מאבד ריכוז, השליטה ביסודן המזומן אובדת ולא ניתן להשיבה. היצור ינסה לתקוף את המזמן ואת כל האחרים בדרכו.

רק **ביטול קסם** או **ביטול רוע** יכולים לגרש את היסודן לאחר שאבדה השליטה. יסודן עשוי, כמובן, לבחור לחזור למישור הבית שלו בעצמו; יצורים כאלה לא יישארו במישור החומרי לאורך זמן.

:::

::: {.callout-note icon=false collapse=true}

### רפיסות מוח

טווח: 50 מ'

קוסם 5

משך: קבוע

לחש זה מטיל קללה על יצור חי, ומפחית את התבונה והכריזמה שלו ל־1 כל אחת. מותר גלגול הצלה נגד לחשים כדי להתנגד לאפקט זה; אם המטרה היא מטיל לחשים, מוחל מחסר של 4- לגלגול ההצלה.

לאחר שהושפע, הקורבן אינו יכול להטיל לחשים, לדבר או להבין שפה כלשהי, ואינו מסוגל לתקשר כלל, שכן אינו מבין אפילו מחוות פשוטות כגון הצבעה או קריצה. עם זאת, הקורבן עדיין מזהה את בני בריתו וינסה לעקוב אחריהם ולעזור או להגן עליהם.

אפקט זה ניתן להסרה באמצעות **ריפוי כל** או באמצעות ההיפוך של לחש זה, **השבת מוח**.

:::

::: {.callout-note icon=false collapse=true}

### עצירת מפלצת

טווח: 50 מ'

קוסם 5

משך: 2d8 תורות

לחש זה פועל כמו **עצירת איש**, אך משפיע על כל יצור חי שנכשל בגלגול הצלה נגד לחשים.

:::

::: {.callout-note icon=false collapse=true}

### בקבוק קסם

טווח: 20 מ'

קוסם 5

משך: מיוחד

לחש זה מאפשר למטיל לנסות להשתלט על גופו של יצור חי אחר. המטיל מתחיל בכך שהוא מעביר את רוחו אל אבן חן, תכשיט או קריסטל גדול כלשהו בטווח הלחש, הנקרא בקבוק קסם. המטיל חייב לדעת את מיקומו של בקבוק הקסם, אך אינו חייב לראותו. בזמן שרוחו מחוץ לגופו, הגוף נראה כמת לכל דבר, אך אינו עובר ריקבון כגופה רגילה.

בכל סיבוב לאחר הכניסה לבקבוק הקסם, רוחו של המטיל יכולה לנסות להשתלט על גופו של יצור חי בטווח הלחש; המטרה מקבלת גלגול הצלה נגד לחשים כדי להתנגד. אם גלגול ההצלה נכשל, רוחו של היצור (המכונה מעתה המארח) נלכדת בבקבוק הקסם, ורוחו של המטיל משתלטת על גופו של המארח. השתלטות באמצעות לחש זה נחסמת על ידי **הגנה מרוע** או הגנות דומות.

אם הניסיון להשתלט נכשל, רוחו של המטיל נשארת בבקבוק הקסם, והיצור שנבחר חסין לניסיונות נוספים למשך כל זמן הלחש. המטיל רשאי לנסות להשתלט על מטרה אחרת בסיבוב הבא.

אם הניסיון מצליח, המטיל רשאי להישאר בשליטה על גופו של המארח למשך כל זמן שירצה. רוחו של המטיל יכולה לחזור לבקבוק הקסם בכל עת, כל עוד הוא בטווח הלחש; במקרה כזה רוחו של המארח חוזרת לגופו. המטיל אינו יכול להשתלט שוב על אותו מארח למשך שארית הלחש, אך יכול לעשות זאת בלחש חדש.

בכל זמן שרוחו של המטיל נמצאת בבקבוק הקסם, הוא יכול לבחור לחזור לגופו, אם הוא בטווח הלחש. אם הגוף אינו בטווח, רוחו עלולה להילכד בבקבוק אם אין יצורים פגיעים בטווח.

כאשר רוחו של המטיל חוזרת לגופו, הלחש מסתיים. עם סיום הלחש יש סיכוי של 50% שבקבוק הקסם יתנפץ (אלא אם כבר נשבר), ויהפוך לחסר ערך.

כאשר המטיל שולט בגוף מארח, הוא משתמש בתכונותיו הפיזיות של המארח (כוח, זריזות וחוסן), אך שומר על תכונותיו המנטליות (תבונה, חוכמה וכריזמה). למטיל יש גישה רק לידע שלו, לדרגתו ולמקצועו, לבונוס התקיפה שלו, לגלגולי ההצלה שלו, ליכולת הטלת הלחשים שלו וליכולות מנטליות אחרות.

המטיל אינו מקבל גישה לכוחות על־טבעיים או יוצאי דופן של המארח, וייתכן שלא יוכל לבצע פעולות פיזיות שלא חווה בעבר (כגון תעופה, אם השתלט על גוף מכונף). עם זאת, יש לו גישה לחושים של המארח, כגון ראיית חושך או חוש ריח חד.

אם רוחו של המטיל נמצאת בבקבוק הקסם והבקבוק נשבר (בין אם עקב **ביטול קסם** או נזק פיזי), רוחו של המטיל חוזרת לגופו אם הוא בטווח; אם לא, רוחו אובדת (והמטיל מת). בכל מקרה, הלחש מסתיים.

אם רוחו של המטיל מגורשת מגוף המארח באמצעות **ביטול רוע**, ובקבוק הקסם נמצא בטווח מגוף המארח, רוחו של המטיל חוזרת לבקבוק ורוחו של המארח חוזרת לגופו. המטיל אינו יכול להשתלט שוב על אותו מארח למשך שארית הלחש. אם הבקבוק אינו בטווח, רוחו של המטיל אובדת, רוחו של המארח משתחררת מהבקבוק ואובדת גם היא, וגופו של המארח מת.

אם רוחו של המארח נמצאת בבקבוק הקסם והבקבוק נשבר בעודו בטווח מגופו, רוחו של המטיל אובדת, רוחו של המארח חוזרת לגופו, והלחש מסתיים. אם הבקבוק נשבר כשהוא מחוץ לטווח, רוחו של המארח אובדת, ורוחו של המטיל נתקעת בגוף המארח. במקרה זה הלחש אינו מסתיים. **ביטול רוע** עדיין יכול לגרש את רוחו של המטיל, שתאבד כפי שתואר, ובכך יסתיים הלחש. מטיל שנלכד כך יכול להשתמש בלחש זה שוב (עם בקבוק קסם אחר) כדי לחזור לגופו, פעולה שתהרוג את גוף המארח.

:::

::: {.callout-note icon=false collapse=true}

### מעבר קיר

טווח: 10 מ'

קוסם 5

משך: 3 תורות

לחש זה יוצר מעבר דרך קירות עץ, טיח או אבן, אך לא דרך מתכת או חומרים קשים יותר. עומק המעבר הוא עד 3 מטרים, ועוד 3 מטרים לכל 3 דרגות מטיל מעל דרגה 9 (6 מטרים בדרגה 12, 9 מטרים בדרגה 15, 12 מטרים בדרגה 18).

אם עובי הקיר גדול מעומק המעבר, הלחש יוצר נישה או מנהרה קצרה בלבד. ניתן להטיל את הלחש מספר פעמים כדי ליצור מעבר רציף דרך קירות עבים מאוד.

כאשר המעבר נעלם (עקב סיום משכו, **ביטול קסם**, או לפי בחירת המטיל), יצורים הנמצאים בתוכו נפלטים אל היציאה הקרובה ביותר.

:::

::: {.callout-note icon=false collapse=true}

### טלקניזיס

טווח: עצמי

קוסם 5

משך: 3 תורות

לחש זה מאפשר למטיל להזיז חפצים או יצורים באמצעות ריכוז בלבד; הוא יכול להזיז משקל של עד 25 ק"ג לכל דרגת מטיל, בקצב של עד 6 מטרים לסיבוב. יצורים המושפעים מלחש זה רשאים לגלגל גלגול הצלה נגד קרן מוות כדי להתנגד, בין אם מדובר ביצור עצמו או בחפץ שברשותו.

כדי להשתמש בכוח זה, המטיל חייב לשמור על ריכוז, לנוע לכל היותר בתנועה רגילה (ללא ריצה), לא לתקוף ולא להטיל לחשים נוספים. אם הריכוז אובד (בין אם בכוונה ובין אם לא), ניתן להשתמש בכוח שוב בסיבוב הבא, אך היצור המושפע רשאי לגלגל גלגול הצלה חדש.

:::

::: {.callout-note icon=false collapse=true}

### שיעתוק

טווח: עצמי

קוסם 5

משך: מיידי

הלחש מעביר את המטיל מיידית למיקום אחר, עד 150 ק"מ לכל דרגת מטיל. המעבר מתרחש רק בתוך אותו מישור קיום. יצורים אחרים (נוסעים) וחפצים דוממים (מטען) יכולים לעבור עם המטיל, עד למקסימום של 135 ק"ג ועוד 45 ק"ג לכל דרגה מעל 10. על המטיל להיות במגע עם כל החפצים ו/או היצורים שיועברו (אם כי היצורים יכולים להיות במגע זה עם זה, כל עוד לפחות אחד מהם במגע עם המטיל). יצורים שאינם מעוניינים רשאים לגלגל גלגול הצלה נגד לחשים כדי להתנגד, והמטיל עשוי להידרש לגלגול התקפה כדי לגעת בהם. הצלחה בגלגול הצלה גם מונעת העברת חפצים שבחזקת היצור.

הלחש מונחה על ידי מחשבת המטיל, אשר חייב לדמיין את אזור היעד. כישלון בדמיון מדויק עלול לגרום לתוצאה שגויה, ויעדים רוויים באנרגיה קסומה (לפי קביעת המנחה) גורמים לכישלון אוטומטי.

כדי לקבוע את תוצאת הלחש, גלגל d% והתייעץ בטבלה:

| מכיר היטב | מכיר במידה מסוימת | ראה פעם אחת | תוצאה |
|-----------|--------------------|-------------|--------|
| 01        | 01–02              | 01–03       | אסון   |
| 02        | 03–07              | 04–13       | מקום שגוי |
| 03        | 08–13              | 14–25       | החטאה קצרה |
| 04–100    | 14–00              | 26–100      | הצלחה |

**מכיר היטב**: המטיל ביקר ביעד לעיתים קרובות או בילה בו זמן ניכר. בדרך כלל נדרש לפחות 7 ימים (לא בהכרח רצופים) במהלך השנה האחרונה. מקום שבו המטיל גר יותר מחודש בעשר השנים האחרונות, או יותר משנה בחייו, נחשב גם כן.

**מכיר במידה מסוימת**: המטיל בילה זמן באזור היעד, אך לא די כדי להיחשב "מכיר היטב", או ביצע מחקר מעמיק (מפות, ציורים מדויקים, תיאורים מפורטים ממקורות אמינים).

**ראה פעם אחת**: המטיל ביקר במקום למשך יום אחד לכל היותר, או ביצע מחקר חלקי שלא סיפק מידע מספק (לפי קביעת המנחה).

**אם המטיל מנסה להגיע למיקום שאינו קיים** (או השתנה כך שלא ניתן לזהותו), גלגל 2d20 במקום d%. במקרה של "הצלחה", הלחש נכשל ואיש אינו מועבר.

**הצלחה**: המטיל, הנוסעים והמטען מגיעים בדיוק ליעד.

**החטאה קצרה**: ההגעה מתבצעת בבטחה למרחק של 1d8×10% מהדרך ליעד.

**מקום שגוי**: ההגעה היא למיקום דומה ליעד, כפי שנקבע על ידי המנחה. אם אין מיקום מתאים בטווח, הלחש נכשל.

**אסון**: המטיל, הנוסעים והמטען חווים טורבולנציה מימדית, מתפזרים ונפגעים. כל יצור סופג 1d12 נקודות פגיעה, ולאחר מכן מגלגל שוב באותה עמודה באמצעות 2d20. תוצאה נוספת של "אסון" גורמת לנזק נוסף ולגלגול חוזר. חפצים בדרך כלל אינם נפגעים, אך יש לגלגל עבור כל פריט כדי לקבוע את מיקומו; תוצאת "אסון" גורמת להיעלמות הפריט לצמיתות.

:::

::: {.callout-note icon=false collapse=true}

### קיר אבן

טווח: 4.5 מ'/דרגה

קוסם 5

משך: קבוע

לחש זה יוצר קיר אבן. הקיר מורכב ממקטעים מרובעים בגודל של עד 3x3 מטרים, בעובי של חצי מטר, לכל דרגת מטיל. המטיל יכול לעצב את הקיר כמעט בכל צורה, בכפוף למספר מגבלות. ניתן להגדיל את עובי הקיר על חשבון שטחו; לדוגמה, הכפלת העובי מפחיתה את השטח בחצי. הקיר אינו יכול להיווצר כך שיתפוס את מקומם של חפצים או יצורים. עליו להיות נתמך על ידי אבן קיימת, שאליה הוא מתחבר אוטומטית, אך אין צורך בתמיכה לכל אורכו. לדוגמה, ניתן ליצור קיר אבן כגשר מעל נחל או תהום, כל עוד שני קצותיו נשענים ומתחברים לאבן קיימת.

גשרים באורך העולה על 6 מטרים חייבים להיות מקושתים, מחוזקים או שניהם כדי להחזיק מעמד; בנייה זו מפחיתה את נפח הקיר השמיש בחצי, וכך גם יצירת חומות, חרכי ירי ואלמנטים מבניים בסיסיים דומים. לא ניתן ליצור אלמנטים מבניים מורכבים באמצעות לחש זה.

למרות שנוצר באמצעות קסם, הקיר עשוי אבן וניתן לשבור או לפגוע בו כאילו היה אבן רגילה.

ניתן ליצור את הקיר כמיכל הלוכד יצורים; במקרה זה, יצורים בתחום רשאים לגלגל גלגול הצלה נגד קרן מוות כדי להימנע מלכידה. אם הגלגול מצליח, הם יכולים לבצע תנועה מלאה אחת אל מחוץ למיכל.

:::

:::

<!-- ------------------------------------ -->

::: {.callout-tip icon=false collapse=true}

# עוצמה 6, קוסם

::: {.callout-note icon=false collapse=true}

### קליפה נגד קסם

טווח: רדיוס 3 מ'

קוסם 6

משך: 1 תור/דרגה

הלחש יוצר תחום ברדיוס של 3 מטרים סביב המטיל, שבו קסם אינו פועל. התקפות קסומות אינן משפיעות על המטיל, וחפצים ולחשים קסומים בתוך התחום מדוכאים. המטיל אינו יכול להטיל לחשים נוספים כל עוד הלחש פעיל.

:::

::: {.callout-note icon=false collapse=true}

### לחש מוות

טווח: 70 מ'

קוסם 6

משך: מיידי

לחש זה הורג עד 3d12 קוביות פגיעה או דרגות של יצורים בתחום כדור ברדיוס של 9 מטרים, שממוקם בכל נקודה שהמטיל בוחר (בתוך הטווח). קוביות פגיעה או דרגות מעבר לכך אינן נחשבות.

כל יצור מושפע רשאי לגלגל גלגול הצלה נגד קרן מוות; יצורים שנכשלים בגלגול מתים מיד. יצורים בעלי 8 קוביות פגיעה או יותר, או 8 דרגות או יותר, חסינים ללחש, וכן מפלצות אל-מתות, גלמים, וכל יצור שאינו חי באמת.

:::

::: {.callout-note icon=false collapse=true}

### התפוררות

טווח: 20 מ'

קוסם 6

משך: מיידי

לחש זה יורה קרן אור ירוקה מאצבעו המצביעה של המטיל. כל יצור או חפץ יחיד (עד נפח של 10×10×3 מטרים) מתפורר לחלוטין. המטרה רשאית לגלגל גלגול הצלה נגד לחשים כדי להתנגד; אם ההצלה מצליחה, הלחש נכשל.

הלחש יכול למקד יצור אחד בלבד לכל הטלה.

ציוד שנלבש או נישא על ידי יצור שהתפורר אינו מושפע, ונופל לקרקע.

:::

::: {.callout-note icon=false collapse=true}

### בשר לאבן

טווח: 10 מ'/דרגה

קוסם 6

משך: קבוע

לחש זה גורם ליצור חי, יחד עם כל הציוד שהוא לובש או נושא, להתאבן. זהו אותו אפקט הנגרם ממבט של מדוזה או ממגע של קוקטריס. מותר גלגול הצלה נגד התאבנות כדי להתנגד ללחש.

הקורבן המאובן נכנס למצב של קיפאון מוחלט; לא ניתן ליצור קשר עם תודעתו בשום דרך, והוא אינו נחשב חי ואינו נחשב מת. כל נזק הנגרם לצורתו המאובנת יחול על גופו אם יושב למצבו הבשרי; שבירת איבר, למשל, עלולה לגרום למוות עקב אובדן דם. המנחה תקבע את ההשפעות המדויקות של פציעות כאלה.

לחש ההיפוך, **אבן לבשר**, משמש כלחש נגד ל־**בשר לאבן**, ומשיב את היצור למצבו כפי שהיה ברגע ההתאבנות. הלחש אינו משפיע על אבן שאינה תוצאה של **בשר לאבן** או של אפקטי התאבנות דומים (כגון מבט של מדוזה).


:::

::: {.callout-note icon=false collapse=true}

### פיקוד

טווח: 1.5 מ' לדרגה

קוסם 6

משך: מיוחד

לחש זה מחייב יצור חי לבצע פעולה או שירות מסוים, או להימנע מביצוע פעולה מסוימת. היצור המטרה חייב להיות מסוגל לשמוע ולהבין את המטיל; אחרת אינו מושפע. הלחש נכשל אוטומטית אם הוא מורה לבצע פעולה שהיא הרס עצמי מובהק.

גלגול הצלה נגד לחשים מאפשר למטרה שאינה מסכימה להתנגד ללחש בעת הטלתו. עם זאת, המטרה יכולה לבחור לקבל את הפקודה, בדרך כלל כחלק מעסקה עם המטיל. לאחר שהושפעה מהלחש, המטרה חייבת לציית להוראות ללא הגבלת זמן; אם הפקודה היא ביצוע פעולה מסוימת, הלחש מסתיים כאשר הפעולה הושלמה.

בכל 24 שעות שבהן המטרה אינה מצייתת לפקודה (או נמנעת מלציית לה), היא סובלת ממחסר של 2- לכל אחד מערכי התכונות שלה, עד למקסימום של 8-. אף ערך תכונה אינו יכול לרדת מתחת ל־3 כתוצאה מאפקט זה. אם המטרה חוזרת לציית לפקודה, כל המחסרים מוסרים לאחר 24 שעות.

אם המשימה שהוטלה פתוחה או בלתי ניתנת להשלמה, המטרה עדיין מחויבת לנסות לבצע אותה, אך הלחש מסתיים לאחר לכל היותר יום אחד לכל דרגת מטיל. יצורים חכמים מאוד עשויים לעקוף את ההוראות; המנחה קובעת את התוצאות של ניסיונות כאלה.

לחש זה מסתיים באמצעות **הסרת קללה** המוטלת על ידי מטיל בדרגה גבוהה משל מטיל הלחש, ואינו מושפע מ־**ביטול קסם**.

:::

::: {.callout-note icon=false collapse=true}

### עוקב בלתי-נראה

טווח: 0

קוסם 6

משך: מיוחד

המטיל מזמן **עוקב בלתי נראה** לבצע את פקודותיו (ראי סעיף [מפלצות](monstersAll.qmd#עוקב-בלתי-נראה) לפרטים). הלחש נמשך עד שמוטל על היצור **ביטול רוע**, עד שהוא נהרג, או עד שהמשימה הושלמה. מומלץ למנחה לעיין בתיאור המפלצת כאשר הלחש מוטל, שכן יצורים אלה אינם תמיד משרתים אמינים.

:::

::: {.callout-note icon=false collapse=true}

### הנמכת מים

טווח: 6 מ'/דרגה

קוסם 6

משך: תור אחד/דרגה

באמצעות לחש זה המטיל מנמיך את מפלס המים בנהר, באגם או אפילו בים, עד 0.5 מטרים לכל דרגת מטיל למשך הזמן הנתון, אך לא לפחות מ-5 סנטימטרים עומק. הלחש משפיע על אזור שמרכזו במיקום שנבחר על ידי המטיל (בתוך הטווח הנתון), ברדיוס של לכל היותר 3 מטרים לכל דרגה.

במקום שבו יש מדרון תלול אל פני השטח של אזור המים שלא הונמך, מחוץ לרדיוס הלחש, ספינות שכבר נמצאות באזור ההשפעה, וכן כל אלו שמעזות להיכנס אליו, לא יוכלו לטפס על המדרון ולכן לא יוכלו לעזוב את האזור (אם לא נתקעו על החוף מלכתחילה עקב הלחש).

לחש זה פועל כמו **האטה** (ההיפוך של **האצה**) כאשר הוא מוטל על יסודני מים ויצורים אחרים שנוצרו ממים. גלגול הצלה נגד לחשים מותר; הצלחה מבטלת את האפקט. לא ניתן להטיל את הלחש על יצורים מסוג אחר.

:::

::: {.callout-note icon=false collapse=true}

### דמות מוקרנת

טווח: 70 מ'

קוסם 6

משך: 6 תורות

לחש זה יוצר דמות אשלייתית כמעין־אמיתית של המטיל. דמות מוקרנת זו נראית, נשמעת ומריחה כמו המטיל, וכן מחקה את מחוותיו ופעולותיו (כולל דיבור, המוקרן מן המטיל אל הדמות האשלייתית כאילו באמצעות **פיתומות**). כל לחשים נוספים שהמטיל מטיל נראים כאילו הם נובעים מהאשליה, ולא מן המטיל האמיתי.

יש לשמור על קו ראייה בין המטיל לבין הדמות האשלייתית, אחרת הלחש מסתיים. כל אפקט או פעולה שמפרים את קו הראייה מבטלים את הדמות, וכך גם אם הדמות האשלייתית נפגעת בקרב. שימו לב שלחש זה אינו מעניק למטיל יכולות חישה מיוחדות; לדוגמה, אם הדמות האשלייתית ממוקמת כך שתוכל לראות משהו שהמטיל אינו יכול לראות ישירות, המטיל אינו רואה זאת. בנוסף, כל טווחי הלחשים עדיין מחושבים ממיקומו האמיתי של המטיל, ולא ממיקום הדמות האשלייתית.


:::

::: {.callout-note icon=false collapse=true}

### גלגול נשמות

טווח: מגע

קוסם 6

משך: מיידי

על ידי נגיעה בגופו של יצור דמוי־אנוש (כפי שמוגדר ב**הקסמת איש**) שנפטר, המטיל מחזיר אותו לחיים בגוף חדש לחלוטין. הגוף כולו אינו נדרש; למעשה, אפילו החלק הקטן ביותר של הגוף מספיק, כל עוד החלק הזה היה חלק מהגוף בזמן מותה של המטרה.

המטיל יכול להחזיר לחיים בגלגול נשמות רק יצור שלא היה מת יותר משבוע. רוח המטרה חייבת להיות מוכנה לחזור. אם רוח המטרה כלואה או מוחזקת בכל דרך שהיא, הלחש ייכשל.

גלגלו על הטבלה הבאה כדי לקבוע לאיזה סוג של יצור הדמות הופכת:


```{ojs}

import {generalTableSelect} from "../custom.js"

viewof reincarnate = Inputs.button("גלגלו על טבלה", {value: 0, reduce: () => highlightTableRow("#reincarnate-spell", generalTableSelect([1,100,0],[[1,1],[2,15],[16,29],[30,30],[31,39],[40,46],[47,60],[61,88],[89,91],[92,93],[94,98],[99,100]]))})

```
<br>

:::{#reincarnate-spell}

| d% | גלגול נשמות |
|----|----|
| 01 | דובלין |
| 02--15 | גמד |
| 16--29 | אלף |
| 30 | גנול |
| 31--39 | ננס |
| 40--46 | גובלין |
| 47--60 | בן-מחצית |
| 61--88 | אדם |
| 89--91 | קובולד |
| 92--93 | איש לטאה |
| 94--98 | אורק |
| 99--100 | בחירה* |

:::

אם "בחירה" מגולגלת עבור דמות שחקן שעוברת גלגול נשמות, השחקן רשאי לבחור את הצורה החדשה מבין אלה שבטבלה למעלה. אם דמות מנחה עוברת גלגול נשמות, המנחה עשויה לבחור או לגלגל שוב.

כאשר הלחש מוטל, גוף חדש נוצר במיקום סמוך שנבחר על ידי המטיל. הגוף נוצר במשך 6 תורות (כלומר שעה), תחילה כמתאר ערפילי, ואז הופך למוצק יותר מרגע לרגע עד שהוא נושם לראשונה ומתעורר. הצורה החדשה היא צעיר בוגר, אלא אם המטרה הייתה צעירה מזה כאשר מתה, ובמקרה זה הגוף החדש הוא באותו גיל כמו הגוף שנפטר.

לגוף החדש של היצור לא נגרם שום נזק שיכול היה להיגרם לגוף הישן, והוא בריא לחלוטין (לפחות, בהתחלה).

המטרה זוכרת את חייה הקודמים, ושומרת על אותה מקצוע (אם אפשרי לצורה החדשה) כמו גם על תבונה, חוכמה וכריזמה. כוח, זריזות וחוסן צריכים להיות מגולגלים מחדש. (אם ציוני היכולת של הדמות הם מחוץ לטווח המותר לצורה החדשה, הם צריכים להיות מותאמים למעלה או למטה על ידי המנחה לפי הצורך.) המטרה מאבדת דרגה אחת (או קוביית פגיעה); זו הפחתה ממשית, לא דרגה שלילית, ואינה כפופה ל**השבה** קסומה. נקודות הפגיעה של המטרה צריכות להיות מגולגלות מחדש לחלוטין, שכן זהו גוף חדש לחלוטין. אם המטרה הייתה בדרגה 1, במקום הפחתת נקודות פגיעה, הציון החדש של חוסן מופחת ב-2.

דמויות שהפכו ליצורי מפלצות שאינם דמויות (כגון אלף שחוזר כקובולד) ידרשו שיפוט על ידי המנחה; אם המטרה שהוחזרה היא דמות שחקן, המנחה מומלצת לתת כמה שיותר חופש לשחקן עם הצורה החדשה של הדמות. לעומת זאת, יצורי מפלצות שאינם דמויות שחוזרים כדמויות ידרשו גלגול מחדש של כל ציוני היכולת; דמויות כאלה יהיו בדרך כלל לוחמים בדרגה השווה לקוביות הפגיעה הקודמות של המטרה פחות 1, או כאנשים רגילים אם קוביות הפגיעה הקודמות של המטרה היו 1 או פחות.

יצורים אל-מתים אינם מושפעים מהלחש הזה; יצורים כאלה אינם יכולים לחזור לחיים במובן רגיל.

:::

::: {.callout-note icon=false collapse=true}

### קיר ברזל

טווח: 30 מ'

קוסם 6

משך: קבוע

לחש זה יוצר קיר ברזל. הקיר עומד זקוף ומורכב ממקטעים מרובעים בגודל 3x3 מטרים, בעובי של 3 סנטימטרים לכל דרגת מטיל. ניתן להגדיל את עובי הקיר על חשבון שטחו; לדוגמה, הכפלת העובי מפחיתה את השטח בחצי. המטיל יכול לבחור ליצור קיר קטן יותר. עובי הקיר אינו יכול להיות קטן מ־3 סנטימטרים, והוא חייב להיווצר במגע עם הקרקע או הרצפה שמתחתיו. הקיר הוא לוח שטוח ללא כיפופים, אך קצותיו יכולים להתעצב סביב מכשולים סמוכים. הקיר אינו יכול להיווצר כך שיתפוס את מקומם של חפצים או יצורים.

אם המטיל מעוניין בכך, קצות הקיר מתחברים לכל חומר דומם שהם נוגעים בו (כגון קירות אבן, אדמה או רהיטים). אחרת, הקיר עשוי להישאר ללא תמיכה (לפי החלטת המנחה) ועלול ליפול. אם אינו נתמך, יש סיכוי שווה שהוא ייפול לאחד הכיוונים בתוך 1d6 סיבובים. ניתן להפיל את הקיר בכיוון מסוים על ידי יצור בעל כוח 13 או יותר, או על ידי מפלצת בעלת 4 קוביות פגיעה או יותר. מספר יצורים יכולים לשתף פעולה לשם כך. (אם משתמשים בכלל גלגול התכונה האופציונלי, גלגול כוח של 3 מספיק כדי להפיל את הקיר.)

כאשר הקיר נופל, כל יצור שמתחתיו עלול להיפגע או להיהרג. אם ליצור יש אפשרות להימלט (כלומר יש לו מהירות תנועה מספקת והוא אינו מנוע מכך), הוא רשאי לגלגל גלגול הצלה נגד קרן מוות, עם בונוס נוסף לזריזות. אם הגלגול מצליח, היצור נע בדרך הישירה ביותר אל מקום בטוח קרוב; אם הגלגול נכשל, או אם לא ניתן להימלט, הוא סופג 10d6 נקודות פגיעה. יצורים גדולים מעוג חסינים לריסוק זה, אך יופלו אם הגלגול נכשל.

הקיר קבוע, אך מאחר שהוא עשוי ברזל, הוא רגיש לחלודה ולקורוזיה.

:::

:::
