# אוצר

*"הרעיון שלך היה טוב, דאריון," אמר מורנינגסטאר לאחר שסובבנו את מכסה הסרקופג חצי סיבוב. "פשוט מיהרת קצת לנסות אותו."*

*"אכן," אמרתי, מרגיש טיפש. הבטתי אל תוך הסרקופג; על גבי השרידים החנוטים שבתוכו ראיתי חרב, מוחזקת בשתי ידיים גרומות כשחודה מופנה לעבר רגלי הגופה. הלהב הזהוב לא הוכתם; האודם העצום ששובץ במגן הניצב זהר באור הלפידים.*

*לא שלחתי יד אליה, אף שהתפתיתי מאוד. "ברת’אל," אמרתי, "אמור לי, האם בטוח להושיט יד פנימה?" בן-המחצית טיפס אל שפת הבמה והתכופף מעל הסרקופג, סוקר את תוכו.*

*"איני רואה מלכודת," העיר לאחר בחינה מדוקדקת. "האם אתה חושב שהמת ההוא שם יקום אם תיגע בחרבו?"*

*"ייתכן," השיבה אפוקוליס, "אך אני בספק. השלדים היו ככל הנראה השומרים היחידים בקבר הזה."*

*נראה היה שכל העיניים נשואות אליי. בחוסר רצון הושטתי יד פנימה ואחזתי בלהב החרב בכפפת השריון שלי כדי להימנע ממגע בגופה. ראש השבט שמת לפני זמן רב לא רצה להיפרד מנשקו, אך לאחר שסובבתי אותה מעט הצלחתי לשחרר אותה.*

*ניערתי פיסות בשר מיובש מן הניצב, אחזתי בנשק כראוי והרמתי אותו אל על. הוא הרגיש טוב בידי... תהיתי איזה קסם עשוי להיות טמון בו?*

*קולו של ברת’אל הוציא אותי מהרהוריי. "הביטו כאן!" אמר, והבטתי מטה. הוא פתח לוח סודי בבמה... ולעיניי החלו מטבעות זהב וכסף להישפך החוצה. ברת’אל קרא בשמחה, "ג'קפוט!"*

## חלוקת האוצר

יש הרפתקנים שבוחרים לצאת להרפתקה כדי להילחם ברשע, בעוד אחרים מבקשים לזכות בתהילה או בכוח... ואילו אחרים יוצאים לחפש אוצרות: זהב, תכשיטים וחפצי קסם. להלן המידע שהמנחה תצטרך כדי לרצות את תאבי הבצע.

## יצירת אוצר אקראי

הטבלאות שלהלן מתארות את סוגי האוצר השונים המשויכים למפלצות, וכן אוצרות ללא שמירה המתאימים לדרגות מבוך שונות. כדי ליצור אוצר אקראי, מצאי את סוג האוצר המצוין ועברי לאורך השורה; כאשר מצוין סיכוי באחוזים, גלגלי בקוביות אחוזים כדי לבדוק אם סוג אוצר זה נמצא. אם כן, גלגלי את הקוביות המצוינות כדי לקבוע את הכמות.

טבלאות ליצירה אקראית של אבנים יקרות, תכשיטים (וחפצי אמנות משובצי אבנים יקרות) וחפצי קסם מופיעות לאחר טבלאות האוצר הראשיות.

## אוצרות מוצבים

המנחה לעולם אינה נדרשת לגלגל עבור אוצר; במקום זאת אפשר להציב אוצרות או לשנות אוצרות אקראיים, כפי שרצוי או נדרש לצורכי ההרפתקה. אוצרות מיוחדים מוצבים תמיד; לדוגמה, חפץ קסם מיוחד הדרוש להשלמת הרפתקה.

## התאמת תגמולי אוצר

יהיו מקרים רבים שבהם יצירת אוצר אקראי אינה השיטה המתאימה ביותר. לדוגמה, ייתכן שיהיה צורך להקטין אוצר גדול מן הממוצע שהוקצה למאורת מפלצות קטנה מן הממוצע. על המנחה להחליט כמה אוצר היא מעוניינת לאפשר במערכה. יותר מדי זהב (או אוצר אחר שניתן להמיר לזהב) עלול להפוך את הדברים לקלים מדי עבור דמויות השחקנים. באופן דומה, גם יותר מדי חפצי קסם עלולים להקל יתר על המידה.

אם את מנחה מתחילה, זכרי שתמיד תוכלי להעניק אוצר נוסף, אך קשה לקחת אוצר מן החבורה מבלי להכעיס את השחקנים... בייחוד אם תשתמשי בשיטות כוחניות. התחילי במעט והגדילי בהדרגה ככל שתצברי ניסיון.

## סוגי אוצר:

### אוצרות מאורה

::: {.column-screen-inset-right}

<div class="tableFixHead">

| **סוג** | **מאות מטבעות** **נחושת** | **מאות מטבעות** **כסף**  | **מאות מטבעות** **אלקטרום** | **מאות מטבעות**  **זהב**   | **מאות מטבעות** **פלטינה** | **אבנים יקרות** **ותכשיטים**  | **חפצי קסם** |
|---|---|---|---|---|---|---|---|
| A | 50% 5d6 | 60% 5d6 | 40% 5d4 | 70% 10d6 | 50% 1d10 | 50% 6d6, 50% 6d6 | 30% 3 כלשהם |
| B | 75% 5d10 | 50% 5d6 | 50% 5d4 | 50% 3d6 | אין | 25% 1d6, 25% 1d6 | 10% 1 נשק או שריון |
| C | 60% 6d6 | 60% 5d4 | 30% 2d6 | אין | אין | 25% 1d4, 25% 1d4 | 15% 1d2 כלשהם |
| D | 30% 4d6 | 45% 6d6 | אין | 90% 5d8 | אין | 30% 1d8, 30% 1d8 | 20% 1d2 כלשהם + 1 שיקוי |
| E | 30% 2d8 | 60% 6d10 | 50% 3d8 | 50% 4d10 | אין | 10% 1d10, 10% 1d10 | 30% 1d4 כלשהם + 1 מגילה |
| F | אין | 40% 3d8 | 50% 4d8 | 85% 6d10 | 70% 2d8 | 20% 2d12, 10% 1d12 | 35% 1d4 כלשהם מלבד כלי נשק + 1 שיקוי + 1 מגילה |
| G | אין | אין | אין | 90% 4d6x10 | 75% 5d8 | 25% 3d6, 25% 1d10 | 50% 1d4 כלשהם + 1 מגילה |
| H | 75% 8d10 | 75% 6d10x10 | 75% 3d10x10 | 75% 5d8x10 | 75% 9d8 | 50% 1d100, 50% 10d4 | 20% 1d4 כלשהם + 1 שיקוי + 1 מגילה |
| I | אין | אין | אין | אין | 80% 3d10 | 50% 2d6, 50% 2d6 | 15% 1 כלשהו |
| J | 45% 3d8 | 45% 1d8 | אין | אין | אין | אין  | אין |
| K | אין | 90% 2d10 | 35% 1d8 | אין | אין | אין | אין |
| L | אין | אין | אין | אין | אין | 50% 1d4  | אין |
| M | אין | אין | אין | 90% 4d10 | 90% 2d8x10 | 55% 5d4, 45% 2d6 | אין |
| N | אין | אין | אין | אין | אין | אין | 40% 2d4 שיקויים |
| O | אין | אין | אין | אין | אין | אין | 50% 1d4 מגילות |

</div>

:::

\* אוצרות מסוג H הם אוצרות דרקונים; הסיכוי לכל סוג מטבע נע בין 35% בקטגוריית הגיל השנייה ל־85% בשביעית, ואילו הסיכוי לאבנים יקרות, תכשיטים וחפצי קסם הוא 5% לכל קוביית פגיעה של המפלצת. גורי דרקונים בדרך כלל אינם מחזיקים אוצר כלל.


### אוצרות אישיים

::: {.column-screen-inset-right}

| **סוג** | **מטבעות** **נחושת**  | **מטבעות** **כסף**  | **מטבעות** **אלקטרום** | **מטבעות** **זהב** | **מטבעות** **פלטינה**  | **אבנים יקרות** **ותכשיטים** | **חפצי קסם** |
|---|---|---|---|---|---|---|---|
| P | 3d8 | אין | אין | אין | אין | אין | אין |
| Q | אין | 3d6 | אין | אין | אין | אין  | אין |
| R | אין | אין | 2d6 | אין | אין | אין  | אין |
| S | אין | אין | אין | 2d4 | אין | אין | אין |
| T | אין | אין | אין | אין | 1d6 | אין | אין |
| U | 50% 1d20 | 50% 1d20 | אין | 25% 1d20 | אין | 5% 1d4, 5% 1d4 | 2% כלשהו |
| V | אין | 25% 1d20 | 25% 1d20 | 50% 1d20 | 25% 1d20 | 10% 1d4, 10% 1d4 | 5% כלשהו |

::: 

### אוצרות ללא שמירה

::: {.column-screen-inset-right}

::: {#unguarded-treasure}

| **דרגה** | **מאות מטבעות** **נחושת**  | **מאות מטבעות** **כסף**  | **מאות מטבעות** **אלקטרום**  | **מאות מטבעות** **זהב**  | **מאות מטבעות** **פלטינה**  | **אבנים יקרות** **ותכשיטים**  | **חפצי קסם** |
|---|---|---|---|---|---|---|---|
| 1 | 75% 1d8 | 50% 1d6 | 25% 1d4 | 7% 1d4 | 1% 1d4 | 7% 1d4, 3% 1d4 | 2% 1 כלשהו |
| 2 | 50% 1d10 | 50% 1d8 | 25% 1d6 | 20% 1d6 | 2% 1d4 | 10% 1d6, 7% 1d4 | 5% 1 כלשהו |
| 3 | 30% 2d6 | 50% 1d10 | 25% 1d8 | 50% 1d6 | 4% 1d4 | 15% 1d6, 7% 1d6 | 8% 1 כלשהו |
| 4-5 | 20% 3d6 | 50% 2d6 | 25% 1d10 | 50% 2d6 | 8% 1d4 | 20% 1d8, 10% 1d6 | 12% 1 כלשהו |
| 6-7 | 15% 4d6 | 50% 3d6 | 25% 1d12 | 70% 2d8 | 15% 1d4 | 30% 1d8, 15% 1d6 | 16% 1 כלשהו |
| 8+ | 10% 5d6 | 50% 5d6 | 25% 2d8 | 75% 4d6 | 30% 1d4 | 40% 1d8, 30% 1d8 | 20% 1 כלשהו |

:::
::: 

הערה: אוצרות ללא שמירה צריכים להיות נדירים; ראי את [מנחת המשחק](gm01.qmd) להלן, לקבלת עצות על מיקום אוצרות ללא שמירה.

### אבנים יקרות ותכשיטים

השתמשי בטבלאות שלהלן כדי לקבוע את הערך הבסיסי ואת מספר האבנים שנמצאו כאשר האוצר כולל אבנים יקרות. אם המספר שנקבע בטבלה הראשית שלעיל קטן, גלגלי עבור כל אבן; אך אם המספר גדול (10 או יותר, לפי שיקול דעתך), לאחר כל גלגול לקביעת הסוג והערך הבסיסי גלגלי את הקובייה המצוינת כדי לקבוע כמה אבנים כאלה נמצאות באוצר.

```{ojs}

import {highlightTableRow, treasureGeMTable} from "../custom.js"

viewof gemJewel = Inputs.button("גלגלו בטבלה", {value: 0, reduce: () => highlightTableRow("#gem-jewelry", treasureGeMTable())})

```

::: {#gem-jewelry}

| **d%** | **סוג** | **ערך בסיסי** **במטבעות זהב** | **מספר** **שנמצא** |
|---|----|---|----|
| 01-20 | נוי | 10 | 1d10 |
| 21-45 | חצי-יקר | 50 | 1d8 |
| 46-75 | מפואר | 100 | 1d6 |
| 76-95 | יקר | 500 | 1d4 |
| 96-00 | אבן חן | 1000 | 1d2 |
|  | תכשיט | 5000 | 1 |

::: 

ערכי האבנים עשויים לסטות מן הערכים שלעיל בשל איכותן, גודלן וכדומה. המנחה רשאית להשתמש בטבלה שלהלן כדי להתאים את ערכי האבנים שבאוצר, לפי שיקול דעתה. זו הסיבה שבטבלה שלעיל לא מופיעה תוצאת קובייה עבור תכשיט; בתוצאה 12 בטבלה שלהלן, אבן חן יכולה להפוך לתכשיט.


```{ojs}

import {treasureGeMTable2} from "../custom.js"

viewof gemJewel2 = Inputs.button("גלגלו בטבלה", {value: 0, reduce: () => highlightTableRow("#gem-jewelry-2", treasureGeMTable2())})

```

::: {#gem-jewelry-2}

| **2d6** | **התאמת ערך** |
|---|----|
| 2 | שורה אחת לערך נמוך יותר |
| 3 | 1/2 |
| 4 | 3/4 |
| 5-9 | ערך רגיל |
| 10 | פי 1.5 |
| 11 | פי 2 |
| 12 | שורה אחת לערך גבוה יותר  |

::: 

```{ojs}

import {generalTableSelect} from "../custom.js"

viewof gemJewel3 = Inputs.button("גלגלו בטבלה", 
{value: 0, 
reduce: () => highlightTableRow("#gem-jewelry-3", 
generalTableSelect([1,100,0],[[1,5],[6,12],[13,20],[21,30],[31,40],[41,43],[44,48],[49,57],[58,63],[64,68],[69,78],[79,88],[89,91],[92,95],[96,100]]))})

```

::: {#gem-jewelry-3}

| d%    | סוג אבן חן       |
|-------|----------------|
| 01-05 | אלכסנדריט    |
| 06-12 | אמטיסט       |
| 13-20 | אוונטורין     |
| 21-30 | כלוראסטרוליט |
| 31-40 | יהלום        |
| 41-43 | ברקת         |
| 44-48 | אופל אש      |
| 49-57 | פלואורוספאר     |
| 58-63 | גרנט         |
| 64-68 | הליוטרופ     |
| 69-78 | מלכיט        |
| 79-88 | רודוניט      |
| 89-91 | אודם          |
| 92-95 | ספיר         |
| 96-00 | פטדה          |


:::

פריטי תכשיטים רגילים שווים 2d8x100 מטבעות זהב. אפשר להשתמש בטבלה שלהלן כדי ליצור תיאורים של הפריטים עצמם.

```{ojs}

import {treasureGeMTable4, highlightTableCell} from "../custom.js"

viewof gemJewel4 = Inputs.button("גלגלו בטבלה", {value: 0, reduce: () => {var temp = treasureGeMTable4(); highlightTableCell("#gem-jewelry-4", temp[0], temp[1])}})

```

::: {#gem-jewelry-4}

| **d%** | **סוג** |  **d%** | **סוג** |
|---|----|---|----|
| 01-06 | צמיד קרסול  |  56-62 | עגיל |
| 07-12 | חגורה    |  63-65 | קנקן |
| 13-14 | קערה    |  66-68 | גביע |
| 15-21 | צמיד | 69-73 | סכין |
| 22-27 | סיכת נוי  |  74-77 | סכין לפתיחת מכתבים |
| 28-32 | אבזם  |  78-80 | תליון נפתח |
| 33-37 | שרשרת   |  81-82 | מדליה |
| 38-40 | צ'וקר  |  83-89 | מחרוזת |
| 41-42 | עטרה |  90 | צלחת |
| 43-47 | תפס   |  91-95 | סיכה |
| 48-51 | מסרק    |  96 | שרביט |
| 52 | כתר      |  97-99 | פסלון |
| 53-55 | כוס     |  00 | טיארה |

::: 