# כלי רכב

הטבלאות הבאות מספקות פרטים על כלי רכב יבשתיים וימיים שונים. מנחות המשחק מוזמנות ליצור כלי רכב משלהן, ובמקרה כזה ניתן להשתמש בטבלה כהנחיה. חלק מהסטטיסטיקות המופיעות להלן מוסברות בפירוט בהמשך.

## תחבורה יבשתית

::: {.column-screen-inset-right}

<div class="tableFixHead">

| כלי רכב | אורך x רוחב* | משקל (ק"ג) | מטען (ק"ג) | תנועה | קשיחות / נקודות פגיעה | עלות (מ"ז) |
|---------|-----------------|--------|-------|----------|---------------|-----------|
| מרכבה | 4.5 על 2 | 150 | 675 | 18 (3) | 10 / 10 | 400 |
| כרכרה | 9 על 2.5 | 500 | 1000 | 12 (5) | 6 / 12 | 1,500 |
| עגלה | 10.5 על 2.5 | 1000 | 2000 | 6 (5) | 6 / 16 | 500 |

</div>

:::

*כולל סוסים או פרדות רתומים.

## תחבורה ימית

::: {.column-screen-inset-right}

<div class="tableFixHead">

| כלי רכב | אורך x רוחב | מטען | צוות | תנועה | ק"מ/יום | קשיחות / נקודות פגיעה | עלות (מ"ז) |
|---|---|---|---|---|---|---|---|
| קאנו | 4.5 על 1 | ½ טון | 1 | 12 (2) | 50 | 4 / 4 | 50 |
| קרוולה | 16.5 על 4.5 | 75 טון | 10 | 6 (3) | 70 | 8 / 75 | 10,000 |
| קאראק | 18 על 6 | 135 טון | 20 | 9 (9) | 80 | 10 / 120 | 20,000 |
| גליאה קטנה | 30 על 4.5 | 210 טון | 90 | 6 (6) | 60 / 40 | 8 / 75 | 15,000 |
| גליאה גדולה | 36 על 6 | 375 טון | 160 | 10 (8) | 70 / 40 | 10 / 120 | 30,000 |
| ספינת ארוכה | 33 על 4.5 | 10 טון | 70 | 10 (8) | 70 / 40 | 9 / 110 | 25,000 |
| רפסודה/דוברה | 3 על 3 לכל טון | 1 טון | 2 | 13 (3) | 30 | 6 / 12 | 100 |
| ספינת נהר | 15 על 6 | 50 טון | 10 | 7 (7) | 50 | 8 / 30 | 3,500 |
| סירת משוטים | 4.5 על 2 | 1 טון | 1 | 10 (3) | 40 | 6 / 8 | 60 |
| סירת מפרש | 12 על 2.5 | 5 טון | 1 | 12 (5) | 60 | 7 / 20 | 2,000 |

</div>

:::

## הערות לגבי כלי רכב

המספר של **הצוות** שניתן משקף את מספר המינימום של מלחים ו/או חותרים הנדרשים לתפעול הספינה. קצינים אינם נכללים במספרים אלה, וכמובן שתמיד כדאי לשכור מלחים ו/או חותרים נוספים כדי להבטיח שבמידה ומי מהצוות נפגע, הכלי לא יואט.

**המטען** עבור עגלות ניתן בק"ג, בעוד שעבור ספינות הוא ניתן בטונות. אם הספינה מפליגה יום ולילה, עבור כל נוסע נדרש מרחב מחיה השווה לטון אחד של מטען; בנוסף, אספקה לאדם אחד לחודש תופסת 1/10 טון של מרחב.

**התנועה** ניתנת כאן בנפרד במטרים (ראו [זמן וקנה מידה](dungeonAdventures.qmd#time-and-scale) להסבר) וכן בקילומטרים ליום. תנועת המפגש של ספינות אינה קשורה ישירות לקצב הנסיעה למרחקים ארוכים, שכן הצוות חייב לעבוד קשה כדי להזיז את הספינה במהירות בקרב, ורמת מאמץ זו לא יכולה להישמר יום ולילה.

המספר בסוגריים מייצג את יכולת התמרון; ראו **יכולת תמרון** ב**חלק 5: המפגש** לפרטים.

ראו **תקיפת כלי רכב**, גם כן בקטע [המפגש](combat.qmd#maneuverability), לפרטים על הסטטיסטיקות של **קשיחות** ו**נקודות פגיעה**.

**מרכבה** דורשת סוס אחד, בדרך כלל סוס מלחמה, כדי למשוך אותה. גם **כרכרות** וגם **עגלות** דורשות לפחות זוג סוסים רתומים כדי למשוך אותן.

**קרוולה** היא ספינת מפרש בעלת יכולת תמרון גבוהה עם שניים או שלושה תורנים. למרות שהיא דומה במבט ראשון לקאראק הגדולה יותר, הקרוולה מסוגלת להפליג בנהרות, משימה שהספינה הגדולה אינה מתאימה לה.

**קאראק** היא ספינת מפרש גדולה להפלגות באוקיינוס עם שלושה או ארבעה תורנים.

**גליאות** מצוידות גם במפרשים וגם במשוטים; קצב התנועה השני המופיע עבור גליאות הוא מהירות החתירה. גליאה קטנה תכלול כ-20 שורות של משוטים, כאשר כל משוט נמשך על ידי שני אנשים (בסך הכל 80 חותרים) בעוד שגליאה גדולה תכלול כ-35 שורות של משוטים (בסך הכל 140 חותרים). לגליאות בדרך כלל יכולת תמרון גבוהה יותר מאשר ספינות מפרש כמו הקאראק או הקרוולה, וניתן לצייד אותן באילי ניגוח.

**הספינה הארוכה** הנפוצה בקרב פושטים צפוניים דומה מאוד לגליאה הגדולה. עם זאת, בעוד שמדינות מתורבתות יותר מחזיקות חותרים, מלחים ונחתים מומחים, הצוות של ספינה ארוכה הוא יותר כללי; רוב אנשי הצוות יהיו מוסמכים לכל המשימות הללו.

## מנועי מצור

אלו הם כלי נשק המשמשים לתקיפת מבצרים, או לפעמים ספינות. עלותם עשויה להיות כפולה במיקום מרוחק. מנוע מצור שמשליך קליעים (בליסטה, אונגר או טרבושה) חייב להיות מופעל על ידי תותחן מאומן; זהו הדמות שמבצעת את גלגולי התקיפה עבור הנשק. למנועי השלכת קליעים יש עונשי תקיפה, המפורטים להלן. הערה: מנועי מצור אינם ניתנים לשימוש בדרך כלל נגד יחידים או מפלצות; המנחה עשויה לעשות חריגים עבור מפלצות גדולות מאוד כמו ענקים או דרקונים. עיינו בכללים בקטע [מבצר](gm02.qmd#strongholds) לפרטים לגבי תקיפת מבנים מבוצרים כמו טירות, מגדלים, מבצרים וכדומה.

::: {.column-screen-inset-right}

<div class="tableFixHead">

| נשק | עלות | קצב אש | עונש תקיפה | נזק | טווח קצר (+1) | טווח בינוני (+0) | טווח ארוך (-2) |
|---|---|---|---|---|---|---|---|
| בליסטה | 100 מטבעות זהב | 1/4 | -3 | 2d8 | 15 מטר | 30 מטר | 45 מטר |
| איל ניגוח | 200 מטבעות זהב | 1/3 | +0 | 2d8 | N/A | N/A | N/A |
| קטפולטה | 300 מטבעות זהב | 1/6 | -6 | 2d12 | 30 מטר | 60 מטר | 90 מטר |
| מקדח מצור | 200 מטבעות זהב | N/A |  N/A | 1d8  | N/A | N/A | N/A |
| גגון מצור | 100 מטבעות זהב | N/A | N/A | N/A | N/A | N/A | N/A |
| טרבושה | 400 מטבעות זהב | 1/10 | -8 | 3d10 | N/A | 90 מטר | 120 מטר |

</div>

:::

**בליסטה:** זהו למעשה רובה קשת גדול מאוד שיכול לירות חץ דמוי חנית או אבן גדולה. בדרך כלל הוא מותקן על חצובה או עגלה, אך ניתן גם להתקינו על ספינה. כאשר יורה חצים, בליסטה אינה יכולה לפגוע בלבנים או באבן. בליסטה דורשת צוות של שלושה אנשים להפעלה.

**איל ניגוח:** בדרך כלל מופעלים תחת גגון מצור. הם דורשים צוות של שמונה אנשים או יותר.

**קטפולטה:** נשק זה משליך אבן במסלול שטוח יחסית. קטפולטה דורש צוות של ארבעה אנשים להפעלה.

**מקדח מצור**: מכשיר זה עשוי לשמש לתקיפת מבצר, באמצעות קידוח דרך הקירות. צוות של לפחות שמונה אנשים נדרש להפעלתו. הוא משמש רק בבסיס הקיר, ובדרך כלל מופעל תחת גגון מצור.

**גגון מצור**: זהו סוג של גג נייד, המשמש להגנה בעת ביצוע תקיפות איטיות יותר על מבנה מבוצר. אלו שמתחת לגגון יהיו קשים יותר לפגיעה, ויקבלו לפחות בונוס של +6 לדירוג שריון נגד התקפות מרחוק בעת שהם מכוסים תחתיו. לגגון עצמו יש קשיחות של 9 ו-50 נקודות פגיעה.

**טרבושה:** נשק אדיר זה משתמש במשקל נגד כדי להשליך אבן במסלול גבוה וקשת. הוא אינו יכול לירות על מטרות בטווח של פחות מ-200 מטרים. אם הוא מכוון למטרה שגבוהה יותר מ-6 מטר מהנשק, יש עונש תקיפה נוסף של -2. טרבושה דורשת צוות של שמונה אנשים להפעלה.

