## הרפתקאות בשטח פתוח

### קצבי תנועה בשטח פתוח


## הרפתקאות בשטח פתוח

### קצבי תנועה בשטח פתוח

קצבי התנועה בעת מסע בשטח פתוח קשורים ישירות לקצבי התנועה במבוכים, כפי שמוצג בטבלה להלן:



| תנועה במבוך (מטר לסיבוב) | תנועה בשטח פתוח (ק"מ ליום) |
|----|----|
| 3 מטר | 10 |
| 6 מטר | 20 |
| 9 מטר | 30 |
| 12 מטר | 40 |
| 15 מטר | 50 |
| 18 מטר | 60 |
| 21 מטר | 68 |
| 24 מטר | 77 |
| 27 מטר | 87 |
| 30 מטר | 97 |
| 33 מטר | 53 |
| 36 מטר | 116 |

מטבע הדברים, כל קבוצה הנעה יחד תתקדם לפי קצב התנועה של החבר האיטי ביותר בה.

### נסיעה ביבשה

קצבי התנועה המופיעים בטבלה לעיל מחושבים על בסיס יום מסע של 8 שעות בשטח פתוח ונוח למעבר. סוג הקרקע עשוי לשנות את הקצב במידה מסוימת, כפי שמוצג בטבלה הבאה:


| **שטח** | **התאמה** |
|-------------|------------------|
| ג'ונגל, הרים, ביצה | 1/3 x|
| מדבר, יער, גבעות | 2/3 x|
| פתוח, מישורים, שביל | x1 |
| כביש (מרוצף) |  1/3 x 1|


דמויות יכולות לבחור לבצע **מסע מאומץ**, ולנוע במשך 12 שעות ביום. במקרה כזה, יש להוסיף 50% נוספים למרחק הנע ביום.

כל יום של מסע מאומץ מעבר ליום הראשון גורם לנזק של 1ק6 נקודות פגיעה לדמויות (ולבעלי החיים שלהן, אם יש). ניתן לבצע גלגול הצלה נגד קרן מוות, בתוספת בונוס החוסן, כדי להימנע מנזק זה. אולם, לאחר שכישלון בגלגול זה התרחש פעם אחת, אין לגלגל שוב עבור אותה דמות או יצור.

יום מנוחה אחד "מאפס" את ההתקדמות הזו.


### איבוד הדרך

הרפתקנים הנעים לאורך דרכים, נהרות או נקודות ציון ברורות אחרות אינם צפויים ללכת לאיבוד. אולם, יציאה אל יערות חסרי שבילים, מדבריות מוכי רוחות וכדומה היא עניין אחר לחלוטין.

יש לגלגל בחשאי גלגול הצלה נגד קרן מוות, עם התאמה לפי תבונת מנהיג הקבוצה (כלומר, הדמות שנראית כמובילה). אם משתמשים בכלל האופציונלי, ניתן במקום זאת לבצע גלגול תכונה כנגד תבונה.

המנחה תקבע את השלכות הכישלון.



### מסע ימי

מסע דרך מים יכול להתבצע באמצעות מגוון סירות ואוניות; לפרטים ראו את הטבלה בסעיף [כלי רכב](vehicles.qmd#תחבורה-ימית). מרחקי התנועה מבוססים על יום מסע של 12 שעות, במקום 8 השעות הרגילות המצוינות לעיל.

שימו לב שאוניות מפרש עשויות לנוע במשך 24 שעות ביממה (אם יש על הסיפון נווט מוסמך), ולכן עשויות לכסות עד פי שניים מהמרחק היומי הרגיל. זאת בנוסף למכפיל המופיע בטבלה להלן. אם האונייה עוצרת מדי לילה, כפי שנהוג בחלק מהכלים הנעים לאורך חופים, או כאשר אין די אנשי צוות, מכפיל פי שניים זה אינו חל.

תנועת אוניות מפרש משתנה בהתאם לתנאי מזג האוויר, כפי שמוצג בטבלה הבאה. מתאמי התנועה לשיט חלים כאשר מפליגים עם הרוח; הפלגה נגד הרוח מחייבת **תימרון זיגזג** (המכונה לעיתים „זיגזוג” על ידי אנשי יבשה), אשר מפחית את קצב התנועה בהתאם לטבלה.



```{ojs}

import {generalTableSelect, highlightTableRow} from "../custom.js"

Inputs.button("גלגלי בטבלה", {value: 0, reduce: () => highlightTableRow("#wind-direction", generalTableSelect([1,12,0],[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,12]]))})
```

:::{#wind-direction}

| **d12** | **כיוון רוח** |
|---------|--------------------|
| 1 | צפונית |
| 2 | צפון-מזרחית |
| 3 | מזרחית |
| 4 | דרום-מזרחית |
| 5 | דרומית |
| 6 | דרום-מערבית |
| 7 | מערבית |
| 8 | צפון-מערבית |
| 9-12 | כיוון הרוח השולט באזור זה |

::: 

```{ojs}

Inputs.button("גלגלי בטבלה", {value: 0, reduce: () => highlightTableRow("#wind-condition", generalTableSelect([1,100,0],[[1,5],[6,13],[14,25],[26,40],[41,70],[71,85],[86,96],[97,100]]))})

```

:::{#wind-condition}

| **d%** | **תנאי רוח** | **מפרש** | **זיגזוג** |
|---------|--------------------|-------------|-------------|
| 01-05 | ללא רוח | x0 | x0 |
| 06-13 | בריזה קלה מאוד | x1/3 | x0 |
| 14-25 | בריזה קלה | x1/2 | x1/3 |
| 26-40 | בריזה מתונה | x2/3 | x1/3 |
| 41-70 | רוחות ממוצעות | x1 | x1/2 |
| 71-85 | רוחות חזקות | x1 1/3 | x2/3 |
| 86-96 | רוחות חזקות מאוד | x1 1/2 | x0 |
| 97-00 | סערה | x2 | x0 |

:::

**הערות:**

**ללא רוח:** ספינות מפרש אינן יכולות לנוע. ספינות משוטים עשויות לנוע בקצב תנועת חתירה.

**רוחות חזקות מאוד:** הפלגה נגד הרוח (תימרון זיגזוג) אינה אפשרית.

**סערה:** הפלגה נגד הרוח אינה אפשרית, וספינות החשופות לסערה עשויות להינזק או לטבוע; יש להחיל 2d8 נקודות נזק על כל ספינה כזו, לכל שעה של הפלגה.


### תעופה

בעת תנועה באוויר, קצבי התנועה למרחקים מוכפלים, וכל השפעות הקרקע אינן חלות.

רוב היצורים בעלי הכנפיים חייבים לשמור על לפחות שליש מקצב התנועה הקדמי הרגיל שלהם כדי להישאר באוויר. עם זאת, אמצעים כגון **שטיחים מעופפים** לרוב אינם מוגבלים כך.

