project:
  type: book
  output-dir: docs/he

book:
  title: "מערכת פנטזיה בסיסית לשחקני תפקידים, מהדורה 4"
  author: "כריס גונרמן"
  date: "5/2/2023"
  chapters:
  - he/index.qmd
  - part: מבוא
    chapters:
      - he/whatIsThis.qmd
  - part: דמויות שחקן
    chapters:
      - he/char-creation.qmd
  - part: מפגשים
    chapters:
      - he/combat.qmd

format:
  html:
    theme: cosmo
    lang: he
    dir: rtl
    css: [custom.css, custom-rtl.css]
    number-depth: 0
    toc-depth: 4
    execute:
      echo: false
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Frank+Ruhl+Libre">
      <script src="../../translator/lang-switch.js"></script>
    mainfont: "Frank Ruhl Libre"
