<div class="rtl">
# התקדמות

## נקודות נסיון (נק"נ)

נקודות ניסיון ניתנות עבור מפלצות שהובסו, וכן עבור אתגרים אחרים לפי שיקול דעתו של המנחה. הטבלה הבאה מספקת ערכי נק״נ למפלצות. כאשר למפלצת מצוינים גם דרגת דמות וגם קוביות פגיעה, יש להשתמש בערך הגבוה מבין השניים כדרגת המפלצת. לאתגרים שאינם קרביים ניתן לשייך דרגה, או להעניק ערך נק״נ קבוע, לפי רצון המנחה.

אם מופיעות כוכביות אחרי ציון קוביות הפגיעה של מפלצת, כל כוכבית מוסיפה פעם אחת את בונוס היכולת המיוחדת; לדוגמה, יצור עם 2** קוביות פגיעה שווה 125 נק״נ.

למפלצות עם יותר מ־25 קוביות פגיעה, יש להוסיף 750 נק״נ לערך הנק״נ, ועוד 25 נק״נ לבונוס היכולת המיוחדת עבור כל קוביית פגיעה נוספת.

יש להתייחס לדב״שים כמפלצות עם מספר קוביות פגיעה השווה לדרגת הדמות. יש להוסיף בונוס יכולת מיוחדת לכוהנים ולקוסמים אם הם מסוגלים להטיל לחשים שימושיים במהלך המפגש.

לאחר חישוב סך הנק״נ שהורווחו בהרפתקה מסוימת, יש לחלק את הסכום במספר ההרפתקנים. כפי שתואר לעיל, כל בן־לוויה מקבל חצי חלק; לכן חבורה הכוללת ארבע דמויות שחקן ובן־לוויה נספרת כ־4½ חברים. אם הקבוצה צוברת 2,000 נק״נ, חלק אחד שווה 444 נק״נ, והבן־לוויה מקבל 222 נק״נ.

אף דמות אינה רשאית לעלות יותר מדרגה אחת כתוצאה מנקודות הניסיון מהרפתקה אחת. לדוגמה, ברתאל הגנב הוא בדרגה 1 ויש לו 1,000 נק״נ לפני יציאה להרפתקה; במהלך ההרפתקה הוא מרוויח עוד 2,000 נק״נ (הישג מרשים). סך הכול יהיו לו 3,000 נק״נ, מה שהיה הופך אותו לגנב בדרגה 3. דבר זה אינו מותר; במקום זאת הוא מתקדם ל־2,499 נק״נ, נקודה אחת פחות מהנדרש לדרגה 3, ומתחיל את ההרפתקה הבאה שלו בדרגה 2.

</div>

<div class="tableFixHead rtl">

| **קוביות פגיעה של מפלצת** | **ערך נק"נ** | **בונוס יכולת מיוחדת** |
|----|----|---|
| פחות מ־1 | 10 | 3 |
| 1 | 25 | 12 |
| 2 | 75 | 25 |
| 3 | 145 | 30 |
| 4 | 240 | 40 |
| 5 | 360 | 45 |
| 6 | 500 | 55 |
| 7 | 670 | 65 |
| 8 | 875 | 70 |
| 9 | 1,075 | 75 |
| 10 | 1,300 | 90 |
| 11 | 1,575 | 95 |
| 12 | 1,875 | 100 |
| 13 | 2,175 | 110 |
| 14 | 2,500 | 115 |
| 15 | 2,850 | 125 |
| 16 | 3,250 | 135 |
| 17 | 3,600 | 145 |
| 18 | 4,000 | 160 |
| 19 | 4,500 | 175 |
| 20 | 5,250 | 200 |
| 21 | 6,000 | 225 |
| 22 | 6,750 | 250 |
| 23 | 7,500 | 275 |
| 24 | 8,250 | 300 |
| 25 | 9,000 | 325 |

: ערכי נק"נ למפלצות {#tbl-monsterexp}

</div>